var statusTags = [

"A-completer",
"Brands-to-be-completed",
"Caracteristiques-a-completer",
"Categories-a-completer",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Date-limite-a-completer",
"Emballage-a-completer",
"Expiration-date-to-be-completed",
"Informations-nutritionnelles-a-completer",
"Ingredients-a-completer",
"Ingredients-completed",
"Ingredients-to-be-completed",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Product-name-to-be-completed",
"Quantity-to-be-completed",
"To-be-completed"];
