var statusTags = [

"A compléter",
"A vérifier",
"Brands-to-be-completed",
"Caractéristiques à compléter",
"Caractéristiques complétées",
"Categories-to-be-completed",
"Characteristics-to-be-completed",
"Complet",
"Date limite à compléter",
"Date limite complétée",
"Emballage à compléter",
"Expiration-date-to-be-completed",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingrédients à compléter",
"Ingrédients complétés",
"Ingredients-to-be-completed",
"Marques à compléter",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos validées",
"Product-name-to-be-completed",
"Quantité à compléter",
"Quantity-to-be-completed",
"To-be-completed"];
