var categoriesTags = [

"Dairies",
"Yogurts",
"Beverages",
"Fruit yogurts",
"Frozen foods",
"Canned foods",
"Meats",
"fr:Pizzas et tartes surgelées",
"Canned Vegetables",
"Fishes",
"Fruit juices and nectars",
"Plain yogurts",
"Seafood",
"Vegetables",
"Vegetables and derived products",
"Biscuits",
"Candies",
"Desserts",
"Fruit juices",
"Groceries",
"Meals",
"Milks",
"Pastas",
"Prepared meats",
"fr:Pizzas surgelées",
"Breakfasts",
"Cakes",
"Cereals",
"Cheeses",
"Farming products",
"Jams",
"Soy milks",
"Spreads",
"Sweet spreads",
"Sweetened yogurts",
"fr:Laits végétaux",
"fr:Oeufs",
"Breads",
"Carbonated drinks",
"Chocolate desserts",
"Chocolates",
"Fresh",
"Fruit sodas",
"Grated cheese",
"Orange juices",
"Pineapple juices",
"Rices",
"Sauces",
"Sodas",
"Spices",
"Sugars",
"fr:Biscuits au chocolat",
"fr:Bonbons",
"fr:Charcuteries diverses",
"fr:Chocolats noirs",
"fr:Crèmes dessert",
"fr:Crèmes dessert chocolat",
"fr:Gelées de fruits",
"fr:Lardons",
"fr:Lardons fumés",
"fr:Madeleines",
"fr:Maquereaux",
"fr:Morues",
"fr:Pates-de-fruits",
"fr:Pâtes fraîches",
"fr:Petits pois en conserve",
"fr:Pizzas",
"fr:Plats cuisinés surgelés",
"fr:Sucres de canne",
"fr:Tablettes de chocolat",
"fr:Tartes surgelées",
"Alcoholic drinks",
"Canned fishes",
"Chili peppers",
"Condiments",
"Cow Cheeses",
"Creams",
"Diet drinks",
"Diet sodas",
"Drinkable yogurts",
"Emmentaler",
"Fats",
"Flavors",
"Flavoured yogurts",
"Food additives",
"French cheeses",
"Fruit nectars",
"Guava nectars",
"Hams",
"Hard liquors",
"Hot drinks",
"Ice creams",
"Ice creams and sorbets",
"Pies",
"Pommes-de-terre",
"Rillettes",
"Salmons",
"Smoked fishes",
"Soups",
"Squeezed juices",
"Squeezed orange juices",
"Stirred yogurts",
"Tomatoes",
"Vanilla yogurts",
"Vegetable fats",
"Vegetable oils",
"Waters",
"Whole milk yogurts",
"fr:Arômes pâtisserie",
"fr:Bâtonnets",
"fr:Bio",
"fr:Biscuits-sales",
"fr:Boissons-aux-fruits",
"fr:Bretzels",
"fr:Cafés",
"fr:Cafés en poudre",
"fr:Chocolats Suisse",
"fr:Colins",
"fr:Compotes",
"fr:Crèmes dessert chocolat noir",
"fr:Crèmes fraîches",
"fr:Desserts-lactes",
"fr:Desserts-lactes-framboise",
"fr:Eaux-de-vie",
"fr:Édulcorants",
"fr:Emmentals français",
"fr:Emmentals rapés",
"fr:Filets de Maquereaux",
"fr:Filtes-de-cabillaud",
"fr:Flageolets en conserve",
"fr:Foie-de-morue",
"fr:Fromages à pâte pressée cuite",
"fr:Fromages au lait cru",
"fr:Fromages-bio",
"fr:Fromages de chèvre",
"fr:Galettes de céréales",
"fr:Galettes de riz",
"fr:Galettes de riz complet",
"fr:Haricots verts en conserve",
"fr:Jambons blancs",
"fr:Jus-de-canne",
"fr:Laits demi-écrémés",
"fr:Laits UHT",
"fr:Lentilles",
"fr:Madeleines-aux-oeufs",
"fr:Maquereaux-a-l-escabeche",
"fr:Maquereaux-a-la-catalane",
"fr:Miel-doux",
"fr:Mousses-lactees",
"fr:Mousses-lactees-framboise",
"fr:Pains pour hamburgers",
"fr:Pate",
"fr:Pates",
"fr:Petits beurres",
"fr:Pizzas-bio",
"fr:Poêlées",
"fr:Pulpe-de-tomates",
"fr:Quatre-quarts",
"Rums",
"fr:Rhums agricoles",
"fr:Rhums français",
"fr:Rillettes de poissons",
"fr:Riz Basmati",
"fr:Riz-rond",
"fr:Riz thaï",
"fr:Sablés",
"fr:Sodas à l'orange",
"fr:Sodas aux fruits light",
"fr:Soupes déshydratées",
"fr:Spaghetti",
"fr:Steaks-haches",
"fr:Steaks-haches-surgeles",
"fr:Tomates en conserve",
"fr:Tortellini",
"fr:Tortellinis",
"fr:Vanille",
"fr:Viandes de boeuf",
"fr:Viandes-hachees",
"fr:Yaourts-a-boire-a-la-vanille",
"fr:Yaourts-natures-bio"];
