var labelsTags = [

"Organic",
"fr:AB Agriculture Biologique",
"EU Organic",
"fr:Production-locale",
"No preservatives",
"No colorings",
"fr:Labels de distributeurs",
"No added sugar",
"fr:Viande Française",
"Carrefour Quality",
"FR-BIO-01",
"Green Dot",
"Palm oil free",
"fr:Eco-emballages",
"fr:Ecocert",
"fr:Fabrication-locale",
"fr:Origine-france",
"fr:Porc Français",
"fr:Produit-peyi",
"fr:Source-de-calcium",
"fr:Testé par le panel test Carrefour",
"fr:Viande Bovine Française",
"Made in France",
"Natural colorings",
"Pure juice",
"Sustainable fishery",
"Sustainable Seafood MSC",
"fr:100-arabica",
"fr:100-guadeloupe",
"fr:Bioeuropeen",
"fr:Ble-de-france",
"fr:Ble-francais-selectionne",
"fr:Cuisine-en-france",
"fr:Desarete",
"fr:Engagement-qualite-carrefour",
"fr:Fabircation-locale",
"fr:Fraichement-fabrique-en-guadeloupe",
"fr:Fumage-au-bois",
"fr:Lait-de-chevre-100-francais",
"fr:Light",
"fr:Porc-nourri-sans-ogm-lt-0-9",
"fr:Produit-local",
"fr:Qualite-controlee",
"fr:Riche-en-vitamine-c",
"fr:Sans-cartilage",
"fr:Sans-couenne",
"fr:Verifie-rainforest-alliance"];
