var manufacturing_placesTags = [

"25170-noironte",
"44330-vallet",
"52140-is-en-bassigny",
"62820-libercourt",
"Allemagne",
"Champagne-ardenne",
"Doubs",
"France",
"Franche-comte",
"Fromagerie-le-centurion-flc-filiale-sodagral",
"Fromagerie-mulin-filiale-sodagral",
"Fromagerie-overney-filiale-sodagral",
"Haute-marne",
"Lactalis-nestle-ultra-frais-marques-lnuf-marques-filiale-groupe-lactalis-boulevard-louis-beauquin",
"Loire-atlantique",
"Nord-pas-de-calais",
"Pas-de-calais",
"Pays-de-la-loire"];
