var categoriesTags = [

"Produits laitiers",
"Yaourts",
"Boissons",
"Yaourts aux fruits",
"Surgelés",
"Conserves",
"Viandes",
"Pizzas et tartes surgelées",
"Légumes en conserve",
"Poissons",
"Jus et nectars de fruits",
"Yaourts natures",
"Produits de la mer",
"Légumes",
"Végétaux et dérivés",
"Biscuits",
"Confiseries",
"Desserts",
"Jus de fruits",
"Epicerie",
"Plats préparés",
"Laits",
"Pâtes alimentaires",
"Charcuteries",
"Pizzas surgelées",
"Petit-déjeuners",
"Gâteaux",
"Céréales",
"Fromages",
"Produits d'élevages",
"Confitures",
"Laits de soja",
"Produits à tartiner",
"Produits à tartiner sucrés",
"Yaourts sucrés",
"Laits végétaux",
"Oeufs",
"Pains",
"Boissons gazeuses",
"Desserts au chocolat",
"Chocolats",
"Frais",
"Sodas aux fruits",
"Fromages râpés",
"Jus d'orange",
"Jus d'ananas",
"Riz",
"Sauces",
"Sodas",
"Epices",
"Sucres",
"Biscuits au chocolat",
"Bonbons",
"Charcuteries diverses",
"Chocolats noirs",
"Crèmes dessert",
"Crèmes dessert chocolat",
"Gelées de fruits",
"Lardons",
"Lardons fumés",
"Madeleines",
"Maquereaux",
"Morues",
"Pates-de-fruits",
"Pâtes fraîches",
"Petits pois en conserve",
"Pizzas",
"Plats cuisinés surgelés",
"Sucres de canne",
"Tablettes de chocolat",
"Tartes surgelées",
"Boissons alcoolisées",
"Poissons en conserve",
"Piments",
"Condiments",
"Fromages de vache",
"Crèmes",
"Boissons light",
"Sodas light",
"Yaourts à boire",
"Emmental",
"Matières grasses",
"Arômes",
"Yaourts aromatisés",
"Additifs alimentaires",
"Fromages de France",
"Nectars de fruits",
"Nectars de goyave",
"Jambons",
"Alcools forts",
"Boissons chaudes",
"Glaces",
"Glaces et sorbets",
"Tartes",
"en:Pommes-de-terre",
"Rillettes",
"Saumons",
"Poissons fumés",
"Soupes",
"Jus de fruits 100% pur jus",
"Jus d'orange 100% pur jus",
"Yaourts brassés",
"Tomates",
"Yaourts vanille",
"Matières grasses végétales",
"Huiles",
"Eaux",
"Yaourts entiers",
"Arômes pâtisserie",
"Bâtonnets",
"Bio",
"Biscuits-sales",
"Boissons-aux-fruits",
"Bretzels",
"Cafés",
"Cafés en poudre",
"Chocolats Suisse",
"Colins",
"Compotes",
"Crèmes dessert chocolat noir",
"Crèmes fraîches",
"Desserts-lactes",
"Desserts-lactes-framboise",
"Eaux-de-vie",
"Édulcorants",
"Emmentals français",
"Emmentals rapés",
"Filets de Maquereaux",
"Filtes-de-cabillaud",
"Flageolets en conserve",
"Foie-de-morue",
"Fromages à pâte pressée cuite",
"Fromages au lait cru",
"Fromages-bio",
"Fromages de chèvre",
"Galettes de céréales",
"Galettes de riz",
"Galettes de riz complet",
"Haricots verts en conserve",
"Jambons blancs",
"Jus-de-canne",
"Laits demi-écrémés",
"Laits UHT",
"Lentilles",
"Madeleines-aux-oeufs",
"Maquereaux-a-l-escabeche",
"Maquereaux-a-la-catalane",
"Miel-doux",
"Mousses-lactees",
"Mousses-lactees-framboise",
"Pains pour hamburgers",
"Pate",
"Pates",
"Petits beurres",
"Pizzas-bio",
"Poêlées",
"Pulpe-de-tomates",
"Quatre-quarts",
"Rhums",
"Rhums agricoles",
"Rhums français",
"Rillettes de poissons",
"Riz Basmati",
"Riz-rond",
"Riz thaï",
"Sablés",
"Sodas à l'orange",
"Sodas aux fruits light",
"Soupes déshydratées",
"Spaghetti",
"Steaks-haches",
"Steaks-haches-surgeles",
"Tomates en conserve",
"Tortellini",
"Tortellinis",
"Vanille",
"Viandes de boeuf",
"Viandes-hachees",
"Yaourts-a-boire-a-la-vanille",
"Yaourts-natures-bio"];
