var labelsTags = [

"Bio",
"AB Agriculture Biologique",
"Bio européen",
"Production-locale",
"Sans conservateurs",
"Sans colorants",
"Labels de distributeurs",
"Sans sucre ajouté",
"Viande Française",
"Qualité Carrefour",
"FR-BIO-01",
"Point Vert",
"Sans huile de palme",
"Eco-emballages",
"Ecocert",
"Fabrication-locale",
"Origine-france",
"Porc Français",
"Produit-peyi",
"Source-de-calcium",
"Testé par le panel test Carrefour",
"Viande Bovine Française",
"Fabriqué en France",
"Colorants naturels",
"Pur jus",
"Pêche durable",
"Pêche durable MSC",
"100-arabica",
"100-guadeloupe",
"Bioeuropeen",
"Ble-de-france",
"Ble-francais-selectionne",
"Cuisine-en-france",
"Desarete",
"Engagement-qualite-carrefour",
"Fabircation-locale",
"Fraichement-fabrique-en-guadeloupe",
"Fumage-au-bois",
"Lait-de-chevre-100-francais",
"Light",
"Porc-nourri-sans-ogm-lt-0-9",
"Produit-local",
"Qualite-controlee",
"Riche-en-vitamine-c",
"Sans-cartilage",
"Sans-couenne",
"Verifie-rainforest-alliance"];
