var statusTags = [

"A compléter",
"A vérifier",
"Caractéristiques à compléter",
"Caractéristiques complétées",
"Catégories à compléter",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Complete",
"Date limite à compléter",
"Date limite complétée",
"Emballage à compléter",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingrédients à compléter",
"Ingredients-completed",
"Ingrédients complétés",
"Marques à compléter",
"Nom du produit à compléter",
"Nutrition-facts-completed",
"Packaging-to-be-completed",
"Photos à envoyer",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos validées",
"Quantité à compléter",
"To-be-checked",
"To-be-completed"];
