var labelsTags = [

"Ökologische Produkt",
"Glutenfrei",
"Laktosefrei",
"Ohne-konservierungsstoffe",
"Bio",
"Vegan",
"Vegetarisch",
"At-bio-301",
"Ohne-farbstoffe",
"DE-ÖKO-001",
"EU Organic",
"Alkoholfrei",
"Ama-biozeichen",
"Ama-gutesiegel",
"Bayerisches-bier",
"Bio-nach-eg-okoverordnung",
"Eu-nicht-eu-landwirtschaft",
"Gentechnikfrei-erzeugt",
"Mikrowellen-geeignet",
"Ohne-gentechnik-hergestellt",
"Ohne-zucker",
"Ohne-zuckerzusatz",
"Ohne-zusatz-von-aromen",
"Osterreichische-landwirtschaft",
"Slow-brewing",
"Fair trade",
"Fairtrade International"];
