var labelsTags = [

"Organic",
"de:Glutenfrei",
"de:Laktosefrei",
"de:Ohne-konservierungsstoffe",
"de:Bio",
"Vegan",
"Vegetarian",
"de:At-bio-301",
"de:Ohne-farbstoffe",
"DE-ÖKO-001",
"EU Organic",
"de:Alkoholfrei",
"de:Ama-biozeichen",
"de:Ama-gutesiegel",
"de:Bayerisches-bier",
"de:Bio-nach-eg-okoverordnung",
"de:Eu-nicht-eu-landwirtschaft",
"de:Gentechnikfrei-erzeugt",
"de:Mikrowellen-geeignet",
"de:Ohne-gentechnik-hergestellt",
"de:Ohne-zucker",
"de:Ohne-zuckerzusatz",
"de:Ohne-zusatz-von-aromen",
"de:Osterreichische-landwirtschaft",
"de:Slow-brewing",
"Fair trade",
"Fairtrade International"];
