var categoriesTags = [

"Desserts",
"Breakfasts",
"fr:Céréales pour petit-déjeuner",
"fr:Compotes",
"Beverages",
"Biscuits",
"Canned foods",
"Canned Vegetables",
"Cereals",
"Herbal teas",
"Hot drinks",
"Vegetables",
"fr:Bio",
"fr:Flan",
"fr:Légumes bio",
"fr:Mueslis",
"fr:Pois-chiches",
"fr:Pois-chiches-bio",
"fr:Pois chiches en conserve",
"fr:Rooibos"];
