var categoriesTags = [

"Desserts",
"Petit-déjeuners",
"Céréales pour petit-déjeuner",
"Compotes",
"Boissons",
"Biscuits",
"Conserves",
"Légumes en conserve",
"Céréales",
"Infusions",
"Boissons chaudes",
"Légumes",
"Bio",
"Flan",
"Légumes bio",
"Mueslis",
"Pois-chiches",
"Pois-chiches-bio",
"Pois chiches en conserve",
"Rooibos"];
