var statusTags = [

"A-completer",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredients-a-completer",
"Ingredients-completes",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Quantite-a-completer",
"Vide"];
