project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /po/common/common.pot
    translation: /po/common/%two_letters_code%.po
    ignore: ["/po/common/nl.po"]
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-HK: zh_HK
        en-GB: en_GB
        en-AU: en_AU
        en-US: en_US
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /po/openbeautyfacts/openbeautyfacts.pot
    translation: /po/openbeautyfacts/%two_letters_code%.po
    ignore: ["/po/openbeautyfacts/nl.po"]
    languages_mapping:
      two_letters_code:
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        en-AU: en_AU
        en-US: en_US
        zh-CN: zh_CN
        zh-HK: zh_HK
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /po/openfoodfacts/openfoodfacts.pot
    translation: /po/openfoodfacts/%two_letters_code%.po
    ignore: ["/po/openfoodfacts/nl.po"]
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        en-US: en_US
        nl-BE: nl_BE
        nl: nl_NL
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /po/openproductsfacts/openproductsfacts.pot
    translation: /po/openproductsfacts/%two_letters_code%.po
    ignore: ["/po/openproductsfacts/nl.po"]
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        en-US: en_US
        nl-BE: nl_BE
        nl: nl_NL
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /po/openpetfoodfacts/openpetfoodfacts.pot
    translation: /po/openpetfoodfacts/%two_letters_code%.po
    ignore: ["/po/openpetfoodfacts/nl.po"]
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        en-US: en_US
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /html/donate/en.html
    translation: /html/donate/%two_letters_code%.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        en-US: en_US
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
