files:
  - source: /po/common/en.po
    translation: /po/common/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-HK: zh_HK
        en-GB: en_GB
        en-AU: en_AU
        nl-BE: nl_BE
        nl: nl_NL
  - source: /po/openbeautyfacts/en.po
    translation: /po/openbeautyfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        en-AU: en_AU
        zh-CN: zh_CN
        zh-HK: zh_HK
        nl-BE: nl_BE
        nl: nl_NL
  - source: /po/openfoodfacts/en.po
    translation: /po/openfoodfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        nl-BE: nl_BE
        nl: nl_NL
        pt-BR: pt_BR
        pt-PT: pt_PT
