FROM node:lts as builder
COPY package*.json /data/
WORKDIR /data
RUN npm install
ENV PATH /data/node_modules/.bin:$PATH

COPY . /data/
RUN npm run build

FROM nginx:stable-alpine
WORKDIR /opt/product-opener
COPY --from=builder /data/node_modules/ /opt/product-opener/node_modules/
COPY --from=builder /data/html/ /opt/product-opener/html/
