CSV_BASE_COLUMNS = [
    "code",
    "name",
    "last_updated_t",
    "categories",
    "countries",
    "ingredients",
    "serving_size",
    "brands",
    "brand_owner",
    "preparationStateCode",
    "quantity",
    "sources_fields:org-database-usda:available_date",
    "sources_fields:org-database-usda:fdc_branded_category",
    "sources_fields:org-database-usda:fdc_data_source",
    "sources_fields:org-database-usda:fdc_id",
    "sources_fields:org-database-usda:modified_date",
    "sources_fields:org-database-usda:publication_date",
    "sources_fields:org-database-usda:preparation_state_code"
]

FDC_NUTRIENTS = {
    "Protein": {"g"},
    "Total lipid (fat)": {"g"},
    "Sodium, Na": {"mg"},
    "Energy": {"kcal", "kJ"},
    "Carbohydrate, by difference": {"g"},
    "Total Sugars": {"g"},
    "Fatty acids, total saturated": {"g"},
    "Cholesterol": {"mg"},
    "Fiber, total dietary": {"g"},
    "Fatty acids, total trans": {"g"},
    "Iron, Fe": {"mg"},
    "Calcium, Ca": {"mg"},
    "Potassium, K": {"mg"},
    "Vitamin C, total ascorbic acid": {"mg"},
    "Vitamin A, IU": {"IU"},
    "Sugars, added": {"g"},
    "Vitamin D (D2 + D3), International Units": {"IU"},
    "Vitamin D (D2 + D3)": {"µg"},
    "Fatty acids, total monounsaturated": {"g"},
    "Fatty acids, total polyunsaturated": {"g"},
    "Vitamin A, RAE": {"µg"},
    "Niacin": {"mg"},
    "Thiamin": {"mg"},
    "Riboflavin": {"mg"},
    "Vitamin B-6": {"mg"},
    "Folate, total": {"µg"},
    "Magnesium, Mg": {"mg"},
    "Vitamin B-12": {"µg"},
    "Phosphorus, P": {"mg"},
    "Zinc, Zn": {"mg"},
    "Folic acid": {"µg"},
    "Pantothenic acid": {"mg"},
    "Total sugar alcohols": {"g"},
    "Manganese, Mn": {"mg"},
    "Copper, Cu": {"mg"},
    "Fiber, soluble": {"g"},
    "Fiber, insoluble": {"g"},
    "Vitamin E": {"mg", "mg_ATE"},  # also mg_ATE, what is it?
    "Selenium, Se": {"µg"},
    "Vitamin K (phylloquinone)": {"µg"},
    "Iodine, I": {"µg"},
    "Vitamin E (label entry primarily)": {"IU"},
    "Biotin": {"µg"},
    "Ash": {"g"},
    "Water": {"g"},
    "Carbohydrate, other": {"g"},
    "Molybdenum, Mo": {"µg"},
    "Chromium, Cr": {"µg"},
    "Chlorine, Cl": {"mg"},
    "Folate, DFE": {"µg"},
    "Sugars, Total": {"g"},
    "Vitamin E (alpha-tocopherol)": {"mg"},
    "Choline, total": {"mg"},
    "Lactose": {"g"},
    "Caffeine": {"mg"},
    "Xylitol": {"g"},
    "Arginine": {"g"},
    "Proline": {"g"},
    "Lysine": {"g"},
    "Methionine": {"g"},
    "Phenylalanine": {"g"},
    "Histidine": {"g"},
    "Threonine": {"g"},
    "Valine": {"g"},
    "Alanine": {"g"},
    "Serine": {"g"},
    "Leucine": {"g"},
    "Glycine": {"g"},
    "Isoleucine": {"g"},
    "Tyrosine": {"g"},
    "Aspartic acid": {"g"},
    "Tryptophan": {"g"},
    "Glutamic acid": {"g"},
    "Inositol": {"mg"},
    "Sorbitol": {"g"},
    "Vitamin D3 (cholecalciferol)": {"µg"},
    "Cystine": {"g"},
    "Starch": {"g"},
    "Inulin": {"g"},
    "Retinol": {"µg"},
    "Cysteine": {"g"},
    "Folate, food": {"µg"},
    "Taurine": {"g"},
    "Carotene, beta": {"µg"},
    "Lutein + zeaxanthin": {"µg"},
    "Salt, NaCl": {"mg"},
    "Epigallocatechin-3-gallate": {"mg"},
    "Alcohol, ethyl": {"g"},
    "Glutamine": {"g"},
    "PUFA 18:3 n-3 c,c,c (ALA)": {"g"},
    "Glucose": {"g"},
    "Fluoride, F": {"µg"},
    "SFA 12:0": {"g"},
    "Acetic acid": {"mg"},
    "Lactic acid": {"mg"},
    "PUFA 18:2": {"g"},
    "Fructose": {"g"},
    "SFA 8:0": {"g"},
    "SFA 10:0": {"g"},
    "PUFA 18:2 n-6 c,c": {"g"},
    "Sugars, intrinsic": {"g"},
    "Ribose": {"g"},
    "Choline, from phosphotidyl choline": {"mg"},
    "Beta-glucans": {"g"},
    "Vitamin D2 (ergocalciferol)": {"µg"},
    "Lignin": {"g"},
    "Maltose": {"g"},
}
