var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Dairies",
"Candies",
"Sodas",
"Groceries",
"Chocolates",
"Alcoholic drinks",
"Beers",
"Breakfasts",
"Meats",
"Meals",
"Milks",
"Cheeses",
"Seafood",
"Cereals",
"Condiments",
"Prepared meats",
"Joghurte",
"Fishes",
"Fruit juices",
"Fruit juices and nectars",
"Hot drinks",
"Spreads",
"Vegetables",
"Vegetables and derived products",
"fr:Sodas au cola",
"Sauces",
"Sweet spreads",
"fr:Apéritif",
"fr:Pâtes à tartiner",
"Canned foods",
"Diet drinks",
"Diet sodas",
"Soups",
"Biscuits",
"Frozen foods",
"Cow Cheeses",
"Farming products",
"Fats",
"Fresh",
"Herbal teas",
"Waters",
"fr:Barres",
"fr:Barres chocolatées",
"Breads",
"Spices",
"fr:Bières blondes",
"fr:Céréales pour petit-déjeuner",
"fr:Laits végétaux",
"fr:Sodas au cola light",
"Bee products",
"Canned fishes",
"Chips and fries",
"Fruit sodas",
"Honeys",
"Sardines",
"fr:Chips",
"fr:Fromages à pâte fraîche",
"fr:Fromages pasteurisés",
"Canned sardines",
"Concentrated fruit juices",
"Desserts",
"Fruit yogurts",
"Pastas",
"Rices",
"Sweetened yogurts",
"Teas",
"Vegetable fats",
"Wines",
"fr:Bonbons",
"fr:Cafés",
"fr:Chips de pommes de terre",
"fr:Chips de pommes de terre à l'huile de tournesol",
"fr:Chocolats noirs",
"fr:Eaux minérales",
"fr:Pates",
"fr:Pizzas",
"fr:Sodas au citron",
"fr:Soupes déshydratées",
"fr:Yaourts-au-bifidus",
"Canned Vegetables",
"Fruits",
"Olives",
"Orange juices",
"Pickled vegetables",
"Pickles",
"Poultries",
"fr:Laits demi-écrémés",
"fr:Laits UHT",
"fr:Plats cuisinés surgelés",
"fr:Sardines à l'huile",
"Apple juices",
"Dried fruits",
"Green olives",
"Olive oils",
"Smoked fishes",
"Sojamilch",
"Strawberry yogurts",
"Vegetable oils",
"Waffles",
"fr:Amuse-bouches",
"fr:Bières blanches",
"fr:Boissons énergisantes",
"fr:Cafés en poudre",
"fr:Chocolats au lait",
"fr:Fromages à pâte pressée non cuite",
"fr:Fruits au sirop",
"fr:Laits concentrés",
"fr:Mueslis",
"fr:Pâtes à tartiner aux noisettes",
"fr:Quinoa",
"fr:Saucissons",
"Animal fats",
"Cakes",
"Coconuts",
"Concentrated orange juices",
"Green teas",
"Hams",
"Ice creams and sorbets",
"Margarines",
"Multifruit juices",
"Plain yogurts",
"Red wines",
"Salted spreads",
"Sausages",
"Sugars",
"Tomatoes",
"Tropical fruits",
"Tunas",
"Whole milk yogurts",
"fr:Ananas au sirop",
"fr:Aubergines",
"fr:Bieres-belges",
"fr:Biscottes",
"fr:Biscuits-aperitif",
"fr:Biscuits-aperitifs",
"fr:Boulangerie",
"fr:Eaux de sources",
"fr:Fromage-blanc-demi-ecreme",
"fr:Fromages à tartiner",
"fr:Fromages de chèvre",
"fr:Gaufrettes",
"fr:Gaufrettes-chocolatees",
"fr:Harengs",
"fr:Ketchup",
"fr:Laits de coco",
"fr:Légumes surgelés",
"fr:Mayonnaises",
"fr:Oeufs",
"fr:Pâtes à tartiner au chocolat",
"fr:Pâtes à tartiner aux noisettes et au cacao",
"fr:Pates-tagliatelles",
"fr:Pizzas ovales",
"fr:Poulets",
"fr:Produits-vendus-dans-les-annees-2000",
"fr:Quiches",
"fr:Sardines à l'huile d'olive",
"fr:Sodas au citron light",
"fr:Sodas aux fruits light",
"fr:Tablettes de chocolat",
"fr:Thés glacés",
"fr:Viandes-bbq",
"fr:Yaourts-a-l-abricot",
"fr:Yaourts-a-l-ananas",
"fr:Yaourts-a-la-mangue",
"fr:Yaourts-multifruits",
"Asparagus",
"en:Biscuits-aperitifs-sales",
"Blue-veined cheeses",
"Butters",
"en:Coffee-in-capsules",
"en:Coke",
"Concentrated apple juices",
"Crustaceans",
"Drinkable yogurts",
"Ducks",
"Fish fillets",
"Flavoured yogurts",
"French cheeses",
"Fresh vegetables",
"Hard liquors",
"Ice creams",
"Industrial cheese",
"Meals with meat",
"Non-dairy desserts",
"Nuts",
"Pastries",
"Pies",
"Products without gluten",
"Salmons",
"en:Sirop-leger",
"Soy desserts",
"Squeezed juices",
"Vanilla yogurts",
"Vegetable rods",
"Vinegars",
"Virgin olive oils",
"Whisky",
"White wines",
"Wine vinegars",
"Wines from Spain",
"en:Worcestershire-sauce",
"fr:Abats",
"fr:Aioli",
"fr:Alc7-vol",
"fr:Aperitifs-sales",
"fr:Asperges en conserve",
"fr:Attieke",
"fr:Barre-chocolate",
"fr:Beignets-de-crevettes",
"fr:Beurre-73",
"fr:Beurre-et-huile-d-olive",
"fr:Beurres demi-sel",
"fr:Biere-belge-d-abbaye",
"fr:Biere-d-abbaye",
"fr:Bières à la cerise",
"fr:Bières avec des fruits",
"fr:Bières brunes",
"fr:Biscuit-au-fruits",
"fr:Biscuits-aperitifs-sales",
"fr:Biscuits au chocolat",
"fr:Biscuits-cigarettes",
"fr:Biscuits-fourres",
"fr:Biscuits-sales",
"fr:Blé",
"fr:Blés",
"fr:Blés durs",
"fr:Bles-durs-precuits",
"fr:Blinis",
"fr:Boison-gazeuse",
"fr:Boisson-au-jus-de-pomme",
"fr:Boisson-fraiche",
"fr:Boisson-gazeuse-light-aux-fruits",
"fr:Boissons chaudes instantanées",
"fr:Boissons énergétiques",
"fr:Bouillon",
"fr:Boules-de-neige",
"fr:Buiscuit-aperitif",
"fr:Cafe-cappuccino-instantane",
"fr:Cafe-en-poudre-instantane",
"fr:Caramel-sauce",
"fr:Caramels",
"fr:Cassonade-de-candi-brune",
"fr:Chicoree",
"fr:Chocolat-70",
"fr:Chocolat-au-lait-praline",
"fr:Chocolat-noir-pur",
"fr:Chocolat-praline",
"fr:Chocolats en poudre",
"fr:Choux-rouge-aux-pommes",
"fr:Compotes",
"fr:Confits de canard",
"fr:Cornichons",
"fr:Couscous",
"fr:Couscous-de-manioc",
"fr:Creem-entiere",
"fr:Creme-culinaire",
"fr:Creme-diluee-10-matiere-grasse",
"fr:Crèmes dessert",
"fr:Crèmes glacées",
"fr:Crevettes",
"fr:Crevettes grises",
"fr:Cuisine-asiatique",
"fr:Demi-ecreme",
"fr:Eau-minerale-aromatisee",
"fr:Eau-mineralle-naturelle",
"fr:Eau-plate",
"fr:Eaux-de-vie",
"fr:Eaux gazeuses",
"fr:Eaux minérales naturelles",
"fr:Édulcorants",
"fr:Enrichi-d-huile-de-colza",
"fr:Epices-pour-viande",
"fr:Farcies-d-anchois",
"fr:Feuilles-de-brick",
"fr:Filets d'anchois",
"fr:Flocons-d-avoine",
"fr:Foies gras",
"fr:Fromage-a-pate-dure",
"fr:Fromage-frais-de-chevre",
"fr:Fromage-gouda",
"fr:Fromage-light",
"fr:Fromage-mi-vieux",
"fr:Fromages à pâte fondue",
"fr:Fromages au lait cru",
"fr:Fromages de vache Prim'Holstein",
"fr:Fromages des Pays-Bas",
"fr:Fromages fondus",
"fr:Gaspacho",
"fr:Gauffrettes-au-miel",
"fr:Genoise",
"fr:Genoises",
"fr:Gorgonzolas",
"fr:Goudas",
"fr:Graines",
"fr:Graines-de-lin",
"fr:Gueuze",
"fr:Hache",
"fr:Haddocks fumés",
"fr:Halal",
"fr:Harengs-marines",
"fr:Haricots",
"fr:Haricots-rouges-sauce-chili",
"fr:Houmous",
"fr:Houmus-piquant",
"fr:Jambons blancs",
"fr:Jus-d-agrumes",
"fr:Jus-de-betteraves-rouges",
"fr:Jus-de-fruits-a-base-de-jus-concentres",
"fr:Jus-multi-fruits",
"fr:Jus-multifruits-a-base-de-concentre",
"fr:Lait-sucre",
"fr:Laits aromatisés",
"fr:Laits concentrés non sucrés",
"fr:Laits d'amande",
"fr:Laits écrémés",
"fr:Laits frais",
"fr:Laits-micro-filtres",
"fr:Lasagnes à garnir",
"fr:Lasagnes préparées",
"fr:Légumes secs",
"fr:Limonades",
"fr:Maizena",
"fr:Matiere-grasse-vegetale-a-tartiner",
"fr:Miel-au-chocolat",
"fr:Mistelle",
"fr:Mollusques",
"fr:Morues",
"fr:Moules",
"fr:Moutardes",
"fr:Naturelle",
"fr:Nougat-tendre",
"fr:Nouilles-asiatiques",
"fr:Nouilles-instantanees",
"fr:Nouilles-orientales",
"fr:Nutella",
"fr:Oeufs plein air",
"fr:Olive-aperitives",
"fr:Olives-violettes",
"fr:Opuree-de-tomate-passata",
"fr:Pain grillé",
"fr:Pains croustillants",
"fr:Pains-pita",
"fr:Pains sans gluten",
"fr:Pate",
"fr:Pâtes fraîches",
"fr:Pâtes sèches",
"fr:Petits-pois-carottes",
"fr:Pineau des Charentes",
"fr:Pinot-gris",
"fr:Pistaches",
"fr:Pizza-croquantina-biscuits-aperitifs",
"fr:Plat-prepare-complet",
"fr:Plats à base de canards",
"fr:Plats à base de volaille",
"fr:Pois-chiche",
"fr:Poissons-prepares",
"fr:Polenta",
"fr:Pollen-en-pelottes",
"fr:Pop-corn",
"fr:Potages",
"fr:Poudre-pudding",
"fr:Preparation-pour-crepes",
"fr:Produit-a-la-noisette",
"fr:Produit-au-chocolat-au-lait",
"fr:Produit-au-sel-de-guerande",
"fr:Produit-de-boulangerie",
"fr:Produits-lactes",
"fr:Pruneaux",
"fr:Puree-d-ail",
"fr:Purées",
"fr:Purées de pommes de terre",
"fr:Reblochons",
"fr:Rehausseur-de-gout",
"fr:Riz Basmati",
"fr:Riz Basmati blancs",
"fr:Riz long grain",
"fr:Riz pour sushi",
"fr:Riz soufflé",
"fr:Rosettes",
"fr:Salades-en-conserves",
"fr:Salades-repas",
"fr:Sardines à l'huile et au piment",
"fr:Sardines sans huile",
"fr:Sauce-a-l-ail",
"fr:Sauce-soya",
"fr:Sauce-vinaigrette",
"fr:Saucissons secs",
"fr:Saucissons secs pur porc",
"fr:Sauves",
"fr:Sel-aux-herbes",
"fr:Semoule",
"fr:Sesame",
"fr:Sirops",
"fr:Sirops aux fruits",
"fr:Snacking",
"fr:Sodas aux fruits exotiques",
"fr:Soja-a-tartiner",
"fr:Sorbets",
"fr:Soupes-de-nouilles",
"fr:Soupes froides",
"fr:Spéculoos",
"fr:Speculoos-tendres",
"fr:Spiruline",
"fr:Sucres de canne",
"fr:Sucres en morceaux",
"fr:Sucres glaces",
"fr:Superaliment",
"fr:Superfood",
"fr:Tartes salées",
"fr:Thons à l'huile",
"fr:Tomates-au-jus",
"fr:Tomates-en-cubes",
"fr:Tomates-entieres-pelees-au-jus",
"fr:Tomates pelées",
"fr:Tomates-poivrons",
"fr:Tomates séchées",
"fr:Torsades",
"fr:Tortis",
"fr:Veloutés",
"fr:Verrines",
"fr:Viandes de porc",
"fr:Vins-d-alsace",
"fr:Vins effervescents",
"fr:Vins mutés",
"fr:Vins-naturels",
"fr:Vins pétillant",
"fr:Yaourts-a-la-cerise",
"fr:Yaourts-a-la-figue",
"fr:Yaourts-au-kiwi",
"fr:Yugourth"];
