var categoriesTags = [

"Boissons",
"Boissons gazeuses",
"Produits laitiers",
"Confiseries",
"Sodas",
"Epicerie",
"Chocolats",
"Boissons alcoolisées",
"Bières",
"Petit-déjeuners",
"Viandes",
"Plats préparés",
"Laits",
"Fromages",
"Produits de la mer",
"Céréales",
"Condiments",
"Charcuteries",
"Yaourts",
"Poissons",
"Jus de fruits",
"Jus et nectars de fruits",
"Boissons chaudes",
"Produits à tartiner",
"Légumes",
"Végétaux et dérivés",
"Sodas au cola",
"Sauces",
"Produits à tartiner sucrés",
"Apéritif",
"Pâtes à tartiner",
"Conserves",
"Boissons light",
"Sodas light",
"Soupes",
"Biscuits",
"Surgelés",
"Fromages de vache",
"Produits d'élevages",
"Matières grasses",
"Frais",
"Infusions",
"Eaux",
"Barres",
"Barres chocolatées",
"Pains",
"Epices",
"Bières blondes",
"Céréales pour petit-déjeuner",
"Laits végétaux",
"Sodas au cola light",
"Produits de la ruche",
"Poissons en conserve",
"Chips et frites",
"Sodas aux fruits",
"Miels",
"Sardines",
"Chips",
"Fromages à pâte fraîche",
"Fromages pasteurisés",
"Sardines en conserve",
"Jus de fruits à base de concentré",
"Desserts",
"Yaourts aux fruits",
"Pâtes alimentaires",
"Riz",
"Yaourts sucrés",
"Thés",
"Matières grasses végétales",
"Vins",
"Bonbons",
"Cafés",
"Chips de pommes de terre",
"Chips de pommes de terre à l'huile de tournesol",
"Chocolats noirs",
"Eaux minérales",
"Pates",
"Pizzas",
"Sodas au citron",
"Soupes déshydratées",
"Yaourts-au-bifidus",
"Légumes en conserve",
"Fruits",
"Olives",
"Jus d'orange",
"Pickles de légumes",
"Pickles",
"Volailles",
"Laits demi-écrémés",
"Laits UHT",
"Plats cuisinés surgelés",
"Sardines à l'huile",
"Jus de pomme",
"Fruits secs",
"Olives vertes",
"Huiles d'olive",
"Poissons fumés",
"Laits de soja",
"Yaourts à la fraise",
"Huiles",
"Gaufres",
"Amuse-bouches",
"Bières blanches",
"Boissons énergisantes",
"Cafés en poudre",
"Chocolats au lait",
"Fromages à pâte pressée non cuite",
"Fruits au sirop",
"Laits concentrés",
"Mueslis",
"Pâtes à tartiner aux noisettes",
"Quinoa",
"Saucissons",
"Matières grasses animales",
"Gâteaux",
"Noix de coco",
"Jus d'orange à base de concentré",
"Thés verts",
"Jambons",
"Glaces et sorbets",
"Margarines",
"Jus multifruits",
"Yaourts natures",
"Vins rouges",
"Produits à tartiner salés",
"Saucisses",
"Sucres",
"Tomates",
"Fruits tropicaux",
"Thons",
"Yaourts entiers",
"Ananas au sirop",
"Aubergines",
"Bieres-belges",
"Biscottes",
"Biscuits-aperitif",
"Biscuits-aperitifs",
"Boulangerie",
"Eaux de sources",
"Fromage-blanc-demi-ecreme",
"Fromages à tartiner",
"Fromages de chèvre",
"Gaufrettes",
"Gaufrettes-chocolatees",
"Harengs",
"Ketchup",
"Laits de coco",
"Légumes surgelés",
"Mayonnaises",
"Oeufs",
"Pâtes à tartiner au chocolat",
"Pâtes à tartiner aux noisettes et au cacao",
"Pates-tagliatelles",
"Pizzas ovales",
"Poulets",
"Produits-vendus-dans-les-annees-2000",
"Quiches",
"Sardines à l'huile d'olive",
"Sodas au citron light",
"Sodas aux fruits light",
"Tablettes de chocolat",
"Thés glacés",
"Viandes-bbq",
"Yaourts-a-l-abricot",
"Yaourts-a-l-ananas",
"Yaourts-a-la-mangue",
"Yaourts-multifruits",
"Asperges",
"en:Biscuits-aperitifs-sales",
"Fromages à pâte persillée",
"Beurres",
"en:Coffee-in-capsules",
"en:Coke",
"Jus de pomme à base de concentré",
"Crustacés",
"Yaourts à boire",
"Canards",
"Filets de poissons",
"Yaourts aromatisés",
"Fromages de France",
"Légumes frais",
"Alcools forts",
"Glaces",
"Fromages industriels",
"Plats à base de viande",
"Desserts végétaliens",
"Fruits à coques",
"Pâtisseries",
"Tartes",
"Produits sans gluten",
"Saumons",
"en:Sirop-leger",
"Desserts au soja",
"Jus de fruits 100% pur jus",
"Yaourts vanille",
"Légumes tiges",
"Vinaigres",
"Huiles d'olive vierges",
"Whiskys",
"Vins blancs",
"Vinaigres de vin",
"Vins espagnols",
"en:Worcestershire-sauce",
"Abats",
"Aioli",
"Alc7-vol",
"Aperitifs-sales",
"Asperges en conserve",
"Attieke",
"Barre-chocolate",
"Beignets-de-crevettes",
"Beurre-73",
"Beurre-et-huile-d-olive",
"Beurres demi-sel",
"Biere-belge-d-abbaye",
"Biere-d-abbaye",
"Bières à la cerise",
"Bières avec des fruits",
"Bières brunes",
"Biscuit-au-fruits",
"Biscuits-aperitifs-sales",
"Biscuits au chocolat",
"Biscuits-cigarettes",
"Biscuits-fourres",
"Biscuits-sales",
"Blé",
"Blés",
"Blés durs",
"Bles-durs-precuits",
"Blinis",
"Boison-gazeuse",
"Boisson-au-jus-de-pomme",
"Boisson-fraiche",
"Boisson-gazeuse-light-aux-fruits",
"Boissons chaudes instantanées",
"Boissons énergétiques",
"Bouillon",
"Boules-de-neige",
"Buiscuit-aperitif",
"Cafe-cappuccino-instantane",
"Cafe-en-poudre-instantane",
"Caramel-sauce",
"Caramels",
"Cassonade-de-candi-brune",
"Chicoree",
"Chocolat-70",
"Chocolat-au-lait-praline",
"Chocolat-noir-pur",
"Chocolat-praline",
"Chocolats en poudre",
"Choux-rouge-aux-pommes",
"Compotes",
"Confits de canard",
"Cornichons",
"Couscous",
"Couscous-de-manioc",
"Creem-entiere",
"Creme-culinaire",
"Creme-diluee-10-matiere-grasse",
"Crèmes dessert",
"Crèmes glacées",
"Crevettes",
"Crevettes grises",
"Cuisine-asiatique",
"Demi-ecreme",
"Eau-minerale-aromatisee",
"Eau-mineralle-naturelle",
"Eau-plate",
"Eaux-de-vie",
"Eaux gazeuses",
"Eaux minérales naturelles",
"Édulcorants",
"Enrichi-d-huile-de-colza",
"Epices-pour-viande",
"Farcies-d-anchois",
"Feuilles-de-brick",
"Filets d'anchois",
"Flocons-d-avoine",
"Foies gras",
"Fromage-a-pate-dure",
"Fromage-frais-de-chevre",
"Fromage-gouda",
"Fromage-light",
"Fromage-mi-vieux",
"Fromages à pâte fondue",
"Fromages au lait cru",
"Fromages de vache Prim'Holstein",
"Fromages des Pays-Bas",
"Fromages fondus",
"Gaspacho",
"Gauffrettes-au-miel",
"Genoise",
"Genoises",
"Gorgonzolas",
"Goudas",
"Graines",
"Graines-de-lin",
"Gueuze",
"Hache",
"Haddocks fumés",
"Halal",
"Harengs-marines",
"Haricots",
"Haricots-rouges-sauce-chili",
"Houmous",
"Houmus-piquant",
"Jambons blancs",
"Jus-d-agrumes",
"Jus-de-betteraves-rouges",
"Jus-de-fruits-a-base-de-jus-concentres",
"Jus-multi-fruits",
"Jus-multifruits-a-base-de-concentre",
"Lait-sucre",
"Laits aromatisés",
"Laits concentrés non sucrés",
"Laits d'amande",
"Laits écrémés",
"Laits frais",
"Laits-micro-filtres",
"Lasagnes à garnir",
"Lasagnes préparées",
"Légumes secs",
"Limonades",
"Maizena",
"Matiere-grasse-vegetale-a-tartiner",
"Miel-au-chocolat",
"Mistelle",
"Mollusques",
"Morues",
"Moules",
"Moutardes",
"Naturelle",
"Nougat-tendre",
"Nouilles-asiatiques",
"Nouilles-instantanees",
"Nouilles-orientales",
"Nutella",
"Oeufs plein air",
"Olive-aperitives",
"Olives-violettes",
"Opuree-de-tomate-passata",
"Pain grillé",
"Pains croustillants",
"Pains-pita",
"Pains sans gluten",
"Pate",
"Pâtes fraîches",
"Pâtes sèches",
"Petits-pois-carottes",
"Pineau des Charentes",
"Pinot-gris",
"Pistaches",
"Pizza-croquantina-biscuits-aperitifs",
"Plat-prepare-complet",
"Plats à base de canards",
"Plats à base de volaille",
"Pois-chiche",
"Poissons-prepares",
"Polenta",
"Pollen-en-pelottes",
"Pop-corn",
"Potages",
"Poudre-pudding",
"Preparation-pour-crepes",
"Produit-a-la-noisette",
"Produit-au-chocolat-au-lait",
"Produit-au-sel-de-guerande",
"Produit-de-boulangerie",
"Produits-lactes",
"Pruneaux",
"Puree-d-ail",
"Purées",
"Purées de pommes de terre",
"Reblochons",
"Rehausseur-de-gout",
"Riz Basmati",
"Riz Basmati blancs",
"Riz long grain",
"Riz pour sushi",
"Riz soufflé",
"Rosettes",
"Salades-en-conserves",
"Salades-repas",
"Sardines à l'huile et au piment",
"Sardines sans huile",
"Sauce-a-l-ail",
"Sauce-soya",
"Sauce-vinaigrette",
"Saucissons secs",
"Saucissons secs pur porc",
"Sauves",
"Sel-aux-herbes",
"Semoule",
"Sesame",
"Sirops",
"Sirops aux fruits",
"Snacking",
"Sodas aux fruits exotiques",
"Soja-a-tartiner",
"Sorbets",
"Soupes-de-nouilles",
"Soupes froides",
"Spéculoos",
"Speculoos-tendres",
"Spiruline",
"Sucres de canne",
"Sucres en morceaux",
"Sucres glaces",
"Superaliment",
"Superfood",
"Tartes salées",
"Thons à l'huile",
"Tomates-au-jus",
"Tomates-en-cubes",
"Tomates-entieres-pelees-au-jus",
"Tomates pelées",
"Tomates-poivrons",
"Tomates séchées",
"Torsades",
"Tortis",
"Veloutés",
"Verrines",
"Viandes de porc",
"Vins-d-alsace",
"Vins effervescents",
"Vins mutés",
"Vins-naturels",
"Vins pétillant",
"Yaourts-a-la-cerise",
"Yaourts-a-la-figue",
"Yaourts-au-kiwi",
"Yugourth"];
