var labelsTags = [

"Commerce équitable",
"Bio",
"Fairtrade International",
"Bio européen",
"Sans conservateurs",
"Max Havelaar",
"AB Agriculture Biologique",
"Sans colorants",
"BE-BIO-02",
"FSC",
"Végétarien",
"BE-BIO-01",
"Point Vert",
"Sans exhausteur de goût",
"Sans lactose",
"AOP",
"AOC",
"Eco-emballages",
"Empreinte carbone",
"Sans gluten",
"Sans sucre ajouté",
"Sans colorants artificiels",
"Sans glutamate",
"Pêche durable",
"Pêche durable MSC",
"Certifie-rainforest-alliance",
"Eco",
"Labels de distributeurs",
"Norge",
"Végétalien",
"en:100-fruits",
"100% naturel",
"Qualité Carrefour",
"ES-ECO-020-CV",
"Agriculture UE",
"FR-BIO-01",
"Riche en fibres",
"Colorants naturels",
"Arômes naturels",
"Sans arômes artificiels",
"Sans arômes",
"Sans OGM",
"Pur beurre",
"Rainforest Alliance",
"en:Sans-sucres-ajoutes",
"USDA Organic",
"Vegan Society",
"Vegetarian Society",
"A l'huile de tournesol",
"100-recyclable",
"100-semoule-de-ble-dur",
"30-du-cacao-rainforest-alliance",
"60-cereales",
"Au sel de Guérande",
"Aucun",
"Bio-équitable",
"Bio-nach-eg-oko-verordnung",
"Biogarantie",
"Ble-cultive-en-france",
"Bouteille-et-bouchon-enti-erement-recyclable",
"Carrefour-kraainem-a-une-tres-bonne-boulangerie",
"Convient-aux-personnes-allergiques-au-gluten",
"De-la-nature-ardennaise",
"Ecocert",
"Fumes-delicatement-au-bois-de-hetre",
"Halal",
"Iso-14001",
"Iso-9001",
"La-marque-n-1-de-vins-francais-dans-le-monde",
"Label Carrefour",
"Lait-belge",
"Lait-de-paturage",
"Made-in-respect",
"Mon-choix",
"No-oil-added",
"Oeufs-de-poules-elevees-en-plein-air",
"Origine-certifiee-sud-ouest",
"Pas-de-sel-ajoute",
"Peches-en-pleine-mer",
"Plant-bottle",
"Qualite-controlee",
"Sans-conservateur-artificiel",
"Sans-edulcorant",
"Sans-epaissisant-ajoute",
"Sans-matieres-grasses-hydrogenees",
"Sans-sulfites-ajoutes",
"Skal-4236",
"Testé par le panel test Carrefour",
"Tested-by-kids",
"Utz-certified",
"nl:Eco-emballages",
"nl:Labels-de-distributeurs",
"nl:Point-vert",
"nl:Qualite-carrefour"];
