var labelsTags = [

"Fair trade",
"Organic",
"Fairtrade International",
"EU Organic",
"No preservatives",
"Max Havelaar",
"fr:AB Agriculture Biologique",
"No colorings",
"BE-BIO-02",
"FSC",
"de:Vegetarisch",
"BE-BIO-01",
"Green Dot",
"No flavour enhancer",
"No lactose",
"PDO",
"fr:AOC",
"fr:Eco-emballages",
"Carbon footprint",
"Gluten-free",
"No added sugar",
"No artificial colors",
"No MSG",
"Sustainable fishery",
"Sustainable Seafood MSC",
"fr:Certifie-rainforest-alliance",
"fr:Eco",
"fr:Labels de distributeurs",
"fr:Norge",
"de:Vegan",
"en:100-fruits",
"100% natural",
"Carrefour Quality",
"ES-ECO-020-CV",
"EU Agriculture",
"FR-BIO-01",
"High fibres",
"Natural colorings",
"Natural flavors",
"No artificial flavors",
"No flavors",
"No GMOs",
"Pure butter",
"Rainforest Alliance",
"en:Sans-sucres-ajoutes",
"USDA Organic",
"Vegan Society",
"Vegetarian Society",
"With Sunflower oil",
"fr:100-recyclable",
"fr:100-semoule-de-ble-dur",
"fr:30-du-cacao-rainforest-alliance",
"fr:60-cereales",
"fr:Au sel de Guérande",
"fr:Aucun",
"fr:Bio-équitable",
"fr:Bio-nach-eg-oko-verordnung",
"fr:Biogarantie",
"fr:Ble-cultive-en-france",
"fr:Bouteille-et-bouchon-enti-erement-recyclable",
"fr:Carrefour-kraainem-a-une-tres-bonne-boulangerie",
"fr:Convient-aux-personnes-allergiques-au-gluten",
"fr:De-la-nature-ardennaise",
"fr:Ecocert",
"fr:Fumes-delicatement-au-bois-de-hetre",
"fr:Halal",
"fr:Iso-14001",
"fr:Iso-9001",
"fr:La-marque-n-1-de-vins-francais-dans-le-monde",
"fr:Label Carrefour",
"fr:Lait-belge",
"fr:Lait-de-paturage",
"fr:Made-in-respect",
"fr:Mon-choix",
"fr:No-oil-added",
"fr:Oeufs-de-poules-elevees-en-plein-air",
"fr:Origine-certifiee-sud-ouest",
"fr:Pas-de-sel-ajoute",
"fr:Peches-en-pleine-mer",
"fr:Plant-bottle",
"fr:Qualite-controlee",
"fr:Sans-conservateur-artificiel",
"fr:Sans-edulcorant",
"fr:Sans-epaissisant-ajoute",
"fr:Sans-matieres-grasses-hydrogenees",
"fr:Sans-sulfites-ajoutes",
"fr:Skal-4236",
"fr:Testé par le panel test Carrefour",
"fr:Tested-by-kids",
"fr:Utz-certified",
"Eco-emballages",
"Labels-de-distributeurs",
"Point-vert",
"Qualite-carrefour"];
