var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Sodas",
"Candies",
"Diet drinks",
"Diet sodas",
"Meats",
"Dairies",
"Prepared meats",
"fr:Sodas au cola",
"Alcoholic drinks",
"Fishes",
"Frozen foods",
"Fruit sodas",
"Seafood",
"Beers",
"Hot drinks",
"Milks",
"Vegetables",
"fr:Apéritif",
"fr:Sodas au citron",
"fr:Sodas au cola light",
"Fruit juices",
"Fruit juices and nectars",
"Groceries",
"Herbal teas",
"Waters",
"fr:Bonbons",
"fr:Laits végétaux",
"Breads",
"Breakfasts",
"Canned foods",
"Cereals",
"Chips and fries",
"Chocolates",
"Condiments",
"Desserts",
"Meals",
"Smoked fishes",
"Soups",
"Tunas",
"fr:Bieres-belges",
"fr:Céréales pour petit-déjeuner",
"fr:Chips",
"fr:Chips de pommes de terre",
"fr:Chips de pommes de terre à l’huile de tournesol",
"fr:Chocolats noirs",
"fr:Harengs",
"fr:Légumes surgelés",
"fr:Mueslis",
"fr:Plats cuisinés surgelés",
"fr:Sauces",
"fr:Saucissons",
"fr:Sodas au citron light",
"fr:Sodas aux fruits light",
"Apple juices",
"Biscuits",
"Cakes",
"Canned fishes",
"Canned sardines",
"Cheeses",
"Concentrated apple juices",
"Concentrated fruit juices",
"Green olives",
"Green teas",
"Olives",
"Orange juices",
"Pastas",
"Pickled vegetables",
"Pickles",
"Products without gluten",
"Salted spreads",
"Sardines",
"Spreads",
"Teas",
"Tomatoes",
"Wines",
"Wines from Spain",
"Yogurts",
"fr:Aperitifs-sales",
"fr:Barres",
"fr:Barres chocolatées",
"fr:Bières à la cerise",
"fr:Bières avec des fruits",
"fr:Bières blondes",
"fr:Biscuits-fourres",
"fr:Boisson-au-jus-de-pomme",
"fr:Boissons énergétiques",
"fr:Boissons énergisantes",
"fr:Boules-de-neige",
"fr:Cafés",
"fr:Cafés en poudre",
"fr:Cassonade-de-candi-brune",
"fr:Crèmes dessert",
"fr:Desserts au soja",
"fr:Eaux de sources",
"fr:Eaux gazeuses",
"fr:Eaux minérales",
"fr:Édulcorants",
"fr:Fromages à tartiner",
"fr:Fruits au sirop",
"fr:Hache",
"fr:Jus-de-fruits-a-base-de-jus-concentres",
"fr:Jus-multifruits",
"fr:Jus-multifruits-a-base-de-concentre",
"fr:Laits d'amande",
"fr:Laits de soja",
"fr:Légumes en conserve",
"fr:Limonades",
"fr:Pains sans gluten",
"fr:Pâtes sèches",
"fr:Poissons-prepares",
"fr:Rehausseur-de-gout",
"fr:Rosettes",
"fr:Sardines sans huile",
"fr:Saucissons secs pur porc",
"fr:Sel-aux-herbes",
"fr:Sodas aux fruits exotiques",
"fr:Soupes déshydratées",
"fr:Thés glacés",
"fr:Thons à l’huile",
"fr:Tomates-au-jus",
"fr:Tomates-entieres-pelees-au-jus",
"fr:Tomates pelées",
"fr:Verrines",
"fr:Viandes de porc",
"fr:Vins effervescents",
"fr:Vins pétillant"];
