var labelsTags = [

"Organic",
"EU Organic",
"No colorings",
"fr:AB Agriculture Biologique",
"No flavour enhancer",
"No lactose",
"No preservatives",
"Sustainable fishery",
"Sustainable Seafood MSC",
"fr:Norge",
"BE-BIO-02",
"Carbon footprint",
"Fair trade",
"FSC",
"Gluten-free",
"Max Havelaar",
"Natural colorings",
"No added sugar",
"No artificial colors",
"No artificial flavors",
"No GMOs",
"No MSG",
"Vegetarian",
"fr:60-cereales",
"fr:De-la-nature-ardennaise",
"fr:Eco",
"fr:Iso-14001",
"fr:Iso-9001",
"fr:Mon-choix",
"fr:Pas-de-sel-ajoute",
"fr:Riche-en-fibres",
"fr:Sans-conservateur-artificiel"];
