var purchase_placesTags = [

"Aywaille",
"Aywaille-en-belgique",
"Belgique",
"Belgique-bruxelles",
"Belgium",
"Bruxelles",
"Charleroi",
"Flemalle",
"France",
"Hornu",
"Liege",
"Louvain-la-neuve",
"Marche-en-famenne",
"Montmedy-france",
"Mouscron",
"Pessac-france",
"Quaregnon",
"Saint-gilles-ile-de-la-reunion-france",
"Tournai-belgique",
"Virton-belgique",
"Wanze",
"Wavre"];
