language: generic
dist: trusty
os: linux

before_script:
  - xmllint --version

script:
  - xmllint --noout img/*.svg

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    # Necessary to get xmllint available
    - libxml2-utils
