var categoriesTags = [

"Dairies",
"Beverages",
"Yogurts",
"Groceries",
"Meats",
"Alcoholic drinks",
"Drinkable yogurts",
"Spices",
"Candies",
"Canned foods",
"Prepared meats",
"Condiments",
"Vegetables and derived products",
"Biscuits",
"Cheeses",
"Fruit juices and nectars",
"Vegetables",
"Carbonated drinks",
"Fats",
"Meals",
"Fruit nectars",
"Canned fishes",
"Fishes",
"Milks",
"Seafood",
"Tomatoes",
"fr:Pizzas",
"Animal fats",
"Beers",
"Chocolates",
"Hard liquors",
"Sauces",
"Sodas",
"Waters",
"fr:Bonbons",
"fr:Eaux-de-vie",
"fr:Laits demi-écrémés",
"fr:Tomates pelées",
"Butters",
"Canned sardines",
"Canned Vegetables",
"Flavoured yogurts",
"Herbal teas",
"Hot drinks",
"Pastas",
"Sardines",
"Wines",
"Wines from Portugal",
"fr:Eaux minérales",
"fr:Laits UHT",
"fr:Sardines à l'huile",
"Cereals",
"Chili peppers",
"Hams",
"Salts",
"Sugars",
"Sweet wines",
"Teas",
"Vegetable fats",
"Vegetable oils",
"fr:Beurres salés",
"fr:Eaux gazeuses",
"fr:Fromages pasteurisés",
"fr:Poivrons",
"fr:Porto",
"Rums",
"fr:Thés glacés",
"Fortified wines",
"fr:Vins mutés de type vin doux naturel",
"Breads",
"Canned beans",
"Cow Cheeses",
"Desserts",
"Flours",
"Frozen foods",
"Fruit juices",
"Green teas",
"Olive oils",
"Peach nectars",
"Plain yogurts",
"Rices",
"Vinegars",
"Wheat flours",
"Wine vinegars",
"fr:Bières blondes",
"fr:Chocolats au lait",
"fr:Eaux minérales gazeuses",
"fr:Mayonnaises",
"fr:Moutardes",
"fr:Paprika",
"fr:Rhums agricoles",
"fr:Rhums blancs",
"fr:Saucissons",
"fr:Sodas au cola",
"fr:Sucres blancs",
"Apple juices",
"Blue-veined cheeses",
"Breakfasts",
"Cakes",
"Canned tunas",
"Chips and fries",
"Creams",
"Diet drinks",
"Diet sodas",
"Fresh vegetables",
"Fruit sodas",
"Iogurte-liquido-com-raspas-de-chocolate",
"Multifruit nectars",
"Mushrooms",
"Non-dairy desserts",
"Non-dairy yogurts",
"Poultries",
"Red ports",
"Red wine vinegars",
"Red wines",
"Sausages",
"Soups",
"Straciatella",
"Tunas",
"Whisky",
"White vinegars",
"White wines",
"es:Vegetales en conserva",
"fr:Barres",
"fr:Barres chocolatées",
"fr:Beurres doux",
"fr:Bières blanches",
"fr:Biscuits-sales",
"fr:Cacahuetes",
"fr:Calvados",
"Camemberts",
"fr:Céréales pour petit-déjeuner",
"fr:Champignons de Paris",
"fr:Chocolats noirs",
"fr:Complement-alimentaire",
"fr:Confiseries-sans-sucre",
"fr:Eaux minérales naturelles",
"fr:Farines de blé type T55",
"fr:Frites",
"fr:Frites surgelées",
"fr:Fromages à pâte fraîche",
"fr:Fromages à pâte molle à croûte fleurie",
"fr:Fromages de chèvre",
"fr:Fruits en conserve",
"fr:Jambons blancs",
"fr:Jambons crus",
"fr:Jambons fumés",
"Ketchup",
"fr:Lait-chocolate",
"fr:Laits demi-écrémés biologiques",
"fr:Laits écrémés",
"fr:Lasagnes préparées",
"fr:Madeleines",
"fr:Maïs en conserve",
"fr:Moutardes de Dijon",
"fr:Moutardes fines",
"fr:Mueslis",
"fr:Pois chiches en conserve",
"fr:Poivres",
"fr:Poivres noirs",
"fr:Poivrons rouges",
"fr:Porto Tawny",
"fr:Portos oxydatifs",
"fr:Poulets",
"fr:Saucisses sèches",
"fr:Saucissons secs pur porc",
"fr:Sels fins",
"fr:Sels marins",
"fr:Sirops",
"fr:Sodas au cola light",
"fr:Soupes déshydratées",
"fr:Sucres glaces",
"fr:Thés noirs",
"fr:Viandes de boeuf",
"fr:Viandes de porc",
"fr:Vinaigres de vins blancs",
"pt:Cervejas",
"pt:Chips",
"pt:Complementos-alimentares",
"pt:Complements-alimentaires",
"pt:Cremes-vegetais",
"pt:Epices",
"pt:Ervas-aromaticas",
"pt:Ervas-aromaticas-e-especiarias",
"pt:Graisses",
"pt:Griek",
"pt:Hortela-verde",
"pt:Iogurte-liquido-com-frutos-tropicais",
"pt:Lard",
"pt:Legumineuses",
"pt:Milk-based",
"pt:Milk-based-dessert",
"pt:Pates-alimentaires",
"pt:Pates-au-pesto",
"pt:Plantas-de-hortela-verde",
"pt:Potages",
"pt:Sobremesa-lactea",
"pt:Soupes",
"pt:Temperos",
"pt:Vinho-tinto",
"pt:Vinho-verde"];
