var labelsTags = [

"pt:Contem-leite",
"Gluten-free",
"pt:Contem-soja",
"pt:Contem-gluten",
"pt:Isento-de-gluten",
"EU Organic",
"Organic",
"pt:Contem-edulcorantes",
"pt:Contem-sulfitos",
"pt:Contem-uma-fonte-de-fenilalanina",
"pt:Contem-acucares",
"pt:Contem-cereais-com-gluten",
"pt:Sem-acucares-adicionados",
"pt:Sem-conservantes",
"pt:Sem-corantes",
"pt:Sem-gluten",
"Vegan",
"Vegetarian",
"No cholesterol",
"No colorings",
"fr:28-medailles-d-or",
"pt:Com-edulcorantes",
"pt:Contem-mostarda",
"pt:Contem-ovo",
"pt:Contem-ovos",
"pt:Contem-produtos-a-base-de-leite",
"pt:Contem-trigo",
"Fair trade",
"Fairtrade International",
"FR-BIO-01",
"Max Havelaar",
"Natural colorings",
"No preservatives",
"No sugar",
"PT-BIO-03",
"PT-BIO-04",
"Rainforest Alliance",
"fr:7-annees-d-age",
"fr:AB Agriculture Biologique",
"fr:AOC",
"fr:Appellation-calvados-controlee",
"fr:Ecocert",
"fr:Label Rouge",
"fr:Medaille-d-or",
"fr:Produit-elu-de-l-annee-2012-par-des-consommateurs-belges",
"fr:Saveurs de l'Année",
"fr:Saveurs de l'Année 2011",
"pt:0-materia-gorda",
"pt:Aop",
"pt:Casca-nao-comestivel",
"pt:Com-stevia",
"pt:Contem-acucar",
"pt:Contem-acucares-naturalmente-presentes",
"pt:Contem-avelas",
"pt:Contem-cereais",
"pt:Contem-derivados-de-ovos",
"pt:Contem-derivados-de-soja",
"pt:Contem-edulcorante",
"pt:Contem-fonte-de-fenilalanina",
"pt:Contem-lactose",
"pt:Contem-produtos-a-base-de-soja",
"pt:Curado-com-lenha-de-azinho",
"pt:Curado-em-fumeiro-tradicional",
"pt:Dop",
"pt:Earth-island-institute-dolphin-safe",
"pt:Eau-soumise-a-une-technique-d-absorption-autorisee",
"pt:Ecologico",
"pt:Ecologico-ue",
"pt:Enchido-em-tripa-natural",
"pt:Halal",
"pt:Para-profissionais",
"pt:Sem-acucares",
"pt:Sem-edulcorantes-artificiais",
"pt:Sem-lactose",
"pt:Uma-escolha-saudavel-fundacao-portuguesa-de-cardiologia",
"pt:Vegano",
"pt:Vegetariano",
"pt:Wine-spirits-2011-winery-of-the-year"];
