var statusTags = [

"A-completar",
"A-completer",
"A-verifier",
"Brands to be completed",
"Caracteristicas-a-completar",
"Caracteristicas-completadas",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categorias-a-completar",
"Categories-a-completer",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Complet",
"Completado",
"Complete",
"Completo",
"Data-de-validade-a-completar",
"Data-de-validade-completada",
"Date-limite-a-completer",
"Date-limite-completee",
"Embalagem-a-completar",
"Emballage-a-completer",
"Expiration date completed",
"Expiration date to be completed",
"Fecha-limite-de-consumo-a-completar",
"Imagenes-agregadas",
"Imagenes-validadas",
"Imagens-a-enviar",
"Imagens-a-validar",
"Imagens-enviadas",
"Imagens-validadas",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredientes-completados",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients-completes",
"Ingredients to be completed",
"Marcas-a-completar",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Pendente-de-verificacao",
"Pendiente-de-comprobacion",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be uploaded",
"Photos to be validated",
"Photos uploaded",
"Photos validated",
"Photos-validees",
"Product name to be completed",
"Quantidade-a-completar",
"Quantite-a-completer",
"Quantity to be completed",
"To be checked",
"To be completed",
"Valores-nutricionais-a-completar",
"Valores-nutricionais-completados",
"Valores-nutricionales-completados"];
