var labelsTags = [

"Contem-leite",
"Gluten-free",
"Contem-soja",
"Contem-gluten",
"Isento-de-gluten",
"EU Organic",
"Organic",
"Contem-edulcorantes",
"Contem-sulfitos",
"Contem-uma-fonte-de-fenilalanina",
"Contem-acucares",
"Contem-cereais-com-gluten",
"Sem-acucares-adicionados",
"Sem-conservantes",
"Sem-corantes",
"Sem-gluten",
"de:Vegan",
"de:Vegetarisch",
"No cholesterol",
"No colorings",
"fr:28-medailles-d-or",
"Com-edulcorantes",
"Contem-mostarda",
"Contem-ovo",
"Contem-ovos",
"Contem-produtos-a-base-de-leite",
"Contem-trigo",
"Fair trade",
"Fairtrade International",
"FR-BIO-01",
"Max Havelaar",
"Natural colorings",
"No preservatives",
"No sugar",
"PT-BIO-03",
"PT-BIO-04",
"Rainforest Alliance",
"fr:7-annees-d-age",
"fr:AB Agriculture Biologique",
"fr:AOC",
"fr:Appellation-calvados-controlee",
"fr:Ecocert",
"fr:Label Rouge",
"fr:Medaille-d-or",
"fr:Produit-elu-de-l-annee-2012-par-des-consommateurs-belges",
"fr:Saveurs de l'Année",
"fr:Saveurs de l'Année 2011",
"0-materia-gorda",
"Aop",
"Casca-nao-comestivel",
"Com-stevia",
"Contem-acucar",
"Contem-acucares-naturalmente-presentes",
"Contem-avelas",
"Contem-cereais",
"Contem-derivados-de-ovos",
"Contem-derivados-de-soja",
"Contem-edulcorante",
"Contem-fonte-de-fenilalanina",
"Contem-lactose",
"Contem-produtos-a-base-de-soja",
"Curado-com-lenha-de-azinho",
"Curado-em-fumeiro-tradicional",
"Dop",
"Earth-island-institute-dolphin-safe",
"Eau-soumise-a-une-technique-d-absorption-autorisee",
"Ecologico",
"Ecologico-ue",
"Enchido-em-tripa-natural",
"Halal",
"Para-profissionais",
"Sem-acucares",
"Sem-edulcorantes-artificiais",
"Sem-lactose",
"Uma-escolha-saudavel-fundacao-portuguesa-de-cardiologia",
"Vegano",
"Vegetariano",
"Wine-spirits-2011-winery-of-the-year"];
