var additivesTags = [

"E100 - Curcumine",
"E120 - Acide carminique",
"E133 - Bleu brillant FCF",
"E1422 - Adipate de diamidon acétylé",
"E150a - Caramels",
"E150c - Caramel ammoniacal",
"E150d - Caramel au sulfite d'ammonium",
"E160 - Caroténoïdes",
"E160a - Bêta-carotène",
"E160b - Rocou",
"E160c - Extrait de paprika",
"E200 - Acide sorbique",
"E202 - Sorbate de potassium",
"E220 - Anhydride sulfureux",
"E224 - Disulfite de potassium",
"E250 - Nitrite de sodium",
"E252 - Nitrate de potassium",
"E262 - Acétates de sodium",
"E282 - Propionate de calcium",
"E290 - Dioxyde de carbone",
"E300 - Acide ascorbique",
"E301 - Ascorbate de sodium",
"E304 - Acide palmityle-6-L-ascorbique",
"E306 - Extrait riche en tocophérols",
"E307 - Alphatocophérol",
"E310 - Gallate de propyle",
"E316 - Erythorbate de sodium",
"E320 - Buthylhydroxyanisol",
"E322 - Lécithines",
"E325 - Lactate de sodium",
"E326 - Lactate de potassium",
"E330 - Acide citrique",
"E331 - Citrates de sodium",
"E335 - Tartrate monosodique",
"E338 - Acide orthophosphorique",
"E339 - Orthophosphates de sodium",
"E385 - Éthylène diamine tétra-acétate de calcium disodium",
"E407 - Carraghénanes",
"E407a - Algues euchema transformées",
"E410 - Farine de graines de caroube",
"E412 - Gomme de guar",
"E415 - Gomme xanthane",
"E420 - Sorbitol",
"E428 - Gélatine",
"E440 - Pectines",
"E440a - Pectine",
"E441 - Gélatine animale",
"E450 - Sels métalliques de diphosphates",
"E451 - Triphosphates",
"E463 - Hydroxypropylcellulose",
"E470b - Stéarate de magnésium",
"E471 - Mono- et diglycérides d'acides gras alimentaires",
"E476 - Esters polyglycériques d'acides gras d'huile de ricin",
"E481 - Stéaroyl-2-lactylate de sodium",
"E500 - Carbonates de sodium",
"E524 - Hydroxyde de sodium",
"E536 - Ferrocyanure de potassium",
"E554 - Silicate alumino-sodique",
"E621 - Glutamate monosodique",
"E627 - Guanylate disodique",
"E631 - Inosinate disodique",
"E950 - Acésulfame K",
"E951 - Aspartame",
"E953 - Isomalt",
"E955 - Sucralose"];
