var categoriesTags = [

"Beverages",
"Groceries",
"Dairies",
"Alcoholic drinks",
"Spices",
"Iogurtes",
"Condiments",
"Meats",
"Candies",
"Prepared meats",
"Cheeses",
"Hard liquors",
"fr:Bonbons",
"fr:Eaux-de-vie",
"Beers",
"Carbonated drinks",
"Herbal teas",
"Hot drinks",
"Vegetables",
"Wines",
"Wines from Portugal",
"Iogurte",
"Canned fishes",
"Canned foods",
"Chili peppers",
"Fishes",
"Seafood",
"Sodas",
"Sweet wines",
"Teas",
"fr:Fromages pasteurisés",
"fr:Poivrons",
"fr:Porto",
"Rum",
"fr:Vins mutés",
"fr:Vins mutés de type vin doux naturel",
"Canned sardines",
"Cow Cheeses",
"Flours",
"Fruit juices and nectars",
"Green teas",
"Meals",
"Milks",
"Salts",
"Sardines",
"Sauces",
"Vegetables and derived products",
"Vinegars",
"Waters",
"Wheat flours",
"Wine vinegars",
"fr:Bières blondes",
"fr:Paprika",
"fr:Rhums agricoles",
"fr:Rhums blancs",
"fr:Sardines à l'huile",
"fr:Saucissons",
"Conserves-de-poisson",
"Diary",
"Queijos",
"Animal fats",
"Blue-veined cheeses",
"Butters",
"Chocolates",
"en:Creamy-white-sugared-yogurt",
"en:Dairy-product",
"Desserts",
"Diet drinks",
"Diet sodas",
"Fats",
"Fresh vegetables",
"Fruit juices",
"Fruit nectars",
"Hams",
"en:Iogurte-liquido-com-raspas-de-chocolate",
"en:Liquid-yoghurt",
"Pastas",
"Red ports",
"Red wine vinegars",
"Red wines",
"Soups",
"en:Straciatella",
"Sugars",
"Whisky",
"White vinegars",
"White wines",
"es:Pan-de-molde",
"fr:Beurres doux",
"fr:Bières blanches",
"fr:Biscuits-sales",
"fr:Cacahuetes",
"fr:Calvados",
"fr:Camemberts",
"fr:Chocolats au lait",
"fr:Complement-alimentaire",
"fr:Confiseries-sans-sucre",
"fr:Eau-gazeifiee",
"fr:Eaux gazeuses",
"fr:Eaux minérales",
"fr:Farines de blé type T55",
"fr:Fromages à pâte fraîche",
"fr:Fromages à pâte molle à croûte fleurie",
"fr:Jambons blancs",
"fr:Laits demi-écrémés",
"fr:Laits écrémés",
"fr:Laits UHT",
"fr:Mayonnaises",
"fr:Moutardes",
"fr:Moutardes de Dijon",
"fr:Moutardes fines",
"fr:Pizzas",
"fr:Poivres",
"fr:Poivres noirs",
"fr:Poivrons rouges",
"fr:Porto Tawny",
"fr:Portos oxydatifs",
"fr:Saucisses sèches",
"fr:Saucissons secs pur porc",
"fr:Sels marins",
"fr:Sirops",
"fr:Sodas au cola",
"fr:Sodas au cola light",
"fr:Soupes déshydratées",
"fr:Sucres blancs",
"fr:Thés noirs",
"fr:Viandes de boeuf",
"fr:Vinaigres de vins blancs",
"Agua",
"Aguas",
"Bebidas-sem-acucar",
"Beurre",
"Biere",
"Biscoitos",
"Bolachas",
"Cervejas",
"Charcuterie",
"Chips",
"Complementos-alimentares",
"Complements-alimentaires",
"Conserves-de-legumes",
"Epices",
"Ervas-aromaticas",
"Ervas-aromaticas-e-especiarias",
"Frescos",
"Gelados",
"Graisses",
"Griek",
"Hortela-verde",
"Iogurte-liquido",
"Iogurte-liquido-com-frutos-tropicais",
"Iogurte-natural",
"Jambon",
"Jambon-fume",
"Lacticinio",
"Legumineuses",
"Milk-based",
"Milk-based-dessert",
"Pates-alimentaires",
"Pates-au-pesto",
"Plantas-de-hortela-verde",
"Potages",
"Sobremesa-lactea",
"Soupes",
"Temperos",
"Vinho-tinto",
"Vinho-verde"];
