var labelsTags = [

"EU Organic",
"Organic",
"No colorings",
"fr:28-medailles-d-or",
"de:Vegan",
"de:Vegetarisch",
"Fair trade",
"Fairtrade International",
"FR-BIO-01",
"Max Havelaar",
"Natural colorings",
"No preservatives",
"PT-BIO-03",
"Rainforest Alliance",
"en:Sem-lactose",
"fr:7-annees-d-age",
"fr:AB Agriculture Biologique",
"fr:AOC",
"fr:Appellation-calvados-controlee",
"fr:Ecocert",
"fr:Label Rouge",
"fr:Medaille-d-or",
"fr:Produit-elu-de-l-annee-2012-par-des-consommateurs-belges",
"fr:Saveurs de l'Année",
"fr:Saveurs de l'Année 2011",
"Aop",
"Eau-soumise-a-une-technique-d-absorption-autorisee",
"Ecologico",
"Ecologico-ue",
"Vegano",
"Vegetariano",
"Wine-spirits-2011-winery-of-the-year"];
