var unknown_nutrientsTags = [

"Alpha-linolenic-acid-ala-18-3-n-3",
"Ca2-par-litre",
"Cl-par-litre",
"Co2",
"Equivalente-em-sal",
"Flavonoides",
"Hco3-par-litre",
"Linoleic-acid-la-18-2-n-6",
"Mg2-par-litre",
"Mineralisation-totale-par-litre",
"Na-par-litre",
"Nitrates",
"No3-par-litre",
"Omega-3-fatty-acids",
"Omega-6-fatty-acids",
"Residu-sec-a-180",
"Sio2-par-litre",
"Sulfate"];
