var categoriesTags = [

"Beverages",
"Waters",
"fr:Eaux minérales",
"Choclate",
"Cakes",
"Dairies",
"Fats",
"Flavors",
"Food additives",
"Fresh",
"Frozen foods",
"Ice creams",
"Ice creams and sorbets",
"Margarines",
"Milks",
"Vegetable fats",
"fr:Crèmes glacées",
"fr:Laits demi-écrémés",
"fr:Laits frais",
"fr:Laits-micro-filtres"];
