var categoriesTags = [

"Boissons",
"Eaux",
"Eaux minérales",
"ar:Choclate",
"Gâteaux",
"Produits laitiers",
"Matières grasses",
"Arômes",
"Additifs alimentaires",
"Frais",
"Surgelés",
"Glaces",
"Glaces et sorbets",
"Margarines",
"Laits",
"Matières grasses végétales",
"Crèmes glacées",
"Laits demi-écrémés",
"Laits frais",
"Laits-micro-filtres"];
