title: Product update API V3 (WRITE)
type: object
description: Model for creating or updating products using the v3 version of the product update API.
examples: []
allOf: 
  - $ref: ./product_type.yaml
  - $ref: ./tags/tags-write.yaml
  - type: object
    properties:
      packagings:
        $ref: ./packagings/packagings-write.yaml
      packagings_add:
        $ref: ./packagings/packagings-write.yaml
      packagings_complete:
        $ref: ./packagings/packagings_complete.yaml
      lang:
        type: string
        minLength: 2
        maxLength: 2
        example: fr
        description: 2 letter language code of the main language of the product (the most prominent on the packaging)
      quantity:
        type: string
      serving_size:
        type: string
      images:
        type: object
        properties:
          selected:
            description: |
              Images with specific information (e.g. front, ingredients, nutrition, packaging) for specific languages.
              Each selected image is a cropped version of an uploaded image.
            type: object
            $ref: "./image_selected.yaml#/components/schemas/ImagesSelected"

