type: object
properties:
  preparation:
    type: string
    enum:
      - as_sold
      - prepared
    description: |
      Indicates whether the nutrition values refer to the product *as_sold* or *prepared*.

      The preparation state affects nutrient values.
  per:
    type: string
    enum:
      - 100g
      - 100ml
      - 1l
      - 1kg
      - serving
    description: |
      The nutrition data on the package can be per serving, per 100g, per 100ml, per 1l or per 1kg.

      For a food, `1kg` is only used for the carbon footprint (e.g. 0.48 kg CO₂e per kg of product).

      This is essential to understand if values in the `nutrients` object apply for a serving, for 100g or for 100ml.