components:
  schemas:
    ProductNutritionDataV3:
      type: object
      title: Product Nutrition Data
      description: |
        Nutrition fields of a product

        Most of these properties are read-only.

        See [how to add nutrition data](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-cheatsheet/#add-nutrition-facts-values-units-and-base)
      properties:
        nutrition:
          type: object
          description: |
            todo
          properties:
            nutrient_set_preferred:
              type: object
              description: | 
                todo
              allOf:
                - $ref: "../schemas/product_nutrition_properties.yaml"
                - $ref: "../schemas/nutrients_v3.yaml"
            #$ref: "../schemas/nutrients_v3.yaml"
            nutrient_sets:
              type: array
              description: |
                An array of nutrient sets of the product.

                Each nutrient set represents a version of the nutrition facts, defined by a combination of:
                - the preparation state (e.g. *as_sold* or *prepared*),
                - the reference quantity (*per 100g*, *per 100ml* or *per serving*), and
                - the source of the data (e.g. *packaging*, *manufacturer*, *estimate*).

                This structure allows capturing multiple nutritional profiles for a single product.
              items:
                type: object
                allOf:
                  - $ref: "../schemas/nutrients_v3.yaml"
                  - $ref: "../schemas/product_nutrition_properties.yaml"
                  - type: object
                    properties:
                      source:
                        type: string
                        enum:
                          - packaging
                          - manufacturer
                          - usda
                          - estimate
                        description: |
                          The nutrition data of products can be obtained through several sources.
                      source_description:
                        type: string
                        description: |
                          A description of the source used for this nutrition set.

                          This provides more information on how and when the source was used.
                        examples:
                          - USDA non-branded foods 2025/04
                          - Import from org-nestle-france through Equadis
                          - "Estimate from ingredients”, “Estimate from category: Olive oils"
                      last_updated_t:
                        type: integer
                        description: |
                          A timestamp indicating when this nutrition set was last updated.
                        examples:
                          - 1631270265
                          - 1512153487
                      unspecific_nutrients(optional):
                        type: array
                        description: |
                          todo
                        items:
                          type: string
                          description: |
                            todo
                          example: ["fibers"]
                          
