type: object
description: |
  This is data that is linked to products data quality
properties:
  data_quality_bugs_tags:
    type: array
    items:
      type: string
      description: |
        Each data quality bug describes a data quality bug on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_errors_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality Error describes a data quality error on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_info_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality Info describes a data quality info on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality tag describes a data quality issue on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_warnings_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality warning tag describes a data quality warning on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_sources:
    type: string
    description: |
      Source of data imported from producers.
  data_sources_tags:
    type: array
    items:
      type: string
  last_check_dates_tags:
    type: array
    items:
      type: string
  last_checked_t:
    type: integer
  last_checker:
    type: string

  states:
    description: |
      comma separated list of values indicating some states of the product,
      like things to be done, or to be completed.
      See [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
    type: string
  states_hierarchy:
    type: array
    items:
      type: string
  states_tags:
    type: array
    items:
      description: |
        Each state describe something that is completed or is to be done or improved on the product.

        Refer to [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
      type: string

  misc_tags:
    description: |
      Information about different aspect of the product
        Refer to [misc taxonomy](https://static.openfoodfacts.org/data/taxonomies/misc.json)
    type: array
    items:
      type: string
