type: object
title: Product-Images
description: |
  Information about Images of a product.

  Images ensure the reliability of Open Food Facts data.
  It provides a primary source and proof of all the structured data.
  You may therefore want to display it along the structured information.

  See also tutorials about images:
  * [Getting images](https://openfoodfacts.github.io/openfoodfacts-server/api/how-to-download-images/)
  * [Uploading images](https://openfoodfacts.github.io/openfoodfacts-server/api/tutorial-uploading-photo-to-a-product/)
properties:
  images:
    description: |
      This contains properties for all images contained on the product.
    type: object
    title: product_images_properties
    properties:
      front:
        $ref: "./image_role.yaml#/components/schemas/ImageRole"

    additionalProperties:
      $ref: "./image.yaml#/components/schemas/Image"
    propertyNames:
      type: integer

    patternProperties:
      '(?<imgid>\d+)':
        description: |
          See property `1` to get the real type of those objects
          (Put this way because of a [bug in rapidoc](https://github.com/rapi-doc/RapiDoc/issues/880))
        type: string
      '(?<image_type>front|nutrition|ingredients|packaging|other)_(?<language_code>\w\w)':
        description: |
          See property `front` to get the real type of those objects
          (Put this way because of a [bug in rapidoc](https://github.com/rapi-doc/RapiDoc/issues/880))
        type: string

  last_image_dates_tags:
    type: array
    items:
      type: string
  last_image_t:
    description: timestamp of last image upload (or update?)
    type: integer

  selected_images:
    type: object
    title: product_selected_images
    description: |
      URL for selected (important) images of the product.

      This is very handy if you display the product to users.
    properties:
      front:
        $ref: "./image_urls.yaml#/components/schemas/SelectedImage"

    patternProperties:
      "(?<image_type>front|packaging|ingredients|nutrition|other)":
        description: |
          See property `front` to get the real type of those objects
          (Put this way because of a [bug in rapidoc](https://github.com/rapi-doc/RapiDoc/issues/880))
        type: string

  image_small_url:
    type: string
    description: URL for the small (200px max) image
  image_thumb_url:
    type: string
    description: URL for the thumbnail (100px max) image
  image_url:
    type: string
    description: URL for the display (400px max) image
  image_front_small_url:
    type: string
    description: |
      URL for the small version (200px max) of the front image. 
      This is the front product image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.
  image_front_thumb_url:
    type: string
    description: |
      URL for the thumbnail version (100px max) of the front image.
      This is the front product image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.
  image_front_url:
    type: string
    description: |
      URL for the display version (400px max) of the front image.
      This is the front product image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.
  image_nutrition_small_url:
    type: string
    description: |
      URL for the small version (200px max) of the nutrition image.
      This is the nutrition image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.
  image_nutrition_thumb_url:
    type: string
    description: |
      URL for the thumbnail version (100px max) of the nutrition image.
      This is the nutrition image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.
  image_nutrition_url:
    type: string
    description: |
      URL for the display version (400px max) of the nutrition image.
      This is the nutrition image in the requested language if available, 
      otherwise in the main product language.
      
      **IMPORTANT:** you should use `selected_images` field instead of this one.

patternProperties:
  "^image_(front|ingredients|nutrition|packaging|other)_url$":
    description: |
      URL for the display version (400px max) of product images.
      
      The image is the one for current language (affected by `lc` parameter) if an image exists for this language, the image in main product language otherwise.

      **IMPORTANT:** you should use `selected_images` field instead of these individual URL fields.
    type: string
  "^image_(front|ingredients|nutrition|packaging|other)_small_url$":
    description: |
      URL for the small version (200px max) of product images.
      
      The image is the one for current language (affected by `lc` parameter) if an image exists for this language, the image in main product language otherwise.

      **IMPORTANT:** you should use `selected_images` field instead of these individual URL fields.
    type: string
  "^image_(front|ingredients|nutrition|packaging|other)_thumb_url$":
    description: |
      URL for the thumbnail version (100px max) of product images.
      
      The image is the one for current language (affected by `lc` parameter) if an image exists for this language, the image in main product language otherwise.

      **IMPORTANT:** you should use `selected_images` field instead of these individual URL fields.
    type: string
