components:
  schemas:
    ProductTagsV3:
      type: object
      title: Product Tags
      allOf:
      - $ref: './product_base_tags.yaml'
      - type: object
        properties:
          tags_sources:
            type: object
            description: |
              All the relevant data on the sources of the different tags of the product.
              The data is sorted by the sources from which the tags are obtained, e.g. packaging, producer, predicted.
              The current sources are:
                - packaging: what is written on the packaging of the product
                - manufacturer: information that was sent directly from the manufacturer to Open Food Facts, through our producers platform
                - ingredients: information that is derived from the ingredients list (e.g. allergens and traces)
                - database-* (e.g. database-usda): information from another open database
                - label-* (e.g. label-non-gmo-project): information from a label organization (e.g. some labels send us lists of products that have the label)
              New sources may be added at anytime, so we are using patternProperties to make sure parsing does not break if a new source is encountered.
            patternProperties:
              "^[a-z]+(_-[a-z]+)*$":
                type: object
                description: |
                  A tag type such as "categories", "labels", "stores"
                patternProperties:
                  "^[a-z]+(_-[a-z]+)*$":
                    type: object
                    description: |
                      A source such as "packaging", "manufacturer" or "ingredients"
                    properties:
                      last_updated_t:
                        type: string
                        description: |
                          Timestamp indicating when tags related to this source were last updated.
                      tags:
                        type: array
                        description: |
                          The specific tags related to this source.
                        items:
                          type: string
                        example: ["en:organic"]
            example:
              packaging:
                categories:
                  last_updated_t: "2026-02-22T10:00:00Z"
                  tags:
                    - en:organic
                    - en:vegetarian
                labels:
                  last_updated_t: "2026-02-22T10:00:00Z"
                  tags:
                    - en:fair-trade
              manufacturer:
                categories:
                  last_updated_t: "2026-02-22T10:00:00Z"
                  tags:
                    - en:organic
