var categoriesTags = [

"Beverages",
"Dairies",
"Meals",
"fr:Bio",
"Desserts",
"Candies",
"Biscuits",
"Meats",
"Cheeses",
"Vegetables",
"Groceries",
"Seafood",
"Prepared meats",
"Frozen foods",
"Chocolates",
"Cereals",
"Fishes",
"Canned foods",
"Fruit juices and nectars",
"Breakfasts",
"Carbonated drinks",
"Fruit juices",
"fr:Gouter",
"fr:Sauces",
"Sodas",
"Wines",
"Pastas",
"Hot drinks",
"Alcoholic drinks",
"Yogurts",
"Breads",
"Cakes",
"Fats",
"fr:Apéritif",
"Cow Cheeses",
"fr:Pates",
"fr:Céréales pour petit-déjeuner",
"Fresh",
"Milks",
"Rices",
"fr:Compotes",
"fr:Légumes en conserve",
"fr:Chocolats noirs",
"Herbal teas",
"Red wines",
"Condiments",
"Spreads",
"fr:Plats cuisinés surgelés",
"Hams",
"Farming products",
"fr:Fromages pasteurisés",
"Baby foods",
"Spices",
"Soups",
"Chips and fries",
"Beers",
"fr:Cafés",
"fr:Plats préparés à réchauffer au micro-ondes",
"Animal fats",
"Canned fishes",
"Butters",
"Sweet spreads",
"Vegetable fats",
"fr:Oeufs",
"fr:Bonbons",
"Orange juices",
"Teas",
"Ice creams and sorbets",
"Smoked fishes",
"Squeezed juices",
"Waters",
"Salmons",
"Vegetable oils",
"fr:Chocolats au lait",
"Dried fruits",
"fr:Sirops",
"Ice creams",
"Sandwiches",
"fr:Chips",
"fr:Saucissons",
"fr:Compotes de pomme",
"fr:Fromages à pâte molle à croûte fleurie",
"Fresh vegetables",
"fr:Biscuits au chocolat",
"fr:Jambons blancs",
"fr:Moutardes",
"Sardines",
"Sausages",
"fr:Sauces tomate",
"Fruits",
"Poultries",
"Tunas",
"fr:Sodas au cola",
"fr:Saumons fumés",
"Creams",
"Vinegars",
"fr:Biscottes",
"fr:Mueslis",
"fr:Barres",
"fr:Eaux minérales",
"fr:Fromages à pâte fraîche",
"fr:Laits végétaux",
"Diet drinks",
"Fruit sodas",
"Sugars",
"Canned sardines",
"Fruit yogurts",
"fr:Limonades",
"Diet sodas",
"fr:Légumes secs",
"fr:Pâtes fraîches",
"fr:Plats préparés frais",
"Apple juices",
"Flours",
"French cheeses",
"White wines",
"fr:Laits demi-écrémés",
"Jams",
"Olives",
"Pickled vegetables",
"Pickles",
"fr:Beurres doux",
"fr:Pains de mie",
"fr:Camemberts",
"fr:Cidres",
"Labeled products",
"fr:Pains azymes",
"fr:Plats préparés en conserve",
"fr:Bières blondes",
"fr:Charcuteries diverses",
"fr:Crêpes et galettes",
"fr:Maquereaux",
"fr:Oeufs plein air",
"fr:Yaourts natures",
"Pastries",
"fr:Cafés moulus",
"fr:Galettes de céréales",
"fr:Lardons",
"fr:Pizzas",
"fr:Ravioli",
"fr:Crèmes fraîches",
"fr:Fromages à pâte pressée cuite",
"fr:Pâtes à tartiner",
"fr:Sablés",
"fr:Saumons fumés d'élevage",
"fr:Semoule-de-ble-dur",
"fr:Crèmes glacées",
"fr:Laits UHT",
"fr:Salades",
"fr:Sardines à l'huile",
"fr:Sucrerie",
"Mushrooms",
"fr:Couscous",
"fr:Fromages blancs",
"fr:Fromages de chèvre",
"fr:Fromages râpés",
"fr:Poulets",
"fr:Saucisses françaises",
"Bee products",
"fr:Mayonnaises",
"fr:Riz long grain",
"fr:Sodas au cola light",
"fr:Spaghetti",
"fr:Tablettes de chocolat",
"Meta-category",
"Olive oils",
"fr:Maïs en conserve",
"fr:Quenelles",
"Concentrated fruit juices",
"Cookies",
"Crustaceans",
"Green teas",
"Honeys",
"Nuts",
"Stirred yogurts",
"fr:Barres de céréales",
"fr:Brioches",
"fr:Crèmes dessert",
"fr:Riz Basmati",
"fr:Vins rosés",
"Emmentaler",
"Salts",
"Squeezed orange juices",
"fr:Chocolats en poudre",
"fr:Filets de Maquereaux",
"fr:Fruits au sirop",
"fr:Sans-gluten",
"Salted spreads",
"Vegetable rods",
"fr:Bourgogne",
"fr:Purées",
"fr:Taboulés",
"Chocolate desserts",
"Hard liquors",
"Meals with meat",
"Rillettes",
"fr:Gâteaux apéritifs",
"fr:Lardons fumés",
"fr:Sauces pour pâtes",
"Breaded products",
"Potatoes",
"fr:Dès 12 mois",
"fr:Lentilles",
"fr:Oeufs labellisés",
"Tomatoes",
"Wheat flours",
"fr:Beurres demi-sel",
"fr:Biscuits-aperitifs",
"fr:Chewing-gum",
"fr:Frites",
"fr:Légumes surgelés",
"fr:Lentilles sèches",
"fr:Pâtes à tarte",
"fr:Plats principaux pour bébé",
"fr:Semoule",
"fr:Soupes déshydratées",
"fr:Thés glacés",
"fr:Thons albacore",
"fr:Thons au naturel",
"fr:Thons tropicaux",
"fr:Veloutés",
"Balsamic vinegars",
"Green olives",
"Products with reduced salt",
"Waffles",
"fr:Barres chocolatées",
"fr:Dès 06 mois",
"fr:Fromage à pâte pressée cuite",
"fr:Laits de soja",
"fr:Laits pour bébé",
"fr:Poissons panés",
"fr:Sardines à l'huile d'olive",
"fr:Soja",
"fr:Sucres de canne",
"fr:Viandes de porc",
"Bordeaux",
"Drinkable yogurts",
"Virgin olive oils",
"fr:Chips de pommes de terre",
"fr:Cornichons",
"fr:Crêpes",
"fr:Crevettes",
"fr:Eaux-de-vie",
"fr:Fromages à pâte pressée non cuite",
"fr:Galettes",
"fr:Moutardes de Dijon",
"fr:Poivres",
"Culinary plants",
"fr:Bouillon",
"fr:Jambons crus",
"fr:Lasagnes préparées",
"fr:Mozzarella",
"fr:Produits Label Rouge",
"fr:Quinoa",
"fr:Raviolis en conserve",
"fr:Riz long",
"Black olives",
"Fruit nectars",
"fr:Champignons de Paris",
"fr:Chips de pommes de terre à l’huile de tournesol",
"fr:Compotes pommes nature",
"fr:Eaux gazeuses",
"fr:Fromages au lait cru",
"fr:Haricots-verts",
"fr:Haricots verts en conserve",
"fr:Infusion-bio",
"fr:Jambons de Paris",
"fr:Petits beurres",
"fr:Plats préparés surgelés",
"fr:Thés noirs",
"Food additives",
"Whole milk yogurts",
"fr:Chocolats dessert",
"fr:Corn-flakes",
"fr:Eaux de sources",
"fr:Foies gras",
"fr:Fromages à tartiner",
"fr:Fromages italiens",
"fr:Goûters et desserts pour bébé",
"fr:Pain grillé",
"fr:Pâtes à tartiner aux noisettes",
"fr:Saucissons secs pur porc",
"fr:Sodas à l'orange",
"fr:Steaks-haches",
"Aromatic plants",
"Artisan products",
"French wines",
"Grapefruit juices",
"Pineapple juices",
"fr:Amandes",
"fr:Beurres moulés",
"fr:Blancs de poulet",
"fr:Boissons énergisantes",
"fr:Cafes-en-dosettes",
"fr:Chocolats de dégustation",
"fr:Dessert-lacte",
"fr:Emmentals rapés",
"fr:Galettes de riz",
"fr:Glaces au chocolat",
"fr:Gouters",
"fr:Ketchup",
"fr:Maquereaux en conserve",
"fr:Oeufs Label Rouge",
"fr:Pains azymes à la farine de froment",
"fr:Poissons surgelés",
"fr:Salades composées",
"fr:Sirops de menthe",
"fr:Vin-rouge-bio",
"Asparagus",
"Blue-veined cheeses",
"Concentrated orange juices",
"Grape juices",
"Pies",
"Potted meats",
"Sweetened yogurts",
"fr:Boisson-aux-fruits",
"fr:Charcuteries à teneur réduite en sel",
"fr:Choucroutes",
"fr:Cidres demi-secs",
"fr:Comté",
"fr:Coquillettes",
"fr:Desserts au soja",
"fr:Eaux minérales naturelles",
"fr:Fromages AOC",
"fr:Fromages labéllisés",
"fr:Gratins",
"fr:Hachis parmentier",
"fr:Laits écrémés",
"fr:Lentilles vertes",
"fr:Mousses au chocolat",
"fr:Petits-pois",
"fr:Plats à base de viande bovine",
"fr:Produits AOC",
"fr:Raviolis frais",
"fr:Surimi",
"fr:Terrines",
"fr:The-bio",
"fr:Vins effervescents",
"Soft cheeses with washed rind",
"Tropical fruits",
"fr:Aide-culinaire",
"fr:Blé",
"fr:Champagne",
"fr:Cordons bleus",
"fr:Crabes",
"fr:Crèmes fraîches épaisses",
"fr:Dès 04 mois",
"fr:Epinards",
"fr:Filets de sardine",
"fr:Fromages fondus",
"fr:Gateaux-pour-le-petit-dejeuner",
"fr:Haricots",
"fr:Jambons blancs à teneur réduite en sel",
"fr:Jus-multifruits",
"fr:Menus Viandes pour bébé",
"fr:Miels de fleurs",
"fr:Nems",
"fr:Noix-de-cajou",
"fr:Pains de mie complet",
"fr:Pâtes feuilletées",
"fr:Plats à base de volaille",
"fr:Pop-corn",
"fr:Quenelles de poisson",
"fr:Riz cargo",
"fr:Riz thaï",
"fr:Sauces au soja",
"fr:Sirops de grenadine",
"fr:Soupes de légumes",
"fr:Tagliatelles",
"fr:Tomates en conserve",
"Aromatic herbs",
"Dried hams",
"Ducks",
"Sunflower oils",
"Walnut oils",
"Wine vinegars",
"fr:Agrumes",
"fr:Assaisonnements",
"fr:Cacahuetes",
"fr:Chocolats blancs",
"fr:Colins",
"fr:Complement-alimentaire",
"fr:Compotes à boire",
"fr:Coulommiers",
"fr:Farines de blé type T45",
"fr:Fromages-a-pate-molle",
"fr:Fromages industriels",
"fr:Hamburgers",
"fr:Haricots en conserve",
"fr:Jus-de-citron",
"fr:Laits de croissance",
"fr:Laits entiers",
"fr:Légumes préparés",
"fr:Macedoine-de-legumes",
"fr:Madeleines",
"fr:Nouilles",
"fr:Oeufs biologiques",
"fr:Pain-d-epices",
"fr:Pains de seigle",
"fr:Parmigiano Reggiano",
"fr:Pâtes brisées",
"fr:Pistaches",
"fr:Produit-frais",
"fr:Quenelles nature",
"fr:Raviolis au boeuf",
"fr:Rillettes de poissons",
"fr:Sauces bolognaises",
"fr:Sauces Pesto",
"fr:Saucisses de Strasbourg",
"fr:Saucissons secs",
"fr:Sodas au citron",
"fr:Sodas aux fruits light",
"fr:Sorbets",
"fr:Spaghettis au blé dur",
"fr:Sucres en morceaux",
"fr:Taboulés orientaux",
"fr:Thons à l’huile",
"fr:Truites fumées",
"Chili peppers",
"Fish fillets",
"Flavors",
"Margarines",
"Mountain products",
"Pitted olives",
"Products without gluten",
"fr:Alcools artisanaux",
"fr:Aromates",
"fr:Bacon",
"fr:Biscuits-sales",
"fr:Biscuits-sucres",
"fr:Bonbons-de-chocolat",
"fr:Bouillons",
"fr:Boulgour",
"fr:Carottes",
"fr:Chipolatas",
"fr:Chorizos",
"fr:Cidres doux",
"fr:Confitures de fraises",
"fr:Cookies au chocolat",
"fr:Crèmes dessert chocolat",
"fr:Crèmes fraîches liquides",
"fr:Croutons",
"fr:Dattes",
"fr:Dès 10 mois",
"fr:Dietetique",
"fr:Emmentals français",
"fr:Fromages à pâte filée",
"fr:Gaufrettes",
"fr:Haricots-blancs",
"fr:Laits de coco",
"fr:Laits demi-écrémés biologiques",
"fr:Levure",
"fr:Merguez",
"fr:Pâtes sèches",
"fr:Petits pois en conserve",
"fr:Plats du soir pour bébé",
"fr:Pois-chiches",
"fr:Pruneaux",
"fr:Pruneaux d’Agen",
"fr:Purées de pommes de terre",
"fr:Rhums",
"fr:Rillettes de porc",
"fr:Rillettes de viande rouge",
"fr:Sandwich polaire",
"fr:Sardines à l'huile de tournesol",
"fr:Sauces-vinaigrettes",
"fr:Sirops de fraise",
"fr:Steaks-haches-surgeles",
"fr:Sucre-en-poudre",
"fr:Tofu",
"Cider vinegars",
"Concentrated apple juices",
"Flavoured yogurts",
"Green pitted olives",
"Lemons",
"Sheep's milk yogurts",
"fr:Abricots secs",
"fr:Bières ambrées",
"fr:Bières blanches",
"fr:Biscuits feuilletés",
"fr:Biscuits pour bébé",
"fr:Boisson-au-soja",
"fr:Boissons-aux-fruits",
"fr:Cafés en poudre",
"fr:Camemberts au lait cru",
"fr:Caramels",
"fr:Carottes râpées",
"fr:Coeurs de palmier",
"fr:Compotes pommes fraise",
"fr:Confits de canard",
"fr:Cordons bleus de dinde",
"fr:Cotes-du-rhone",
"fr:Curry",
"fr:Dès 18 mois",
"fr:Eaux arômatisées",
"fr:Édulcorants",
"fr:Farfalle",
"fr:Frites surgelées",
"fr:Fromages à pâte fondue",
"fr:Fromages à pâte persillée français",
"fr:Fromages de brebis",
"fr:Fruits-confits",
"fr:Gateaux-au-chocolat",
"fr:Genoise",
"fr:Gratins de légumes",
"fr:Herbes de Provence",
"fr:Jus de pamplemousse rose",
"fr:Jus-de-soja",
"fr:Laits 2ème âge",
"fr:Laits concentrés",
"fr:Laits en poudre",
"fr:Lentilles corail",
"fr:Liqueurs",
"fr:Maïs doux",
"fr:Mayonnaises de Dijon",
"fr:Plats à base de canards",
"fr:Poivres moulus",
"fr:Poivres noirs",
"fr:Poivrons",
"fr:Raclettes",
"fr:Raisins secs",
"fr:Raviolis au fromage",
"fr:Salade-preparee",
"fr:Sardines à la tomate",
"fr:Sauces Pesto Rosso",
"fr:Saucisses sèches",
"fr:Sels fins",
"fr:Sels naturels",
"fr:Sucres blancs",
"fr:Sucres roux",
"fr:Suppléments",
"fr:Suppléments fastfoods",
"fr:Surimis",
"fr:Tapenade",
"fr:Torsades",
"fr:Tortellini",
"fr:Viande-hachee",
"fr:Wrap",
"fr:Yaourts-au-bifidus",
"Products sold before year 2000",
"Vanilla yogurts",
"fr:Artichauts en conserve",
"fr:Baguettes",
"fr:Bières artisanales",
"fr:Bières sans alcool",
"fr:Biscottes complètes",
"fr:Biscuits à la fraise",
"fr:Biscuits-aperitif",
"fr:Biscuits diététiques",
"fr:Biscuits secs",
"fr:Boissons chaudes instantanées",
"fr:Boudins",
"fr:Boudoirs",
"fr:Bouillon-cube",
"fr:Brioches au chocolat",
"fr:Cabillauds",
"fr:Carotte",
"fr:Cassoulets",
"fr:Celeri-remoulade",
"fr:Charcuteries cuites",
"fr:Cheeseburger",
"fr:Cidres bouchés",
"fr:Compotes-de-fruits",
"fr:Compotes pommes poires",
"fr:Compotes pour bébé",
"fr:Conserves-de-legumes",
"fr:Crackers",
"fr:Creme-de-marrons",
"fr:Crèmes chantilly",
"fr:Desserts-lactes",
"fr:Eaux minérales gazeuses",
"fr:Fecules",
"fr:Filets de poulet",
"fr:Flageolets en conserve",
"fr:Fleurs de sel",
"fr:Foie-de-morue",
"fr:Fromages de montagne",
"fr:Fruits-frais",
"fr:Galettes des rois",
"fr:Gateaux-secs",
"fr:Gros sels",
"fr:Jambons de Bayonne",
"fr:Knacks industrielles",
"fr:Laits frais",
"fr:Lasagnes à garnir",
"fr:Menus Poissons pour bébé",
"fr:Mollusques",
"fr:Moutardes fines",
"fr:Munsters",
"fr:Noix de coco",
"fr:Nouilles-instantanees",
"fr:Nuggets",
"fr:Oignons",
"fr:Pains-au-lait",
"fr:Palmiers (biscuits",
"fr:Pate",
"fr:Pates-au-ble-complet",
"fr:Pates-de-fruits",
"fr:Pâtes de sarrazin",
"fr:Penne",
"fr:Persil",
"fr:Petits Munsters",
"fr:Poivres gris",
"fr:Pommes",
"fr:Pommes-noisettes",
"fr:Potage",
"fr:Pour-gateaux",
"fr:Produit-au-sel-de-guerande",
"fr:Quenelles de saumon",
"fr:Ratatouille",
"fr:Ratatouilles",
"fr:Repas-pour-bebe",
"fr:Rillettes de la Sarthe",
"fr:Rillettes de thon",
"fr:Rillettes du Mans",
"fr:Rillettes françaises",
"fr:Riz de Camargue",
"fr:Rosettes",
"fr:Sandwichs jambon fromage",
"fr:Sauces salades",
"fr:Sels marins",
"fr:Soupes froides",
"fr:Spaghettis au blé complet",
"fr:Spéculoos",
"fr:Tablettes",
"fr:Tapenades noires",
"fr:Tartes salées",
"fr:Thés aromatisés",
"fr:Thons à l’huile de tournesol",
"fr:Tisane-vegetale",
"fr:Toast",
"fr:Tommes",
"fr:Tortillas",
"fr:Veloutés de légumes",
"fr:Verveine",
"fr:Viandes de boeuf",
"fr:Viandes surgelées",
"fr:Vin-rose-bio",
"Canned tunas",
"Lemon yogurts",
"Low-fat yogurts",
"Red wine vinegars",
"Squeezed grapefruit juices",
"Squeezed pineapple juices",
"Sweet wines",
"Whisky",
"White vinegars",
"fr:Ail",
"fr:Allege",
"fr:Arômes pâtisserie",
"fr:Asperges violettes",
"fr:Avoines",
"fr:Basilic",
"fr:Bières avec des fruits",
"fr:Bières brunes",
"fr:Biscottes au froment",
"fr:Biscuits sans gluten",
"fr:Blancs-de-dinde",
"fr:Boisson-aromatisee",
"fr:Boisson-fermentee",
"fr:Boisson-sucree",
"fr:Boisson-vegetale",
"fr:Boissons lyophilisées",
"fr:Bouchees",
"fr:Boudins blancs",
"fr:Bouillon-deshydrate",
"fr:Boulettes-de-viande",
"fr:Cacao",
"fr:Cafe-arabica",
"fr:Cancoillotte",
"fr:Caramels au beurre salé",
"fr:Champignons en conserve",
"fr:Chicoree",
"fr:Cidres rosés",
"fr:Cocktail de fruits au sirop",
"fr:Coeurs de palmier en conserve",
"fr:Compotes allégées",
"fr:Concentre-de-tomates",
"fr:Confitures d’abricot",
"fr:Confitures diététiques",
"fr:Cordons bleus de poulet",
"fr:Cornichons au vinaigre",
"fr:Cornichons extra-fins",
"fr:Cotes-de-porc",
"fr:Coulis-de-tomate",
"fr:Creme-legere",
"fr:Crevettes roses",
"fr:Croque-monsieur",
"fr:Dosettes-cafe",
"fr:Épeautre",
"fr:Epicerie-sucree",
"fr:Epinards-haches",
"fr:Escalopes de poulet",
"fr:Feculent",
"fr:Feculents",
"fr:Fromage-au-lait-de-chevre",
"fr:Fromages du Nord-Pas-de-Calais",
"fr:Galettes à la frangipane",
"fr:Gambas",
"fr:Gateaux-ou-compotes",
"fr:Gélifiants",
"fr:Gnocchi",
"fr:Infusions Bonne Nuit",
"fr:Jambon-cuit-superieur",
"fr:Japon",
"fr:Jus d’orange sanguine",
"fr:Jus-de-legume",
"fr:Jus-de-tomate",
"fr:Laits 1er âge",
"fr:Laits aromatisés",
"fr:Laits concentrés sucrés",
"fr:Laits d'amande",
"fr:Lentilles préparées",
"fr:Maasdam",
"fr:Macaroni",
"fr:Mascarpone",
"fr:Merlu-blanc",
"fr:Mimolettes",
"fr:Morues",
"fr:Moutardes à l’ancienne",
"fr:Noisettes",
"fr:Oeufs-de-poule",
"fr:Olives vertes en saumure",
"fr:Pain-complet",
"fr:Pains pour hamburgers",
"fr:Pains spéciaux",
"fr:Palmiers",
"fr:Pastis",
"fr:Pâtes à tartiner au caramel",
"fr:Penne-rigate",
"fr:Petits pains grillés",
"fr:Petits-suisses-pour-bebe",
"fr:Pizzas ovales",
"fr:Plats susceptibles de contenir de la viande de cheval - lots retirés de la vente en février 2013",
"fr:Poire",
"fr:Poivrons rouges",
"fr:Pommes de terre Charlotte",
"fr:Potage-deshydrate",
"fr:Pousses",
"fr:Pralines",
"fr:Preparation-culinaire",
"fr:Preparation-pour-desserts",
"fr:Preparations-pour-patisseries",
"fr:Produits décongelés",
"fr:Puree-de-tomates",
"fr:Quenelles de brochet",
"fr:Rhums blancs",
"fr:Rillettes de viande blanche",
"fr:Rillettes de volaille",
"fr:Risotto",
"fr:Riz-au-lait",
"fr:Riz blanc",
"fr:Riz pour risotto",
"fr:Riz pour sushi",
"fr:Riz-rond",
"fr:Rooibos",
"fr:Roqueforts",
"fr:Saint-emilion",
"fr:Saint-felicien",
"fr:Salade-prete-a-l-emploi",
"fr:Salades-preparees",
"fr:Salamis",
"fr:Sardines à l'ancienne",
"fr:Sardines sans huile",
"fr:Sauce-cuisinee",
"fr:Saucisse-a-cuire",
"fr:Saucisses de Morteau",
"fr:Saucisses de Toulouse",
"fr:Saucisses fumées",
"fr:Saumon-fume-bio",
"fr:Saumons fumés sauvages",
"fr:Sels de table",
"fr:Sirop-sans-sucre",
"fr:Sodas à l'orange light",
"fr:Son",
"fr:Soupe-de-legumes-frais",
"fr:Specialite-fromagere",
"fr:Specialite-vegetale-a-base-de-tofu",
"fr:Steak-hache",
"fr:Stevia",
"fr:Sticks-de-chocolat",
"fr:Sucres glaces",
"fr:Tagliatelles-carbonara",
"fr:Tartelettes",
"fr:Tartes aux poireaux",
"fr:Thés à la menthe",
"fr:Thons à l’huile d’olive",
"fr:Thons blancs",
"fr:Toast-croustillant",
"fr:Tomates pelées",
"fr:Tourtes",
"fr:Veloutés de potiron",
"fr:Vinaigres aromatisés",
"fr:Vinaigrette",
"fr:Vins mutés",
"fr:Vins mutés de type vin doux naturel",
"it:Vino",
"Argan oils",
"Concentrated pineapple juices",
"Extra-virgin olive oils",
"Greek yogurts",
"Hazelnut oils",
"Honeys from France",
"Mango nectars",
"Rapeseed oils",
"Raw fishes",
"Refrigerated squeezed juices",
"Refrigerated squeezed orange juices",
"Seaweed",
"Sesame oils",
"Sweet pies",
"Wines from Portugal",
"fr:A-cuire",
"fr:Amandes en poudre",
"fr:Ananas",
"fr:Ananas au sirop",
"fr:Artichauts",
"fr:Asperges blanches",
"fr:Asperges en conserve",
"fr:Asperges fraîches",
"fr:Asperges miniatures",
"fr:Asperges vertes",
"fr:Assortiments de chocolats",
"fr:Bananes",
"fr:Barquettes",
"fr:Barres glacées",
"fr:Batavia",
"fr:Bâtonnets",
"fr:Beaujolais",
"fr:Beignets-de-poulet",
"fr:Betteraves",
"fr:Beurre-doux-bio",
"fr:Beurres-de-baratte",
"fr:Bières à la cerise",
"fr:Biscuit-fourre",
"fr:Biscuits-au-beurre",
"fr:Blanquette-de-veau",
"fr:Blinis",
"fr:Boisson-au-riz",
"fr:Boisson-lactee",
"fr:Boisson-lactee-fermentee-nature-sucree",
"fr:Boudins blanc à l'ancienne",
"fr:Bouillon-de-volaille",
"fr:Boulangerie",
"fr:Brioches au fruit",
"fr:Brocolis",
"fr:Brownie",
"fr:Burrito",
"fr:Cafés décaféinés",
"fr:Camemberts au lait microfiltré",
"fr:Cannelloni",
"fr:Capres",
"fr:Carottes en conserve",
"fr:Carottes-en-rondelles",
"fr:Carottes-surgelees",
"fr:Cassonades",
"fr:Céréales pour bébé",
"fr:Céréales préparées",
"fr:Cervelas",
"fr:Chardonnay",
"fr:Chataignes",
"fr:Chocolat-au-lait-aux-noisettes",
"fr:Chocolat-aux-noisettes-entieres",
"fr:Chocolat-fourre",
"fr:Chocolats-au-lait-noirs-et-blancs",
"fr:Chocolats avec amandes",
"fr:Chocolats fourrés au praliné",
"fr:Choucroute-garnie",
"fr:Choux-de-bruxelles",
"fr:Cidre-breton",
"fr:Cidre-breton-doux",
"fr:Cidres artisanaux",
"fr:Citronnade",
"fr:Clémentines",
"fr:Coeurs-d-artichauts",
"fr:Coleslaw",
"fr:Compotes pommes myrtille",
"fr:Cônes",
"fr:Cones-glaces",
"fr:Confitures de figues",
"fr:Conserve-de-legumes",
"fr:Conserver",
"fr:Coppa",
"fr:Coquillettes-au-ble-complet",
"fr:Corn-flakes-bio",
"fr:Corned-beef",
"fr:Cotes-du-roussillon",
"fr:Coulis",
"fr:Court-bouillon",
"fr:Couscous-grain-fin",
"fr:Couscous-grain-moyen",
"fr:Couscous préparés",
"fr:Creme-anglaise",
"fr:Crèmes entières",
"fr:Crepes-au-jambon",
"fr:Dinde",
"fr:Dindes",
"fr:Eau-de-coco",
"fr:Ecorces-d-oranges-confites-enrobees-de-chocolat-noir",
"fr:Ecrase-de-pommes-de-terre",
"fr:Emince-de-champignon",
"fr:Entrées",
"fr:Epinard",
"fr:Equitable",
"fr:Farines de blé type T65",
"fr:Farines de maïs",
"fr:Figues",
"fr:Filets d’anchois",
"fr:Filets de cabillaud",
"fr:Financiers",
"fr:Flageolets",
"fr:Fourres-chocolat",
"fr:Framboises",
"fr:Friandise",
"fr:Fromages-au-lait-de-brebis",
"fr:Fromages au lait thermisé",
"fr:Fromages de vache Prim'Holstein",
"fr:Fromages des Pays-Bas",
"fr:Fusilli",
"fr:Galette-de-tofu",
"fr:Galettes de blé noir",
"fr:Galettes de maïs",
"fr:Gaufres fourrées",
"fr:Gélatine",
"fr:Gelées de fruits",
"fr:Genoises",
"fr:Gingembre",
"fr:Gorgonzolas",
"fr:Goudas",
"fr:Graines",
"fr:Gratin d’aubergine",
"fr:Gratins de poisson",
"fr:Gratins de pomme de terre",
"fr:Halal",
"fr:Haricots-en-grains",
"fr:Haricots-rouges",
"fr:Ice-tea light",
"fr:Jambonneau",
"fr:Jambons fumés",
"fr:Jus",
"fr:Jus-a-base-de-concentre",
"fr:Jus-d-orange-refrigere",
"fr:Jus-de-clementine",
"fr:Jus-de-legumes",
"fr:Jus-de-tomate-bio",
"fr:Kit",
"fr:Lait-chocolate",
"fr:Lait-fermente",
"fr:Laits concentrés non sucrés",
"fr:Laits d'avoine",
"fr:Langues de chat",
"fr:Lapin",
"fr:Lardons-fumes-bio",
"fr:Lardons-nature",
"fr:Legume-cuit",
"fr:Legumes-secs-en-conserve",
"fr:Lentille",
"fr:Lentilles blonde",
"fr:Levures-de-biere",
"fr:Linguine",
"fr:Mangues",
"fr:Maquereaux-au-vin-blanc",
"fr:Maroilles",
"fr:Mayonnaise-bio",
"fr:Miels de montagne",
"fr:Moules",
"fr:Moules-en-conserve",
"fr:Mousse-de-canard",
"fr:Moutardes douces",
"fr:Nappages",
"fr:Non alimentaire",
"fr:Nouilles-orientales",
"fr:Nuggets-de-poulet",
"fr:Orge",
"fr:Paella",
"fr:Pain-aux-cereales",
"fr:Pain-de-seigle-complet",
"fr:Pains-au-chocolat",
"fr:Pains Burger",
"fr:Pains-d-epices",
"fr:Pains sans gluten",
"fr:Pate-a-pizza",
"fr:Pate-a-tartiner-sans-huile-de-palme",
"fr:Pates-a-pizza",
"fr:Pâtes à tartiner au chocolat",
"fr:Pâtes d’amande",
"fr:Pates-de-campagne",
"fr:Pates-de-foie-de-porc",
"fr:Pates-penne-rigate",
"fr:Penaeus-vannamei",
"fr:Petits pots pour bébé",
"fr:Pizzas et tartes surgelées",
"fr:Pizzas surgelées",
"fr:Plats-a-preparer",
"fr:Plats préparés à faible teneur en matières grasses",
"fr:Pois-casses",
"fr:Poissons-d-elevage",
"fr:Poivres blancs",
"fr:Poivrons grillés",
"fr:Poivrons rouges en conserve",
"fr:Pollens",
"fr:Pommes de terre Agata",
"fr:Pommes de terre de l'île de Ré",
"fr:Pommes-de-terre-entieres",
"fr:Pommes de terre primeurs",
"fr:Porto",
"fr:Poudre-de-cacao",
"fr:Poulets cuisinés",
"fr:Pousses de haricot mungo",
"fr:Praline",
"fr:Preparation-en-poudre-pour-entremets",
"fr:Preparation-pour-glace",
"fr:Preparations-pour-dessert",
"fr:Preparations-pour-gateaux",
"fr:Produit-a-la-figue",
"fr:Produit-lacte",
"fr:Produits-sales-aperitifs",
"fr:Produits vendus dans les années 1980",
"fr:Produits vendus dans les années 1990",
"fr:Purées d'amande",
"fr:Purées d'oléagineux",
"fr:Quenelles de veau",
"fr:Quenelles de volaille",
"fr:Quiche-lorraine",
"fr:Quinoa-rouge",
"fr:Raisins secs Sultanines",
"fr:Raviolis à la volaille",
"fr:Raviolis aux légumes",
"fr:Reblochons",
"fr:Rillettes de poulet",
"fr:Rillettes de Saint-Jacques",
"fr:Rillettes de saumon",
"fr:Rillettes poulet rôti",
"fr:Rillettes spéciales",
"fr:Riz arborio",
"fr:Riz-basmati-bio",
"fr:Riz-cantonnais",
"fr:Riz-cuisine",
"fr:Riz-incollable",
"fr:Riz-jasmin",
"fr:Riz-long-blanc-bio",
"fr:Riz-long-complet",
"fr:Riz parfumés",
"fr:Riz préparés",
"fr:Riz soufflé",
"fr:Riz Surinam",
"fr:Riz-thai-bio",
"fr:Saint-jacques",
"fr:Salaison",
"fr:Salsifis en conserve",
"fr:Sardines à l’huile et au citron",
"fr:Sardines à l’huile et au piment",
"fr:Sarrasin",
"fr:Sauce-pour-snacking",
"fr:Sauce-pour-viande",
"fr:Sauce-samourai",
"fr:Sauces au soja sucrées",
"fr:Sauces-pour-frites",
"fr:Sauces provençales",
"fr:Saucisses de Montbéliard",
"fr:Saucisses-de-volaille",
"fr:Saucissons artisanaux",
"fr:Saumon-fume-au-bois-de-hetre-eleve-en-norvege",
"fr:Sirops aux fruits",
"fr:Sirops de cassis",
"fr:Sirops de citron",
"fr:Sodas à la pomme",
"fr:Son-d-avoine",
"fr:Son des blé",
"fr:Sorbets à la framboise",
"fr:Soupe-au-miso",
"fr:Soupe-de-nouilles",
"fr:Soupe de poissons",
"fr:Soupe-potiron-carottes",
"fr:Spaghetti au blé dur complet",
"fr:Sucres blonds",
"fr:Terrines de volailles",
"fr:Thés au citron",
"fr:Thés blancs",
"fr:Thés verts chinois",
"fr:Thons fumés",
"fr:Tomates-au-jus",
"fr:Tomates séchées",
"fr:Traiteur",
"fr:Tripes",
"fr:Truites-fumes",
"fr:Vanille",
"fr:Vegetarien",
"fr:Veloutés de légumes du soleil",
"fr:Vermicelles",
"fr:Viande-panee",
"fr:Viandes de veau",
"fr:Viennoiserie",
"fr:Vin-blanc-bio",
"fr:Vinaigre-basalmique",
"fr:Vinaigres d’alcools",
"fr:Vinaigres de vins blancs",
"fr:Vins de pays",
"fr:Vodkas",
"fr:Yaourt-brasse-aux-fruits",
"fr:Yaourts-liquides",
"Apricot nectars",
"Banana nectars",
"en:Biscuits-chocolates",
"en:Canelle",
"Caviars",
"en:Grated-cheese",
"Japanese green teas",
"en:Jus-de-fruits",
"Labelized vegetables",
"Maple syrups",
"Meals with rabbit or hare",
"en:Naan",
"Peach nectars",
"PGI Products",
"Poppyseed oils",
"Red ports",
"en:Sauces",
"Sausages from Spain",
"Soy milk yogurts",
"en:Soy-sauces",
"Strawberry yogurts",
"Trouts",
"Wines from California",
"Wines from Italy",
"Wines from Spain",
"Xeres vinegars",
"fr:100-pur-jus-de-poire-bio",
"fr:100-pur-jus-de-pomme-bio",
"fr:2-galettes-de-soja-recette-aux-legumes-bio",
"fr:2-galettes-de-soja-recette-mediterraneenne-bio",
"fr:2-paves-de-saumon-bio",
"fr:2-paves-de-truite-bio",
"fr:2-yaourts-au-lait-de-brebis-bio",
"fr:6-gros-oeufs-de-categorie-a",
"fr:8-crackers-a-la-farine-d-epeautre-et-aux-graines-de-tournesol",
"fr:Abricots",
"fr:Abricots au sirop",
"fr:Abricots-moelleux-bio",
"fr:Acai-bio",
"fr:Achards",
"fr:Acras",
"fr:Agar-agars",
"fr:Aide-alimentaire",
"fr:Aide-culinaire-pour-confiture",
"fr:Aiguillettes-de-canard",
"fr:Aiguillettes-de-poulet-aux-epices-tandoori",
"fr:Ailladou",
"fr:Allumettes de bacon",
"fr:Allumettes-de-jambon",
"fr:Alsace",
"fr:Amande-cuisine-bio",
"fr:Amandes-effilees",
"fr:Amidon-de-mais",
"fr:Amuse-bouches",
"fr:Ananas-en-morceaux-au-jus-d-ananas-bio",
"fr:Ananas-en-tranches-au-sirop",
"fr:Anis",
"fr:Arachide",
"fr:Arachide-pralinee",
"fr:Arachide-sucree",
"fr:Arbois",
"fr:Aromate",
"fr:Asperges des sables des Landes",
"fr:Asperges françaises",
"fr:Asperges françaises IGP",
"fr:Asperges IGP",
"fr:Asperges pelées à la main",
"fr:Assaisonnement-salade",
"fr:Assiette-vegetarienne-de-legumes-et-de-quinoa-bio",
"fr:Assiettes pour bébé",
"fr:Aubergine",
"fr:Auces-vinaigrettes",
"fr:Auvergnat-cola",
"fr:Avoine-cuisine-bio",
"fr:Avoine-et-legumes-bio",
"fr:Bac-a-glace",
"fr:Bacon en tranche",
"fr:Baguette-cereales",
"fr:Baguettes-aux-cereales",
"fr:Baguettes-de-campagne",
"fr:Baguettes-precuites",
"fr:Baies",
"fr:Baies-de-goji",
"fr:Barquettes à la fraise",
"fr:Barre-cereales-sans-gluten",
"fr:Barre-de-son-d-avoine-saveur-amande",
"fr:Barre-son-d-avoine",
"fr:Barres-abricot-chocolat-amande-petit-epeautre-bio",
"fr:Barres-cereales-amandes-et-noisettes",
"fr:Barres-cereales-noix-de-coco-sur-lit-de-chocolat-au-lait",
"fr:Barres-cereales-pepites-de-chocolat",
"fr:Barres-cereales-pepites-de-fruits-rouges",
"fr:Barres-cereales-pomme-verte",
"fr:Barres-chocolate",
"fr:Barres-cranberries-cajou-quinoa",
"fr:Barres-croustillantes-riz-et-ble-complet-aux-pepites-de-chocolat",
"fr:Barres-de-regime",
"fr:Barres-de-regime-saveur-chocolat-blanc-enrobees-de-chocolat-au-lait",
"fr:Barres-de-regime-saveur-noix-de-coco-enrobees-de-chocolat-au-lait",
"fr:Baton-de-reglisse",
"fr:Batonnet-de-crabe",
"fr:Bâtonnets au chocolat",
"fr:Bearnaise",
"fr:Beauce-cola",
"fr:Beignets",
"fr:Betteraves-rouges-en-cubes-cuites-sous-vide",
"fr:Beurre-de-baratte-biologique-doux",
"fr:Beurre-tendre-doux",
"fr:Beurres-a-la-baratte",
"fr:Beurres allégés",
"fr:Beurres-crus",
"fr:Beurres-de-bresse",
"fr:Beurres pasteurisés",
"fr:Beurres salés",
"fr:Biere-ambree-malt-bio",
"fr:Biere-aromatisee",
"fr:Biere-blonde-aromatisee-poire",
"fr:Biere-blonde-d-abbaye",
"fr:Bière de gingembre",
"fr:Bières fortes",
"fr:Biftecks",
"fr:Biftecks-de-boeuf",
"fr:Biosson",
"fr:Biscotte-son-de-ble",
"fr:Biscottes-au-sarrasin",
"fr:Biscottes-chataigne",
"fr:Biscottes-completes-bio",
"fr:Biscottes pauvres en sel",
"fr:Biscottes-sarrasin",
"fr:Biscuit-au-beurre",
"fr:Biscuit-choco-fondant",
"fr:Biscuit-chocolat-noir",
"fr:Biscuit-chocolat-nougatine",
"fr:Biscuit-fourre-chocolat",
"fr:Biscuit-nappe-chocolat-au-lait",
"fr:Biscuit-sucre",
"fr:Biscuits-aperitifs-sales",
"fr:Biscuits-apperitif",
"fr:Biscuits-au-chocolat-au-lait",
"fr:Biscuits-au-chocolat-au-lait-bio",
"fr:Biscuits-aux-cereales-nappes-de-chocolat",
"fr:Biscuits-aux-chocolat-et-a-la-noix-de-coco",
"fr:Biscuits-aux-eclats-de-feves-de-cacao",
"fr:Biscuits-aux-oeufs",
"fr:Biscuits-avec-tablettes-de-chocolat-lait",
"fr:Biscuits-barres-chocolat-orange",
"fr:Biscuits-ble",
"fr:Biscuits-chocolat-cacao",
"fr:Biscuits-chocolat-et-quinoa",
"fr:Biscuits-chocolates",
"fr:Biscuits-cookies",
"fr:Biscuits-cuillers",
"fr:Biscuits-enrobes-de-chocolat-au-lait-et-fourres-au-praline",
"fr:Biscuits-fondants",
"fr:Biscuits-fondants-saveur-peche-abricot",
"fr:Biscuits-fourres",
"fr:Biscuits-fourres-gout-chocolat",
"fr:Biscuits-gout-chocolat",
"fr:Biscuits-gout-chocolat-blanc",
"fr:Biscuits-hyperproteines",
"fr:Biscuits-meringues",
"fr:Biscuits-mini-oursons-pepites-de-chocolat",
"fr:Biscuits-moelleux",
"fr:Biscuits-moelleux-saveur-muesli-fleur-d-oranger",
"fr:Biscuits-nappes-chocolat-noir",
"fr:Biscuits-nappes-de-chocolat-au-lait",
"fr:Biscuits-nature",
"fr:Biscuits-orange",
"fr:Biscuits-pavot",
"fr:Biscuits-pavot-saveur-romarin",
"fr:Biscuits-petit-dejeuner-cereales-et-pepites-de-chocolat",
"fr:Biscuits-pour-preparer-un-gateau",
"fr:Biscuits-pur-beurre",
"fr:Biscuits-sables-fourrage-fraise-bio",
"fr:Biscuits-saveur-pomme-figue",
"fr:Biscuits-vegetal",
"fr:Blanc-de-poulet-en-tranches",
"fr:Blanc-de-poulet-fume",
"fr:Blanc-sec",
"fr:Blanquette",
"fr:Blanquette-de-veau-aux-champignons-son-riz",
"fr:Ble-assaisonne",
"fr:Ble-dur-precuit",
"fr:Ble-precuit",
"fr:Bocal-de-cornichons",
"fr:Boisson-a-base-de-citron-et-de-menthe",
"fr:Boisson-a-base-de-fruit-de-la-passion-concentre",
"fr:Boisson-a-base-de-jus-d-orange-et-de-menthe",
"fr:Boisson-a-base-de-jus-de-citron-et-de-menthe",
"fr:Boisson-a-l-aloe-vera",
"fr:Boisson-au-jus-de-fruit",
"fr:Boisson-au-lait",
"fr:Boisson-au-lait-de-soja-chocolatee",
"fr:Boisson-au-soja-allegee",
"fr:Boisson-au-soja-au-miel-bio",
"fr:Boisson-au-soja-nature-bio",
"fr:Boisson-au-soja-saveur-vanille-bio",
"fr:Boisson-aux-extraits-de-the-aromatise-peche",
"fr:Boisson-aux-fruits-a-base-de-concentre",
"fr:Boisson-aux-fruits-a-base-de-jus-concentree-bio-abricot",
"fr:Boisson-aux-fruits-a-base-de-jus-de-fruits-concentres-bio-orange",
"fr:Boisson-cacaoteee-bio",
"fr:Boisson-concentree-a-diluer",
"fr:Boisson-fruite",
"fr:Boisson-gazeuse-aromatise-ananas",
"fr:Boisson-gazeuse-aromatise-aux-fruits",
"fr:Boisson-gazeuse-aromatise-fraise",
"fr:Boisson-gazeuse-aromatisee-aux-fruits",
"fr:Boisson-gazeuse-au-jus-d-orange-sanguine-bio",
"fr:Boisson-gazeuse-au-jus-de-canneberge-et-grenade-bio",
"fr:Boisson-gazeuse-au-jus-de-citron-bio",
"fr:Boisson-gazeuse-au-jus-de-pamplemousse-rose-bio",
"fr:Boisson-gazeuse-aux-fruits",
"fr:Boisson-gazeuse-saveur-exotique",
"fr:Boisson-gazeuse-saveur-grenadine",
"fr:Boisson-gazeuse-saveur-mandarine",
"fr:Boisson-soja-nature",
"fr:Boisson-soja-saveur-vanille",
"fr:Boisson-sucre",
"fr:Boisson-sucrees",
"fr:Boissons-au-jus-de-fruit",
"fr:Boissons-au-the",
"fr:Boissons-energisantes-light",
"fr:Boissons-lactees",
"fr:Boissons-sans-alcool",
"fr:Bolachas",
"fr:Bonbon-au-chocolat",
"fr:Bonbons-a-la-fraise",
"fr:Bonbons-a-la-menthe",
"fr:Bonbons-arome-naturel",
"fr:Bonbons-au-chocolat",
"fr:Bonbons-au-miel",
"fr:Bonbons-de-chocolat-noir",
"fr:Bonbons-sans-sucres",
"fr:Bonbons-tendres",
"fr:Bouchee-a-la-reine",
"fr:Boucherie",
"fr:Boudin-blanc-aux-morilles",
"fr:Boudins noir aux oignons",
"fr:Boudins noirs",
"fr:Bouillon-cube-bio",
"fr:Bouillon-de-legumes",
"fr:Bouillon-de-poule",
"fr:Bouillons-de-poule",
"fr:Bouillons-de-veau",
"fr:Bouillons-de-volaille",
"fr:Bouillons-deshydrates",
"fr:Boule-bio",
"fr:Boulettes-de-viande-cuites",
"fr:Boulgour-bio",
"fr:Boulgour-gros-grains-bio",
"fr:Bouquets-de-mache",
"fr:Bouquets garnis",
"fr:Brandade",
"fr:Brandade-de-morue",
"fr:Brandade-de-morue-parmentiere",
"fr:Bresse Bleu",
"fr:Bretzels",
"fr:Bries",
"fr:Brioche-tressee",
"fr:Brioches a l'abricot",
"fr:Brioches vendéennes",
"fr:Brique",
"fr:Brochette-de-porc",
"fr:Brochettes",
"fr:Brocolis-en-fleurette",
"fr:Brocolis-en-fleurette-surgeles-bio",
"fr:Brownie-chocolat-noisettes",
"fr:Brownies",
"fr:Brownies-bio",
"fr:Buche-de-chevre",
"fr:Buche-glacee",
"fr:Buche-patissiere",
"fr:Buches-glacees",
"fr:Cabillaud-tom-yam-coco-citronnelle-ecrase-de-pommes-de-terre",
"fr:Cacahuete",
"fr:Cacahuete-enrobees",
"fr:Cacahuètes au chocolat",
"fr:Cacahuetes-grillees",
"fr:Cachou-bonbon",
"fr:Cafe-a-la-chicoree",
"fr:Cafe-en-dosettes",
"fr:Cafe-en-grains",
"fr:Cafe-grains",
"fr:Cafes-viennois",
"fr:Cake-aux-fruits",
"fr:Cakes-aux-figues",
"fr:Calamars-en-sauce",
"fr:Calendrier-de-l-avent-24-figurines-de-chocolat",
"fr:Calissons-d-aix",
"fr:Camembert-au-lait-pasteurise",
"fr:Camembert-bio",
"fr:Camemberts de Normandie",
"fr:Camemberts pasteurisés",
"fr:Camenberts",
"fr:Camomille",
"fr:Cancoillotte-ail-bio",
"fr:Cancoillotte-nature",
"fr:Cannelle-moulue",
"fr:Cannelloni-a-garnir",
"fr:Cannellonis",
"fr:Canneloni",
"fr:Cantals",
"fr:Capellini",
"fr:Cappuccino-en-poudre",
"fr:Capsule",
"fr:Caramel-liquide",
"fr:Carottes-cuites",
"fr:Carottes-en-rondelles-bio-surgelees",
"fr:Carottes-fraiches",
"fr:Carpaccios",
"fr:Carpes-fumes",
"fr:Carres-coupe-faim-minceur-cacao",
"fr:Carres-fibre-aux-3-fruits",
"fr:Cassoulet-au-confit-de-canard",
"fr:Caviar Baeri",
"fr:Caviars d'élevage",
"fr:Céleri en conserve",
"fr:Cereales-fourrees-chocolat",
"fr:Cereales-gourmandes-ble-mais-soja",
"fr:Cereales-pilaf-saveurs-forestieres",
"fr:Cereales-soufflees",
"fr:Cereales-soufflees-au-chocolat-bio",
"fr:Cerelales",
"fr:Cerelales-aux-chocolats",
"fr:Cerelales-chocolatees",
"fr:Cerises au sirop",
"fr:Cervelas-a-l-alsacienne",
"fr:Chair-a-saucisse",
"fr:Champagne-bio",
"fr:Champagne-brut",
"fr:Champagnes-extra-brut",
"fr:Champignons-de-paris-eminces-bio",
"fr:Champignons-de-paris-entiers-1er-choix-bio",
"fr:Champignons-de-paris-surgeles",
"fr:Champignons surgelés",
"fr:Chapelure",
"fr:Charcuteries à cuire",
"fr:Chevre",
"fr:Chewing-gum-sans-sucres-gout-fraise",
"fr:Chili-con-carne",
"fr:Chili-con-carne-et-riz-bio",
"fr:Chipolatas aux herbes",
"fr:Chips-au-mais",
"fr:Chips croustillantes",
"fr:Chips-de-crevettes",
"fr:Chocolas",
"fr:Chocolat-70",
"fr:Chocolat-80",
"fr:Chocolat-a-la-noix-de-coco",
"fr:Chocolat-au-lait-bio",
"fr:Chocolat-au-lait-cafe-cannelle",
"fr:Chocolat-au-lait-cajou-caramelisee",
"fr:Chocolat-au-lait-parseme-de-grains-de-nougatine",
"fr:Chocolat-au-lait-riz-souffle",
"fr:Chocolat-au-lait-sesame-gingembre",
"fr:Chocolat-aux-eclats-de-noisettes",
"fr:Chocolat-blanc-fourrage-au-praline-et-aux-eclats-de-noisettes",
"fr:Chocolat-extra-fin",
"fr:Chocolat-fourrage-au-praline",
"fr:Chocolat-fourre-a-la-liqueur",
"fr:Chocolat-fourre-au-fruit",
"fr:Chocolat-lait-fondant",
"fr:Chocolat-lait-noisette",
"fr:Chocolat-lait-praline",
"fr:Chocolat-noir-70",
"fr:Chocolat-noir-85-bio",
"fr:Chocolat-noir-a-la-menthe",
"fr:Chocolat-noir-au-the",
"fr:Chocolat-noir-aux-ecorces-d-orange-confites",
"fr:Chocolat-noir-cacao-80-origine-equateur",
"fr:Chocolat-noir-caramel",
"fr:Chocolat-noir-citron",
"fr:Chocolat-noir-coco",
"fr:Chocolat-noir-degustation",
"fr:Chocolat-noir-eclats-d-amandes-bio",
"fr:Chocolat-noir-eclats-de-menthe-bio",
"fr:Chocolat-noir-ecorces-d-orange-bio",
"fr:Chocolat-noir-fleur-de-sel",
"fr:Chocolat-noir-fourrage-au-praline-et-aux-eclats-de-noisettes",
"fr:Chocolat-noir-fourre",
"fr:Chocolat-noir-framboise",
"fr:Chocolat-noir-orange",
"fr:Chocolat-noir-parseme-de-grains-de-cacao",
"fr:Chocolat-noir-praline-bio",
"fr:Chocolat-noir-quinoa-souffle-bio",
"fr:Chocolat-patissier",
"fr:Chocolat-praline",
"fr:Chocolat-superieur-au-lait",
"fr:Chocolatines",
"fr:Chocolats au lait extra fin",
"fr:Chocolats-chauds",
"fr:Chocolats noirs extra fin",
"fr:Chocolats pur beurre de cacao",
"fr:Chocolats Suisse",
"fr:Chou-rouge",
"fr:Chouchen",
"fr:Choucroute-en-conserve",
"fr:Chutney",
"fr:Ciboulette",
"fr:Cidre-aromatise-a-la-poire",
"fr:Cidre-artisanal-bigouden-demi-sec",
"fr:Cidre-artisanal-bio",
"fr:Cidre-bouche-de-normandie-brut-bio",
"fr:Cidre-bouche-de-normandie-doux",
"fr:Cidre-breton-bio-doux",
"fr:Cidre-cornouaille",
"fr:Cidres traditionnels",
"fr:Cocktail-non-sale",
"fr:Coco",
"fr:Cocos",
"fr:Cognac",
"fr:Cola-bio",
"fr:Collioure",
"fr:Colorants alimentaire",
"fr:Compote-de-peches",
"fr:Compote-de-poire",
"fr:Compote-de-pomme-allegee-en-sucres-bio",
"fr:Compote-de-pomme-bio",
"fr:Compote-de-pomme-peche-passion",
"fr:Compote-de-pommes-allegee-en-sucres-bio",
"fr:Compote-pomme-nature-bio",
"fr:Compote-pomme-poire-bio",
"fr:Compote-pomme-vanille",
"fr:Compote-pommes-vanille",
"fr:Compotes-2-pomme-framboise-2-pomme-fraise",
"fr:Compotes-de-bananes",
"fr:Compotes-de-poire",
"fr:Compotes mangues",
"fr:Compotes-pomme-abricot",
"fr:Compotes-pomme-banane",
"fr:Compotes-pomme-mirabelle",
"fr:Compotes-pomme-nature-bio",
"fr:Compotes-pommes-banane",
"fr:Compotes pommes mangue",
"fr:Comte-20-24-mois-appellation-d-origine-protegee",
"fr:Comte-aop-bio",
"fr:Concentre",
"fr:Conditionne-en-france",
"fr:Confiserie-au-chocolat",
"fr:Confiserie-au-chocolat-au-lait",
"fr:Confiserie-fantaisie",
"fr:Confiserie-sans-sucre",
"fr:Confiseries de France",
"fr:Confit",
"fr:Confit-de-canard-pommes-de-terre-a-la-sarladaise",
"fr:Confits d’oie",
"fr:Confiture-de-cerises",
"fr:Confiture-extra",
"fr:Confiture-extra-de-framboise-allegee-en-sucres",
"fr:Confitures artisanales",
"fr:Confitures d’orange",
"fr:Conserve-de-legumes-cuisines",
"fr:Conserve-de-maquereaux",
"fr:Conserve-de-viande",
"fr:Conserves-de-legume",
"fr:Cookies aux amandes",
"fr:Cookies-aux-pepites-de-chocolat-noir-bio",
"fr:Cookies-bio-au-chocolat",
"fr:Cookies-choco-noisette-coeur-fondant",
"fr:Cookies-pepites-chocolat",
"fr:Coppa-bio",
"fr:Coquille Saint-Jacques",
"fr:Coquillettes-au-ble-integral-bio",
"fr:Coquillettes-bio",
"fr:Corbieres",
"fr:Corn-flakes-cacao-bio",
"fr:Cornet",
"fr:Cornet-de-glace",
"fr:Cornet-glace",
"fr:Cornets",
"fr:Cornets-a-glace",
"fr:Cotes-catalanes",
"fr:Cotes-du-rhone-village",
"fr:Coulis-de-tomate-bio",
"fr:Coup-double-bio",
"fr:Courgette",
"fr:Courgettes",
"fr:Courgettes-en-rondelles-surgeles-bio",
"fr:Courgettes-surgelees",
"fr:Couscous-aux-epices",
"fr:Couscous-bio",
"fr:Couscous-royal-au-poulet",
"fr:Couscous-semi-complet-grain-moyen",
"fr:Crabe-royal",
"fr:Crackers-fromages-tomate-bio",
"fr:Crackers-sales",
"fr:Crakers",
"fr:Cranberries",
"fr:Creme-de-caramel",
"fr:Creme-de-coco",
"fr:Creme-de-riz",
"fr:Creme-de-riz-bio",
"fr:Creme-de-soja",
"fr:Creme-de-soja-liquide",
"fr:Creme-dessert-au-chocolat-bio",
"fr:Creme-dessert-caramel",
"fr:Crème Fraîche d'Isigny",
"fr:Creme-fraiche-legere",
"fr:Creme-fraiche-legere-epaisse",
"fr:Creme-fraiche-sous-pression",
"fr:Creme-glacee-au-chocolat-noir",
"fr:Creme-glacee-chocolat",
"fr:Creme-glacee-vanille-amandes-caramelisees",
"fr:Creme-sous-pression",
"fr:Creme-sucree",
"fr:Cremes-d-anchoiade",
"fr:Cremes-de-cassis",
"fr:Cremes-de-marrons",
"fr:Cremes-legeres",
"fr:Crepes-au-fromage",
"fr:Crepes-aux-fromages",
"fr:Crêpes de froment",
"fr:Crepes-nature-bio",
"fr:Crepes-salees",
"fr:Crepes-sales",
"fr:Crevettes-bio",
"fr:Crevettes nordiques",
"fr:Croissants-precuits",
"fr:Croquettes pour chat",
"fr:Crottin-de-chevre",
"fr:Crousti-panes-tomates",
"fr:Crousti-pause-coeur-fondant-cacao-noisette",
"fr:Croutons-pour-salade",
"fr:Crudites",
"fr:Cuisine",
"fr:Cuisine-du-monde",
"fr:Cuisine-japonaise",
"fr:Cuisses-de-canard",
"fr:Cuisses-de-canard-confites",
"fr:Cuisses-de-canard-du-sud-ouest-confites-surgelees",
"fr:Curry-de-lentilles",
"fr:De-cranberry-et-puree-de-framboise-100-pur-fruit-presse",
"fr:Dentifrices",
"fr:Dès 08 mois",
"fr:Dès 24 mois",
"fr:Des-de-cervelas",
"fr:Desert",
"fr:Dessert-au-soja-caramel-bio",
"fr:Dessert-au-soja-saveur-vanille-bio",
"fr:Dessert-biofruits-pomme-nature",
"fr:Dessert-de-fruits-au-riz-pomme-poire",
"fr:Dessert-de-fruits-pomme-abricot",
"fr:Dessert-de-fruits-pomme-banane",
"fr:Dessert-de-fruits-pomme-poire",
"fr:Dessert-fruitier",
"fr:Dessert-lacte-au-chocolat",
"fr:Dessert-lacte-aux-oeufs",
"fr:Dessert-lactee",
"fr:Dessert-pomme-banane-bio",
"fr:Dessert-pomme-cassis-bio",
"fr:Dessert-pomme-mangue-bio",
"fr:Dessert-vegetal",
"fr:Dosettes-souples-cafe",
"fr:Duo-d-olives-a-la-toscane",
"fr:Duo-de-riz-de-camargue-riz-semi-complet-et-riz-rouge-bio",
"fr:Eau-de-coco-bio",
"fr:Eau-de-fleurs-d-oranger",
"fr:Eau-plate",
"fr:Eaux-minerals-naturelles",
"fr:Echalote-deshydratee",
"fr:Echalotes",
"fr:Echine-de-porc-assaisonnee",
"fr:Édulcorants de table",
"fr:Emiette-de-thon",
"fr:Eminces-de-saumon-atlantique-fume-bio",
"fr:Emmentals français est-central",
"fr:Emmentals suisses",
"fr:Endives",
"fr:Enrobes-de-chocolat-noir",
"fr:Entrees-preparees",
"fr:Entremets",
"fr:Epices-bio",
"fr:Epinards-en-branche",
"fr:Epinards-en-branches",
"fr:Epinards-en-branches-surgeles",
"fr:Epinards-en-conserve",
"fr:Epinards-haches-a-la-creme",
"fr:Epinards-haches-a-la-creme-surgeles-bio",
"fr:Epinards-haches-bio-surgeles",
"fr:Epinards-haches-surgeles",
"fr:Epis-de-mais",
"fr:Epoisses",
"fr:Escalopes-de-dinde",
"fr:Escalopes-de-veau-hache",
"fr:Escargots",
"fr:Esturgeons-fumes",
"fr:Ethiquable",
"fr:Exhausteurs de goût",
"fr:Fabrication-artisanale",
"fr:Faiselle",
"fr:Faiselle-bio",
"fr:Faisselles",
"fr:Falafels",
"fr:Falafels-pois-chiches",
"fr:Farine-complete",
"fr:Farine-complete-de-petit-epeautre",
"fr:Farine-complete-de-quinoa-bio",
"fr:Farine-de-ble-semi-complete-du-gers-bio",
"fr:Farines de Petit Épeautre",
"fr:Farines de petit épeautre T70",
"fr:Farines de pois chiche",
"fr:Farines de sarrasin",
"fr:Farines label rouge",
"fr:Farines labellisées",
"fr:Farines pâtissières",
"fr:Farines-pour-brioche",
"fr:Fenouils",
"fr:Feta",
"fr:Fetas",
"fr:Feuille-de-chene",
"fr:Feuillete",
"fr:Feuilletes",
"fr:Figues-moelleuses-bio",
"fr:Figues-seches",
"fr:Filet",
"fr:Filet-de-colin-d-alaska",
"fr:Filet-mignon",
"fr:Filet-mignon-de-porc",
"fr:Filets-de-colin",
"fr:Filets-de-colin-d-alaska",
"fr:Filets-de-colin-d-alaska-surgeles",
"fr:Filets de sardines à l’huile d’olive",
"fr:Filets-de-sardines-a-l-huile-d-olive-vierge-extra",
"fr:Filets-de-sardines-sans-aretes-a-l-huile-d-olive-vierge-extra",
"fr:Financiers-aux-amandes",
"fr:Financiers-aux-amandes-bio",
"fr:Fines-galettes-epinards-et-pignons-bio",
"fr:Fines-gaufrettes-enrobees-de-chocolat-au-lait",
"fr:Fitou",
"fr:Flageolets-cuisines",
"fr:Flageolets-verts",
"fr:Flakes",
"fr:Flakes-d-epeautre-bio",
"fr:Flammekueche",
"fr:Flammenkueche",
"fr:Flan",
"fr:Flan-a-la-vanille-nappe-de-caramel",
"fr:Flan-caramelise",
"fr:Flans",
"fr:Flans-gout-vanille-nappes-caramel",
"fr:Flocons",
"fr:Flocons-d-avoine",
"fr:Foies gras de canard",
"fr:Foies gras mi-cuits",
"fr:Fonds-de-veau",
"fr:Fondues",
"fr:Fourre-tout-choco-bio",
"fr:Fourres-chocolat-lait-bio",
"fr:Fourres-chocolat-lait-noisettes-bio",
"fr:Friandises-au-chocolat",
"fr:Fromage-a-pate-demi-dure",
"fr:Fromage-a-pate-dure-rape",
"fr:Fromage-a-pate-pressee",
"fr:Fromage-a-raclette",
"fr:Fromage-affine",
"fr:Fromage-ail-et-fines-herbes",
"fr:Fromage-allege",
"fr:Fromage-allege-au-lait-pasteurise",
"fr:Fromage-au-lait-d-ete",
"fr:Fromage-au-lait-de-vache-pasterise",
"fr:Fromage-au-lait-microfiltre",
"fr:Fromage-au-lait-pasterise",
"fr:Fromage-blanc-au-lait-de-brebis-framboise",
"fr:Fromage-blanc-nature-allege",
"fr:Fromage-de-chevre-a-tartiner-bio",
"fr:Fromage-de-lait-de-brebis",
"fr:Fromage-double-creme",
"fr:Fromage-dur-a-pate-cuite",
"fr:Fromage-emmental",
"fr:Fromage-fouette",
"fr:Fromage-frais-allege",
"fr:Fromage-frais-aux-herbes",
"fr:Fromage-frais-de-chevre-nature-bio",
"fr:Fromage-nature",
"fr:Fromages-alleges",
"fr:Fromages au lait de bufflonne",
"fr:Fromages aux noix",
"fr:Fromages de Suisse",
"fr:Fromages en conserve",
"fr:Fromages-frais-aux-fruits",
"fr:Fromages-libre-service",
"fr:Fromages-pour-croque-monsieur",
"fr:Fructose",
"fr:Fructose-pur-cristallise",
"fr:Fruits-de-mer",
"fr:Fruits-surgeles",
"fr:Fusilli-carbonara",
"fr:Gache",
"fr:Galette-de-riz-souffle",
"fr:Galette-de-soja",
"fr:Galettes-au-son-d-avoine",
"fr:Galettes-au-son-d-avoine-finement-salees-bio",
"fr:Galettes-bio",
"fr:Galettes-bretonnes",
"fr:Galettes-cereales-orge",
"fr:Galettes-cereales-sarrasin-comte-bio",
"fr:Galettes-chocolat",
"fr:Galettes-de-ble",
"fr:Galettes-de-mais-chocolat-noir-bio",
"fr:Galettes-de-pommes-de-terre-rapees",
"fr:Galettes-de-riz-fourrees",
"fr:Galettes-de-riz-fourrees-gout-choco-noisette-bio",
"fr:Galettes-de-riz-gout-choco-noisettes-au-riz-complet-bio",
"fr:Galettes-de-riz-nappees-chocolat-blanc-saveur-yaourt-bio",
"fr:Galettes-de-riz-nappees-de-chocolat-noir",
"fr:Galettes-de-riz-nappees-de-chocolat-noir-bio",
"fr:Galettes-de-soja",
"fr:Galettes-fines-aux-3-cereales-et-sesame-bio",
"fr:Galettes-son-d-avoine-vanillees",
"fr:Gansettes",
"fr:Gateau-au-caramel",
"fr:Gateau-de-semoule",
"fr:Gateau-de-semoule-nappage-chocolat",
"fr:Gateau-fourre",
"fr:Gateau-marbre",
"fr:Gâteaux apéritifs soufflés",
"fr:Gateaux-de-riz",
"fr:Gateaux-fourres",
"fr:Gateaux-marbres",
"fr:Gauffres",
"fr:Gauffres-au-miel-bio",
"fr:Gauffrettes",
"fr:Gaufrettes-au-chocolat-au-lait",
"fr:Gaufrettes-chocolatees",
"fr:Gaufrettes fourrées",
"fr:Gélifiants végétaux",
"fr:Gentiane",
"fr:Gesiers",
"fr:Gesiers-de-volaille-eminces",
"fr:Glace-au-yaourt",
"fr:Glaces rhum-raisin",
"fr:Gnocchi-de-pommes-de-terre",
"fr:Gnochetti",
"fr:Gougeres",
"fr:Gourdes-de-compote-de-pomme",
"fr:Gout-framboise",
"fr:Gouter-4s-aux-pommes",
"fr:Gouter-aux-raisins",
"fr:Gouters-au-chocolat",
"fr:Gouters-dores-pocket",
"fr:Gouters-pour-enfants",
"fr:Graine-de-couscous-facile",
"fr:Graines-a-germer-de-tournesol",
"fr:Graines-et-fruits-secs",
"fr:Graines-soja",
"fr:Grains-de-ble-precuit",
"fr:Graisse-de-canard",
"fr:Granule",
"fr:Gratin-d-endives-au-jambon",
"fr:Gratin-dauphinois-au-jambon",
"fr:Grenade-bio",
"fr:Grenadine",
"fr:Gruyere-rape",
"fr:Guimauves",
"fr:Hachis-parmentier-au-boeuf-bio",
"fr:Hachis-parmentier-bio",
"fr:Hachis-parmentier-pur-boeuf",
"fr:Haddocks fumés",
"fr:Hamburger-au-poulet",
"fr:Harengs",
"fr:Haricot-rouge-du-japon",
"fr:Haricots-blancs-a-la-tomate",
"fr:Haricots-blancs-secs",
"fr:Haricots-cocos",
"fr:Haricots-vert",
"fr:Haricots-verts-surgeles",
"fr:Haricots-verts-tres-fins-bio",
"fr:Haut-medoc",
"fr:Herbes de Provence Label Rouge",
"fr:Houmous",
"fr:Hove",
"fr:Huile-d-argan-grille-bio",
"fr:Huile-de-noisette-bio",
"fr:Huile-de-noix-bio",
"fr:Huile-de-tournesol-vierge-bio",
"fr:Huile-pimentee",
"fr:Huiles de poissons",
"fr:Hule-d-olive",
"fr:Ice-tea-zero-sucres-saveur-peche",
"fr:Igp",
"fr:Infusion-fenouil",
"fr:Infusions aux agrumes",
"fr:Jambon-cuit-de-paris",
"fr:Jambon-cuit-superieur-de-paris",
"fr:Jambon-de-campagne",
"fr:Jambon-serano",
"fr:Jambonneau-en-boite",
"fr:Jambons de la Forêt Noire",
"fr:Jambons Label Rouge",
"fr:Jus-carotte-citron-bio",
"fr:Jus-d-agrumes",
"fr:Jus-d-orange-100-pur-fruit-presse",
"fr:Jus-d-orange-avec-pulpe",
"fr:Jus-d-orange-avec-pulpe-frais",
"fr:Jus-d-orange-bio",
"fr:Jus-d-orange-pasteurise-bio",
"fr:Jus-d-orange-pur-jus",
"fr:Jus-d-orange-sans-pulpe",
"fr:Jus-d-orge",
"fr:Jus-de-banane",
"fr:Jus-de-carotte",
"fr:Jus-de-citron-a-base-de-concentre",
"fr:Jus-de-fruis",
"fr:Jus-de-fruit-pasteurise",
"fr:Jus-de-fruits-100",
"fr:Jus-de-fruits-a-base-de-jus-concentres",
"fr:Jus-de-fruits-presses-pomme-framboise",
"fr:Jus-de-fruits-presses-pomme-mangue",
"fr:Jus-de-fuits",
"fr:Jus-de-goyave",
"fr:Jus-de-mangue",
"fr:Jus-de-pamplemouse",
"fr:Jus-de-pamplemousse-blanc-bio",
"fr:Jus-de-peche",
"fr:Jus-de-pomme-100-pur-fruit-presse-bio",
"fr:Jus-de-pomme-100-pur-jus",
"fr:Jus-de-pomme-bio",
"fr:Jus-de-pomme-biologique",
"fr:Jus-de-pomme-cassis",
"fr:Jus-de-pomme-et-de-mangue",
"fr:Jus-de-pomme-petillant",
"fr:Jus-de-pruneau-bio",
"fr:Jus-de-raisin-bio",
"fr:Jus-de-tomate-sale",
"fr:Jus-multifruit-a-base-de-concentre",
"fr:Jus-multifruit-a-base-de-jus-concentres",
"fr:Jus-orange-banane",
"fr:Knacks industrielles à teneur réduite en sel",
"fr:La-vache-en-pot-aux-noisettes",
"fr:Lait-de-montagne-entier",
"fr:Lait-de-soja-chocolat",
"fr:Lait-empresure-sucre-aromatise-cacao",
"fr:Lait-maternise",
"fr:Lait-parfume",
"fr:Lait-sterilise-uht",
"fr:Laits de riz",
"fr:Laits-micro-filtres",
"fr:Laitue-rouge",
"fr:Landes",
"fr:Langres",
"fr:Lapin-chasseur",
"fr:Lapin-chasseur-ses-pommes-de-terre",
"fr:Lardons-allumettes-nature",
"fr:Lardons-nature-bio",
"fr:Lardons-natures-bio",
"fr:Lasagnes-a-la-bolognaise-pur-boeuf-bio",
"fr:Le-p-tit-nature-bio",
"fr:Le-petit-beurre-tablette-chocolat-au-lait",
"fr:Le-petit-beurre-tablette-chocolat-au-lait-fourre-noisette",
"fr:Légumes bio",
"fr:Legumes-chinois",
"fr:Legumes-conserve",
"fr:Légumes IGP",
"fr:Legumes-prefrits",
"fr:Legumes-sec-en-conserve",
"fr:Legumes-secs-gourmands-lentilles-ble-pois-casses",
"fr:Legumes-verts",
"fr:Lentille-cuite",
"fr:Lentilles-carottes-bio",
"fr:Lentilles-en-conserve",
"fr:Lentilles-vertes-aux-lardons",
"fr:Lentilles-vertes-bio",
"fr:Lentilles-vertes-du-berry",
"fr:Levure-de-biere",
"fr:Levures-chimiques",
"fr:Liegeois",
"fr:Limonade-au-sucre-de-canne-bio",
"fr:Limonade-bio",
"fr:Lin",
"fr:Linguine-chic-crevettes-coriandre-ail-et-poivre-noi",
"fr:Litchis",
"fr:Livarot",
"fr:Lussac-saint-emilion",
"fr:Lychees au sirop",
"fr:Macaroni-sauce-morilles-cremeux-et-corse",
"fr:Madeleines au raisin",
"fr:Madeleines longues",
"fr:Madeleines-natures-aux-oeufs-frais",
"fr:Magret",
"fr:Magret-de-canard",
"fr:Mais-tendre",
"fr:Mais-ultra-croquant",
"fr:Mangues au sirop",
"fr:Maquereaux-a-la-moutarde",
"fr:Maquereaux-aux-aromates",
"fr:Maquereaux-aux-tomate-basilic-et-olives",
"fr:Margaux",
"fr:Marmelades",
"fr:Marrons",
"fr:Marrons-cuits-a-la-vapeur",
"fr:Mascarpone-cremeux-bio",
"fr:Matiere-grasse-a-tartiner-et-a-cuire",
"fr:Mayonnaise-allege",
"fr:Mayonnaises allégées",
"fr:Médicaments",
"fr:Medoc",
"fr:Melange-aperitif",
"fr:Melange-d-epices",
"fr:Melange-d-huiles",
"fr:Melange-de-5-cereales-bio",
"fr:Melange-de-ble-et-de-sarrasin",
"fr:Melange-de-cereales-ble",
"fr:Melange-de-cereales-legumes-secs-ble",
"fr:Melange-de-cereales-precuites",
"fr:Melange-de-graines-pour-pain",
"fr:Melange-de-legume",
"fr:Melange-de-legumes",
"fr:Melange-quinoa-boulgour-bio",
"fr:Melisse",
"fr:Menthe",
"fr:Menus Légumes pour bébé",
"fr:Merguez-et-agneau",
"fr:Mes-compotes-pommes-fraise-pommes-vanille",
"fr:Miel-de-fleurs-bio",
"fr:Miels d’acacia",
"fr:Miels d’agrumes",
"fr:Miels d’oranger",
"fr:Miels d'ulmo",
"fr:Miels de forêt",
"fr:Miels liquides",
"fr:Milk-shake",
"fr:Milk-shake-substitut-de-repas-saveur-chocolat",
"fr:Mini-cakes-aux-figues-bio",
"fr:Mini-cakes-aux-fruits-bio",
"fr:Mini-cakes-aux-pepites-de-chocolat",
"fr:Mini-cakes-raisins",
"fr:Mini-cones-glacees",
"fr:Mini-moelleux-au-chocolat-bio",
"fr:Mini-toasts",
"fr:Mini-toasts-graines-de-lin",
"fr:Mini-toasts-pavot-et-graines-de-lin",
"fr:Miso",
"fr:Moelleux-pomme-cannelle",
"fr:Morbiers",
"fr:Mou",
"fr:Moulages en chocolat",
"fr:Moules-en-sauce",
"fr:Moulin-a-vent",
"fr:Mouline",
"fr:Mouline-de-legumes",
"fr:Mouline-de-legumes-d-autrefois",
"fr:Mousse-au-chocolat-au-lait",
"fr:Mousse-au-chocolat-noir",
"fr:Mousse-de-foie",
"fr:Mousse-de-marrons",
"fr:Moutardes au miel",
"fr:Mozzarellas",
"fr:Muesli-25-de-fruit-4-cereales-bio",
"fr:Muesli-aux-fruits-bio",
"fr:Muesli-croustillant-choco-bio",
"fr:Muesli-croustillant-chocolat-bio",
"fr:Muesli-croustillant-fruits-rouges-bio",
"fr:Muesli-croustillant-natures-bio",
"fr:Muesli-croustillant-pomme-cannelle-bio",
"fr:Muesli-floconneux-5-cereales-nature-bio",
"fr:Muesli-pomme-abricot-bio-et-equitable",
"fr:Muesli-raisins-noisettes-bio",
"fr:Muffins",
"fr:Muffins-complets",
"fr:Muscat-sec",
"fr:Muscats",
"fr:Nappage",
"fr:Nappes-au-chocolat-au-lait",
"fr:Nectar-a-base-de-concentre-et-de-puree",
"fr:Nectar-d-orange-bio",
"fr:Nectar-de-letchis",
"fr:Nectar-de-pomme-bio",
"fr:Nectar-multifruits-bio",
"fr:Nectar-multivitamine-a-base-de-jus-concentres",
"fr:Nectar-orange-avec-sa-pulpe-a-base-de-jus-d-orange-concentre",
"fr:Nectars-de-litchis",
"fr:Nems-au-porc",
"fr:Nems-au-poulet",
"fr:Nids-d-oeufs",
"fr:Noix",
"fr:Noix-de-cajou-grillees-salees",
"fr:Noix-de-pecan",
"fr:Nougats",
"fr:Nougats de Montélimar",
"fr:Nouilles-asiatiques",
"fr:Nouilles-aux-oeufs",
"fr:Nouilles-instantannee",
"fr:Nouilles-royales-bami-goreng",
"fr:Nourriture pour animaux",
"fr:Nourriture pour chats",
"fr:Nutella",
"fr:Oeuf-de-poule-en-plein-air",
"fr:Oeufs de cailles",
"fr:Oeufs-de-poules",
"fr:Oignon-cat-1-cal-50-70",
"fr:Oignons-frits",
"fr:Olive-verte-farcie",
"fr:Olives-aux-amandes",
"fr:Olives-denoyautees-noires-nature",
"fr:Olives-farcies-pate-de-poivron",
"fr:Olives-noires-a-la-grecque",
"fr:Onctueuse-puree-de-pomme-de-terre-bio",
"fr:Orange-confite",
"fr:Orangettes-chocolat-noir",
"fr:Orge-et-avoine",
"fr:Paellas",
"fr:Pain-au-mais",
"fr:Pain-au-son-tranche",
"fr:Pain-aux-cereales-bio",
"fr:Pain-aux-fibres-tranche",
"fr:Pain-d-epice",
"fr:Pain-d-epices-au-sirop-d-agave",
"fr:Pain-d-epices-bio",
"fr:Pain-de-mie-bio",
"fr:Pain-de-mie-blanc-bio",
"fr:Pain-de-mie-sans-croute",
"fr:Pain-grille-bio",
"fr:Pain-pave-tranche-500g-label-rouge",
"fr:Pain-special-de-campagne-bio",
"fr:Pains azymes à la farine complète",
"fr:Pains azymes à la farine d'épeautre",
"fr:Pains azymes au seigle",
"fr:Pains azymes pilés",
"fr:Pains croustillants",
"fr:Pains de mie aux céréales",
"fr:Pains-speciaux-complets",
"fr:Palets-chocolat-cookies-de-cacao",
"fr:Palets-de-legumes",
"fr:Palets-pepites-chocolat",
"fr:Palmiers-allonges-au-sucre-un-peu-caramelise",
"fr:Palmiers-allonges-aux-gouttes-de-chocolat",
"fr:Palmiers-bio",
"fr:Palmiers-feuilletes-et-dores",
"fr:Pamplemousse-bio",
"fr:Pamplemousses",
"fr:Pancetta",
"fr:Panes-de-poulet",
"fr:Pappardelles",
"fr:Paprika",
"fr:Parfum-cerise",
"fr:Parmesan-rape",
"fr:Pasta-with-mushroom-sauce",
"fr:Pastilla",
"fr:Pate-a-fondant-au-chocolat",
"fr:Pate-a-tartiner-a-l-huile-de-coprah",
"fr:Pate-capellini",
"fr:Pate-de-campagne",
"fr:Pate-de-jambon",
"fr:Pâte de riz",
"fr:Pâté de tête",
"fr:Pate-en-croute",
"fr:Pate-imperial",
"fr:Pate-linguine",
"fr:Pate-molle",
"fr:Pate-pizza",
"fr:Pate-spaghetti",
"fr:Pâtes à base de Petit Épeautre",
"fr:Pates-a-tartinee",
"fr:Pâtes à tartiner aux noisettes et au cacao",
"fr:Pates-a-tartiner-sucrees",
"fr:Pates-abc",
"fr:Pates-alphabets",
"fr:Pates-amorini",
"fr:Pates-aux-ble-complet",
"fr:Pates-avoines",
"fr:Pates-castellane-parmigiane",
"fr:Pates-cavatelli-pugliesi",
"fr:Pates-cellentani",
"fr:Pates-cheveux-d-ange-de-qualite-superieure",
"fr:Pates-completes",
"fr:Pates-conchiglie-rigate",
"fr:Pates-d-alsace-nids",
"fr:Pates-d-alsace-nouilles-bouclees",
"fr:Pates-d-alsace-spaghetti",
"fr:Pates-de-ble-dur",
"fr:Pates-de-foie",
"fr:Pates-de-fruits-bio",
"fr:Pates-en-croute",
"fr:Pates-farfalle",
"fr:Pates-farfalle-tricolore",
"fr:Pates-farfalles-au-ble-complet",
"fr:Pates-fraiches-cuites",
"fr:Pates-fusilli",
"fr:Pates-fusilli-bio",
"fr:Pates-gansettes",
"fr:Pates-gnocchetti-sardi",
"fr:Pates-les-crozets-nature",
"fr:Pates-les-crozets-tomate-piment-d-espelette",
"fr:Pates-mafalde-corte-napoletane",
"fr:Pates-mezze-penne-tricolore",
"fr:Pates-piccolini-mini-farfalle-aux-carottes-et-potiron",
"fr:Pates-piccolini-mini-penne-rigate-aux-courgettes-et-epinards",
"fr:Pates-pour-enfant",
"fr:Pates-preparees",
"fr:Pâtes sablées",
"fr:Pates-spatzle-d-alsace",
"fr:Pates-torsades",
"fr:Pates-torsettes-au-ble-complet",
"fr:Pates-trofie-liguri",
"fr:Patisserie-orientale",
"fr:Patisseries-surgelees",
"fr:Patisseries-surgelees-a-cuire",
"fr:Paupiettes-de-porc",
"fr:Pauvre-en-graisse-saturees",
"fr:Pave-de-saumon-a-l-oseille",
"fr:Paves-de-saumon",
"fr:Peche-ou-framboise",
"fr:Penne-au-ble-integral-bio",
"fr:Penne-rigate-au-ble-complet",
"fr:Pepites-croustillantes-30-de-fruits",
"fr:Pepites-croustillantes-eclats-de-chocolat-noir",
"fr:Pepites-croustillantes-fruits-rouges-framboise-fraise-myrtille",
"fr:Pepites-de-chocolat",
"fr:Pepito-pockitos",
"fr:Petales-de-ble",
"fr:Petales-de-ble-au-chocolat",
"fr:Petales-de-cereales-copeaux-de-chocolat",
"fr:Petales-de-mais-dores-corn-flakes",
"fr:Petales-de-mais-sucres",
"fr:Petales-de-riz-et-ble-complet",
"fr:Petales-riz-et-ble-complet",
"fr:Petales-riz-et-ble-complet-aux-fruits-rouges",
"fr:Petit-cake-fourre-saveur-chocolat",
"fr:Petit-cake-pepites-chocolat",
"fr:Petit-gateau",
"fr:Petit-pont-l-eveque",
"fr:Petit-pot-de-yaourt-au-citron-vert",
"fr:Petit salé",
"fr:Petit-suisse",
"fr:Petites-tartines-legeres-et-craquantes",
"fr:Petits-carres-au-beurre-un-peu-sale-et-chocolat-noir",
"fr:Petits-fromages-frais-de-chevre-nature-bio",
"fr:Petits-gateaux",
"fr:Petits-pains-grilles-au-froment-bio",
"fr:Petits-pains-grilles-multi-cereales-bio",
"fr:Petits-pois-carottes",
"fr:Petits-pois-et-carottes",
"fr:Petits-pois-et-jeunes-carottes",
"fr:Petits-pois-tres-fin",
"fr:Petits-pois-tres-fin-et-jeunes-carottes",
"fr:Petits-suisses",
"fr:Petits-suisses-pour-bebes",
"fr:Pilchards",
"fr:Pilons-de-poulet",
"fr:Pineaux",
"fr:Pipe-rigate",
"fr:Pistaches-grillees-nature",
"fr:Pistaches-grillees-non-salees",
"fr:Pistaches-grillees-salees",
"fr:Pistaches-grillees-sans-sel",
"fr:Plat-prepare-surgeme",
"fr:Plats à base d’oies",
"fr:Plats à base de dinde",
"fr:Plats à base de lapin",
"fr:Plats-chinois",
"fr:Plats-chinois-surgeles",
"fr:Plats-desydrates",
"fr:Pockys",
"fr:Poelee-de-legumes",
"fr:Poelee-surgelee",
"fr:Poêlées",
"fr:Poire-de-normandie",
"fr:Poireaux",
"fr:Poireaux-en-rondelles-surgeles-bio",
"fr:Pois-casses-de-france",
"fr:Pois chiches en conserve",
"fr:Pois-chiches-special-couscous",
"fr:Poisson-sugele",
"fr:Poissons-cuisines",
"fr:Poissons panés de colin",
"fr:Poitrine-de-porc",
"fr:Poivronnades",
"fr:Polenta",
"fr:Pomme-dauphine",
"fr:Pomme-nature",
"fr:Pomme-noisette",
"fr:Pommes-dauphines",
"fr:Pommes-de-terre-annabelle-cat-1-cal-35-55",
"fr:Pommes-de-terre-bio",
"fr:Pommes-de-terre-cat-1-cal-35-55",
"fr:Pommes-de-terre-cuites",
"fr:Pommes-de-terre-en-cubes",
"fr:Pommes-de-terre-entieres-epluchees",
"fr:Pommes-rissolees",
"fr:Pont-l'Evêque",
"fr:Pops-miel-bio",
"fr:Pops-miel-chocolat-bio",
"fr:Porc-au-caramel-et-riz-basmati-bio",
"fr:Porc-mijote-aubergines-et-4-cereales-bio",
"fr:Portion-individuelle",
"fr:Porto réductifs",
"fr:Porto Ruby",
"fr:Potages",
"fr:Poudre-a-lever",
"fr:Poudre-chocolatee",
"fr:Poulet-basquaise",
"fr:Poulet-basquaise-au-piment-du-pays-basque-son-riz",
"fr:Poulet-korma",
"fr:Poulet-korma-et-riz-basmati",
"fr:Poulet-roti-jus-au-thym-ecrasee-de-pommes-de-terre-bio",
"fr:Poulet-sauce-aux-olives-et-quinoa-bio",
"fr:Poulet-tikka-masala",
"fr:Poulet-tikka-massala",
"fr:Poulets panés",
"fr:Pour-cuisiner",
"fr:Pour-la-confiserie",
"fr:Pour-les-gateaux",
"fr:Pour-plats-chinois",
"fr:Pousses de bambou",
"fr:Preparation",
"fr:Preparation-a-base-de-jus-de-fruits",
"fr:Preparation-a-base-de-viande",
"fr:Preparation-a-l-huile",
"fr:Preparation-a-l-huile-d-olive-arome-basilic-bio",
"fr:Preparation-a-l-huile-d-olive-saveur-truffe-bio",
"fr:Preparation-de-soja-cuisine",
"fr:Preparation-pour-aperitif-a-base-de-tomate-et-de-basilic",
"fr:Preparation-pour-creme-patissiere",
"fr:Preparation-pour-entremet-en-poudre",
"fr:Preparation-pour-flan-patissier",
"fr:Preparation-pour-fondant-au-chocolat",
"fr:Preparation-pour-infusion",
"fr:Preparation-pour-pain-special-et-patisserie",
"fr:Preparation-pour-pate-sablee",
"fr:Preparation-pour-sauce",
"fr:Preparation-precuite",
"fr:Preparations",
"fr:Preparations-a-base-de-legumes",
"fr:Preparations-a-base-de-poisson",
"fr:Preparations-culinaires",
"fr:Produit-a-la-menthe",
"fr:Produit-a-la-noisette",
"fr:Produit-au-chocolat",
"fr:Produit-au-chocolat-au-lait",
"fr:Produit-au-citron",
"fr:Produit-au-poulet",
"fr:Produit-au-saumon",
"fr:Produit-au-sucre-de-canne",
"fr:Produit-au-wasabi",
"fr:Produit-issu-de-la-ruche",
"fr:Produit-kasher",
"fr:Produit-pocket",
"fr:Produit-pour-usage-culinaire",
"fr:Produit-recolte-par-des-abeilles",
"fr:Produits-a-la-pomme",
"fr:Produits-au-miel",
"fr:Produits-aux-cereales",
"fr:Produits-avec-des-edulcorants",
"fr:Produits-frais",
"fr:Produits introuvables en Métropole",
"fr:Produits-sucrants",
"fr:Produits-vendus-dans-les-annees-2000",
"fr:Projet-archeologie",
"fr:Pruneaux-d-agen-bio",
"fr:Pruneaux-geants",
"fr:Pur-jus-d-orange-bio",
"fr:Puree-de-fruit",
"fr:Puree-de-mangues-et-de-pommes",
"fr:Puree-de-mangues-et-de-pommes-bio",
"fr:Puree-de-piments",
"fr:Puree-de-pois",
"fr:Puree-de-pommes-de-terre-au-lait-entier",
"fr:Puree-de-pommes-et-de-bananes-bio",
"fr:Puree-de-pommes-et-de-cassis-bio",
"fr:Puree-de-pommes-et-de-mangues-bio",
"fr:Puree-de-pommes-et-de-poires-bio",
"fr:Puree-de-tomate-fraiche",
"fr:Puree-lentilles",
"fr:Puree-lentilles-corail-potiron-bio",
"fr:Purées d'amande complète",
"fr:Purées en flocons",
"fr:Quatre-quarts",
"fr:Quiches",
"fr:Quinoa-blond",
"fr:Quinoa-de-bolivie-bio",
"fr:Quinoa-lentilles-bio",
"fr:Quinoa-noir",
"fr:Quinoa-royal-bio",
"fr:Quinoa-tomates-olives-bio",
"fr:Quinoa-vert-asperges-petit-pois-haricots-verts",
"fr:Raclette-bio",
"fr:Raclette-de-caractere-lait-de-montagne",
"fr:Raclette-de-savoie-au-lait-cru",
"fr:Ratatouille-cuisinee",
"fr:Ratatouilles-en-conserve",
"fr:Ravioles",
"fr:Ravioli-au-jambon",
"fr:Raviolis à la bolognaise",
"fr:Raviolis-au-porc",
"fr:Raviolis aux champignons",
"fr:Raviolis-aux-epinards",
"fr:Raviolis-d-epinards-au-tofu-sauce-tomate-pesto-bio",
"fr:Raviolis-japonais",
"fr:Regal-de-legumes-verts-bio",
"fr:Regime",
"fr:Reglisse",
"fr:Rehausseur-de-gout",
"fr:Rhum cubain",
"fr:Rhums agricoles",
"fr:Rillettes artisanales",
"fr:Rillettes de canard",
"fr:Rillettes de saumon rose",
"fr:Rillettes de truite",
"fr:Rillons",
"fr:Risotto-au-crabe",
"fr:Risotto-aux-cepes",
"fr:Risotto-cremeux-poulet-asperges-morilles",
"fr:Riste",
"fr:Riz-au-lait-au-chocolat",
"fr:Riz-au-lait-saveur-vanille",
"fr:Riz-basmati-au-curry",
"fr:Riz-basmati-bio-et-ethiquable",
"fr:Riz Basmati blancs",
"fr:Riz-basmati-citron-et-aneth",
"fr:Riz-blanc-du-surinam",
"fr:Riz-cantonnais-nasi-goreng",
"fr:Riz-complet-rouge",
"fr:Riz-etuve",
"fr:Riz-etuve-grande-saveu",
"fr:Riz-le-basmati-du-penjab",
"fr:Riz-long-blanc",
"fr:Riz-long-blanc-camargue",
"fr:Riz-long-complet-bio",
"fr:Riz-long-etuve",
"fr:Riz-long-grain-basmati",
"fr:Riz-long-grain-complet",
"fr:Riz-long-grain-incollable",
"fr:Riz-long-grain-thai",
"fr:Riz-long-pour-risotto",
"fr:Riz-noir",
"fr:Riz-pour-risotto-arborio",
"fr:Riz-rouge",
"fr:Riz-sauvage",
"fr:Riz-special-paella",
"fr:Riz-special-risotto",
"fr:Riz-special-salades",
"fr:Riz thaï blanc",
"fr:Riz-thai-jasmine",
"fr:Riz-thai-parfume-jasmin",
"fr:Riz Vialone Nano",
"fr:Rocamadour",
"fr:Rollmops",
"fr:Romarin",
"fr:Roquefort-au-lait-cru-de-brebis-bio",
"fr:Rosette-bio",
"fr:Rosti",
"fr:Roti-de-dinde",
"fr:Roti-de-porc-a-cuire",
"fr:Rouille",
"fr:Roussillon",
"fr:Sable-au-caramel-et-chocolat-au-lait",
"fr:Sable-miel-datte",
"fr:Sables-au-chocolat",
"fr:Sables-aux-cereales",
"fr:Sables-aux-cereales-nappes-de-chocolat-noir",
"fr:Sables-aux-figues",
"fr:Sables-bio-nappes-chocolat-au-lait",
"fr:Sables-caramel-au-sel-de-guerande",
"fr:Sables-choco-lait-coco",
"fr:Sables-coco-chocolat",
"fr:Sables-framboise",
"fr:Sables-pur-beurre",
"fr:Saint Agur",
"fr:Saint-marcelin",
"fr:Salade-assaisonnee",
"fr:Salade-chinoise",
"fr:Salade-de-carottes",
"fr:Salade-de-carottes-rapees-aux-ecorces-d-agrumes-bio",
"fr:Salade-iceberg",
"fr:Salade-lentilles-et-legumes",
"fr:Salade-lentilles-et-legumes-bio",
"fr:Salade-quinoa-et-legumes",
"fr:Salade-quinoa-et-legumes-bio",
"fr:Salade-riz",
"fr:Salade-riz-avoine-legumes",
"fr:Salades-vertes",
"fr:Samoussas",
"fr:Sardine-a-l-huile-d-arachide",
"fr:Sardines-a-la-sauce-tomate",
"fr:Sardines-grillees",
"fr:Sardines-marinade-citron-basilic",
"fr:Sardines-marinees-au-muscadet-et-aux-aromates",
"fr:Sauce-aigre-douce",
"fr:Sauce-au-beurre-blanc",
"fr:Sauce-aux-cepes",
"fr:Sauce-basquaise-bio",
"fr:Sauce-bolognaise-bio",
"fr:Sauce-carbonara",
"fr:Sauce-froide",
"fr:Sauce-nantua",
"fr:Sauce-pesto-vert-au-basilic",
"fr:Sauce-piquante",
"fr:Sauce-tartare",
"fr:Sauce-tomate-a-la-provencale-bio",
"fr:Sauce-tomate-aux-olives-vertes-et-noires-bio",
"fr:Sauce-yakitori",
"fr:Sauces au fromage",
"fr:Sauces au roquefort",
"fr:Sauces aux légumes",
"fr:Sauces aux olives",
"fr:Sauces-mayonnaise",
"fr:Sauces pour pizzas",
"fr:Saucisse-de-canard",
"fr:Saucisse-pur-porc",
"fr:Saucisses allemandes",
"fr:Saucisses-cocktail",
"fr:Saucisses confites",
"fr:Saucisses de Francfort",
"fr:Saucisses-de-francfort-bio",
"fr:Saucisses-de-toulouse-aux-lentilles-cuisinees",
"fr:Saucisses-fraiches",
"fr:Saucisses-fumees-bio",
"fr:Saucissons à l’ail",
"fr:Saumon-atlantique-fume-bio",
"fr:Saumon-fume-au-bois-de-hetre-eleve-en-ecosse",
"fr:Saumon-fume-ecosse",
"fr:Saumon-fume-norvege",
"fr:Saumon-sauce-oseille-ses-torsades",
"fr:Saumons-d-elevage",
"fr:Saumons fumés de dégustation",
"fr:Sauvignon",
"fr:Saveur-cerise",
"fr:Schweppes-zero-ananas",
"fr:Schweppes-zero-fraise",
"fr:Sel-de-cuisine",
"fr:Sel-fin-iode",
"fr:Sel-rose-de-l-himalaya",
"fr:Sels de Guérande",
"fr:Sels des marais salants",
"fr:Semoule-au-lait",
"fr:Semoule-de-couscous-a-la-tomate",
"fr:Semoule-de-couscous-aux-epices-douces",
"fr:Semoule-et-legumes-secs",
"fr:Semoules de blé",
"fr:Serano",
"fr:Série spéciale",
"fr:Sesame",
"fr:Sesame-et-lin-bio",
"fr:Sesame-sel",
"fr:Sirops de violette",
"fr:Smoothie-framboise-myrtille",
"fr:Snack-aperitif",
"fr:Soda-aux-ecorces-de-quinquina",
"fr:Sodas au citron light",
"fr:Sodas au cola sans caféine",
"fr:Sodas aux fruits exotiques",
"fr:Soins-specifiques",
"fr:Soja-calcium",
"fr:Soja-doux-saveur-noisette",
"fr:Soja-gratin-bio",
"fr:Soja-nature",
"fr:Soja-vanille",
"fr:Son-d-avoine-bio",
"fr:Son-fin-de-ble-bio",
"fr:Sorbets à la fraise",
"fr:Sorbets à la mangue",
"fr:Sorbets au citron vert",
"fr:Soule-de-legumes",
"fr:Soupe-au-choux",
"fr:Soupe-de-legumes-verts",
"fr:Soupe-deshydratee-de-nouilles",
"fr:Soupe-deshydratee-de-nouilles-japonaises",
"fr:Soupe-deshydratee-en-sachet",
"fr:Soupe-gaspacho",
"fr:Soupe-instantannee",
"fr:Soupe-mouline-campagnard-bio",
"fr:Spaghetti-aux-oeuf",
"fr:Spaghetti-bio",
"fr:Spaghettis au petit épeautre",
"fr:Spatzle",
"fr:Specialite-culinaire-a-l-ail-et-aux-fines-herbes",
"fr:Specialite-de-saucisse-seche",
"fr:Specialite-fromagere-pasteurisee",
"fr:Steack-hache",
"fr:Steack-hache-surgele",
"fr:Steak",
"fr:Steak-hache-frais",
"fr:Steak-hache-pur-boeuf",
"fr:Sticks",
"fr:Sticks-et-bretzels",
"fr:Sucettes",
"fr:Sucre-blond-de-canne-en-morceaux-bio",
"fr:Sucre-blond-de-canne-en-poudre-bio",
"fr:Sucre-sale",
"fr:Sucre-vanille",
"fr:Sucreries",
"fr:Sucres-en-poudre",
"fr:Super-cookies-coeur-fondant-au-chocolat-au-lait-et-noisette",
"fr:Sushis",
"fr:Tablette-chocolat-85",
"fr:Taboule-a-l-orientale-petits-legumes-menthe",
"fr:Taboulés au poulet",
"fr:Taboulés frais",
"fr:Tagliatelles-bio",
"fr:Tartare",
"fr:Tarte-aux-poireaux-surgelee",
"fr:Tarte-aux-tomates-cerises",
"fr:Tarte-aux-tomates-cerises-et-au-fromage-frais",
"fr:Tartelettes-framboise-bio",
"fr:Tartes au fromage",
"fr:Tartes au saumon",
"fr:Tartes françaises",
"fr:Tartines-craquantes-bio-chataigne",
"fr:Tartines-craquantes-sarrasin-bio",
"fr:Tartines-croustillantes-au-sesame",
"fr:Tendres-perles-ble",
"fr:Terrines de campagne",
"fr:Terrines de canard",
"fr:Terrines de lapin",
"fr:Terrines de Saint-Jacques",
"fr:Terrines de sanglier",
"fr:The-earl-grey",
"fr:The-glace-saveur-peche",
"fr:The-vert-aromatise-mure-bio",
"fr:The-vert-de-ceylan",
"fr:The-vert-earl-grey-bio-ethiquable",
"fr:The-vert-menthe-bio",
"fr:The-vert-orange-bergamote-bio",
"fr:Thés Fukuju",
"fr:Thes-noirs-aromatises",
"fr:Thés Sencha",
"fr:Thon-a-l-eau",
"fr:Thon-basquaise-et-riz-complet-bio",
"fr:Thons-a-la-tomate",
"fr:Thons blancs au naturel",
"fr:Thons-entiers",
"fr:Tielles",
"fr:Tilleul",
"fr:Tiramisu",
"fr:Toast-brioche-au-ble-complet-bio",
"fr:Toast-croustillant-au-fromage-et-aux-graines-de-courge-bio",
"fr:Toast-croustillant-aux-3-graines-bio",
"fr:Toast-croustillant-tomate-et-mozzarella-bio",
"fr:Toasts",
"fr:Tofu-a-l-indienne-riz-basmati-et-lentilles-bio",
"fr:Tomates cerise",
"fr:Tomates-farcies",
"fr:Tomme de Savoie",
"fr:Torsades-au-ble-integral-bio",
"fr:Torsades-carbonara",
"fr:Torsades-semi-completes",
"fr:Tortellini-carbonara",
"fr:Tortelloni",
"fr:Tortilla",
"fr:Tranches-de-poulet",
"fr:Trio-d-olives-cocktail-oriental",
"fr:Trio-de-quinoas-blond-rouge-noir-bio-et-ethiquable",
"fr:Truffes",
"fr:Truffes en chocolat",
"fr:Tuiles-fromage",
"fr:Turron",
"fr:Vache-a-boire-aux-citrons-jaune-et-vert",
"fr:Vache-a-boire-mangue-passion",
"fr:Vache-a-boire-myrtille",
"fr:Vache-a-boire-vanille-de-madagascar",
"fr:Veau-hache",
"fr:Veloutés de courgettes",
"fr:Veloutés de tomates",
"fr:Vermicelle de riz",
"fr:Viande-bovine",
"fr:Viande-de-boeuf-sechee",
"fr:Viande-de-poulet",
"fr:Viande-en-sauce",
"fr:Viande-hache-de-boeuf",
"fr:Viande-preparee",
"fr:Viande-seche",
"fr:Viandes-hachees",
"fr:Vin-aperitif",
"fr:Vin-blanc-gewurztraminer-bio",
"fr:Vin-blanc-sec",
"fr:Vin-d-alsace-muscat-bio",
"fr:Vin-d-alsace-pinot-blanc-bio",
"fr:Vin-de-pays-rouge",
"fr:Vin-rose-gris-bio",
"fr:Vin-rouge-bonnezaux-bio",
"fr:Vin-rouge-de-bordeaux",
"fr:Vin-ventoux-aop-bio",
"fr:Vinaigre-d-alcool-8-d-acidite",
"fr:Vinaigres-balsamiques-de-modene",
"fr:Vinaigres de tomate",
"fr:Vinaigrette-allegee",
"fr:Vins américains",
"fr:Vins-de-cepage-zinfandel",
"fr:Vins-des-sables",
"fr:Vins mousseux",
"fr:Vins pétillant",
"fr:Vollailles",
"fr:Vollkornbrot-mini-toasts-pain-de-seigle-complet",
"fr:Vollkornbrot-pain-de-seigle-complet-bio",
"fr:Wrap-au-poulet",
"fr:Wrap-au-poulet-et-au-bacon",
"fr:Yaourt-a-la-vanille-de-madagascar",
"fr:Yaourt-au-lait-entier-sucre-a-la-framboise",
"fr:Yaourt-au-lait-entier-sucre-a-la-mure",
"fr:Yaourt-au-lait-entier-sucre-a-la-myrtille",
"fr:Yaourt-au-lait-pasteurise",
"fr:Yaourt-brasse-abricot-au-lait-entier-bio",
"fr:Yaourt-brasse-nature-bio",
"fr:Yaourt-de-brebis-a-la-grecque-bio",
"fr:Yaourt-de-brebis-nature",
"fr:Yaourt-maigre",
"fr:Yaourt-nature-0-bio",
"fr:Yaourt-nature-au-lait-de-chevre",
"fr:Yaourt-nature-bio",
"fr:Yaourt-nature-biologique",
"fr:Yaourt-onctueux-mangue-passion",
"fr:Yaourt-surce",
"fr:Yaourt-vanille-de-madagascar-bio",
"fr:Yaourts-a-l-abricot",
"fr:Yaourts-aromatises-au-lait-entier",
"fr:Yaourts-au-lait-entier-pruneaux",
"fr:Yaourts-aux-fruits-avec-morceaux-de-fruits",
"fr:Yaourts-aux-fruits-fraise",
"fr:Yaourts-brasse-sucre-aromatise",
"fr:Yaourts-brasses-nature-au-lait-entier-bio",
"fr:Yaourts-framboise",
"fr:Yaourts-grecs",
"fr:Yaourts-nature-alleges",
"fr:Yaourts-nature-sucres",
"fr:Yaourts-sans-morceaux",
"it:Fromage-frais",
"it:Pomodoro",
"it:Vino-frizzante"];
