var labelsTags = [

"Organic",
"fr:AB Agriculture Biologique",
"EU Organic",
"No preservatives",
"No colorings",
"fr:Ecocert",
"Gluten-free",
"Fair trade",
"PGI",
"FR-BIO-01",
"fr:Labels de distributeurs",
"FSC",
"fr:Viande Française",
"fr:AOC",
"PDO",
"Max Havelaar",
"Palm oil free",
"Carbon footprint",
"No added sugar",
"fr:Viande Porcine Française",
"Carbon compensated product",
"No artificial flavors",
"Carrefour Quality",
"No artificial colors",
"Vegetarian",
"No GMOs",
"fr:Label Carrefour",
"fr:Label Rouge",
"Fairtrade International",
"No additives",
"Sustainable fishery",
"No flavour enhancer",
"fr:Testé par le panel test Carrefour",
"No flavors",
"Sustainable Seafood MSC",
"fr:Viande Bovine Française",
"Pure cocoa butter",
"fr:Produit en Bretagne",
"fr:Halal",
"fr:Saveurs de l'Année",
"No added salt",
"fr:Porc Français",
"fr:Produit en braille",
"fr:Qualité France",
"fr:Garantie IPLC",
"fr:Aucun",
"No sugar",
"Rainforest Alliance",
"Vegan",
"fr:Sélection Intermarché",
"Made in France",
"No Bisphenol-A",
"fr:Naturel",
"CH-BIO-006",
"fr:100% muscle",
"Natural flavors",
"No aspartame",
"No lactose",
"RSPO",
"fr:Saveurs de l'Année 2012",
"fr:Saveurs de l'Année 2013",
"Kosher",
"Never frozen",
"fr:1-for-the-planet",
"fr:Bio-Solidaire",
"fr:Certipaq",
"fr:Volaille française",
"EU Agriculture",
"Pure pork",
"fr:Agri-confiance",
"fr:Cacher-lepessah",
"fr:Fumé au bois de hêtre",
"fr:Riche en Oméga-3",
"25% less salt",
"Demeter",
"Fed without GMOs",
"IT-BIO-006",
"Natural colorings",
"No caffeine",
"No cholesterol",
"Pure butter",
"fr:Acier-recyclable",
"fr:Bio-dynamie",
"fr:Bio-équitable",
"fr:Blé français",
"fr:Ccpb",
"fr:Certifie-par-bureau-veritas",
"fr:Certisys-be-bio-01",
"fr:Engagement-qualite-labeyrie",
"fr:Maitre-artisan",
"IT-BIO-009",
"No alcohol",
"USDA Organic",
"Without",
"fr:Bleu Blanc Coeur",
"fr:Controle-par-face",
"fr:Ecocert-sas-f-32600",
"fr:Entreprise-du-patrimoine-vivant",
"fr:Nature-progres",
"fr:Origine-france",
"fr:Qualite-u",
"fr:Recette-traditionnelle",
"fr:Recommande-par-ufsbd",
"fr:Sans-huiles-hydrogenees",
"fr:Sans-matiere-grasse-hydrogenee",
"fr:Sans-utilisation-d-ogm",
"1% for the planet",
"BE-BIO-01",
"BE-BIO-02",
"No lecithine",
"No milk",
"No soy",
"Pure juice",
"fr:Biologique-canada",
"fr:Bureau-veritas",
"fr:Caae",
"fr:Cereales-d-origine-locale",
"fr:Certisys",
"fr:De-oko-006",
"fr:Eco-emballages",
"fr:Ecolo-pass",
"fr:Eleve-en-plein-air",
"fr:Exploitations-familiales",
"fr:Filiere-alpina",
"fr:Origine-certifiee-sud-ouest",
"fr:Produit-en-gourmandie",
"fr:Sans-ajout-de-matiere-grasse",
"fr:Sans arachide",
"fr:Sans-conservateur-artificiel",
"fr:Sans-huile",
"fr:Sans-lecithine-de-soja",
"fr:Sans-proteines-de-lait",
"NL-BIO-01",
"No eggs",
"No MSG",
"Superior quality",
"Vegetarian Society",
"With Sunflower oil",
"es:Producto protegido de España",
"fr:1-solidaire",
"fr:10-th-international-food-award-dusseldorf-1987",
"fr:100-origine-france",
"fr:100-tournesol",
"fr:A-l-eau-de-source",
"fr:Abcert-ag",
"fr:Agriculture-francaise-durable",
"fr:Agriculture-france",
"fr:Alimentation-100-vegetaux-mineraux-et-vitamines",
"fr:An",
"fr:Animavinum",
"fr:Appelation-d-origine-protegee",
"fr:Artisan",
"fr:Bio-Cohérence",
"fr:Ble-de-france",
"fr:Canard-a-foie-gras-du-sud-ouest",
"fr:Certiconfiance",
"fr:Certifie-par-certipaq",
"fr:Certifie-par-qualisud",
"fr:Certifie-par-sgs-ics",
"fr:Certified-sustainable-palm-oil",
"fr:Choix-nutrition",
"fr:Collecte-de-proximite",
"fr:Dolphin-safe",
"fr:Dop",
"fr:Emballage-sans-aluminium",
"fr:Engagement-qualite-carrefour",
"fr:Equitable-ecocert",
"fr:European-fruit-juice-control-system",
"fr:Fabrication-artisan-chocolatier-francais",
"fr:Fairetrade",
"fr:Farine-100-francaise",
"fr:Filiere-soja-francais",
"fr:Fr-bio-10",
"fr:Garantie-avec-du-ble-complet",
"fr:Garantie-qualite-or",
"fr:Iglo-forever-food",
"fr:Lait-100-origine-france",
"fr:Lait-biologique-francais",
"fr:Lait-de-france",
"fr:Lait-non-homogeneise",
"fr:Lait-origine-france",
"fr:Medaille-d-or-paris-2011",
"fr:Non-fabrique-a-l-huile-d-arachide",
"fr:Oeufs-de-poules-elevees-en-plein-air",
"fr:Oeufs-origine-france",
"fr:Oeufs-pondus-en-france",
"fr:Oeufs-tries-a-la-main",
"fr:Origine-france-garantie",
"fr:Parmigiano-reggiano",
"fr:Pauvre-en-sodium",
"fr:Peche-a-la-ligne",
"fr:Pefc-30-31-113",
"fr:Porc-fermier-du-sud-ouest",
"fr:Premier-prix",
"fr:Producteurs-paysans",
"fr:Producteurs-regionaux",
"fr:Produit-de-montagne",
"fr:Pur-jus-de-fruits",
"fr:Recette-a-l-ancienne",
"fr:Salé au sel sec",
"fr:Sans-additif-artificiel",
"fr:Sans-adjonction-de-sel",
"fr:Sans-arete",
"fr:Sans-couenne",
"fr:Sans-emulsifiant",
"fr:Sans-epaississants",
"fr:Sans-gelatine",
"fr:Sans-graisse-ajoutee",
"fr:Sans-lactoserum",
"fr:Sans-levure-ajoute",
"fr:Sans-levure-ajoutee",
"fr:Sans-matiere-grasse-ajoute",
"fr:Sans-polyphosphate",
"fr:Sans-poudre-de-lait",
"fr:Sans-saccharose",
"fr:Saveurs de l'Année 2011",
"fr:Skal",
"fr:Sol-association",
"fr:Transforme-en-france",
"fr:Tres-faible-teneur-en-gluten",
"en:Ab",
"en:Agriculture-non-ue",
"DE-ÖKO-003",
"en:Ecocert",
"IT-BIO-007",
"IT-BIO-014",
"Not advised for pregnant women",
"en:Oko-garantie-bcs",
"Pure beef",
"TSG",
"With sulfites",
"es:DO",
"es:DO Navarra",
"es:VT",
"es:VT Castilla",
"fr:0-calories",
"fr:0-matieres-grasses",
"fr:0-pesticide",
"fr:1-for-planet",
"fr:10-th-international-food-award-duseldorf-1887",
"fr:100-arabica",
"fr:100-filet",
"fr:100-francais",
"fr:100-france",
"fr:100-natural-product",
"fr:100-plein-filet",
"fr:100-pommes-de-france",
"fr:100-pur-et-naturel",
"fr:100-pur-fruit-presse",
"fr:100-pur-grain",
"fr:100-pur-jus-de-fruits",
"fr:100-pur-jus-presse",
"fr:100-recyclable",
"fr:100-soja-francais",
"fr:100-teneur-en-fruits",
"fr:2-3-m-g",
"fr:25-de-sel-en-moins",
"fr:30-de-sucre-en-moins-que-la-moyenne-des-colas-hors-light",
"fr:30-de-sucres",
"fr:30-moins-sucre",
"fr:60-de-m-g",
"fr:62-de-sucres-49-d-acide-gras-satures-36-de-sel-par-rapport-a-la-moyenne-des-principaux-biscuits-du-marche",
"fr:67-d-acides-gras-satures",
"fr:70-de-cacao",
"fr:75-de-cacao-minimum",
"fr:A-l-huile-d-olive-vierge-extra",
"fr:A-la-levure-boulangere",
"fr:Abattu-en-france",
"fr:Aceto-balsamico-di-modena-igp",
"fr:Afdiag",
"fr:Afdiag-epi-barre",
"fr:Afdiag-epi-de-ble-barre-dans-un-cercle",
"fr:Affinage-5-mois-minimum",
"fr:Affinage-de-tradition",
"fr:Agriculteurs-n-utilisant-aucun-produit-chimique-de-synthese-ni-pesticides-ni-ensilage",
"fr:Agricultura-ecoloxica",
"fr:Agriculture-ecologique",
"fr:Agriculture-familiale",
"fr:Agriculture-francaise-equitable",
"fr:Agriculture-u-e",
"fr:Aide-ue",
"fr:Alimentation-100-vegetaux",
"fr:Allege-en-matieres-grasses-par-rapport-a-la-moyenne-des-jambons",
"fr:Allege-en-sucre",
"fr:Allegee-en-matieres-grasses",
"fr:Alliance-carton-nature",
"fr:Anima-vinum",
"fr:Animaux-nes-eleves-et-abattus-en-france",
"fr:Aoc-haut-medoc",
"fr:Apellation-d-origine-protegee",
"fr:Appelation-bourgone-passe-tout-grain-controlee",
"fr:Appellation-beaujolais-controlee",
"fr:Appellation-d-origine",
"fr:Appellation-d-origine-garantie-guerrouane",
"fr:Appellation-luberon-controlee",
"fr:Appellation-pommard-controlee",
"fr:Appertise",
"fr:Apport-en-matiere-grasse-maitrise",
"fr:Apport-en-sel-maitrise",
"fr:Aromes-et-colorants-naturels",
"fr:At-bio-301",
"fr:Au-feu-de-bois",
"fr:Au-lait-entier",
"fr:Au sel de Guérande",
"fr:Au-sel-de-mer",
"fr:Aucun-ensilage-d-herbe-ni-de-mais",
"fr:Aucune",
"fr:Aux-oeufs-frais",
"fr:Avec-arome-naturel",
"fr:Baratte-en-normandie",
"fr:Beurre-a-teneur-reduite-en-mg",
"fr:Bien-se-nourrir-pour-mieux-vivre",
"fr:Bio-allemand",
"fr:Bio-pays-de-la-loire",
"fr:Bio-vin-solidaire",
"fr:Biogarantie",
"fr:Ble-complet",
"fr:Ble-de-fabrication-francaise",
"fr:Ble-francais-issu-de-l-agriculture-responsable",
"fr:Ble-francais-selectionne",
"fr:Boeuf-d-origine-controle",
"fr:Boeuf-francais-controle",
"fr:Boi-europeen",
"fr:Bouteille-100-recyclable",
"fr:Boyau-naturel",
"fr:Brasserie-artisanale",
"fr:Bvcert",
"fr:Cabillaud-peche-en-atlantique-nord-ouest-et-atlantique-nord-est",
"fr:Cacao-30-minimum",
"fr:Cacao-30-minimum-dans-le-chocolat-au-lait",
"fr:Cacao-60-minimum",
"fr:Cacao-controle-par-ecocert-sa",
"fr:Canard-a-fois-gras-du-sud-ouest",
"fr:Carton-recyclable",
"fr:Cereal-partners",
"fr:Certification-france",
"fr:Certificato-biologico-icea",
"fr:Certifie-ab-fr-bio-01-agriculture-france",
"fr:Certifie-certisys-be-bio-01",
"fr:Certifie-iso-9001",
"fr:Certifie-par-abcert-ag",
"fr:Certifie-par-blik-b-2600",
"fr:Certifie-par-blik-b2600-be-bio-02",
"fr:Certifie-par-certisys",
"fr:Certifie-par-ocacia",
"fr:Certifie-par-skal-nl-bio-01",
"fr:Certifie-sud-ouest",
"fr:Certified-cocoa",
"fr:Certifiee-par-be-bio-001",
"fr:Certifiees-par-sgs-ics",
"fr:Certifies-par-qualisud",
"fr:Charte-qualite-environnement",
"fr:Chemouroth",
"fr:Chocolar-pur-beurre-de-cacao",
"fr:Chocolat-issus-du-commerce-equitable",
"fr:Choux-fleurs-de-bretagne",
"fr:Classe-a",
"fr:Cnipt-n-228-414-8733",
"fr:Cnipt-n-88519048",
"fr:Colorants-d-origine-naturels",
"fr:Comite-agricultura-ecologica",
"fr:Comte",
"fr:Concours-general-agricole-medaille-d-argent-2013",
"fr:Concours-general-agricole-medaille-d-argent-paris-2010",
"fr:Conservation-grade",
"fr:Conservation-naturelle",
"fr:Convient-a-l-alimentation-des-nourrissons",
"fr:Creme-d-isigny",
"fr:Cru-bourgeois",
"fr:Cueillis-a-la-main",
"fr:Cuisine-en-france",
"fr:Cuisine-sans-huile-de-palme",
"fr:Cuisson-en-chaudron-de-cuivre-rouge",
"fr:Cuisson-vapeur",
"fr:Cuit-sur-pierre",
"fr:Cuite-au-chaudron",
"fr:Cuite-sur-pierre",
"fr:Cultive-recolte-en-france",
"fr:Cuvee-prestige",
"fr:De-85-de-fruits",
"fr:De-oko-034",
"fr:Decongele-sur-place",
"fr:Denominacion-de-origen",
"fr:Denominazione-di-origine-protetta",
"fr:Developpe-les-energies-renouvelables",
"fr:Distillee-trois-fois",
"fr:Distribution-certifiee",
"fr:Distribution-certifiee-par-ecocert",
"fr:Distribution-certifiee-par-ecocert-sas",
"fr:Distribution-certifiee-qualite-france-sas-fr-bio-10",
"fr:Duree-de-vie-56-jours-minimum",
"fr:Eco-emballage",
"fr:Ecocert-f-32600",
"fr:Ecocert-fr-bio-01",
"fr:Ecocert-s-a-s-f-32600",
"fr:Ecoemballage",
"fr:Ecolopass",
"fr:Elabore-au-pays-d-auge",
"fr:Elabore-avec-les-conseils-d-un-comite-de-pediatres",
"fr:Elabore-par-un-nutritionniste",
"fr:Eleve-en-france",
"fr:Eleve-en-futs-de-chene",
"fr:Eleve-sans-antibiotiques",
"fr:Eleveurs-laitiers-de-france",
"fr:Elu-produit-de-l-annee-2011",
"fr:Emballage-100-recyclable",
"fr:Emballage-reduit",
"fr:Engagement-qualite",
"fr:Entr-aide",
"fr:Entreprise-adaptee",
"fr:Eqc",
"fr:Eqcs-european-fruit-juice-control-system",
"fr:Es-eco-002",
"fr:Etiquette-en-braille",
"fr:F-32600-fr",
"fr:Fabrication-artisanale",
"fr:Fabrication-traditionnelle",
"fr:Fabrique-dans-le-jura",
"fr:Fabrique-en-isere",
"fr:Facile-a-digerer",
"fr:Faible-teneur-en-matiere-grasse",
"fr:Faible-teneur-en-matieres-grasses",
"fr:Faible-teneur-en-sel",
"fr:Fairtrade-max-havelaar",
"fr:Fairtraide",
"fr:Fibres",
"fr:Fieko-201",
"fr:Filiere-nutrition-omega-3-naturels",
"fr:Filiere-quinoa-bio-equitable",
"fr:Filiere-soja-francais-sans-ogm",
"fr:Filiere-soja-francais-sans-ogm-sojasun",
"fr:Flo-cert",
"fr:Fr-43-040-002-ce",
"fr:Fr-bio",
"fr:Fr-bio-09",
"fr:Fsc-c002324",
"fr:Fsc-c014047",
"fr:Fumage-au-bois-de-hetre",
"fr:Garantie-boeuf-francais-controle",
"fr:Garantie-qualite",
"fr:Gb-org-05",
"fr:Gb-organic-certification-5",
"fr:Glucoregul",
"fr:Good-food-foundation",
"fr:Great-taste-gold-09",
"fr:Guild-of-conservation-grade",
"fr:Huile-de-palme-durable",
"fr:Huile-de-palme-durable-certifiee-rspo",
"fr:Huile-de-palme-issue-de-forets-gerees-durablement",
"fr:Imo",
"fr:Impact-environnemental-reduit",
"fr:Imprim-vert",
"fr:Incice-carbone",
"fr:Indice-carbone",
"fr:Indice-environnemental-3-6-pour-100g",
"fr:Inspire",
"fr:Inspire-teste-et-approuve-par-le-panel-test-carrefour",
"fr:It-bio-006-agriculture-ue",
"fr:Jambon-qualite-superieure",
"fr:Label-quot-dolphin-safe-quot",
"fr:Lait-100-francais",
"fr:Lait-bio-francais",
"fr:Lait-bio-origine-france",
"fr:Lait-collecte-en-mayenne",
"fr:Lait-collectee-dans-les-fermes-selectionnees",
"fr:Lea-nature",
"fr:Lea-nature-group",
"fr:Leaf",
"fr:Legumes-frais-francais",
"fr:Liger-d-argent-2013-concours-vins-du-val-de-loire",
"fr:Lu-harmony",
"fr:Mais-doux-cultive-en-france",
"fr:Mais-sans-ogm",
"fr:Maitre-confiturier-de-france",
"fr:Marque-repere",
"fr:Master-blenders",
"fr:Medaille-argent-bruxelles-2012",
"fr:Medaille-argent-concours-mondial-bruxelles-2012",
"fr:Medaille-argent-vinalles-internationales-2013-paris",
"fr:Medaille-bronze-concours-2012-vignerons-independants",
"fr:Medaille-bronze-vignerons-independants-2012",
"fr:Medaille-d-argent-2013",
"fr:Medaille-d-argent-concours-des-burgondia-2010",
"fr:Medaille-d-argent-concours-general-agricole-paris-2013-medaille-de-l-agriculture-et-de-l-alimentation",
"fr:Medaille-d-argent-concours-mondial-bruxelles-2011",
"fr:Medaille-d-argent-paris",
"fr:Medaille-d-argent-paris-2012",
"fr:Medaille-d-argent-vinalies-internationales-2012-paris",
"fr:Medaille-d-or",
"fr:Medaille-d-or-2012",
"fr:Medaille-d-or-concours-de-bordeaux-2011",
"fr:Medaille-d-or-concours-general-agricole-paris",
"fr:Medaille-d-or-concours-general-agricole-paris-2011",
"fr:Medaille-d-or-paris-2012",
"fr:Medaille-d-or-paris-2013-concours-general-agricole",
"fr:Medaille-de-bronze-macon-2012",
"fr:Medaille-or-agriculture",
"fr:Medaille-or-concours-general-agricole-2012",
"fr:Medaille-or-du-guide-gilbert-gaillard",
"fr:Mg",
"fr:Moins-de-1-de-sel",
"fr:Moule-a-la-louche",
"fr:Mozzarella-di-bufala",
"fr:Msc-sgs-nl-msc-c-0031",
"fr:N-de-tracabilite-07050-e-137",
"fr:N-de-tracabilite-26050-o-211-g-30",
"fr:Nature-et-progres",
"fr:Naturellement-sans-gluten",
"fr:Ne-en-france",
"fr:No-artificial-colourings",
"fr:Non-irradiees",
"fr:Non-ogm",
"fr:Nothing-artificial",
"fr:Nourri-sans-ogm-lt-0-9",
"fr:Oeuf-de-poule-alimentee-avec-65-de-cereales",
"fr:Oeuf-de-poule-fermiere-elevee-en-liberte",
"fr:Oeufs-francais",
"fr:Omega-3",
"fr:Origine-bles-de-france",
"fr:Origine-italie",
"fr:Panel-carrefour",
"fr:Participe-au-reboisement",
"fr:Pate-pur-beurre",
"fr:Pates-fraiches",
"fr:Pauvre-en-gluten",
"fr:Pauvre-en-sel",
"fr:Peche-francaise",
"fr:Petits-producteurs",
"fr:Plant-bottle",
"fr:Plastique-pet-recyclable",
"fr:Point-vert",
"fr:Poissons-bleus-de-bretagne",
"fr:Pommes-de-france",
"fr:Porc-charcutier-breton",
"fr:Porc-ne-et-eleve-au-pays-basque",
"fr:Poules-elevees-en-liberte",
"fr:Poules-nourries-sans-ogm",
"fr:Presence-de-l-indice-environnemental",
"fr:Preservation-des-ressources-marines",
"fr:Preservation-du-patrimoine-forestier-mondial",
"fr:Prix-des-vinalies-2012",
"fr:Prodotto-in-italia",
"fr:Producteur-regionaux",
"fr:Production-certifiee-ccpb",
"fr:Produit-cerfifie-alimente-100-de-vegetaux",
"fr:Produit-dans-le-parc-naturel-perigord-limousin",
"fr:Produit-normalise-i",
"fr:Produit-qualite",
"fr:Produit-trappiste-authentique",
"fr:Produto-organico-brasil",
"fr:Programme-d-agriculture-durable",
"fr:Programme-fracais-de-recuperation-et-de-retraitement-des-emballages",
"fr:Programme-francais-de-recuperation-et-de-retraitement-des-emballages",
"fr:Proteines-100-vegetales",
"fr:Pure-chocolat",
"fr:Qualisud",
"fr:Qualite-controlee",
"fr:Qualite-danoise",
"fr:Qualite-garantie",
"fr:Qualite-responsable",
"fr:Qualite-sans-arrete",
"fr:Qualite-supreme",
"fr:Race-charolaise",
"fr:Rafraichissant",
"fr:Recette-artisanale",
"fr:Recette-originale",
"fr:Recoltes-testees-et-controlees-analyse-pesticides-et-metaux-lourds",
"fr:Recommande-par-usfbd",
"fr:Reconnu-saveur-de-l-annee-2012-goute-par-un-jury-de-consommateurs",
"fr:Regime-lacto-ovo-vegetarien",
"fr:Riche-en-acide-gras-omega-3",
"fr:Riche-en-calcium",
"fr:Riche-en-fibres",
"fr:Riche-en-gout",
"fr:Riche-en-proteines",
"fr:Riche-en-vitamine-e",
"fr:Riche-n-omega-3-naturels",
"fr:Riz-de-camargue",
"fr:Roquefort",
"fr:Rspo-1106065",
"fr:Rspo-1106067",
"fr:Sale-au-sel-fin",
"fr:Sans-acides-gras-trans",
"fr:Sans-addition-de-polyphosphate",
"fr:Sans-addition-de-polyphosphates",
"fr:Sans-agent-conservateur",
"fr:Sans-ajout-de-glutamate-monosodique",
"fr:Sans-aretes",
"fr:Sans-arretes",
"fr:Sans-ble",
"fr:Sans-cartilage",
"fr:Sans-cartillage",
"fr:Sans-colorant-ni-conservateur",
"fr:Sans-concervateur",
"fr:Sans-conservateurs-artificiels",
"fr:Sans-conservatteur",
"fr:Sans-conversateur",
"fr:Sans-edulcorant",
"fr:Sans-edulcorant-artificiel",
"fr:Sans-edulcorants",
"fr:Sans-electronarcose",
"fr:Sans-epaissisant",
"fr:Sans-epaississant",
"fr:Sans-exhausteurs-de-gout-artificiels",
"fr:Sans-extrait",
"fr:Sans-fruit-a-coque",
"fr:Sans-glutamate-ajoute",
"fr:Sans-graisses-animales",
"fr:Sans-graisses-hydrogenees",
"fr:Sans-ingredient-a-base-de-gluten",
"fr:Sans-matiere-grasse",
"fr:Sans-matieres-grasses-hydrogenee",
"fr:Sans-matieres-grasses-hydrogenees",
"fr:Sans-morceaux",
"fr:Sans-peau",
"fr:Sans-pepin",
"fr:Sans-polyphosphates",
"fr:Sans-produit-laitier",
"fr:Sans-proteine-de-lait",
"fr:Sans-sel",
"fr:Sans-sulfites",
"fr:Sans-utilisation-de-pecticide",
"fr:Sans-utilisation-de-pecticides",
"fr:Sans-utilisation-de-pesticide",
"fr:Sans-viande",
"fr:Sans-vitamine-d3",
"fr:Saveur-2002",
"fr:Saveur-d-or-2011-concours-des-saveurs-regionales",
"fr:Saveur-en-or",
"fr:Saveur-preservee",
"fr:Saveurs-en-or",
"fr:Saveurs-paris-ile-de-france",
"fr:Selectionne-par-nos-fromagers",
"fr:Solo-pomodoro-italiano",
"fr:Source-de-calcium",
"fr:Sucre-d-origine-naturelle",
"fr:Sucre-roux-non-raffine-pure-canne",
"fr:Surgele",
"fr:Teste-et-approuve-par-le-pannel-test-carrefour",
"fr:Tomates-de-plein-champ",
"fr:Toothfriendly",
"fr:Traditions-mediterraneennes",
"fr:Trophee-de-l-innovation",
"fr:Utz-certified",
"fr:Utz-certified-cacao",
"fr:Utz-certified-cocoa",
"fr:Vegan-friendly",
"fr:Veritablement-fume-en-tuye",
"fr:Veritas",
"fr:Viande-100-jambon",
"fr:Viande-100-muscle",
"fr:Viande-bovine-fracaise",
"fr:Viande-charolaise",
"fr:Viande-d-origine-controlee",
"fr:Viande-de-boeuf-origine-france",
"fr:Viande-de-porc-francais",
"fr:Viande-de-porc-origine-france",
"fr:Vignerons-independants",
"fr:Vit",
"fr:Volaille-origine-france",
"fr:Volailles-de-nos-regions",
"it:Denominazione-d-origine-protetta",
"it:Docg",
"it:Indicazione-geografica-tipica",
"it:Origine-controllata",
"it:Qualita-controllata"];
