var categoriesTags = [

"Dairies",
"Yogurts",
"Plain yogurts",
"Fruit yogurts",
"Alcoholic drinks",
"Beers",
"Beverages",
"Breads",
"Drinkable yogurts",
"Meats",
"Prepared meats",
"Sausages",
"Vanilla yogurts",
"fr:Bières blondes",
"fr:Biscottes",
"fr:Knacks industrielles",
"fr:Saucisses de Strasbourg",
"fr:Saucisses françaises",
"fr:The-vert-au-miel",
"fr:Yaourts-a-boire-a-la-vanille",
"fr:Yaourts-a-la-goyave",
"fr:Yaourts-natures-bio"];
