var categoriesTags = [

"Produits laitiers",
"Yaourts",
"Yaourts natures",
"Yaourts aux fruits",
"Boissons alcoolisées",
"Bières",
"Boissons",
"Pains",
"Yaourts à boire",
"Viandes",
"Charcuteries",
"Saucisses",
"Yaourts vanille",
"Bières blondes",
"Biscottes",
"Knacks industrielles",
"Saucisses de Strasbourg",
"Saucisses françaises",
"The-vert-au-miel",
"Yaourts-a-boire-a-la-vanille",
"Yaourts-a-la-goyave",
"Yaourts-natures-bio"];
