var categoriesTags = [

"Extra-virgin olive oils",
"Fats",
"Olive oils",
"Vegetable fats",
"Vegetable oils",
"Vegetables and derived products",
"es:Untables vegetales",
"es:Mermeladas-y-confituras",
"es:Untables",
"es:Untables-dulces",
"Vinegars",
"es:Mermeladas-y-confituras-de-frutas",
"es:Endulzantes",
"es:Miel",
"Condiments",
"Groceries",
"es:",
"es:Azafrán",
"es:Especias",
"Pickled vegetables",
"Pickles",
"Vegetables",
"Green olives",
"Olives",
"Beverages",
"Carbonated drinks",
"Green whole olives",
"Marinated olives",
"Mixed pickles",
"Sodas",
"Whole olives",
"es:Mermeladas-y-confituras-de-citricos",
"es:Mermeladas-y-confituras-de-flores",
"es:Mermeladas-y-confituras-de-higos",
"es:Mermeladas-y-confituras-de-petalos-de-rosas",
"Candies",
"Dairies",
"Whole marinated green olives",
"es:Mermeladas-y-confituras-de-cebolla",
"es:Mermeladas-y-confituras-de-manzana",
"es:Mermeladas-y-confituras-de-naranja",
"es:Mermeladas-y-confituras-de-peras",
"es:Mermeladas-y-confituras-de-verduras-y-hortalizas",
"es:Mermeladas-y-confituras-multifruta",
"es:Patés vegetales",
"Banderillas",
"Cereals",
"Chocolates",
"Citrus-fruit",
"Cracked marinated green olives",
"Cracked olives",
"Green cracked olives",
"Green pitted olives",
"Meats",
"Milks",
"Pastas",
"Pitted olives",
"Prepared meats",
"Rices",
"Seafood",
"Soy milks",
"Yogurts",
"es:Mermeladas-y-confituras-de-cereza",
"es:Mermeladas-y-confituras-de-limon",
"es:Mermeladas-y-confituras-de-melocoton",
"fr:Bonbons",
"fr:Bonbons-a-la-reglisse",
"fr:Drop",
"fr:Laits végétaux",
"fr:Méduse",
"fr:Rehausseur-de-gout",
"fr:Riz Basmati",
"fr:Salmiak",
"fr:Saucissons",
"fr:Saucissons secs",
"fr:Thés glacés",
"nl:Pastasaus"];
