var categoriesTags = [

"Dairies",
"Candies",
"Fishes",
"Seafood",
"Beverages",
"Breakfasts",
"Desserts",
"Groceries",
"fr:Céréales pour petit-déjeuner",
"fr:Compotes",
"Canned fishes",
"Canned foods",
"Cheeses",
"Chocolates",
"Fats",
"Fruit juices and nectars",
"Pastas",
"Smoked fishes",
"Vegetable fats",
"Vegetables and derived products",
"fr:Bonbons",
"fr:Chocolats noirs",
"fr:Fromages pasteurisés",
"Breakfast-cereals",
"Canned sardines",
"Cow Cheeses",
"Creams",
"Dried fruits",
"Frozen foods",
"Fruit juices",
"Fruit nectars",
"Galette",
"Ice creams",
"Ice creams and sorbets",
"Margarines",
"Oil",
"Orange juices",
"Pain",
"Pates",
"Produits-laitiers",
"Rapeseed oils",
"Sardines",
"Sauces",
"Tortillas",
"Tunas",
"Vegetable oils",
"Yogurts",
"fr:Chocolats pur beurre de cacao",
"fr:Confiserie-fantaisie",
"fr:Crèmes fraîches",
"fr:Crèmes fraîches liquides",
"fr:Crèmes glacées",
"fr:Foie-de-morue",
"fr:Fromages à pâte fraîche",
"fr:Fromages de chèvre",
"fr:Glaces à la vanille",
"fr:Mayonnaises",
"fr:Mayonnaises allégées",
"fr:Morues",
"fr:Mueslis",
"fr:Pates",
"fr:Pâtes fraîches",
"fr:Produit-au-wasabi",
"fr:Sardines à l'huile",
"fr:Sirops",
"fr:Sirops de citron",
"fr:Thons albacore",
"fr:Thons au naturel",
"fr:Thons tropicaux",
"fr:Tortellini",
"fr:Vermicelle de riz"];
