var categoriesTags = [

"Produits laitiers",
"Confiseries",
"Poissons",
"Produits de la mer",
"Boissons",
"Petit-déjeuners",
"Desserts",
"Epicerie",
"Céréales pour petit-déjeuner",
"Compotes",
"Poissons en conserve",
"Conserves",
"Fromages",
"Chocolats",
"Matières grasses",
"Jus et nectars de fruits",
"Pâtes alimentaires",
"Poissons fumés",
"Matières grasses végétales",
"Végétaux et dérivés",
"Bonbons",
"Chocolats noirs",
"Fromages pasteurisés",
"en:Breakfast-cereals",
"Sardines en conserve",
"Fromages de vache",
"Crèmes",
"Fruits secs",
"Surgelés",
"Jus de fruits",
"Nectars de fruits",
"en:Galette",
"Glaces",
"Glaces et sorbets",
"Margarines",
"en:Oil",
"Jus d'orange",
"en:Pain",
"en:Pates",
"en:Produits-laitiers",
"Huiles de colza",
"Sardines",
"Sauces",
"en:Tortillas",
"Thons",
"Huiles",
"Yaourts",
"Chocolats pur beurre de cacao",
"Confiserie-fantaisie",
"Crèmes fraîches",
"Crèmes fraîches liquides",
"Crèmes glacées",
"Foie-de-morue",
"Fromages à pâte fraîche",
"Fromages de chèvre",
"Glaces à la vanille",
"Mayonnaises",
"Mayonnaises allégées",
"Morues",
"Mueslis",
"Pates",
"Pâtes fraîches",
"Produit-au-wasabi",
"Sardines à l'huile",
"Sirops",
"Sirops de citron",
"Thons albacore",
"Thons au naturel",
"Thons tropicaux",
"Tortellini",
"Vermicelle de riz"];
