var statusTags = [

"A compléter",
"A vérifier",
"Caractéristiques complétées",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Complete",
"Date limite à compléter",
"Date limite complétée",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingredients-completed",
"Ingrédients complétés",
"Ingredients-to-be-completed",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos validées",
"Quantity-to-be-completed",
"To-be-checked",
"To-be-completed"];
