var categoriesTags = [

"Dairies",
"Desserts",
"fr:Compotes",
"Beverages",
"Cheeses",
"Fishes",
"Seafood",
"fr:Fromages pasteurisés",
"Canned fishes",
"Canned foods",
"Canned sardines",
"Cow Cheeses",
"Creams",
"Fats",
"Fruit juices and nectars",
"Fruit nectars",
"Pastas",
"Rapeseed oils",
"Sardines",
"Tunas",
"Vegetable fats",
"Vegetable oils",
"Yogurts",
"fr:Crèmes fraîches",
"fr:Crèmes fraîches liquides",
"fr:Fromages à pâte fraîche",
"fr:Fromages de chèvre",
"fr:Pâtes fraîches",
"fr:Sardines à l'huile",
"fr:Sirops",
"fr:Sirops de citron",
"fr:Thons albacore",
"fr:Thons au naturel",
"fr:Thons tropicaux",
"fr:Tortellini"];
