var categoriesTags = [

"Beverages",
"Dairies",
"Meals",
"Candies",
"Groceries",
"Vegetables",
"Biscuits",
"Meats",
"Cheeses",
"Desserts",
"Seafood",
"fr:Bio",
"Prepared meats",
"Frozen foods",
"Chocolates",
"Fishes",
"Breakfasts",
"fr:Sauces",
"Canned foods",
"Fruit juices and nectars",
"Cereals",
"Carbonated drinks",
"Fruit juices",
"es:Vegetales y derivados",
"Sodas",
"Alcoholic drinks",
"Fats",
"Hot drinks",
"Wines",
"Pastas",
"Yogurts",
"fr:Gouter",
"Milks",
"Breads",
"Cakes",
"fr:Apéritif",
"Cow Cheeses",
"Spreads",
"Condiments",
"es:Vegetales frescos",
"fr:Céréales pour petit-déjeuner",
"Herbal teas",
"fr:Plats cuisinés surgelés",
"fr:Compotes",
"es:Vegetales-congelados",
"Rices",
"fr:Pates",
"Sweet spreads",
"es:Pan-y-reposteria",
"fr:Chocolats noirs",
"fr:Légumes en conserve",
"Spices",
"Canned fishes",
"Pickled vegetables",
"Pickles",
"Hams",
"Fresh",
"Vegetable fats",
"Animal fats",
"fr:Bonbons",
"Beers",
"Butters",
"Red wines",
"Farming products",
"fr:Fromages pasteurisés",
"Waters",
"Baby foods",
"Soups",
"Vegetable oils",
"Chips and fries",
"Orange juices",
"Sardines",
"es:Alimentos estimulantes",
"es:Cacaos y chocolates",
"Teas",
"Dried fruits",
"Olives",
"Ice creams and sorbets",
"Smoked fishes",
"fr:Cafés",
"Canned sardines",
"fr:Chips",
"fr:Plats préparés à réchauffer au micro-ondes",
"fr:Chocolats au lait",
"fr:Oeufs",
"Salmons",
"Squeezed juices",
"fr:Sirops",
"fr:Biscuits au chocolat",
"Sugars",
"Ice creams",
"Tunas",
"fr:Fromages à pâte molle à croûte fleurie",
"fr:Saucissons",
"es:Aperitivos",
"fr:Pâtes à tartiner",
"fr:Laits végétaux",
"es:Cereales-y-derivados",
"fr:Eaux minérales",
"fr:Sodas au cola",
"es:Bebidas vegetales",
"fr:Moutardes",
"fr:Sardines à l'huile",
"Sausages",
"fr:Jambons blancs",
"Fresh vegetables",
"es:Platos-preparados-vegetales",
"Jams",
"fr:Laits demi-écrémés",
"fr:Sauces tomate",
"fr:Saumons fumés",
"Olive oils",
"fr:Fromages à pâte fraîche",
"Creams",
"Sandwiches",
"Vinegars",
"fr:Barres",
"es:Vegetales",
"Flours",
"Poultries",
"fr:Compotes de pomme",
"fr:Mueslis",
"fr:Pains de mie",
"Diet drinks",
"Fruit sodas",
"Fruits",
"fr:Beurres doux",
"Green olives",
"es:Vegetales en conserva",
"fr:Laits UHT",
"fr:Légumes secs",
"Diet sodas",
"es:Hierbas-aromaticas-y-especias",
"fr:Biscottes",
"fr:Camemberts",
"Apple juices",
"French cheeses",
"Salts",
"White wines",
"fr:Limonades",
"fr:Plats préparés en conserve",
"fr:Tablettes de chocolat",
"es:Frutos-secos",
"fr:Maquereaux",
"fr:Pizzas",
"fr:Bières blondes",
"fr:Pâtes fraîches",
"Fruit yogurts",
"es:Frutas frescas",
"es:Untables vegetales",
"fr:Crêpes et galettes",
"fr:Fromages de chèvre",
"fr:Oeufs plein air",
"fr:Plats préparés frais",
"Concentrated fruit juices",
"Labeled products",
"Cookies",
"Green teas",
"es:Dulces-tipicos-de-navidad",
"fr:Beurres demi-sel",
"fr:Crèmes fraîches",
"Meta-category",
"Bee products",
"Nuts",
"es:Patés vegetales",
"es:Vegetales deshidratados",
"fr:Sardines à l'huile d'olive",
"Rillettes",
"fr:Charcuteries diverses",
"fr:Chocolats en poudre",
"fr:Cidres",
"fr:Crèmes glacées",
"fr:Saucisses françaises",
"fr:Fromages à pâte pressée cuite",
"fr:Galettes de céréales",
"fr:Mayonnaises",
"fr:Saumons fumés d'élevage",
"Honeys",
"Vegetable rods",
"es:Postres-vegetales",
"fr:Chewing-gum",
"fr:Ravioli",
"Crustaceans",
"Pastries",
"fr:Brioches",
"fr:Couscous",
"fr:Lardons",
"fr:Pâtes à tartiner aux noisettes",
"fr:Purées",
"fr:Salades",
"fr:Yaourts natures",
"Hard liquors",
"fr:Sodas au cola light",
"Stirred yogurts",
"Tomatoes",
"Wheat flours",
"es:Mermeladas-y-confituras",
"fr:Cafés moulus",
"fr:Riz Basmati",
"fr:Riz long grain",
"Fruit nectars",
"Mushrooms",
"Squeezed orange juices",
"es:Preparados-vegetales",
"fr:Dès 06 mois",
"fr:Fromages râpés",
"fr:Pains azymes",
"fr:Poulets",
"fr:Barres de céréales",
"fr:Fromages blancs",
"fr:Jambons crus",
"fr:Ketchup",
"fr:Sablés",
"Emmentaler",
"fr:Soupes déshydratées",
"fr:Bouillon",
"fr:Maïs en conserve",
"fr:Plats susceptibles de contenir de la viande de cheval - lots retirés de la vente en février 2013",
"fr:Spaghetti",
"fr:Sucres de canne",
"Food additives",
"Virgin olive oils",
"es:Tofus",
"fr:Barres chocolatées",
"fr:Biscuits-aperitifs",
"fr:Eaux-de-vie",
"fr:Fromages à pâte pressée non cuite",
"fr:Lentilles sèches",
"fr:Quenelles",
"fr:Semoule-de-ble-dur",
"fr:Veloutés",
"Black olives",
"Waffles",
"fr:Chips de pommes de terre",
"fr:Crèmes dessert",
"fr:Fruits au sirop",
"fr:Légumes surgelés",
"fr:Lentilles",
"fr:Sucrerie",
"Chili peppers",
"Drinkable yogurts",
"fr:Bourgogne",
"fr:Eaux gazeuses",
"fr:Goûters et desserts pour bébé",
"fr:Laits de soja",
"fr:Lasagnes préparées",
"fr:Mozzarella",
"fr:Sauces pour pâtes",
"Balsamic vinegars",
"Margarines",
"Meals with meat",
"Products with reduced salt",
"Salted spreads",
"fr:Foies gras",
"fr:Fromages au lait cru",
"fr:Taboulés",
"fr:Vins rosés",
"Breaded products",
"Chocolate desserts",
"Potatoes",
"fr:Dès 12 mois",
"fr:Filets de Maquereaux",
"fr:Fromage à pâte pressée cuite",
"fr:Gâteaux apéritifs",
"fr:Pâtes à tarte",
"fr:Petits beurres",
"fr:Plats principaux pour bébé",
"fr:Thons tropicaux",
"fr:Viandes de porc",
"Culinary plants",
"es:Caldos-consomes-sopas-y-cremas",
"es:Hamburguesas-vegetales",
"fr:Chips de pommes de terre à l’huile de tournesol",
"fr:Crêpes",
"fr:Lardons fumés",
"fr:Oeufs labellisés",
"fr:Semoule",
"fr:Thés glacés",
"fr:Thons albacore",
"fr:Crevettes",
"fr:Laits pour bébé",
"fr:Moutardes de Dijon",
"fr:Poissons panés",
"fr:Rillettes de poissons",
"fr:Sans-gluten",
"fr:Cornichons",
"fr:Édulcorants",
"fr:Galettes",
"fr:Poivrons",
"fr:Thés noirs",
"fr:Thons au naturel",
"Dried hams",
"Extra-virgin olive oils",
"Marinated olives",
"Pies",
"es:Legumbres-y-derivados",
"fr:Eaux minérales naturelles",
"fr:Laits de coco",
"fr:Pain grillé",
"fr:Pains de mie complet",
"fr:Poivres",
"fr:Quinoa",
"Aromatic plants",
"Bordeaux",
"fr:Amandes",
"fr:Charcuteries à teneur réduite en sel",
"fr:Eaux de sources",
"fr:Raviolis en conserve",
"Blue-veined cheeses",
"Grapefruit juices",
"Pitted olives",
"fr:Champignons de Paris",
"fr:Chocolats de dégustation",
"fr:Chocolats dessert",
"fr:Frites",
"fr:Haricots verts en conserve",
"fr:Jambons blancs à teneur réduite en sel",
"fr:Jambons de Paris",
"fr:Lentilles vertes",
"fr:Riz long",
"fr:Terrines",
"Asparagus",
"Concentrated orange juices",
"Pineapple juices",
"Tropical fruits",
"Whole milk yogurts",
"es:Infusiones",
"fr:Boissons énergisantes",
"fr:Fromages à tartiner",
"fr:Fromages italiens",
"fr:Haricots-verts",
"fr:Laits demi-écrémés biologiques",
"fr:Laits écrémés",
"fr:Sodas au citron",
"fr:Soja",
"es:Semillas",
"fr:Desserts au soja",
"fr:Fromages fondus",
"fr:Gaufrettes",
"fr:Genoise",
"fr:Laits entiers",
"fr:Madeleines",
"fr:Maquereaux en conserve",
"fr:Petits-pois",
"fr:Produits Label Rouge",
"fr:Saucissons secs pur porc",
"Aromatic herbs",
"Artisan products",
"Cracked marinated green olives",
"Cracked olives",
"Flavors",
"Green cracked olives",
"Whole olives",
"es:Platos-preparados",
"fr:Aide-culinaire",
"fr:Boisson-aux-fruits",
"fr:Cidres demi-secs",
"fr:Compotes pommes nature",
"fr:Comté",
"fr:Cookies au chocolat",
"fr:Corn-flakes",
"fr:Croutons",
"fr:Dès 04 mois",
"fr:Emmentals rapés",
"fr:Fromages AOC",
"fr:Fromages labéllisés",
"fr:Gouters",
"fr:Pate",
"fr:Pop-corn",
"fr:Produits AOC",
"fr:Rhums",
"fr:Salades composées",
"fr:Sorbets",
"fr:Soupes de légumes",
"fr:Vins effervescents",
"Green pitted olives",
"Wine vinegars",
"fr:Bacon",
"fr:Beurres moulés",
"fr:Colins",
"fr:Compotes pour bébé",
"fr:Coquillettes",
"fr:Coulommiers",
"fr:Galettes de riz",
"fr:Hachis parmentier",
"fr:Infusion-bio",
"fr:Laits concentrés",
"fr:Menus Viandes pour bébé",
"fr:Pâtes feuilletées",
"fr:Plats à base de viande bovine",
"fr:Plats préparés surgelés",
"fr:Pois-chiches",
"fr:Purées d'oléagineux",
"fr:Riz cargo",
"fr:Riz thaï",
"fr:Sardines à la tomate",
"fr:Sauces au soja",
"fr:Saucisses de Strasbourg",
"fr:Sirops de menthe",
"fr:Steaks-haches",
"fr:Surimi",
"fr:Tomates en conserve",
"Fish fillets",
"French wines",
"Potted meats",
"Sweetened yogurts",
"es:Bebidas-de-zumo-y-soja",
"es:Endulzantes",
"fr:Biscuits-sales",
"fr:Blancs de poulet",
"fr:Champagne",
"fr:Chorizos",
"fr:Choucroutes",
"fr:Coeurs de palmier",
"fr:Complement-alimentaire",
"fr:Crabes",
"fr:Dessert-lacte",
"fr:Farines de blé type T45",
"fr:Fromages à pâte fondue",
"fr:Fromages industriels",
"fr:Glaces au chocolat",
"fr:Haricots",
"fr:Légumes préparés",
"fr:Oeufs biologiques",
"fr:Pâtes à tartiner au chocolat",
"fr:Pâtes sèches",
"fr:Pistaches",
"fr:Raviolis frais",
"fr:Sauces Pesto",
"fr:Sels fins",
"fr:Sels marins",
"fr:Sirops de grenadine",
"fr:Sodas à l'orange",
"fr:Sodas aux fruits light",
"fr:Sucre-en-poudre",
"fr:Sucres en morceaux",
"fr:Tagliatelles",
"fr:Thons à l’huile",
"Products without gluten",
"Refrigerated squeezed juices",
"Soft cheeses with washed rind",
"Sunflower oils",
"es:Aguas envasadas y hielo",
"es:Aguas minerales naturales",
"es:Algas",
"fr:Assaisonnements",
"fr:Blé",
"fr:Cafes-en-dosettes",
"fr:Cafés en poudre",
"fr:Chocolats blancs",
"fr:Compotes à boire",
"fr:Cordons bleus",
"fr:Crèmes fraîches épaisses",
"fr:Filets de sardine",
"fr:Fromages à pâte persillée français",
"fr:Jus-de-citron",
"fr:Laits de croissance",
"fr:Nems",
"fr:Oeufs Label Rouge",
"fr:Pains azymes à la farine de froment",
"fr:Parmigiano Reggiano",
"fr:Plats à base de volaille",
"fr:Poissons surgelés",
"fr:Purées de pommes de terre",
"fr:Raclettes",
"fr:Raviolis au boeuf",
"fr:Sardines à l'huile de tournesol",
"fr:Stevia",
"fr:Vin-rouge-bio",
"Concentrated apple juices",
"Ducks",
"Grape juices",
"Products sold before year 2000",
"fr:Alcools artisanaux",
"fr:Biscuits à la fraise",
"fr:Biscuits feuilletés",
"fr:Blinis",
"fr:Confitures diététiques",
"fr:Crèmes dessert chocolat",
"fr:Crèmes fraîches liquides",
"fr:Foie-de-morue",
"fr:Fromages de brebis",
"fr:Gratins",
"fr:Hamburgers",
"fr:Herbes de Provence",
"fr:Jus de pamplemousse rose",
"fr:Jus-multifruits",
"fr:Knacks industrielles",
"fr:Macedoine-de-legumes",
"fr:Miels de fleurs",
"fr:Mousses au chocolat",
"fr:Noix-de-cajou",
"fr:Nouilles",
"fr:Pain-d-epices",
"fr:Pâtes à tartiner aux noisettes et au cacao",
"fr:Pâtes brisées",
"fr:Pruneaux",
"fr:Pruneaux d’Agen",
"fr:Quenelles de poisson",
"fr:Rillettes de thon",
"fr:Sauces bolognaises",
"fr:Sels de table",
"fr:The-bio",
"fr:Thons blancs",
"fr:Torsades",
"Mixed pickles",
"Mountain products",
"fr:Agrumes",
"fr:Bières blanches",
"fr:Biscuits secs",
"fr:Boissons-aux-fruits",
"fr:Boulgour",
"fr:Cacahuetes",
"fr:Caramels",
"fr:Carottes râpées",
"fr:Chipolatas",
"fr:Curry",
"fr:Dès 10 mois",
"fr:Desserts au fruit pour bébé",
"fr:Eaux minérales gazeuses",
"fr:Emmentals français",
"fr:Epinards",
"fr:Foies gras de canard",
"fr:Fromages à pâte filée",
"fr:Fruits-frais",
"fr:Gateaux-pour-le-petit-dejeuner",
"fr:Laits frais",
"fr:Mayonnaises de Dijon",
"fr:Pains de seigle",
"fr:Petits pois en conserve",
"fr:Rosettes",
"fr:Sardines à l'ancienne",
"fr:Sardines sans huile",
"fr:Saucissons secs",
"fr:Spaghettis au blé dur",
"fr:Steaks-haches-surgeles",
"fr:Sucres blancs",
"fr:Tartes salées",
"fr:Tofu",
"Black whole olives",
"Pickled eggplants",
"Walnut oils",
"es:Brotes",
"fr:Bâtonnets",
"fr:Biscuits-au-chocolat-au-lait",
"fr:Biscuits pour bébé",
"fr:Biscuits-sucres",
"fr:Camemberts au lait cru",
"fr:Carottes",
"fr:Cassoulets",
"fr:Cidres doux",
"fr:Coeurs de palmier en conserve",
"fr:Confiseries de France",
"fr:Confits de canard",
"fr:Dattes",
"fr:Feculents",
"fr:Fromages-a-pate-molle",
"fr:Gateaux-au-chocolat",
"fr:Haricots en conserve",
"fr:Jambons de Bayonne",
"fr:Laits en poudre",
"fr:Lentilles corail",
"fr:Levure",
"fr:Merguez",
"fr:Mollusques",
"fr:Morues",
"fr:Noisettes",
"fr:Noix de coco",
"fr:Nougats",
"fr:Pains-au-lait",
"fr:Palmiers (biscuits",
"fr:Petits pains grillés",
"fr:Pizzas ovales",
"fr:Plats à base de canards",
"fr:Poivrons farcis",
"fr:Pour-gateaux",
"fr:Produit-frais",
"fr:Quenelles nature",
"fr:Rillettes de saumon",
"fr:Riz parfumés",
"fr:Sandwich polaire",
"fr:Sels naturels",
"fr:Sucres glaces",
"fr:Sucres roux",
"fr:Taboulés orientaux",
"fr:Thés aromatisés",
"fr:Truites fumées",
"Gazpacha marinated green olives",
"Honeys from France",
"Sheep's milk yogurts",
"Sweet wines",
"Whisky",
"Wines from Portugal",
"es:Bebidas refrescantes",
"es:Frutas en conserva",
"fr:Abricots secs",
"fr:Amandes en poudre",
"fr:Aromates",
"fr:Arômes pâtisserie",
"fr:Baguettes",
"fr:Bananes",
"fr:Bonbons-de-chocolat",
"fr:Boudins",
"fr:Bouillons",
"fr:Céréales pour bébé",
"fr:Céréales préparées",
"fr:Cheeseburger",
"fr:Chocolats noirs extra fin",
"fr:Colorants alimentaire",
"fr:Compotes pommes fraise",
"fr:Confitures de fraises",
"fr:Cordons bleus de dinde",
"fr:Crackers",
"fr:Creme-de-marrons",
"fr:Dietetique",
"fr:Eaux arômatisées",
"fr:Farfalle",
"fr:Farines de blé type T65",
"fr:Fleurs de sel",
"fr:Fromages au lait de bufflonne",
"fr:Gelées de fruits",
"fr:Graines",
"fr:Gros sels",
"fr:Haricots-blancs",
"fr:Infusions Bonne Nuit",
"fr:Laits 2ème âge",
"fr:Laits concentrés non sucrés",
"fr:Lasagnes à garnir",
"fr:Liqueurs",
"fr:Maïs doux",
"fr:Moutardes fines",
"fr:Pâtes d’amande",
"fr:Plats du soir pour bébé",
"fr:Poivres noirs",
"fr:Preparations-pour-gateaux",
"fr:Produits décongelés",
"fr:Raisins secs",
"fr:Ratatouille",
"fr:Ratatouilles",
"fr:Rhums blancs",
"fr:Rillettes de porc",
"fr:Rillettes de viande rouge",
"fr:Riz Basmati blancs",
"fr:Riz de Camargue",
"fr:Rooibos",
"fr:Roqueforts",
"fr:Salade-preparee",
"fr:Sardines à l’huile et au citron",
"fr:Sauces salades",
"fr:Sauces-vinaigrettes",
"fr:Saucisses sèches",
"fr:Sirops de fraise",
"fr:Spéculoos",
"fr:Surimis",
"fr:Thons à l’huile d’olive",
"fr:Tomates pelées",
"fr:Tortellini",
"fr:Veloutés de potiron",
"fr:Viandes de boeuf",
"fr:Viandes surgelées",
"fr:Vins mutés",
"fr:Vins mutés de type vin doux naturel",
"pt:Macarrao-instantaneo",
"Cider vinegars",
"Flavoured yogurts",
"Green stuffed olives",
"Green whole olives",
"Lemons",
"Maple syrups",
"Pickled capers",
"Red wine vinegars",
"Refrigerated squeezed orange juices",
"Squeezed grapefruit juices",
"Stuffed olives",
"Sweet pies",
"Vanilla yogurts",
"Wines from Spain",
"es:Caramelos-y-golosinas",
"fr:Ail",
"fr:Amuse-bouches",
"fr:Ananas au sirop",
"fr:Artichauts en conserve",
"fr:Basilic",
"fr:Bières ambrées",
"fr:Bières artisanales",
"fr:Bières brunes",
"fr:Bières sans alcool",
"fr:Biscuit-fourre",
"fr:Biscuits-aperitif",
"fr:Ble-precuit",
"fr:Boisson-au-soja",
"fr:Boudoirs",
"fr:Bouillon-cube",
"fr:Boulangerie",
"fr:Brioches au chocolat",
"fr:Cabillauds",
"fr:Cacao",
"fr:Chicoree",
"fr:Cidres bouchés",
"fr:Compotes-de-fruits",
"fr:Compotes pommes poires",
"fr:Confiserie-fantaisie",
"fr:Cotes-du-rhone",
"fr:Crèmes chantilly",
"fr:Crevettes roses",
"fr:Dès 18 mois",
"fr:Desserts-lactes",
"fr:Filets d’anchois",
"fr:Flageolets en conserve",
"fr:Frites surgelées",
"fr:Fromages de montagne",
"fr:Fruits-confits",
"fr:Galettes des rois",
"fr:Gateaux-secs",
"fr:Gélifiants",
"fr:Gnocchi",
"fr:Gratins de légumes",
"fr:Jus-de-soja",
"fr:Jus-de-tomate",
"fr:Laits concentrés sucrés",
"fr:Laits d'amande",
"fr:Laits de riz",
"fr:Menus Poissons pour bébé",
"fr:Moules",
"fr:Non alimentaire",
"fr:Oignons",
"fr:Pains-au-chocolat",
"fr:Pains-d-epices",
"fr:Pains pour hamburgers",
"fr:Pains sans gluten",
"fr:Pates-de-fruits",
"fr:Pâtes de sarrazin",
"fr:Pois chiches en conserve",
"fr:Poivres blancs",
"fr:Poivres moulus",
"fr:Poivrons rouges",
"fr:Porto",
"fr:Preparation-pour-pain",
"fr:Produit-au-sel-de-guerande",
"fr:Purées d'amande",
"fr:Quenelles de saumon",
"fr:Raviolis au fromage",
"fr:Reblochons",
"fr:Rhums agricoles",
"fr:Rillettes de viande blanche",
"fr:Rillettes de volaille",
"fr:Riz pour risotto",
"fr:Sandwichs jambon fromage",
"fr:Sardines à l’huile et au piment",
"fr:Sauces Pesto Rosso",
"fr:Saucisses de Morteau",
"fr:Saumons fumés sauvages",
"fr:Sirops de cassis",
"fr:Soupe-de-nouilles",
"fr:Soupe de poissons",
"fr:Soupes froides",
"fr:Suppléments",
"fr:Suppléments fastfoods",
"fr:Tapenade",
"fr:Tartelettes",
"fr:Tartes aux poireaux",
"fr:Tomates séchées",
"fr:Tommes",
"fr:Verveine",
"fr:Viande-hachee",
"fr:Vinaigres aromatisés",
"fr:Wrap",
"fr:Yaourts-au-bifidus",
"Banderillas",
"Green olives stuffed of pepper",
"Guava nectars",
"Lemon yogurts",
"Pickled beets",
"Pickled carrots",
"Pickled cucumbers",
"Pickled onions",
"Rapeseed oils",
"Seaweed",
"Squeezed pineapple juices",
"White vinegars",
"Wines from Italy",
"es:",
"es:Cafés",
"es:Lacteos",
"es:Legumbres-y-derivados-en-conserva",
"es:Pures-de-frutas",
"fr:Bacon en tranche",
"fr:Barquettes",
"fr:Beurres allégés",
"fr:Bières avec des fruits",
"fr:Biscottes au froment",
"fr:Biscottes complètes",
"fr:Biscuits diététiques",
"fr:Biscuits-fourres",
"fr:Biscuits sans gluten",
"fr:Boisson-lactee",
"fr:Boisson-sucree",
"fr:Boissons chaudes instantanées",
"fr:Boudins blancs",
"fr:Bouillon-deshydrate",
"fr:Camemberts au lait microfiltré",
"fr:Caramels au beurre salé",
"fr:Carotte",
"fr:Celeri-remoulade",
"fr:Charcuteries cuites",
"fr:Chocolats avec amandes",
"fr:Chocolats de Pâques",
"fr:Cidres artisanaux",
"fr:Cigarettes",
"fr:Compotes allégées",
"fr:Confitures d’abricot",
"fr:Conserves-de-legumes",
"fr:Cordons bleus de poulet",
"fr:Cornichons extra-fins",
"fr:Creme-de-coco",
"fr:Creme-legere",
"fr:Croque-monsieur",
"fr:Dosettes-cafe",
"fr:Epicerie-sucree",
"fr:Escalopes de poulet",
"fr:Farines de blé type T55",
"fr:Fecules",
"fr:Filets de poulet",
"fr:Financiers",
"fr:Fromages de vache Prim'Holstein",
"fr:Fromages des Pays-Bas",
"fr:Galettes à la frangipane",
"fr:Gambas",
"fr:Gateaux-fourres",
"fr:Gaufres fourrées",
"fr:Goudas",
"fr:Harengs",
"fr:Houmous",
"fr:Jambons Serrano",
"fr:Jus",
"fr:Jus d’orange sanguine",
"fr:Kit",
"fr:Laits 1er âge",
"fr:Laits aromatisés",
"fr:Legumes-cuisines",
"fr:Médicaments",
"fr:Moutardes à l’ancienne",
"fr:Munsters",
"fr:Nouilles-instantanees",
"fr:Nuggets",
"fr:Oeufs-de-poule",
"fr:Pains croustillants",
"fr:Pains spéciaux",
"fr:Pates-au-ble-complet",
"fr:Penne",
"fr:Persil",
"fr:Petits Munsters",
"fr:Poivres gris",
"fr:Poivrons grillés",
"fr:Pommes",
"fr:Pommes de terre Agata",
"fr:Pommes-noisettes",
"fr:Potage",
"fr:Pousses",
"fr:Preparation",
"fr:Preparation-culinaire",
"fr:Preparation-pour-desserts",
"fr:Preparations-pour-patisseries",
"fr:Produits vendus dans les années 1990",
"fr:Puree-de-tomates",
"fr:Quenelles de veau",
"fr:Repas-pour-bebe",
"fr:Rillettes de la Sarthe",
"fr:Rillettes du Mans",
"fr:Rillettes françaises",
"fr:Riz-au-lait",
"fr:Riz pour sushi",
"fr:Riz préparés",
"fr:Riz thaï blanc",
"fr:Salade-prete-a-l-emploi",
"fr:Salades-preparees",
"fr:Salamis",
"fr:Saucisses de Montbéliard",
"fr:Saucisses de Toulouse",
"fr:Sirops de citron",
"fr:Spaghettis au blé complet",
"fr:Specialite-fromagere",
"fr:Sucre-vanille",
"fr:Tablettes",
"fr:Tapenades noires",
"fr:Thons à l’huile de tournesol",
"fr:Tisane-vegetale",
"fr:Toast",
"fr:Tomates-au-jus",
"fr:Tortillas",
"fr:Veloutés de légumes",
"fr:Vin-rose-bio",
"fr:Vinaigrette",
"pl:Ryba",
"pt:Sopa-instantanea",
"de:Gefrorene-fruchte",
"Canned tunas",
"Concentrated pineapple juices",
"Greek yogurts",
"Low-fat yogurts",
"Mango nectars",
"en:Peanut-butter",
"Pitted marinated green olives",
"en:Raw",
"Sesame oils",
"Soy milk yogurts",
"es:Frutas-congeladas",
"es:Vino-tinto",
"fr:Allege",
"fr:Anchois",
"fr:Artichauts",
"fr:Asperges blanches",
"fr:Asperges en conserve",
"fr:Asperges miniatures",
"fr:Asperges violettes",
"fr:Assiettes pour bébé",
"fr:Assortiments de chocolats",
"fr:Avoines",
"fr:Barquettes à la fraise",
"fr:Betteraves",
"fr:Bières à la cerise",
"fr:Biscuits-aperitifs-sales",
"fr:Biscuits-au-beurre",
"fr:Blancs-de-dinde",
"fr:Boisson-aromatisee",
"fr:Boisson-fermentee",
"fr:Boisson-rafraichissante",
"fr:Boisson-vegetale",
"fr:Boissons énergétiques",
"fr:Boissons lyophilisées",
"fr:Bonbons-au-chocolat",
"fr:Bouchees",
"fr:Bouillon-de-legumes",
"fr:Boulettes-de-viande",
"fr:Cacahuètes au chocolat",
"fr:Cafe-arabica",
"fr:Camemberts de Normandie",
"fr:Cancoillotte",
"fr:Carottes en conserve",
"fr:Cassonades",
"fr:Cassoulet-au-confit-de-canard",
"fr:Champignons en conserve",
"fr:Chardonnay",
"fr:Chocolats Suisse",
"fr:Cidres rosés",
"fr:Clémentines",
"fr:Cocktail de fruits au sirop",
"fr:Compotes pommes myrtille",
"fr:Concentre-de-tomates",
"fr:Confitures de figues",
"fr:Conserve-de-legumes",
"fr:Cornichons au vinaigre",
"fr:Cotes-de-porc",
"fr:Coulis-de-tomate",
"fr:Crèmes entières",
"fr:Dès 08 mois",
"fr:Édulcorants de table",
"fr:Épeautre",
"fr:Epinards-haches",
"fr:Feculent",
"fr:Feuilles-de-brick",
"fr:Flageolets",
"fr:Flammekueche",
"fr:Foies gras mi-cuits",
"fr:Fondants-au-chocolat",
"fr:Friandise",
"fr:Fromage-au-lait-de-chevre",
"fr:Fromages du Nord-Pas-de-Calais",
"fr:Galettes de blé noir",
"fr:Gateaux-ou-compotes",
"fr:Gauffres",
"fr:Gaufrettes fourrées",
"fr:Gélatine",
"fr:Gorgonzolas",
"fr:Guimauves",
"fr:Jambon-cuit-superieur",
"fr:Jambons fumés",
"fr:Japon",
"fr:Jus-de-clementine",
"fr:Jus-de-legume",
"fr:Langues de chat",
"fr:Lentilles préparées",
"fr:Linguine",
"fr:Maasdam",
"fr:Macaroni",
"fr:Maroilles",
"fr:Mascarpone",
"fr:Merlu-blanc",
"fr:Miels de montagne",
"fr:Mimolettes",
"fr:Olives vertes en saumure",
"fr:Paella",
"fr:Pain-complet",
"fr:Pain-d-epice",
"fr:Palmiers",
"fr:Paprika",
"fr:Pastis",
"fr:Pate-a-tartiner-sans-huile-de-palme",
"fr:Pate-vegetal",
"fr:Pâtes à tartiner au caramel",
"fr:Penne-rigate",
"fr:Petit salé",
"fr:Petits-suisses-pour-bebe",
"fr:Pizzas et tartes surgelées",
"fr:Pizzas surgelées",
"fr:Poire",
"fr:Pois-casses",
"fr:Poivrons rouges en conserve",
"fr:Pollens",
"fr:Pommes de terre Charlotte",
"fr:Pommes-rissolees",
"fr:Potage-deshydrate",
"fr:Praline",
"fr:Pralines",
"fr:Puree-de-pois",
"fr:Purées de sésame",
"fr:Purées en flocons",
"fr:Quatre-quarts",
"fr:Quenelles de brochet",
"fr:Quenelles de volaille",
"fr:Raisins secs Sultanines",
"fr:Raviolis à la bolognaise",
"fr:Raviolis aux légumes",
"fr:Rillettes de canard",
"fr:Rillettes de saumon rose",
"fr:Risotto",
"fr:Riz arborio",
"fr:Riz blanc",
"fr:Riz-rond",
"fr:Riz soufflé",
"fr:Saint-emilion",
"fr:Saint-felicien",
"fr:Salsifis en conserve",
"fr:Sauce-cuisinee",
"fr:Sauce-samourai",
"fr:Saucisse-a-cuire",
"fr:Saucisses fumées",
"fr:Saumon-fume-bio",
"fr:Sels de Guérande",
"fr:Sesame",
"fr:Simili-carne",
"fr:Sirop-sans-sucre",
"fr:Sodas à l'orange light",
"fr:Sodas au citron light",
"fr:Sodas au cola sans caféine",
"fr:Son",
"fr:Son-d-avoine",
"fr:Sorbets à la framboise",
"fr:Soupe-de-legumes-frais",
"fr:Specialite-vegetale-a-base-de-tofu",
"fr:Steak-hache",
"fr:Sticks-de-chocolat",
"fr:Sucres blonds",
"fr:Tagliatelles-carbonara",
"fr:Terrines de volailles",
"fr:Thés à la menthe",
"fr:Thés au citron",
"fr:Thés blancs",
"fr:Thons fumés",
"fr:Toast-croustillant",
"fr:Tourtes",
"fr:Tripes",
"fr:Vermicelle de riz",
"fr:Viennoiserie",
"fr:Viennoiseries",
"fr:Vinaigres de vins blancs",
"it:Vino",
"pl:Zupa",
"pt:Bebidas-nao-alcolicas",
"pt:Biscoito-salgado",
"de:Peanut-butter",
"de:Soja-und-derivate",
"Apricot nectars",
"Argan oils",
"Black pitted olives",
"Hazelnut oils",
"Japanese green teas",
"en:Muesli",
"en:Mustard",
"Palm oils",
"Passion fruit nectars",
"PGI Products",
"Pickled garlic",
"Raw fishes",
"Red ports",
"Refrigerated squeezed pineapple juices",
"Strawberry yogurts",
"es:Agua",
"es:Alimentos especiales",
"es:Alimentos infantiles",
"es:Bombones",
"es:Chocolate en polvo",
"es:Harinas-vegetales",
"es:Helados-de-hielo",
"es:Mazorquitas-de-maiz-encurtidas",
"es:Quesos",
"es:Vino-blanco",
"fr:A-cuire",
"fr:Agar-agars",
"fr:Aioli",
"fr:Ananas",
"fr:Aromate",
"fr:Artichauts-grilles",
"fr:Asperges fraîches",
"fr:Asperges vertes",
"fr:Aubergine",
"fr:Bananes séchées",
"fr:Barre-chocolate",
"fr:Barres glacées",
"fr:Beaujolais",
"fr:Beignets-de-crevettes",
"fr:Beignets-de-poulet",
"fr:Beurre-doux-bio",
"fr:Beurres-de-baratte",
"fr:Beurres de cacahuètes",
"fr:Beurres pasteurisés",
"fr:Bieres-belges",
"fr:Biscuits-cuillers",
"fr:Biscuits-pour-preparer-un-gateau",
"fr:Blanquette-de-veau",
"fr:Boisson-au-riz",
"fr:Boisson-lactee-fermentee-nature-sucree",
"fr:Bolachas",
"fr:Bonbons-a-la-menthe",
"fr:Boudins blanc à l'ancienne",
"fr:Boudins noir aux oignons",
"fr:Boudins noirs",
"fr:Bouillon-de-poule",
"fr:Bouillon-de-volaille",
"fr:Bresse Bleu",
"fr:Bretagne",
"fr:Bries",
"fr:Brioches au fruit",
"fr:Brochettes",
"fr:Brocolis",
"fr:Brownie",
"fr:Burger",
"fr:Burrito",
"fr:Cafe-en-dosettes",
"fr:Cafés décaféinés",
"fr:Cannelloni",
"fr:Cantals",
"fr:Capres",
"fr:Carottes-en-rondelles",
"fr:Carottes-surgelees",
"fr:Cervelas",
"fr:Chair-de-tomates",
"fr:Champagne-brut",
"fr:Chapelure",
"fr:Chataignes",
"fr:Chips croustillantes",
"fr:Chips-de-crevettes",
"fr:Chocolat-au-lait-aux-noisettes",
"fr:Chocolat-aux-noisettes-entieres",
"fr:Chocolat-fourre",
"fr:Chocolats au lait extra fin",
"fr:Chocolats-au-lait-noirs-et-blancs",
"fr:Chocolats fourrés au praliné",
"fr:Chocolats pur beurre de cacao",
"fr:Choucroute-garnie",
"fr:Choux-de-bruxelles",
"fr:Cidre-breton",
"fr:Cidre-breton-doux",
"fr:Citronnade",
"fr:Coeurs-d-artichauts",
"fr:Coleslaw",
"fr:Concasse-de-tomates",
"fr:Cônes",
"fr:Cones-glaces",
"fr:Confiserie-au-chocolat",
"fr:Confiserie-au-chocolat-au-lait",
"fr:Confitures d’orange",
"fr:Conserver",
"fr:Coppa",
"fr:Coquillettes-au-ble-complet",
"fr:Corn-flakes-bio",
"fr:Corned-beef",
"fr:Cornet-de-glace",
"fr:Cotes-du-roussillon",
"fr:Coulis",
"fr:Court-bouillon",
"fr:Couscous-grain-fin",
"fr:Couscous-grain-moyen",
"fr:Couscous préparés",
"fr:Creme-anglaise",
"fr:Crepes-au-jambon",
"fr:Crêpes de froment",
"fr:Croquettes pour chat",
"fr:Crottin-de-chevre",
"fr:Cuisine-du-monde",
"fr:Cuisses-de-canard-confites",
"fr:Dinde",
"fr:Dindes",
"fr:Dvd",
"fr:Eau-de-coco",
"fr:Eau-mineral",
"fr:Ecorces-d-oranges-confites-enrobees-de-chocolat-noir",
"fr:Ecrase-de-pommes-de-terre",
"fr:Emince-de-champignon",
"fr:Entrées",
"fr:Equitable",
"fr:Escargots",
"fr:Exhausteurs de goût",
"fr:Fajitas",
"fr:Farines de maïs",
"fr:Feuillete",
"fr:Figues",
"fr:Filets de cabillaud",
"fr:Flan",
"fr:Fondues",
"fr:Fourres-chocolat",
"fr:Fraises",
"fr:Framboises",
"fr:Fromages-au-lait-de-brebis",
"fr:Fromages au lait thermisé",
"fr:Fromages aux noix",
"fr:Fusilli",
"fr:Gache",
"fr:Galette-de-tofu",
"fr:Galettes-bretonnes",
"fr:Galettes de maïs",
"fr:Galettes-vegetales",
"fr:Gateaux-marbres",
"fr:Gaufrettes-chocolatees",
"fr:Gélifiants végétaux",
"fr:Genoises",
"fr:Gingembre",
"fr:Glaces rhum-raisin",
"fr:Gratin d’aubergine",
"fr:Gratins de poisson",
"fr:Gratins de pomme de terre",
"fr:Haddocks fumés",
"fr:Halal",
"fr:Haricots-en-grains",
"fr:Haricots-rouges",
"fr:Haut-medoc",
"fr:Herbes de Provence Label Rouge",
"fr:Homards",
"fr:Ice-tea light",
"fr:Infusions aux fruits rouges",
"fr:Infusions minceur",
"fr:Jambonneau",
"fr:Jambons de la Forêt Noire",
"fr:Jambons ibériques",
"fr:Jus-a-base-de-concentre",
"fr:Jus-d-orange-refrigere",
"fr:Jus-de-fruits-a-base-de-jus-concentres",
"fr:Jus-de-legumes",
"fr:Jus-de-pomme-100-pur-jus",
"fr:Jus-de-tomate-bio",
"fr:Lait-chocolate",
"fr:Lait-fermente",
"fr:Laits d'avoine",
"fr:Lapin",
"fr:Lardons-fumes-bio",
"fr:Lardons-nature",
"fr:Legume-cuit",
"fr:Legumes-secs-en-conserve",
"fr:Lentille",
"fr:Lentilles blonde",
"fr:Levures-de-biere",
"fr:Liegeois",
"fr:Livarot",
"fr:Mangues",
"fr:Maquereaux-au-vin-blanc",
"fr:Marmelades",
"fr:Marrons",
"fr:Mayonnaise-bio",
"fr:Mayonnaises allégées",
"fr:Melange-de-fruits",
"fr:Melange-de-legumes",
"fr:Menus Légumes pour bébé",
"fr:Miels d’acacia",
"fr:Morbiers",
"fr:Moulages en chocolat",
"fr:Moules-en-conserve",
"fr:Mousse-de-canard",
"fr:Moutardes au miel",
"fr:Moutardes douces",
"fr:Nappages",
"fr:Noisettes-en-poudre",
"fr:Nouilles-orientales",
"fr:Nourriture pour animaux",
"fr:Nourriture pour chats",
"fr:Nuggets-de-poulet",
"fr:Orge",
"fr:Pain-aux-cereales",
"fr:Pain-de-seigle-complet",
"fr:Pains Burger",
"fr:Pains de campagne",
"fr:Pate-a-pizza",
"fr:Pate-a-tartiner-a-l-huile-de-coprah",
"fr:Pate-de-curry",
"fr:Pate-feuillete",
"fr:Pate-pizza",
"fr:Pates-a-pizza",
"fr:Pates-de-campagne",
"fr:Pates-de-foie-de-porc",
"fr:Pates-penne-rigate",
"fr:Pates-preparees",
"fr:Penaeus-vannamei",
"fr:Petits-pois-et-carottes",
"fr:Petits pots pour bébé",
"fr:Piments d'Espelette",
"fr:Plats-a-preparer",
"fr:Plats préparés à faible teneur en matières grasses",
"fr:Pockys",
"fr:Poireaux",
"fr:Pois-chiche",
"fr:Poissons-d-elevage",
"fr:Poissons-prepares",
"fr:Polenta",
"fr:Pomme-dauphine",
"fr:Pommes de terre de l'île de Ré",
"fr:Pommes-de-terre-entieres",
"fr:Pommes de terre primeurs",
"fr:Poudre-chocolatee",
"fr:Poudre-de-cacao",
"fr:Poulets cuisinés",
"fr:Pour-les-gateaux",
"fr:Pousses de bambou",
"fr:Pousses de haricot mungo",
"fr:Preparation-en-poudre-pour-entremets",
"fr:Preparation-pour-gateau",
"fr:Preparation-pour-glace",
"fr:Preparations",
"fr:Preparations-a-base-de-crabe",
"fr:Preparations-pour-dessert",
"fr:Produit-a-la-figue",
"fr:Produit-au-chocolat",
"fr:Produit-au-citron",
"fr:Produit-au-wasabi",
"fr:Produit-lacte",
"fr:Produits-sales-aperitifs",
"fr:Produits vendus dans les années 1980",
"fr:Purées d'amande complète",
"fr:Purées de noisette",
"fr:Purées de sésame blanc",
"fr:Quiche-lorraine",
"fr:Quiches",
"fr:Quinoa-rouge",
"fr:Ravioles",
"fr:Raviolis à la volaille",
"fr:Raviolis aux champignons",
"fr:Reglisse",
"fr:Rillettes de crabe",
"fr:Rillettes de crustacés",
"fr:Rillettes de maquereau",
"fr:Rillettes de poulet",
"fr:Rillettes de Saint-Jacques",
"fr:Rillettes poulet rôti",
"fr:Rillettes spéciales",
"fr:Riz-basmati-bio",
"fr:Riz-cantonnais",
"fr:Riz-cuisine",
"fr:Riz-incollable",
"fr:Riz-jasmin",
"fr:Riz-long-blanc-bio",
"fr:Riz-long-complet",
"fr:Riz Surinam",
"fr:Riz-thai-bio",
"fr:Rocamadour",
"fr:Saint Agur",
"fr:Saint-jacques",
"fr:Salaison",
"fr:Sarrasin",
"fr:Sauce-pour-snacking",
"fr:Sauce-pour-viande",
"fr:Sauces au soja sucrées",
"fr:Sauces-pour-frites",
"fr:Sauces pour pizzas",
"fr:Sauces provençales",
"fr:Saucisse-tofu",
"fr:Saucisses allemandes",
"fr:Saucisses-cocktail",
"fr:Saucisses-de-volaille",
"fr:Saucissons à l’ail",
"fr:Saucissons artisanaux",
"fr:Saumon-fume-au-bois-de-hetre-eleve-en-norvege",
"fr:Saumons fumés de dégustation",
"fr:Sel-aux-herbes",
"fr:Sel-rose-de-l-himalaya",
"fr:Sirops aux fruits",
"fr:Sodas à la pomme",
"fr:Sodas aux fruits exotiques",
"fr:Son des blé",
"fr:Sorbets à la fraise",
"fr:Sorbets au fruit de la passion",
"fr:Soupe-au-miso",
"fr:Soupe-instantannee",
"fr:Soupe-potiron-carottes",
"fr:Spaghetti au blé dur complet",
"fr:Specialite-laitiere",
"fr:Speck",
"fr:Steak",
"fr:Steak-hache-pur-boeuf",
"fr:Tarama",
"fr:Tartes au saumon",
"fr:Terrines de canard",
"fr:Thés verts chinois",
"fr:Thon-a-la-catalane",
"fr:Thons blancs au naturel",
"fr:Thons pales",
"fr:Tiramisu",
"fr:Tomates cerise",
"fr:Tomates-entieres-pelees-au-jus",
"fr:Tomates-farcies",
"fr:Traiteur",
"fr:Truffes en chocolat",
"fr:Truites-fumes",
"fr:Vanille",
"fr:Vegetarien",
"fr:Veloutés de légumes du soleil",
"fr:Vermicelles",
"fr:Viande-panee",
"fr:Viandes-bbq",
"fr:Viandes de veau",
"fr:Vin-blanc-bio",
"fr:Vinaigre-basalmique",
"fr:Vinaigres-balsamiques-de-modene",
"fr:Vinaigres d’alcools",
"fr:Vins de pays",
"fr:Vins pétillant",
"fr:Vodkas",
"fr:Yaourt-brasse-aux-fruits",
"fr:Yaourt-maigre",
"fr:Yaourts-liquides",
"it:Biscotti",
"it:Caffe",
"pl:Boczek",
"pl:Odwodnione-zupa",
"pt:Agua-mineral",
"pt:Biscoito-integral",
"pt:Chocolate-amargo",
"pt:Conserves-de-poisson",
"pt:Creme-de-leite",
"pt:Pao-de-forma",
"pt:Refrigerantes",
"ar:",
"de:Alcopop",
"de:Aufstrich",
"de:Cocktail-sauce",
"de:Cola",
"de:Cracker",
"de:Fruchtsaft",
"de:Garnelen",
"de:Gemuse-getranke",
"de:Grunkern",
"de:Honig",
"de:Kartoffelchips",
"de:Ketchup",
"de:Limonade",
"de:Mate",
"de:Miel",
"de:Milch",
"de:Oliven",
"de:Pasteten-vegetarier",
"de:Pilsner",
"de:Pralinen",
"de:Rot-wein-alcohol",
"de:Rote-rubensaft",
"de:Rotwein",
"de:Sauerrahm",
"de:Senf",
"de:Snacks",
"de:Tomaten-ketchup",
"de:Vodka",
"de:Zaziki",
"de:Zuckerfreier-kaugummi",
"en:Apple-juice-from-concentrate",
"en:Baked-beans",
"en:Banana",
"Banana nectars",
"en:Biscuits-aperitifs-sales",
"en:Biscuits-chocolates",
"Black chopped olives",
"en:Breakfast-cereals",
"en:Brownie",
"en:Cacao",
"en:Canelle",
"Caviars",
"en:Chicken-eggs",
"en:Chips",
"en:Chocolate-chip-cookie",
"Chopped olives",
"Coconut oils",
"en:Coke",
"en:Crisps",
"en:Drinking-chocolate",
"en:Dry-meat",
"en:Eggs",
"en:Galette",
"Grape seed oils",
"en:Grated-cheese",
"Green olives stuffed of lemon",
"en:Herbs",
"en:Instant-noodle",
"en:Jelly",
"en:Jus-de-fruits",
"Labelized vegetables",
"en:Mackerels",
"en:Mayonnaise",
"Meals with rabbit or hare",
"Mixed yogurts",
"en:Mussels",
"en:Naan",
"en:Oatmeal",
"en:Oil",
"en:Orange-juice-from-concentrate",
"en:Organic-eggs",
"en:Pain",
"en:Pates",
"Peach nectars",
"en:Peanut",
"Pickled ginger",
"Pickled guindilla peppers",
"Pickled peppers",
"en:Pizza",
"Poppyseed oils",
"en:Precision-instruments",
"en:Prepared-chicken",
"en:Pretzels",
"en:Products-sold-in-the-years-1990",
"en:Produits-laitiers",
"Refrigerated squeezed apple juices",
"en:Rice-noodles",
"Rice vinegars",
"en:Roasted-eggplant",
"en:Sauces",
"Sausages from Spain",
"Semi-ripe olives",
"Semi-ripe whole olives",
"en:Soy-sauces",
"Squeezed apple juices",
"en:Superfood",
"en:Sweet-potatoes",
"en:Tortilla-chips",
"en:Tortillas",
"Trouts",
"en:Turkey-breast",
"en:Vinegar-spray",
"Whole marinated green olives",
"en:Wholegrains",
"Wines from California",
"Xeres vinegars",
"es:Aditivos-alimentarios",
"es:Agua-mineral-natural",
"es:Alfajor",
"es:Alimentos-funcionales",
"es:Aparitivos",
"es:Apio-encurtido",
"es:Atun-en-aceite-de-oliva",
"es:Barras-de-cereales",
"es:Charcuteria",
"es:Complementos Alimenticios",
"es:Copos de cereales",
"es:Creme-dessert",
"es:Dulces-de-confiteria",
"es:Fuet",
"es:Gaseosa",
"es:Golosina",
"es:Mermelada",
"es:Mueslis",
"es:Preparados-para-bebidas",
"es:Pure-de-patatas",
"es:Sorbetes",
"es:Untables",
"es:Zumos-de-mandarina-exprimida-refrigerados",
"fr:100-pur-jus-de-poire-bio",
"fr:100-pur-jus-de-pomme-bio",
"fr:2-galettes-de-soja-recette-aux-legumes-bio",
"fr:2-galettes-de-soja-recette-mediterraneenne-bio",
"fr:2-paves-de-saumon-bio",
"fr:2-paves-de-truite-bio",
"fr:2-yaourts-au-lait-de-brebis-bio",
"fr:6-gros-oeufs-de-categorie-a",
"fr:8-crackers-a-la-farine-d-epeautre-et-aux-graines-de-tournesol",
"fr:Abats",
"fr:Abricots",
"fr:Abricots au sirop",
"fr:Abricots-moelleux-bio",
"fr:Acai-bio",
"fr:Achards",
"fr:Acras",
"fr:Aide-alimentaire",
"fr:Aide-culinaire-pour-confiture",
"fr:Aides-culinaires",
"fr:Aiguillettes-de-canard",
"fr:Aiguillettes-de-poulet-aux-epices-tandoori",
"fr:Ailes-de-poulet",
"fr:Ailladou",
"fr:Allumettes de bacon",
"fr:Allumettes-de-jambon",
"fr:Alsace",
"fr:Amande-cuisine-bio",
"fr:Amandes-effilees",
"fr:Amidon-de-mais",
"fr:Ananas-en-morceaux-au-jus-d-ananas-bio",
"fr:Ananas-en-tranches-au-sirop",
"fr:Anchois-a-l-huile",
"fr:Andouille",
"fr:Anis",
"fr:Antipasti",
"fr:Aperitifs-sales",
"fr:Arabica",
"fr:Arachide",
"fr:Arachide-pralinee",
"fr:Arachide-sucree",
"fr:Arbois",
"fr:Armagnacs",
"fr:Asperges des sables des Landes",
"fr:Asperges françaises",
"fr:Asperges françaises IGP",
"fr:Asperges IGP",
"fr:Asperges pelées à la main",
"fr:Aspirine",
"fr:Assaisonnement-salade",
"fr:Assiette-vegetarienne-de-legumes-et-de-quinoa-bio",
"fr:Assortiment",
"fr:Assortiment-de-charcutrie",
"fr:Asupprimer",
"fr:Attention produits multiples",
"fr:Attieke",
"fr:Aubergines",
"fr:Aubergines-cuisinees",
"fr:Auces-vinaigrettes",
"fr:Auvergnat-cola",
"fr:Avoine-cuisine-bio",
"fr:Avoine-et-legumes-bio",
"fr:Bac-a-glace",
"fr:Bagel",
"fr:Baguette-cereales",
"fr:Baguettes-aux-cereales",
"fr:Baguettes-de-campagne",
"fr:Baguettes-precuites",
"fr:Bai Mu Dan",
"fr:Baies",
"fr:Baies-de-goji",
"fr:Barre-cereales-sans-gluten",
"fr:Barre-cerealiere-au-chocolat",
"fr:Barre-de-cereale-chocolatee",
"fr:Barre-de-fruits-secs",
"fr:Barre-de-son-d-avoine-saveur-amande",
"fr:Barre-son-d-avoine",
"fr:Barres-abricot-chocolat-amande-petit-epeautre-bio",
"fr:Barres-cereales-amandes-et-noisettes",
"fr:Barres-cereales-noix-de-coco-sur-lit-de-chocolat-au-lait",
"fr:Barres-cereales-pepites-de-chocolat",
"fr:Barres-cereales-pepites-de-fruits-rouges",
"fr:Barres-cereales-pomme-verte",
"fr:Barres-chocolate",
"fr:Barres-cranberries-cajou-quinoa",
"fr:Barres-croustillantes-riz-et-ble-complet-aux-pepites-de-chocolat",
"fr:Barres-de-regime",
"fr:Barres-de-regime-saveur-chocolat-blanc-enrobees-de-chocolat-au-lait",
"fr:Barres-de-regime-saveur-noix-de-coco-enrobees-de-chocolat-au-lait",
"fr:Basilic-frais",
"fr:Batavia",
"fr:Baton-de-reglisse",
"fr:Batonnet-de-crabe",
"fr:Bâtonnets à la vanille",
"fr:Bâtonnets au chocolat",
"fr:Batonnets-glace",
"fr:Battonets-glace",
"fr:Bearnaise",
"fr:Beauce-cola",
"fr:Beaujolais-nouveau-2013",
"fr:Beignets",
"fr:Betterave",
"fr:Betteraves-rouges-en-cubes-cuites-sous-vide",
"fr:Beurre-de-baratte-biologique-doux",
"fr:Beurre-tendre-doux",
"fr:Beurres-a-la-baratte",
"fr:Beurres-crus",
"fr:Beurres-de-bresse",
"fr:Beurres salés",
"fr:Biere-ambree-malt-bio",
"fr:Biere-aromatisee",
"fr:Biere-blonde-aromatisee-poire",
"fr:Biere-blonde-d-abbaye",
"fr:Biere-d-abbaye",
"fr:Bière de gingembre",
"fr:Bieres-aux-fruits",
"fr:Bières fortes",
"fr:Biftecks",
"fr:Biftecks-de-boeuf",
"fr:Biosson",
"fr:Biscotte-son-de-ble",
"fr:Biscottes-au-sarrasin",
"fr:Biscottes-chataigne",
"fr:Biscottes-completes-bio",
"fr:Biscottes pauvres en sel",
"fr:Biscottes-sarrasin",
"fr:Biscuit-au-beurre",
"fr:Biscuit-aux-cereales",
"fr:Biscuit-choco-fondant",
"fr:Biscuit-chocolat-noir",
"fr:Biscuit-chocolat-nougatine",
"fr:Biscuit-fourre-chocolat",
"fr:Biscuit-nappe-chocolat-au-lait",
"fr:Biscuit-sucre",
"fr:Biscuits-a-grignoter",
"fr:Biscuits-apperitif",
"fr:Biscuits-au-chocolat-au-lait-bio",
"fr:Biscuits-au-chocolat-noir",
"fr:Biscuits-aux-cereales-nappes-de-chocolat",
"fr:Biscuits-aux-chocolat-et-a-la-noix-de-coco",
"fr:Biscuits-aux-eclats-de-feves-de-cacao",
"fr:Biscuits-aux-oeufs",
"fr:Biscuits-avec-tablettes-de-chocolat-lait",
"fr:Biscuits-barres-chocolat-orange",
"fr:Biscuits-ble",
"fr:Biscuits-chocolat-cacao",
"fr:Biscuits-chocolat-et-quinoa",
"fr:Biscuits-chocolates",
"fr:Biscuits-cookies",
"fr:Biscuits-enrobes-de-chocolat-au-lait-et-fourres-au-praline",
"fr:Biscuits-fondants",
"fr:Biscuits-fondants-saveur-peche-abricot",
"fr:Biscuits-fourres-au-chocolat",
"fr:Biscuits-fourres-gout-chocolat",
"fr:Biscuits-gout-chocolat",
"fr:Biscuits-gout-chocolat-blanc",
"fr:Biscuits-hyperproteines",
"fr:Biscuits-meringues",
"fr:Biscuits-mini-oursons-pepites-de-chocolat",
"fr:Biscuits-moelleux",
"fr:Biscuits-moelleux-saveur-muesli-fleur-d-oranger",
"fr:Biscuits-nappes-chocolat-noir",
"fr:Biscuits-nappes-de-chocolat-au-lait",
"fr:Biscuits-nature",
"fr:Biscuits-orange",
"fr:Biscuits-pavot",
"fr:Biscuits-pavot-saveur-romarin",
"fr:Biscuits-petit-dejeuner-cereales-et-pepites-de-chocolat",
"fr:Biscuits-pur-beurre",
"fr:Biscuits-sables-fourrage-fraise-bio",
"fr:Biscuits-sale",
"fr:Biscuits-saveur-pomme-figue",
"fr:Biscuits-vegetal",
"fr:Blanc-de-poulet-en-tranches",
"fr:Blanc-de-poulet-fume",
"fr:Blanc-de-poulet-tranche",
"fr:Blanc-sec",
"fr:Blancs-d-oeufs",
"fr:Blanquette",
"fr:Blanquette-de-veau-aux-champignons-son-riz",
"fr:Ble-assaisonne",
"fr:Ble-dur-precuit",
"fr:Blend écossais",
"fr:Blended whisky",
"fr:Blés",
"fr:Blés durs",
"fr:Bles-precuits",
"fr:Bloc de foie gras avec morceaux",
"fr:Bocal-de-cornichons",
"fr:Boisson-a-base-de-citron-et-de-menthe",
"fr:Boisson-a-base-de-fruit-de-la-passion-concentre",
"fr:Boisson-a-base-de-jus-d-orange-et-de-menthe",
"fr:Boisson-a-base-de-jus-de-citron-et-de-menthe",
"fr:Boisson-a-l-aloe-vera",
"fr:Boisson-a-la-mangue",
"fr:Boisson-au-jus-de-fruit",
"fr:Boisson-au-jus-de-pomme",
"fr:Boisson-au-lait",
"fr:Boisson-au-lait-de-soja-chocolatee",
"fr:Boisson-au-soja-allegee",
"fr:Boisson-au-soja-au-miel-bio",
"fr:Boisson-au-soja-nature-bio",
"fr:Boisson-au-soja-saveur-vanille-bio",
"fr:Boisson-aux-extraits-de-fruits",
"fr:Boisson-aux-extraits-de-the-aromatise-peche",
"fr:Boisson-aux-fruits-a-base-de-concentre",
"fr:Boisson-aux-fruits-a-base-de-jus-concentree-bio-abricot",
"fr:Boisson-aux-fruits-a-base-de-jus-de-fruits-concentres-bio-orange",
"fr:Boisson-cacaoteee-bio",
"fr:Boisson-chocolatee",
"fr:Boisson-concentree-a-diluer",
"fr:Boisson-fraiche",
"fr:Boisson-fruite",
"fr:Boisson-gazeuse-aromatise-ananas",
"fr:Boisson-gazeuse-aromatise-aux-fruits",
"fr:Boisson-gazeuse-aromatise-fraise",
"fr:Boisson-gazeuse-aromatisee-aux-fruits",
"fr:Boisson-gazeuse-au-jus-d-orange-sanguine-bio",
"fr:Boisson-gazeuse-au-jus-de-canneberge-et-grenade-bio",
"fr:Boisson-gazeuse-au-jus-de-citron-bio",
"fr:Boisson-gazeuse-au-jus-de-pamplemousse-rose-bio",
"fr:Boisson-gazeuse-aux-fruits",
"fr:Boisson-gazeuse-light-aux-fruits",
"fr:Boisson-gazeuse-saveur-exotique",
"fr:Boisson-gazeuse-saveur-grenadine",
"fr:Boisson-gazeuse-saveur-mandarine",
"fr:Boisson-soja-nature",
"fr:Boisson-soja-saveur-vanille",
"fr:Boisson-sucre",
"fr:Boisson-sucrees",
"fr:Boissons-au-citron",
"fr:Boissons-au-jus-de-fruit",
"fr:Boissons-au-the",
"fr:Boissons-energisantes-light",
"fr:Boissons-lactees",
"fr:Boissons pour bébé",
"fr:Boissons-sans-alcool",
"fr:Bonbon-au-chocolat",
"fr:Bonbons-a-la-fraise",
"fr:Bonbons-arome-naturel",
"fr:Bonbons-au-mentol",
"fr:Bonbons-au-miel",
"fr:Bonbons-de-chocolat-noir",
"fr:Bonbons-gelifies",
"fr:Bonbons-sans-sucres",
"fr:Bonbons-tendres",
"fr:Bouchee-a-la-reine",
"fr:Boucherie",
"fr:Boudin-blanc-aux-morilles",
"fr:Bouillon-cube-bio",
"fr:Bouillon-kub",
"fr:Bouillons-de-poule",
"fr:Bouillons-de-veau",
"fr:Bouillons-de-volaille",
"fr:Bouillons-deshydrates",
"fr:Boule-bio",
"fr:Boules-de-neige",
"fr:Boulettes",
"fr:Boulettes-de-viande-cuites",
"fr:Boulghour",
"fr:Boulgour-bio",
"fr:Boulgour-gros-grains-bio",
"fr:Bouquets-de-mache",
"fr:Bouquets garnis",
"fr:Brandade",
"fr:Brandade-de-morue",
"fr:Brandade-de-morue-parmentiere",
"fr:Bretzels",
"fr:Brezain",
"fr:Brie",
"fr:Brioche-fourree-au-chocolat",
"fr:Brioche-tressee",
"fr:Brioches a l'abricot",
"fr:Brioches pur beurre",
"fr:Brioches vendéennes",
"fr:Brique",
"fr:Brochette-de-porc",
"fr:Brocolis-en-fleurette",
"fr:Brocolis-en-fleurette-surgeles-bio",
"fr:Brownie-chocolat-noisettes",
"fr:Brownies",
"fr:Brownies-bio",
"fr:Buche-de-chevre",
"fr:Buche-glacee",
"fr:Buche-patissiere",
"fr:Buches-glacees",
"fr:Cabillaud-tom-yam-coco-citronnelle-ecrase-de-pommes-de-terre",
"fr:Cacahuete",
"fr:Cacahuete-enrobees",
"fr:Cacahuetes-grillees",
"fr:Cachou-bonbon",
"fr:Cafe-a-la-chicoree",
"fr:Cafe-en-grains",
"fr:Cafe-grains",
"fr:Cafe-lyophilise",
"fr:Cafes-viennois",
"fr:Cake-aux-fruits",
"fr:Cakes-aux-figues",
"fr:Calamars-en-sauce",
"fr:Calendrier-de-l-avent",
"fr:Calendrier-de-l-avent-24-figurines-de-chocolat",
"fr:Calissons-d-aix",
"fr:Calvados",
"fr:Camembert-au-lait-pasteurise",
"fr:Camembert-bio",
"fr:Camemberts-moules-a-la-louche",
"fr:Camemberts pasteurisés",
"fr:Camenberts",
"fr:Camomille",
"fr:Cancoillotte-ail-bio",
"fr:Cancoillotte-nature",
"fr:Cannelle-moulue",
"fr:Cannelloni-a-garnir",
"fr:Cannellonis",
"fr:Canneloni",
"fr:Capellini",
"fr:Cappelletti",
"fr:Cappuccino-en-poudre",
"fr:Capsule",
"fr:Caramel-liquide",
"fr:Carottes-cuites",
"fr:Carottes-en-rondelles-bio-surgelees",
"fr:Carottes-fraiches",
"fr:Carpaccios",
"fr:Carpes-fumes",
"fr:Carres-coupe-faim-minceur-cacao",
"fr:Carres-fibre-aux-3-fruits",
"fr:Cassonade-de-candi-brune",
"fr:Caviar Baeri",
"fr:Caviars d'élevage",
"fr:Céleri",
"fr:Céleri en conserve",
"fr:Cenovis",
"fr:Cereales-fourrees-chocolat",
"fr:Cereales-gourmandes-ble-mais-soja",
"fr:Cereales-pilaf-saveurs-forestieres",
"fr:Cereales-soufflees",
"fr:Cereales-soufflees-au-chocolat-bio",
"fr:Cerelales",
"fr:Cerelales-aux-chocolats",
"fr:Cerelales-chocolatees",
"fr:Cererales-pour-petit-dejeuner",
"fr:Cerises au sirop",
"fr:Cervelas-a-l-alsacienne",
"fr:Cevennes",
"fr:Chablis",
"fr:Chair-a-saucisse",
"fr:Champagne-bio",
"fr:Champagnes-extra-brut",
"fr:Champignons-de-paris-eminces-bio",
"fr:Champignons-de-paris-entiers-1er-choix-bio",
"fr:Champignons-de-paris-surgeles",
"fr:Champignons-en-boite",
"fr:Champignons surgelés",
"fr:Charcuteries à cuire",
"fr:Charcutrie",
"fr:Chataignes-d-eau",
"fr:Cheesecakes",
"fr:Chevre",
"fr:Chewing-gum-sans-sucres-gout-fraise",
"fr:Chili-con-carne",
"fr:Chili-con-carne-et-riz-bio",
"fr:Chipolatas aux herbes",
"fr:Chips-au-mais",
"fr:Chips de panais",
"fr:Chips de patate douce",
"fr:Chips de pommes de terre rouge",
"fr:Chocolas",
"fr:Chocolat-70",
"fr:Chocolat-80",
"fr:Chocolat-a-la-noix-de-coco",
"fr:Chocolat-au-lait-bio",
"fr:Chocolat-au-lait-cafe-cannelle",
"fr:Chocolat-au-lait-cajou-caramelisee",
"fr:Chocolat-au-lait-et-aux-noisettes",
"fr:Chocolat-au-lait-parseme-de-grains-de-nougatine",
"fr:Chocolat-au-lait-riz-souffle",
"fr:Chocolat-au-lait-sesame-gingembre",
"fr:Chocolat-aux-eclats-de-noisettes",
"fr:Chocolat-blanc-fourrage-au-praline-et-aux-eclats-de-noisettes",
"fr:Chocolat-extra-fin",
"fr:Chocolat-fourrage-au-praline",
"fr:Chocolat-fourre-a-la-liqueur",
"fr:Chocolat-fourre-au-fruit",
"fr:Chocolat-lait-fondant",
"fr:Chocolat-lait-noisette",
"fr:Chocolat-lait-praline",
"fr:Chocolat-noir-70",
"fr:Chocolat-noir-85-bio",
"fr:Chocolat-noir-a-la-menthe",
"fr:Chocolat-noir-au-the",
"fr:Chocolat-noir-aux-ecorces-d-orange-confites",
"fr:Chocolat-noir-aux-noisettes",
"fr:Chocolat-noir-cacao-80-origine-equateur",
"fr:Chocolat-noir-caramel",
"fr:Chocolat-noir-citron",
"fr:Chocolat-noir-coco",
"fr:Chocolat-noir-degustation",
"fr:Chocolat-noir-eclats-d-amandes-bio",
"fr:Chocolat-noir-eclats-de-menthe-bio",
"fr:Chocolat-noir-ecorces-d-orange-bio",
"fr:Chocolat-noir-extra",
"fr:Chocolat-noir-fleur-de-sel",
"fr:Chocolat-noir-fourrage-au-praline-et-aux-eclats-de-noisettes",
"fr:Chocolat-noir-fourre",
"fr:Chocolat-noir-framboise",
"fr:Chocolat-noir-orange",
"fr:Chocolat-noir-parseme-de-grains-de-cacao",
"fr:Chocolat-noir-praline-bio",
"fr:Chocolat-noir-pur",
"fr:Chocolat-noir-quinoa-souffle-bio",
"fr:Chocolat-patissier",
"fr:Chocolat-praline",
"fr:Chocolat-superieur-au-lait",
"fr:Chocolatines",
"fr:Chocolats-au-lait-et-aux-noisettes",
"fr:Chocolats-chauds",
"fr:Chocolats diététiques",
"fr:Chou",
"fr:Chou-cuisine",
"fr:Chou-rouge",
"fr:Chouchen",
"fr:Choucroute-en-conserve",
"fr:Chutney",
"fr:Ciboulette",
"fr:Cidre-aromatise-a-la-poire",
"fr:Cidre-artisanal-bigouden-demi-sec",
"fr:Cidre-artisanal-bio",
"fr:Cidre-bouche-de-normandie-brut-bio",
"fr:Cidre-bouche-de-normandie-doux",
"fr:Cidre-breton-bio-doux",
"fr:Cidre-cornouaille",
"fr:Cidres traditionnels",
"fr:Citronelle",
"fr:Clous-de-girofle",
"fr:Cocktail-non-sale",
"fr:Coco",
"fr:Cocos",
"fr:Cognac",
"fr:Cola-bio",
"fr:Collioure",
"fr:Colorants pour oeufs",
"fr:Compote-de-fruits",
"fr:Compote-de-peches",
"fr:Compote-de-poire",
"fr:Compote-de-pomme-allegee-en-sucres-bio",
"fr:Compote-de-pomme-bio",
"fr:Compote-de-pomme-peche-passion",
"fr:Compote-de-pommes-allegee-en-sucres-bio",
"fr:Compote-pomme-nature-bio",
"fr:Compote-pomme-poire-bio",
"fr:Compote-pomme-vanille",
"fr:Compote-pommes-vanille",
"fr:Compotes-2-pomme-framboise-2-pomme-fraise",
"fr:Compotes-de-bananes",
"fr:Compotes de fraise",
"fr:Compotes-de-poire",
"fr:Compotes fraise groseille",
"fr:Compotes mangues",
"fr:Compotes-pomme-abricot",
"fr:Compotes-pomme-banane",
"fr:Compotes-pomme-mirabelle",
"fr:Compotes-pomme-nature-bio",
"fr:Compotes-pommes-banane",
"fr:Compotes pommes cassis",
"fr:Compotes pommes châtaigne",
"fr:Compotes pommes mangue",
"fr:Comte-20-24-mois-appellation-d-origine-protegee",
"fr:Comte-aop-bio",
"fr:Comte-rape",
"fr:Concentre",
"fr:Concentre-tomate",
"fr:Concentres-de-tomate",
"fr:Condiments à tartiner",
"fr:Conditionne-en-france",
"fr:Cone-patissier",
"fr:Confiserie-sans-sucre",
"fr:Confiseries-sans-sucre",
"fr:Confit",
"fr:Confit-d-oignon",
"fr:Confit-de-canard-pommes-de-terre-a-la-sarladaise",
"fr:Confits d’oie",
"fr:Confiture d’agrumes",
"fr:Confiture-d-angelique",
"fr:Confiture-de-cerises",
"fr:Confiture-de-framboises",
"fr:Confiture de roses",
"fr:Confiture-extra",
"fr:Confiture-extra-de-framboise-allegee-en-sucres",
"fr:Confitures artisanales",
"fr:Confitures-de-citron-vert",
"fr:Conserve-de-legumes-cuisines",
"fr:Conserve-de-maquereaux",
"fr:Conserve-de-viande",
"fr:Conserves-de-fruits",
"fr:Conserves-de-legume",
"fr:Cookies au chocolat et à la noix de coco",
"fr:Cookies aux amandes",
"fr:Cookies-aux-pepites-de-chocolat-noir-bio",
"fr:Cookies-bio-au-chocolat",
"fr:Cookies-choco-noisette-coeur-fondant",
"fr:Cookies-pepites-chocolat",
"fr:Coppa-bio",
"fr:Coquille Saint-Jacques",
"fr:Coquillettes-au-ble-integral-bio",
"fr:Coquillettes-bio",
"fr:Corbieres",
"fr:Corn-flakes-cacao-bio",
"fr:Cornet",
"fr:Cornet-glace",
"fr:Cornets",
"fr:Cornets-a-glace",
"fr:Cosmetique",
"fr:Cosmetiques",
"fr:Cote-de-porc",
"fr:Cotes-catalanes",
"fr:Cotes-du-rhone-village",
"fr:Coulis-de-fraises",
"fr:Coulis-de-tomate-bio",
"fr:Coup-double-bio",
"fr:Courges",
"fr:Courgette",
"fr:Courgettes",
"fr:Courgettes-en-rondelles-surgeles-bio",
"fr:Courgettes-surgelees",
"fr:Couscous-aux-epices",
"fr:Couscous-bio",
"fr:Couscous-de-manioc",
"fr:Couscous-royal-au-poulet",
"fr:Couscous-semi-complet-grain-moyen",
"fr:Crabe-royal",
"fr:Crackers-fromages-tomate-bio",
"fr:Crackers-sales",
"fr:Crakers",
"fr:Cranberries",
"fr:Creme-au-caramel",
"fr:Creme-brulee",
"fr:Creme-de-caramel",
"fr:Creme-de-marron",
"fr:Creme-de-riz",
"fr:Creme-de-riz-bio",
"fr:Creme-de-soja",
"fr:Creme-de-soja-liquide",
"fr:Creme-dessert-au-chocolat-bio",
"fr:Creme-dessert-caramel",
"fr:Creme-fouettee",
"fr:Crème Fraîche d'Isigny",
"fr:Creme-fraiche-legere",
"fr:Creme-fraiche-legere-epaisse",
"fr:Creme-fraiche-sous-pression",
"fr:Creme-glacee-au-chocolat-noir",
"fr:Creme-glacee-chocolat",
"fr:Creme-glacee-vanille-amandes-caramelisees",
"fr:Creme-sous-pression",
"fr:Creme-sucree",
"fr:Cremes-d-anchoiade",
"fr:Cremes-de-cassis",
"fr:Cremes-de-marrons",
"fr:Cremes-legeres",
"fr:Crepes-au-fromage",
"fr:Crepes-aux-fromages",
"fr:Crepes-nature-bio",
"fr:Crepes-salees",
"fr:Crepes-sales",
"fr:Crevettes-bio",
"fr:Crevettes-crues",
"fr:Crevettes-entieres",
"fr:Crevettes géantes tigrées",
"fr:Crevettes grises",
"fr:Crevettes nordiques",
"fr:Croissants-precuits",
"fr:Crottin-de-chavignol",
"fr:Crousti-panes-tomates",
"fr:Crousti-pause-coeur-fondant-cacao-noisette",
"fr:Croutons-pour-salade",
"fr:Crudites",
"fr:Cuisine",
"fr:Cuisine-asiatique",
"fr:Cuisine-japonaise",
"fr:Cuisses-de-canard",
"fr:Cuisses-de-canard-du-sud-ouest-confites-surgelees",
"fr:Cuisses-de-poulet",
"fr:Cumin",
"fr:Curry-de-lentilles",
"fr:Curry-rouge",
"fr:De-cranberry-et-puree-de-framboise-100-pur-fruit-presse",
"fr:Demi-margarine",
"fr:Dentifrices",
"fr:Dès 15 mois",
"fr:Dès 24 mois",
"fr:Des-de-cervelas",
"fr:Desert",
"fr:Dessert-au-soja-caramel-bio",
"fr:Dessert-au-soja-saveur-vanille-bio",
"fr:Dessert-biofruits-pomme-nature",
"fr:Dessert-de-fruits-au-riz-pomme-poire",
"fr:Dessert-de-fruits-pomme-abricot",
"fr:Dessert-de-fruits-pomme-banane",
"fr:Dessert-de-fruits-pomme-poire",
"fr:Dessert-en-poudre",
"fr:Dessert-fruitier",
"fr:Dessert-lacte-au-chocolat",
"fr:Dessert-lacte-aux-oeufs",
"fr:Dessert-lactee",
"fr:Dessert-oriental",
"fr:Dessert-pomme-banane-bio",
"fr:Dessert-pomme-cassis-bio",
"fr:Dessert-pomme-mangue-bio",
"fr:Dessert-vegetal",
"fr:Desserts-aux-fruits",
"fr:Desserts lactés pour bébé",
"fr:Dosettes",
"fr:Dosettes-de-cafe",
"fr:Dosettes-souples-cafe",
"fr:Duo-d-olives-a-la-toscane",
"fr:Duo-de-riz-de-camargue-riz-semi-complet-et-riz-rouge-bio",
"fr:Eau-de-coco-bio",
"fr:Eau-de-fleurs-d-oranger",
"fr:Eau-gazeifiee",
"fr:Eau-minerale-aromatisee",
"fr:Eau-minerale-parfumee",
"fr:Eau-plate",
"fr:Eaux-minerals-naturelles",
"fr:Echalote-deshydratee",
"fr:Echalotes",
"fr:Echine-de-porc-assaisonnee",
"fr:Eclair-au-chocolat",
"fr:Emiette-de-thon",
"fr:Eminces-de-poulet-aux-petits-pois",
"fr:Eminces-de-saumon-atlantique-fume-bio",
"fr:Emmentals français est-central",
"fr:Emmentals suisses",
"fr:Endives",
"fr:Enrobes-de-chocolat-noir",
"fr:Entrecote",
"fr:Entrees-preparees",
"fr:Entremets",
"fr:Epices-bio",
"fr:Epices-pour-guacamole",
"fr:Epinard",
"fr:Epinards-a-la-creme",
"fr:Epinards-en-branche",
"fr:Epinards-en-branches",
"fr:Epinards-en-branches-surgeles",
"fr:Epinards-en-conserve",
"fr:Epinards-haches-a-la-creme",
"fr:Epinards-haches-a-la-creme-surgeles-bio",
"fr:Epinards-haches-bio-surgeles",
"fr:Epinards-haches-surgeles",
"fr:Epis-de-mais",
"fr:Epoisses",
"fr:Escalope",
"fr:Escalopes-de-dinde",
"fr:Escalopes-de-veau-hache",
"fr:Espadon",
"fr:Espadons fumés",
"fr:Esturgeons-fumes",
"fr:Ethiquable",
"fr:Expresso-en-dosettes",
"fr:Extrait-de-cafe",
"fr:Extrait-naturel",
"fr:Fabrication-artisanale",
"fr:Faiselle",
"fr:Faiselle-bio",
"fr:Faisselles",
"fr:Falafels",
"fr:Falafels-pois-chiches",
"fr:Farine-a-pain",
"fr:Farine-complete",
"fr:Farine-complete-de-petit-epeautre",
"fr:Farine-complete-de-quinoa-bio",
"fr:Farine-de-ble-semi-complete-du-gers-bio",
"fr:Farines de blé tendre",
"fr:Farines de Petit Épeautre",
"fr:Farines de petit épeautre T70",
"fr:Farines de pois chiche",
"fr:Farines de riz",
"fr:Farines de sarrasin",
"fr:Farines label rouge",
"fr:Farines labellisées",
"fr:Farines pâtissières",
"fr:Farines-pour-brioche",
"fr:Fauffrette",
"fr:Fecule-de-mais",
"fr:Fenouils",
"fr:Feta",
"fr:Fetas",
"fr:Feuilletes",
"fr:Figues-moelleuses-bio",
"fr:Figues-seches",
"fr:Filet",
"fr:Filet-de-colin-d-alaska",
"fr:Filet-de-harengs",
"fr:Filet-mignon",
"fr:Filet-mignon-de-porc",
"fr:Filets-de-colin",
"fr:Filets-de-colin-d-alaska",
"fr:Filets-de-colin-d-alaska-surgeles",
"fr:Filets-de-harengs",
"fr:Filets de sardines à l’huile d’olive",
"fr:Filets-de-sardines-a-l-huile-d-olive-vierge-extra",
"fr:Filets-de-sardines-sans-aretes-a-l-huile-d-olive-vierge-extra",
"fr:Financiers-aux-amandes",
"fr:Financiers-aux-amandes-bio",
"fr:Fines-galettes-epinards-et-pignons-bio",
"fr:Fines-gaufrettes-enrobees-de-chocolat-au-lait",
"fr:Fitou",
"fr:Flageolets-cuisines",
"fr:Flageolets-verts",
"fr:Flakes",
"fr:Flakes-d-epeautre-bio",
"fr:Flammenkueche",
"fr:Flan-a-la-vanille-nappe-de-caramel",
"fr:Flan-caramelise",
"fr:Flans",
"fr:Flans-gout-vanille-nappes-caramel",
"fr:Flocons",
"fr:Flocons-d-avoine",
"fr:Foie-de-veau",
"fr:Foie-gras-de-canard-entier",
"fr:Foies-gras-de-canard-entiers",
"fr:Fond-de-tarte",
"fr:Fonds-d-artifchauts",
"fr:Fonds-de-veau",
"fr:Fourre-tout-choco-bio",
"fr:Fourres-a-la-figue",
"fr:Fourres-chocolat-lait-bio",
"fr:Fourres-chocolat-lait-noisettes-bio",
"fr:Friandises",
"fr:Friandises-au-chocolat",
"fr:Fromage-a-pate-demi-dure",
"fr:Fromage-a-pate-dure",
"fr:Fromage-a-pate-dure-rape",
"fr:Fromage-a-pate-pressee",
"fr:Fromage-a-raclette",
"fr:Fromage-affine",
"fr:Fromage-ail-et-fines-herbes",
"fr:Fromage-allege",
"fr:Fromage-allege-au-lait-pasteurise",
"fr:Fromage-au-lait-d-ete",
"fr:Fromage-au-lait-de-vache-pasterise",
"fr:Fromage-au-lait-microfiltre",
"fr:Fromage-au-lait-pasterise",
"fr:Fromage-blanc-0",
"fr:Fromage-blanc-au-lait-de-brebis-framboise",
"fr:Fromage-blanc-nature-allege",
"fr:Fromage-de-chevre-a-tartiner-bio",
"fr:Fromage-de-lait-de-brebis",
"fr:Fromage-double-creme",
"fr:Fromage-dur-a-pate-cuite",
"fr:Fromage-emmental",
"fr:Fromage-en-tranches",
"fr:Fromage-fouette",
"fr:Fromage-frais-allege",
"fr:Fromage-frais-aux-fruits",
"fr:Fromage-frais-aux-herbes",
"fr:Fromage-frais-de-chevre",
"fr:Fromage-frais-de-chevre-nature-bio",
"fr:Fromage-nature",
"fr:Fromages-alleges",
"fr:Fromages-de-corse",
"fr:Fromages de Suisse",
"fr:Fromages en conserve",
"fr:Fromages-frais-aux-fruits",
"fr:Fromages-fumes",
"fr:Fromages-libre-service",
"fr:Fromages-pour-croque-monsieur",
"fr:Fructose",
"fr:Fructose-pur-cristallise",
"fr:Fruits-de-mer",
"fr:Fruits en conserve",
"fr:Fruits-surgeles",
"fr:Fusilli-carbonara",
"fr:Galette-de-riz-souffle",
"fr:Galette-de-soja",
"fr:Galette-vegetale",
"fr:Galettes-au-son-d-avoine",
"fr:Galettes-au-son-d-avoine-finement-salees-bio",
"fr:Galettes-bio",
"fr:Galettes-cereales-orge",
"fr:Galettes-cereales-sarrasin-comte-bio",
"fr:Galettes-chocolat",
"fr:Galettes-de-ble",
"fr:Galettes-de-mais-chocolat-noir-bio",
"fr:Galettes-de-pommes-de-terre-rapees",
"fr:Galettes-de-riz-fourrees",
"fr:Galettes-de-riz-fourrees-gout-choco-noisette-bio",
"fr:Galettes-de-riz-gout-choco-noisettes-au-riz-complet-bio",
"fr:Galettes-de-riz-nappees-chocolat-blanc-saveur-yaourt-bio",
"fr:Galettes-de-riz-nappees-de-chocolat-noir",
"fr:Galettes-de-riz-nappees-de-chocolat-noir-bio",
"fr:Galettes-de-soja",
"fr:Galettes-fines-aux-3-cereales-et-sesame-bio",
"fr:Galettes-son-d-avoine-vanillees",
"fr:Gansettes",
"fr:Gaspacho",
"fr:Gateau-au-caramel",
"fr:Gateau-au-chocolat",
"fr:Gateau-de-semoule",
"fr:Gateau-de-semoule-nappage-chocolat",
"fr:Gateau-fourre",
"fr:Gateau-marbre",
"fr:Gâteaux apéritifs soufflés",
"fr:Gateaux-de-riz",
"fr:Gateaux-flocon-d-avoine",
"fr:Gauffre",
"fr:Gauffres-au-miel-bio",
"fr:Gauffrettes",
"fr:Gaufrettes-au-chocolat-au-lait",
"fr:Gel-coiffant",
"fr:Genoise-fourre",
"fr:Gentiane",
"fr:Germe-de-ble",
"fr:Gesiers",
"fr:Gesiers-de-volaille-eminces",
"fr:Gewurztraminer",
"fr:Girolles",
"fr:Glace-au-yaourt",
"fr:Glaces à la vanille",
"fr:Gnocchi-de-pommes-de-terre",
"fr:Gnocchis",
"fr:Gnochetti",
"fr:Gougeres",
"fr:Gourdes-de-compote-de-pomme",
"fr:Gout-framboise",
"fr:Gouter-4s-aux-pommes",
"fr:Gouter-aux-raisins",
"fr:Gouters-au-chocolat",
"fr:Gouters-dores-pocket",
"fr:Gouters-pour-enfants",
"fr:Graine-de-couscous-facile",
"fr:Graines-a-germer-de-tournesol",
"fr:Graines-de-lin",
"fr:Graines-et-fruits-secs",
"fr:Graines-soja",
"fr:Grains-de-ble-precuit",
"fr:Graisse-de-canard",
"fr:Granule",
"fr:Gratin-d-endives-au-jambon",
"fr:Gratin-dauphinois-au-jambon",
"fr:Grattons",
"fr:Grenade-bio",
"fr:Grenadine",
"fr:Gruyere-rape",
"fr:Guemene",
"fr:Gueuze",
"fr:Hache",
"fr:Hachis-parmentier-au-boeuf-bio",
"fr:Hachis-parmentier-bio",
"fr:Hachis-parmentier-pur-boeuf",
"fr:Hamburger-au-poulet",
"fr:Haricot-rouge-du-japon",
"fr:Haricots-beurres",
"fr:Haricots-blancs-a-la-tomate",
"fr:Haricots-blancs-secs",
"fr:Haricots-cocos",
"fr:Haricots-vert",
"fr:Haricots-verts-extra-fins",
"fr:Haricots-verts-surgeles",
"fr:Haricots-verts-tres-fins-bio",
"fr:Harissas",
"fr:Herbes",
"fr:Hove",
"fr:Huile-d-argan-grille-bio",
"fr:Huile-de-noisette-bio",
"fr:Huile-de-noix-bio",
"fr:Huile-de-tournesol-vierge-bio",
"fr:Huile-pimentee",
"fr:Huiles de poissons",
"fr:Hule-d-olive",
"fr:Ice-tea-zero-sucres-saveur-peche",
"fr:Igp",
"fr:Infusion-fenouil",
"fr:Infusions aux agrumes",
"fr:Jambon-a-teneur-reduite-en-sel",
"fr:Jambon-cuit-de-paris",
"fr:Jambon-cuit-superieur-avec-couenne",
"fr:Jambon-cuit-superieur-de-paris",
"fr:Jambon-de-campagne",
"fr:Jambon-serano",
"fr:Jambonneau-en-boite",
"fr:Jambons de Parme",
"fr:Jambons-eminces",
"fr:Jambons Label Rouge",
"fr:Jambons-secs-italiens",
"fr:Javel",
"fr:Joghurt",
"fr:Jus-carotte-citron-bio",
"fr:Jus-d-agrumes",
"fr:Jus d'ananas frais",
"fr:Jus-d-orange-100-pur-fruit-presse",
"fr:Jus-d-orange-avec-pulpe",
"fr:Jus-d-orange-avec-pulpe-frais",
"fr:Jus-d-orange-bio",
"fr:Jus-d-orange-pasteurise-bio",
"fr:Jus-d-orange-pur-jus",
"fr:Jus-d-orange-sans-pulpe",
"fr:Jus-d-orge",
"fr:Jus-de-banane",
"fr:Jus-de-carotte",
"fr:Jus-de-citron-a-base-de-concentre",
"fr:Jus-de-fruis",
"fr:Jus-de-fruit-pasteurise",
"fr:Jus-de-fruits-100",
"fr:Jus-de-fruits-multifruits",
"fr:Jus-de-fruits-multifruits-100-pur-jus",
"fr:Jus-de-fruits-presses-pomme-framboise",
"fr:Jus-de-fruits-presses-pomme-mangue",
"fr:Jus-de-fuits",
"fr:Jus-de-goyave",
"fr:Jus-de-grenade",
"fr:Jus-de-mangue",
"fr:Jus-de-mangue-et-de-fruit-de-la-passion",
"fr:Jus-de-pamplemouse",
"fr:Jus-de-pamplemousse-blanc-bio",
"fr:Jus-de-peche",
"fr:Jus-de-poire",
"fr:Jus-de-pomme-100-pur-fruit-presse-bio",
"fr:Jus-de-pomme-bio",
"fr:Jus-de-pomme-biologique",
"fr:Jus-de-pomme-cassis",
"fr:Jus-de-pomme-et-de-mangue",
"fr:Jus-de-pomme-petillant",
"fr:Jus-de-pruneau-bio",
"fr:Jus-de-raisin-bio",
"fr:Jus-de-tomate-sale",
"fr:Jus-multi-fruits",
"fr:Jus-multifruit",
"fr:Jus-multifruit-a-base-de-concentre",
"fr:Jus-multifruit-a-base-de-jus-concentres",
"fr:Jus-multifruits-a-base-de-concentre",
"fr:Jus-multivitamine",
"fr:Jus-orange-banane",
"fr:Kinder",
"fr:Kiwi",
"fr:Kiwis",
"fr:Knacks industrielles à teneur réduite en sel",
"fr:La-vache-en-pot-aux-noisettes",
"fr:Lait-100-vegetal",
"fr:Lait-de-montagne-entier",
"fr:Lait-de-soja-chocolat",
"fr:Lait-demi-ecreme-uht",
"fr:Lait-empresure-sucre-aromatise-cacao",
"fr:Lait-maternise",
"fr:Lait-parfume",
"fr:Lait-sterilise-uht",
"fr:Laits d’Épeautre",
"fr:Laits-de-coco-aromatises",
"fr:Laits-micro-filtres",
"fr:Laitue",
"fr:Landes",
"fr:Langoustines",
"fr:Langres",
"fr:Lapin-chasseur",
"fr:Lapin-chasseur-ses-pommes-de-terre",
"fr:Lardons-allumettes-nature",
"fr:Lardons-nature-bio",
"fr:Lardons-natures-bio",
"fr:Lasagnes-a-la-bolognaise-pur-boeuf-bio",
"fr:Le-p-tit-nature-bio",
"fr:Le-petit-beurre-tablette-chocolat-au-lait",
"fr:Le-petit-beurre-tablette-chocolat-au-lait-fourre-noisette",
"fr:Légumes bio",
"fr:Legumes-chinois",
"fr:Legumes-conserve",
"fr:Légumes IGP",
"fr:Legumes-prefrits",
"fr:Legumes-sec-en-conserve",
"fr:Legumes-seches",
"fr:Legumes-secs-gourmands-lentilles-ble-pois-casses",
"fr:Legumes-verts",
"fr:Legumineuses",
"fr:Lentille-cuite",
"fr:Lentilles-carottes-bio",
"fr:Lentilles-en-conserve",
"fr:Lentilles-vertes-aux-lardons",
"fr:Lentilles-vertes-bio",
"fr:Lentilles-vertes-du-berry",
"fr:Levain",
"fr:Levure-de-biere",
"fr:Levure-de-boulanger-seche",
"fr:Levure-seche",
"fr:Levures-chimiques",
"fr:Limonade-au-sucre-de-canne-bio",
"fr:Limonade-bio",
"fr:Lin",
"fr:Linguine-chic-crevettes-coriandre-ail-et-poivre-noi",
"fr:Litchi",
"fr:Litchis",
"fr:Livre",
"fr:Lussac-saint-emilion",
"fr:Lychees au sirop",
"fr:Macaroni-sauce-morilles-cremeux-et-corse",
"fr:Macarons",
"fr:Mache",
"fr:Macon-blanc",
"fr:Madelaines",
"fr:Madeleines au beurre frais",
"fr:Madeleines au raisin",
"fr:Madeleines longues",
"fr:Madeleines-natures-aux-oeufs-frais",
"fr:Magret",
"fr:Magret-de-canard",
"fr:Mais-grilles",
"fr:Mais-tendre",
"fr:Mais-ultra-croquant",
"fr:Mangues au sirop",
"fr:Mangues séchées",
"fr:Maquereau-en-boite",
"fr:Maquereaux-a-la-moutarde",
"fr:Maquereaux-aux-aromates",
"fr:Maquereaux-aux-tomate-basilic-et-olives",
"fr:Maquereaux fumés",
"fr:Margarine-huile-olive",
"fr:Margaux",
"fr:Marlins fumés",
"fr:Marrons-cuits-a-la-vapeur",
"fr:Marrons-glaces",
"fr:Mascarpone-cremeux-bio",
"fr:Matiere-grasse-a-tartiner",
"fr:Matiere-grasse-a-tartiner-et-a-cuire",
"fr:Mayonnaise-allege",
"fr:Medoc",
"fr:Méduse",
"fr:Melange-aperitif",
"fr:Melange-d-epices",
"fr:Melange-d-huiles",
"fr:Melange-de-5-cereales-bio",
"fr:Melange-de-ble-et-de-sarrasin",
"fr:Melange-de-cereales-ble",
"fr:Melange-de-cereales-legumes-secs-ble",
"fr:Melange-de-cereales-precuites",
"fr:Melange-de-graines-pour-pain",
"fr:Melange-de-legume",
"fr:Melange-quinoa-boulgour-bio",
"fr:Melanges-de-fruits",
"fr:Melisse",
"fr:Melon",
"fr:Menthe",
"fr:Merguez-et-agneau",
"fr:Mes-compotes-pommes-fraise-pommes-vanille",
"fr:Micro-ondes",
"fr:Microonde",
"fr:Miel-de-fleurs-bio",
"fr:Miels d’agrumes",
"fr:Miels d'eucalyptus",
"fr:Miels d’oranger",
"fr:Miels d'ulmo",
"fr:Miels de Bourgogne",
"fr:Miels de châtaignier",
"fr:Miels de forêt",
"fr:Miels du Gâtinais",
"fr:Miels liquides",
"fr:Miettes-de-surimi",
"fr:Milk-shake",
"fr:Milk-shake-substitut-de-repas-saveur-chocolat",
"fr:Mini-cakes-aux-figues-bio",
"fr:Mini-cakes-aux-fruits-bio",
"fr:Mini-cakes-aux-pepites-de-chocolat",
"fr:Mini-cakes-raisins",
"fr:Mini-cones-glacees",
"fr:Mini-moelleux-au-chocolat-bio",
"fr:Mini-toasts",
"fr:Mini-toasts-graines-de-lin",
"fr:Mini-toasts-pavot-et-graines-de-lin",
"fr:Miso",
"fr:Moelleux-pomme-cannelle",
"fr:Mothais",
"fr:Mou",
"fr:Mouchoirs",
"fr:Moules-cuisinees",
"fr:Moules-en-sauce",
"fr:Moulin-a-vent",
"fr:Mouline",
"fr:Mouline-de-legumes",
"fr:Mouline-de-legumes-d-autrefois",
"fr:Mousse-au-chocolat-au-lait",
"fr:Mousse-au-chocolat-noir",
"fr:Mousse-de-foie",
"fr:Mousse-de-marrons",
"fr:Moutarde-en-poudre",
"fr:Moutardes provençales",
"fr:Moutardes violettes",
"fr:Mozzarellas",
"fr:Muesli-25-de-fruit-4-cereales-bio",
"fr:Muesli-aux-fruits-bio",
"fr:Muesli-croustillant-choco-bio",
"fr:Muesli-croustillant-chocolat-bio",
"fr:Muesli-croustillant-fruits-rouges-bio",
"fr:Muesli-croustillant-natures-bio",
"fr:Muesli-croustillant-pomme-cannelle-bio",
"fr:Muesli-floconneux-5-cereales-nature-bio",
"fr:Muesli-pomme-abricot-bio-et-equitable",
"fr:Muesli-raisins-noisettes-bio",
"fr:Muffins",
"fr:Muffins-complets",
"fr:Muscat-sec",
"fr:Muscats",
"fr:Myrtilles",
"fr:Nappage",
"fr:Nappes-au-chocolat-au-lait",
"fr:Nectar-a-base-de-concentre-et-de-puree",
"fr:Nectar-d-orange-bio",
"fr:Nectar-de-letchis",
"fr:Nectar-de-pomme-bio",
"fr:Nectar-multifruits-bio",
"fr:Nectar-multivitamine-a-base-de-jus-concentres",
"fr:Nectar-orange-avec-sa-pulpe-a-base-de-jus-d-orange-concentre",
"fr:Nectars-de-citron-vert",
"fr:Nectars-de-litchis",
"fr:Nectars-de-poire",
"fr:Nectars-exotiques",
"fr:Nectars-tropicaux",
"fr:Nems-au-porc",
"fr:Nems-au-poulet",
"fr:Nids-d-oeufs",
"fr:Noix",
"fr:Noix-de-cajou-grillees-salees",
"fr:Noix-de-pecan",
"fr:Nougats de Montélimar",
"fr:Nouilles-asiatiques",
"fr:Nouilles-aux-oeufs",
"fr:Nouilles-instantannee",
"fr:Nouilles-royales-bami-goreng",
"fr:Nutella",
"fr:Oeuf-de-poule",
"fr:Oeuf-de-poule-en-plein-air",
"fr:Oeufs de cailles",
"fr:Oeufs-de-poules",
"fr:Oeufs en chocolat",
"fr:Oignon-cat-1-cal-50-70",
"fr:Oignons-frits",
"fr:Olive-verte-farcie",
"fr:Olives-aux-amandes",
"fr:Olives-denoyautees-noires-nature",
"fr:Olives-farcies-pate-de-poivron",
"fr:Olives-noires-a-la-grecque",
"fr:Olives-violettes",
"fr:Onctueuse-puree-de-pomme-de-terre-bio",
"fr:Orange-confite",
"fr:Orangettes-chocolat-noir",
"fr:Orge-et-avoine",
"fr:Paellas",
"fr:Pain-a-l-ail",
"fr:Pain-au-mais",
"fr:Pain-au-son-tranche",
"fr:Pain-aux-cereales-bio",
"fr:Pain-aux-fibres-tranche",
"fr:Pain-brioche",
"fr:Pain-d-epices-au-sirop-d-agave",
"fr:Pain-d-epices-bio",
"fr:Pain-de-mie-bio",
"fr:Pain-de-mie-blanc-bio",
"fr:Pain-de-mie-complet-tranche",
"fr:Pain-de-mie-sans-croute",
"fr:Pain-grille-bio",
"fr:Pain-grille-complet",
"fr:Pain-pave-tranche-500g-label-rouge",
"fr:Pain-special-de-campagne-bio",
"fr:Pains azymes à la farine complète",
"fr:Pains azymes à la farine d'épeautre",
"fr:Pains azymes au seigle",
"fr:Pains azymes pilés",
"fr:Pains de mie aux céréales",
"fr:Pains-et-biscottes",
"fr:Pains-speciaux-complets",
"fr:Palets-chocolat-cookies-de-cacao",
"fr:Palets-de-legumes",
"fr:Palets-pepites-chocolat",
"fr:Palmiers-allonges-au-sucre-un-peu-caramelise",
"fr:Palmiers-allonges-aux-gouttes-de-chocolat",
"fr:Palmiers-bio",
"fr:Palmiers-feuilletes-et-dores",
"fr:Pamplemousse-bio",
"fr:Pamplemousses",
"fr:Pancetta",
"fr:Panes-de-poulet",
"fr:Pappardelles",
"fr:Par origine de vente",
"fr:Parfum-cerise",
"fr:Parmesan-rape",
"fr:Pasta-with-mushroom-sauce",
"fr:Pastilla",
"fr:Pastille",
"fr:Pastilles",
"fr:Pate-a-fondant-au-chocolat",
"fr:Pate-a-gateaux",
"fr:Pate-au-piment",
"fr:Pate-capellini",
"fr:Pate-de-campagne",
"fr:Pate-de-foie-de-porc",
"fr:Pate-de-jambon",
"fr:Pâte de riz",
"fr:Pâté de tête",
"fr:Pate-en-croute",
"fr:Pate-imperial",
"fr:Pate-linguine",
"fr:Pate-molle",
"fr:Pate-spaghetti",
"fr:Pates-13-minutes",
"fr:Pâtes à base de Petit Épeautre",
"fr:Pates-a-tartinee",
"fr:Pates-a-tartiner-sucrees",
"fr:Pates-abc",
"fr:Pates-alphabets",
"fr:Pates-amorini",
"fr:Pates-asiatiques",
"fr:Pates-aux-ble-complet",
"fr:Pates-avoines",
"fr:Pates-castellane-parmigiane",
"fr:Pates-cavatelli-pugliesi",
"fr:Pates-cellentani",
"fr:Pates-cheveux-d-ange-de-qualite-superieure",
"fr:Pates-completes",
"fr:Pates-conchiglie-rigate",
"fr:Pates-d-alsace-nids",
"fr:Pates-d-alsace-nouilles-bouclees",
"fr:Pates-d-alsace-spaghetti",
"fr:Pates-d-epices",
"fr:Pates-de-ble-dur",
"fr:Pates-de-foie",
"fr:Pates-de-fruits-bio",
"fr:Pates-de-tandoori",
"fr:Pates-en-croute",
"fr:Pates-farfalle",
"fr:Pates-farfalle-tricolore",
"fr:Pates-farfalles-au-ble-complet",
"fr:Pates-fraiches-cuites",
"fr:Pates-fusilli",
"fr:Pates-fusilli-bio",
"fr:Pates-gansettes",
"fr:Pates-gnocchetti-sardi",
"fr:Pates-les-crozets-nature",
"fr:Pates-les-crozets-tomate-piment-d-espelette",
"fr:Pates-mafalde-corte-napoletane",
"fr:Pates-mezze-penne-tricolore",
"fr:Pates-piccolini-mini-farfalle-aux-carottes-et-potiron",
"fr:Pates-piccolini-mini-penne-rigate-aux-courgettes-et-epinards",
"fr:Pates-pour-enfant",
"fr:Pates-precuites",
"fr:Pâtes sablées",
"fr:Pates-spatzle-d-alsace",
"fr:Pates-torsades",
"fr:Pates-torsettes-au-ble-complet",
"fr:Pates-trofie-liguri",
"fr:Patisserie-orientale",
"fr:Patisseries-surgelees",
"fr:Patisseries-surgelees-a-cuire",
"fr:Paupiettes-de-porc",
"fr:Pauvre-en-graisse-saturees",
"fr:Pave-de-saumon-a-l-oseille",
"fr:Paves-de-saumon",
"fr:Peche-ou-framboise",
"fr:Penne-au-ble-integral-bio",
"fr:Penne-rigate-au-ble-complet",
"fr:Pepites-croustillantes-30-de-fruits",
"fr:Pepites-croustillantes-eclats-de-chocolat-noir",
"fr:Pepites-croustillantes-fruits-rouges-framboise-fraise-myrtille",
"fr:Pepites-de-chocolat",
"fr:Pepites-de-chocolat-noir",
"fr:Pepito-pockitos",
"fr:Petales-de-ble",
"fr:Petales-de-ble-au-chocolat",
"fr:Petales-de-cereales-copeaux-de-chocolat",
"fr:Petales-de-mais-dores-corn-flakes",
"fr:Petales-de-mais-sucres",
"fr:Petales-de-riz-et-ble-complet",
"fr:Petales-riz-et-ble-complet",
"fr:Petales-riz-et-ble-complet-aux-fruits-rouges",
"fr:Petit-beurre-au-chocolat-au-lait",
"fr:Petit-cake-fourre-saveur-chocolat",
"fr:Petit-cake-pepites-chocolat",
"fr:Petit-gateau",
"fr:Petit-pont-l-eveque",
"fr:Petit-pot-de-yaourt-au-citron-vert",
"fr:Petit-suisse",
"fr:Petites-tartines-legeres-et-craquantes",
"fr:Petits-carres-au-beurre-un-peu-sale-et-chocolat-noir",
"fr:Petits-fromages-frais-de-chevre-nature-bio",
"fr:Petits-gateaux",
"fr:Petits-pains",
"fr:Petits-pains-grilles-au-froment-bio",
"fr:Petits-pains-grilles-multi-cereales-bio",
"fr:Petits-pois-carottes",
"fr:Petits-pois-et-jeunes-carottes",
"fr:Petits-pois-tres-fin",
"fr:Petits-pois-tres-fin-et-jeunes-carottes",
"fr:Petits-suisses",
"fr:Petits-suisses-pour-bebes",
"fr:Pieces-en-chocolat",
"fr:Pilchards",
"fr:Pilons-de-poulet",
"fr:Pineaux",
"fr:Pipe-rigate",
"fr:Pistaches-grillees-nature",
"fr:Pistaches-grillees-non-salees",
"fr:Pistaches-grillees-salees",
"fr:Pistaches-grillees-sans-sel",
"fr:Pizza-jambon-fromage",
"fr:Plas-prepares",
"fr:Plat-prepare-surgeme",
"fr:Plats à base d’oies",
"fr:Plats à base de dinde",
"fr:Plats à base de lapin",
"fr:Plats-chinois",
"fr:Plats-chinois-surgeles",
"fr:Plats-desydrates",
"fr:Plats-thailandais",
"fr:Plats traiteurs",
"fr:Poelee-de-legumes",
"fr:Poelee-surgelee",
"fr:Poêlées",
"fr:Poire-de-normandie",
"fr:Poireaux-en-rondelles-surgeles-bio",
"fr:Pois-casses-de-france",
"fr:Pois-chiches-special-couscous",
"fr:Poisson-sugele",
"fr:Poissons-cuisines",
"fr:Poissons panés de colin",
"fr:Poitrine-de-porc",
"fr:Poivron-farci-a-la-morue",
"fr:Poivronnades",
"fr:Pomme-nature",
"fr:Pomme-noisette",
"fr:Pommes-dauphines",
"fr:Pommes-de-terre-annabelle-cat-1-cal-35-55",
"fr:Pommes-de-terre-bio",
"fr:Pommes-de-terre-cat-1-cal-35-55",
"fr:Pommes-de-terre-cuites",
"fr:Pommes-de-terre-en-cubes",
"fr:Pommes-de-terre-entieres-epluchees",
"fr:Pont-l'Evêque",
"fr:Pops-miel-bio",
"fr:Pops-miel-chocolat-bio",
"fr:Porc-au-caramel-et-riz-basmati-bio",
"fr:Porc-mijote-aubergines-et-4-cereales-bio",
"fr:Portion-individuelle",
"fr:Porto réductifs",
"fr:Porto Ruby",
"fr:Porto Tawny",
"fr:Portos oxydatifs",
"fr:Potages",
"fr:Poudre-a-lever",
"fr:Poudre-alimentaire",
"fr:Poudre-de-chocolat",
"fr:Poulet-basquaise",
"fr:Poulet-basquaise-au-piment-du-pays-basque-son-riz",
"fr:Poulet-korma",
"fr:Poulet-korma-et-riz-basmati",
"fr:Poulet-roti-jus-au-thym-ecrasee-de-pommes-de-terre-bio",
"fr:Poulet-sauce-aux-olives-et-quinoa-bio",
"fr:Poulet-tikka-masala",
"fr:Poulet-tikka-massala",
"fr:Poulets panés",
"fr:Pour-cuisiner",
"fr:Pour-la-confiserie",
"fr:Pour-plats-chinois",
"fr:Precuisine",
"fr:Preparation-a-base-de-jus-de-fruits",
"fr:Preparation-a-base-de-pomme-de-terre",
"fr:Preparation-a-base-de-viande",
"fr:Preparation-a-gateau",
"fr:Preparation-a-l-huile",
"fr:Preparation-a-l-huile-d-olive-arome-basilic-bio",
"fr:Preparation-a-l-huile-d-olive-saveur-truffe-bio",
"fr:Preparation-chocolate",
"fr:Preparation-de-soja-cuisine",
"fr:Preparation-instantane",
"fr:Preparation-pour-aperitif-a-base-de-tomate-et-de-basilic",
"fr:Preparation-pour-creme-patissiere",
"fr:Preparation-pour-crepes",
"fr:Preparation-pour-cuisine",
"fr:Preparation-pour-entremet-en-poudre",
"fr:Preparation-pour-flan-patissier",
"fr:Preparation-pour-fondant-au-chocolat",
"fr:Preparation-pour-infusion",
"fr:Preparation-pour-pain-special-et-patisserie",
"fr:Preparation-pour-pate-a-pizza",
"fr:Preparation-pour-pate-sablee",
"fr:Preparation-pour-patisserie",
"fr:Preparation-pour-sauce",
"fr:Preparation-pour-the",
"fr:Preparation-precuite",
"fr:Preparations-a-base-de-legumes",
"fr:Preparations-a-base-de-poisson",
"fr:Preparations-a-tartiner-a-base-de-poisson",
"fr:Preparations-culinaires",
"fr:Preparations-petit-dejeuner",
"fr:Produit-a-base-de-canard",
"fr:Produit-a-la-mangue",
"fr:Produit-a-la-menthe",
"fr:Produit-a-la-noisette",
"fr:Produit-au-chocolat-au-lait",
"fr:Produit-au-mentol",
"fr:Produit-au-poulet",
"fr:Produit-au-saumon",
"fr:Produit-au-sucre-de-canne",
"fr:Produit-congele",
"fr:Produit-importe",
"fr:Produit-issu-de-la-ruche",
"fr:Produit-kasher",
"fr:Produit-menager",
"fr:Produit-pocket",
"fr:Produit-pour-usage-culinaire",
"fr:Produit-recolte-par-des-abeilles",
"fr:Produits-a-la-fleur-de-sel",
"fr:Produits-a-la-pomme",
"fr:Produits-au-miel",
"fr:Produits-au-poisson",
"fr:Produits-aux-cereales",
"fr:Produits-aux-fruits-rouges",
"fr:Produits-avec-des-edulcorants",
"fr:Produits-d-erable-biologique",
"fr:Produits-en-turc",
"fr:Produits-frais",
"fr:Produits introuvables en Métropole",
"fr:Produits sous license",
"fr:Produits-sucrants",
"fr:Produits vendus dans les années 1950",
"fr:Produits vendus dans les années 1970",
"fr:Produits-vendus-dans-les-annees-2000",
"fr:Projet-archeologie",
"fr:Pruneaux-d-agen-bio",
"fr:Pruneaux-geants",
"fr:Pur-jus-d-orange-bio",
"fr:Puree-de-fruit",
"fr:Puree-de-legumes-pour-bebe",
"fr:Puree-de-mangues-et-de-pommes",
"fr:Puree-de-mangues-et-de-pommes-bio",
"fr:Puree-de-marron",
"fr:Puree-de-piments",
"fr:Puree-de-pomme-de-terre-deshydratee",
"fr:Puree-de-pommes-de-terre-au-lait-entier",
"fr:Puree-de-pommes-et-de-bananes-bio",
"fr:Puree-de-pommes-et-de-cassis-bio",
"fr:Puree-de-pommes-et-de-mangues-bio",
"fr:Puree-de-pommes-et-de-poires-bio",
"fr:Puree-de-tomate-fraiche",
"fr:Puree-de-tomates-concentree",
"fr:Puree-lentilles",
"fr:Puree-lentilles-corail-potiron-bio",
"fr:Purées d'amande blanche",
"fr:Purées de cacahuète",
"fr:Purées de noix de cajou",
"fr:Purées de sésame demi-complet",
"fr:Purees-de-tomate",
"fr:Quinoa-blond",
"fr:Quinoa-de-bolivie-bio",
"fr:Quinoa-lentilles-bio",
"fr:Quinoa-noir",
"fr:Quinoa-royal-bio",
"fr:Quinoa-tomates-olives-bio",
"fr:Quinoa-vert-asperges-petit-pois-haricots-verts",
"fr:Raclette-bio",
"fr:Raclette-de-caractere-lait-de-montagne",
"fr:Raclette-de-savoie-au-lait-cru",
"fr:Ras-el-hanout",
"fr:Ratatouille-cuisinee",
"fr:Ratatouilles-en-conserve",
"fr:Ravioli-au-jambon",
"fr:Raviolis-au-porc",
"fr:Raviolis-aux-epinards",
"fr:Raviolis-d-epinards-au-tofu-sauce-tomate-pesto-bio",
"fr:Raviolis-japonais",
"fr:Regal-de-legumes-verts-bio",
"fr:Regime",
"fr:Rehausseur-de-gout",
"fr:Rhum cubain",
"fr:Rhum français",
"fr:Rhums bruns",
"fr:Rillettes artisanales",
"fr:Rillettes de bar sauvage",
"fr:Rillettes de truite",
"fr:Rillons",
"fr:Risotto-au-crabe",
"fr:Risotto-aux-cepes",
"fr:Risotto-cremeux-poulet-asperges-morilles",
"fr:Riste",
"fr:Riz-au-lait-au-chocolat",
"fr:Riz-au-lait-saveur-vanille",
"fr:Riz-basmati-au-curry",
"fr:Riz-basmati-bio-et-ethiquable",
"fr:Riz-basmati-citron-et-aneth",
"fr:Riz-blanc-du-surinam",
"fr:Riz-cantonnais-nasi-goreng",
"fr:Riz-complet-rouge",
"fr:Riz-etuve",
"fr:Riz-etuve-grande-saveu",
"fr:Riz-le-basmati-du-penjab",
"fr:Riz-long-blanc",
"fr:Riz-long-blanc-camargue",
"fr:Riz-long-complet-bio",
"fr:Riz-long-etuve",
"fr:Riz-long-grain-basmati",
"fr:Riz-long-grain-complet",
"fr:Riz-long-grain-incollable",
"fr:Riz-long-grain-thai",
"fr:Riz-long-pour-risotto",
"fr:Riz-noir",
"fr:Riz-pour-risotto-arborio",
"fr:Riz-rouge",
"fr:Riz-sauvage",
"fr:Riz-special-paella",
"fr:Riz-special-risotto",
"fr:Riz-special-salades",
"fr:Riz-thai-jasmine",
"fr:Riz-thai-parfume-jasmin",
"fr:Riz Vialone Nano",
"fr:Rollmops",
"fr:Romarin",
"fr:Roquefort-au-lait-cru-de-brebis-bio",
"fr:Rosette-bio",
"fr:Rosti",
"fr:Roti-de-dinde",
"fr:Roti-de-porc-a-cuire",
"fr:Rouille",
"fr:Roussillon",
"fr:Sable-au-caramel-et-chocolat-au-lait",
"fr:Sable-miel-datte",
"fr:Sables-au-chocolat",
"fr:Sables-aux-cereales",
"fr:Sables-aux-cereales-nappes-de-chocolat-noir",
"fr:Sables-aux-figues",
"fr:Sables-bio-nappes-chocolat-au-lait",
"fr:Sables-caramel-au-sel-de-guerande",
"fr:Sables-choco-lait-coco",
"fr:Sables-coco-chocolat",
"fr:Sables-framboise",
"fr:Sables-pur-beurre",
"fr:Sachet-de-the",
"fr:Saint-marcelin",
"fr:Saint-nectaires",
"fr:Sainte-maure",
"fr:Salade-assaisonnee",
"fr:Salade-chinoise",
"fr:Salade-de-carottes",
"fr:Salade-de-carottes-rapees-aux-ecorces-d-agrumes-bio",
"fr:Salade-iceberg",
"fr:Salade-lentilles-et-legumes",
"fr:Salade-lentilles-et-legumes-bio",
"fr:Salade-quinoa-et-legumes",
"fr:Salade-quinoa-et-legumes-bio",
"fr:Salade-riz",
"fr:Salade-riz-avoine-legumes",
"fr:Salades-vertes",
"fr:Salsifis",
"fr:Samossa",
"fr:Samoussas",
"fr:Sardine-a-l-huile-d-arachide",
"fr:Sardines-a-la-sauce-tomate",
"fr:Sardines-a-poeler",
"fr:Sardines-au-beurre",
"fr:Sardines-au-jambon-fume",
"fr:Sardines-chaudes",
"fr:Sardines frites",
"fr:Sardines-grillees",
"fr:Sardines-marinade-citron-basilic",
"fr:Sardines-marinees-au-muscadet-et-aux-aromates",
"fr:Sarsines-a-l-huile",
"fr:Sauce-aigre-douce",
"fr:Sauce-asiatique",
"fr:Sauce-au-beurre-blanc",
"fr:Sauce-aux-cepes",
"fr:Sauce-barbecue",
"fr:Sauce-barbecue-a-la-chinoise",
"fr:Sauce-basquaise-bio",
"fr:Sauce-bolognaise-bio",
"fr:Sauce-carbonara",
"fr:Sauce-crudite",
"fr:Sauce-crudites",
"fr:Sauce-froide",
"fr:Sauce-nantua",
"fr:Sauce-pesto-vert-au-basilic",
"fr:Sauce-piquante",
"fr:Sauce-pour-cuisson",
"fr:Sauce-tartare",
"fr:Sauce-tomate-a-la-provencale-bio",
"fr:Sauce-tomate-aux-olives-vertes-et-noires-bio",
"fr:Sauce-tomate-bolognaise",
"fr:Sauce-yakitori",
"fr:Sauces au fromage",
"fr:Sauces au roquefort",
"fr:Sauces au soja salées",
"fr:Sauces aux légumes",
"fr:Sauces aux olives",
"fr:Sauces-mayonnaise",
"fr:Sauces-vinaigrette",
"fr:Saucisse-de-canard",
"fr:Saucisse-pur-porc",
"fr:Saucisses confites",
"fr:Saucisses-cuites",
"fr:Saucisses de Francfort",
"fr:Saucisses-de-francfort-bio",
"fr:Saucisses de Nuremberg",
"fr:Saucisses-de-toulouse-aux-lentilles-cuisinees",
"fr:Saucisses-fraiches",
"fr:Saucisses-fumees-bio",
"fr:Saumon-atlantique-fume-bio",
"fr:Saumon-fume-au-bois-de-hetre-eleve-en-ecosse",
"fr:Saumon-fume-ecosse",
"fr:Saumon-fume-norvege",
"fr:Saumon-sauce-oseille-ses-torsades",
"fr:Saumons-d-elevage",
"fr:Saumons-fumes-d-alaska",
"fr:Sauvignon",
"fr:Saveur-cerise",
"fr:Savon-liquide",
"fr:Schweppes-zero-ananas",
"fr:Schweppes-zero-fraise",
"fr:Sel-de-cuisine",
"fr:Sel-fin-iode",
"fr:Sels des marais salants",
"fr:Sels liquides",
"fr:Semoule-au-lait",
"fr:Semoule-de-couscous-a-la-tomate",
"fr:Semoule-de-couscous-aux-epices-douces",
"fr:Semoule-et-legumes-secs",
"fr:Semoules de blé",
"fr:Serano",
"fr:Série spéciale",
"fr:Sesame-et-lin-bio",
"fr:Sesame-sel",
"fr:Sirop-d-agave",
"fr:Sirops-de-peche",
"fr:Sirops de violette",
"fr:Smoothie-framboise-myrtille",
"fr:Snack-aperitif",
"fr:Soda-aux-ecorces-de-quinquina",
"fr:Sodas-a-l-anis",
"fr:Sodas-tonic",
"fr:Soins-specifiques",
"fr:Soja-calcium",
"fr:Soja-doux-saveur-noisette",
"fr:Soja-gratin-bio",
"fr:Soja-nature",
"fr:Soja-vanille",
"fr:Son-d-avoine-bio",
"fr:Son-fin-de-ble-bio",
"fr:Sorbet-mangue-passion",
"fr:Sorbets à la mangue",
"fr:Sorbets au citron",
"fr:Sorbets au citron vert",
"fr:Soule-de-legumes",
"fr:Soupe-au-choux",
"fr:Soupe-de-legumes-verts",
"fr:Soupe-de-sardines",
"fr:Soupe-deshydratee-de-nouilles",
"fr:Soupe-deshydratee-de-nouilles-japonaises",
"fr:Soupe-deshydratee-en-sachet",
"fr:Soupe-gaspacho",
"fr:Soupe-mouline-campagnard-bio",
"fr:Spaetzle",
"fr:Spaghetti-aux-oeuf",
"fr:Spaghetti-bio",
"fr:Spaghettis au petit épeautre",
"fr:Spatzle",
"fr:Spatzli",
"fr:Specialite-culinaire-a-l-ail-et-aux-fines-herbes",
"fr:Specialite-de-saucisse-seche",
"fr:Specialite-fromagere-pasteurisee",
"fr:Steack-hache",
"fr:Steack-hache-surgele",
"fr:Steak-de-cereales",
"fr:Steak-hache-a-l-oignon",
"fr:Steak-hache-frais",
"fr:Stevias",
"fr:Sticks",
"fr:Sticks-et-bretzels",
"fr:Stracciatella",
"fr:Sucettes",
"fr:Sucre-aromatise",
"fr:Sucre-blond-de-canne-en-morceaux-bio",
"fr:Sucre-blond-de-canne-en-poudre-bio",
"fr:Sucre-cristallise",
"fr:Sucre-sale",
"fr:Sucreries",
"fr:Sucres-en-poudre",
"fr:Super-cookies-coeur-fondant-au-chocolat-au-lait-et-noisette",
"fr:Surgelee",
"fr:Sushis",
"fr:Tabac",
"fr:Tabac-a-rouler",
"fr:Tablette-chocolat-85",
"fr:Tablettes-sauces",
"fr:Taboule-a-l-orientale-petits-legumes-menthe",
"fr:Taboulés au poulet",
"fr:Taboulés frais",
"fr:Tagliatelles-bio",
"fr:Tajine-de-legumes",
"fr:Tartare",
"fr:Tarte-aux-poireaux-surgelee",
"fr:Tarte-aux-tomates-cerises",
"fr:Tarte-aux-tomates-cerises-et-au-fromage-frais",
"fr:Tartelettes-a-la-fraise",
"fr:Tartelettes-framboise-bio",
"fr:Tartes au citron",
"fr:Tartes au citron meringuées",
"fr:Tartes au fromage",
"fr:Tartes françaises",
"fr:Tartinade-d-amande",
"fr:Tartines",
"fr:Tartines-craquantes-bio-chataigne",
"fr:Tartines-craquantes-sarrasin-bio",
"fr:Tartines-croustillantes-au-sesame",
"fr:Tendres-perles-ble",
"fr:Terrines de campagne",
"fr:Terrines de foie",
"fr:Terrines de lapin",
"fr:Terrines de Saint-Jacques",
"fr:Terrines de sanglier",
"fr:Thazars fumés",
"fr:The-earl-grey",
"fr:The-glace-saveur-peche",
"fr:The-glacee",
"fr:The-vert-aromatise-mure-bio",
"fr:The-vert-au-miel",
"fr:The-vert-de-ceylan",
"fr:The-vert-earl-grey-bio-ethiquable",
"fr:The-vert-menthe-bio",
"fr:The-vert-orange-bergamote-bio",
"fr:Thés bancha",
"fr:Thés Fukuju",
"fr:Thes-glaces-a-la-peche",
"fr:Thes-glaces-au-citron",
"fr:Thés minceur",
"fr:Thes-noirs-aromatises",
"fr:Thés Sencha",
"fr:Thon-a-l-eau",
"fr:Thon-basquaise-et-riz-complet-bio",
"fr:Thon-blanc-a-l-huile-d-olive-vierge-extra",
"fr:Thon-blanc-veritable-germon-a-l-huile-d-olive-vierge-extra",
"fr:Thons-a-la-tomate",
"fr:Thons-entiers",
"fr:Thons listao",
"fr:Thym",
"fr:Tielles",
"fr:Tilleul",
"fr:Toast-brioche-au-ble-complet-bio",
"fr:Toast-croustillant-au-fromage-et-aux-graines-de-courge-bio",
"fr:Toast-croustillant-aux-3-graines-bio",
"fr:Toast-croustillant-tomate-et-mozzarella-bio",
"fr:Toasts",
"fr:Tofu-a-l-indienne-riz-basmati-et-lentilles-bio",
"fr:Tofus",
"fr:Tomme de Savoie",
"fr:Torsades-au-ble-integral-bio",
"fr:Torsades-carbonara",
"fr:Torsades-semi-completes",
"fr:Tortellini-carbonara",
"fr:Tortelloni",
"fr:Tortilla",
"fr:Tortis",
"fr:Tranches-de-poulet",
"fr:Trempete-thai",
"fr:Trio-d-olives-cocktail-oriental",
"fr:Trio-de-quinoas-blond-rouge-noir-bio-et-ethiquable",
"fr:Truffes",
"fr:Tuiles-chips",
"fr:Tuiles-fromage",
"fr:Turron",
"fr:Vache-a-boire-aux-citrons-jaune-et-vert",
"fr:Vache-a-boire-mangue-passion",
"fr:Vache-a-boire-myrtille",
"fr:Vache-a-boire-vanille-de-madagascar",
"fr:Veau-hache",
"fr:Veloute-de-champignons",
"fr:Veloutés de courgettes",
"fr:Veloutés de poireaux",
"fr:Veloutés de tomates",
"fr:Vermicelle",
"fr:Verrines",
"fr:Verveine menthe",
"fr:Viande-bovine",
"fr:Viande-de-boeuf-sechee",
"fr:Viande-de-poulet",
"fr:Viande-en-sauce",
"fr:Viande-hache-de-boeuf",
"fr:Viande-preparee",
"fr:Viande-seche",
"fr:Viande-vegetale",
"fr:Viandes-bovines",
"fr:Viandes d’agneau",
"fr:Viandes-hachees",
"fr:Vin-aperitif",
"fr:Vin-blanc-gewurztraminer-bio",
"fr:Vin-blanc-sec",
"fr:Vin-d-alsace-muscat-bio",
"fr:Vin-d-alsace-pinot-blanc-bio",
"fr:Vin-de-bordeaux",
"fr:Vin-de-pays-rouge",
"fr:Vin-rose-gris-bio",
"fr:Vin-rouge-bonnezaux-bio",
"fr:Vin-rouge-de-bordeaux",
"fr:Vin-ventoux-aop-bio",
"fr:Vinaigre-d-alcool-8-d-acidite",
"fr:Vinaigres de tomate",
"fr:Vinaigrette-allegee",
"fr:Vins américains",
"fr:Vins-blancs-moelleux",
"fr:Vins-de-cepage-zinfandel",
"fr:Vins-des-sables",
"fr:Vins mousseux",
"fr:Volailles surgelées",
"fr:Vollailles",
"fr:Vollkornbrot-mini-toasts-pain-de-seigle-complet",
"fr:Vollkornbrot-pain-de-seigle-complet-bio",
"fr:Wasabi",
"fr:Whisky écossais",
"fr:Wrap-au-poulet",
"fr:Wrap-au-poulet-et-au-bacon",
"fr:Yaourt-a-la-mangue",
"fr:Yaourt-a-la-vanille-de-madagascar",
"fr:Yaourt-au-lait-entier-sucre-a-la-framboise",
"fr:Yaourt-au-lait-entier-sucre-a-la-mure",
"fr:Yaourt-au-lait-entier-sucre-a-la-myrtille",
"fr:Yaourt-au-lait-pasteurise",
"fr:Yaourt-brasse-abricot-au-lait-entier-bio",
"fr:Yaourt-brasse-nature-bio",
"fr:Yaourt-de-brebis-a-la-grecque-bio",
"fr:Yaourt-de-brebis-nature",
"fr:Yaourt-mocca",
"fr:Yaourt-nature-0-bio",
"fr:Yaourt-nature-au-lait-de-chevre",
"fr:Yaourt-nature-bio",
"fr:Yaourt-nature-biologique",
"fr:Yaourt-onctueux-mangue-passion",
"fr:Yaourt-surce",
"fr:Yaourt-vanille-de-madagascar-bio",
"fr:Yaourts-a-l-abricot",
"fr:Yaourts-aromatises-au-lait-entier",
"fr:Yaourts-au-lait-entier-pruneaux",
"fr:Yaourts-aux-fruits-avec-morceaux-de-fruits",
"fr:Yaourts-aux-fruits-fraise",
"fr:Yaourts-brasse-sucre-aromatise",
"fr:Yaourts-brasses-nature-au-lait-entier-bio",
"fr:Yaourts-framboise",
"fr:Yaourts-grecs",
"fr:Yaourts-nature-alleges",
"fr:Yaourts-nature-sucres",
"fr:Yaourts-natures-sucres",
"fr:Yaourts-sans-morceaux",
"Fromages",
"Fromages-a-pate-pressee-non-cuite",
"Fromages-de-vache",
"Fromages-de-vache-prim-holstein",
"Fromages-des-pays-bas",
"Fromages-pasteurises",
"Gouda",
"it:Bevande-vegetali",
"it:Cioccolato",
"it:Creme-caramel",
"it:Fromage-frais",
"it:Pomodoro",
"it:Snacks",
"it:Vino-frizzante",
"it:Vino-rosso",
"it:Wafer-con-crema-al-cioccolato",
"nl:Bier",
"nl:Gebakjes",
"nl:Koeken",
"nl:Pancakes",
"nl:Pastasaus",
"nl:Peppermunt",
"Other-ketchup",
"pl:",
"pl:Bigos",
"pl:Delicatesy",
"pl:Golonka",
"pl:Karczek",
"pl:Konserwy-ribne",
"pl:Majonez",
"pl:Pasztet-drobiowy",
"pl:Produit-polonais",
"pl:Soupes-deshydratees",
"pl:Sprats",
"pl:Szprot",
"pl:Szynka",
"pl:Vodka",
"pl:Zeberta",
"Produits-laitiers",
"pt:Acai-em-pasta-com-guarana-congelado",
"pt:Acai-em-pasta-congelado-com-aroma-sintetico-de-guarana-identico-ao-natural",
"pt:Agua",
"pt:Arroz-branco",
"pt:Barra-de-cereais",
"pt:Barra-de-cereal",
"pt:Bebida-nao-alcoolica",
"pt:Bebidas-sem-acucar",
"pt:Beurre",
"pt:Biere",
"pt:Biscoito",
"pt:Biscoitos",
"pt:Biscoitos-de-arroz-integral",
"pt:Bisnaguinha",
"pt:Bolachas",
"pt:Castanhas",
"pt:Cereais",
"pt:Cereal-integral",
"pt:Cereal-matinal-de-aveia",
"pt:Cervejas",
"pt:Cha-de-maca",
"pt:Charcuterie",
"pt:Chips",
"pt:Chocolate-aerado",
"pt:Chocolate-ao-leite",
"pt:Chocolate-recheado",
"pt:Complementos-alimentares",
"pt:Complements-alimentaires",
"pt:Conserves-de-legumes",
"pt:Cookies-com-aveia-integral",
"pt:Creme-de-leite-bovino-enlatado",
"pt:Doce-de-amendoim",
"pt:Epices",
"pt:Extrato-de-malte-sabor-chocolate",
"pt:Farinha-de-mandioca",
"pt:Farinha-de-milho",
"pt:Farinha-lactea",
"pt:Flocos-de-cereais",
"pt:Graisses",
"pt:Guarana-em-po",
"pt:Jambon",
"pt:Jambon-fume",
"pt:Legumineuses",
"pt:Leite-com-chocolate",
"pt:Leite-condensado",
"pt:Leite-semidesnatado",
"pt:Mantegia",
"pt:Massa-salgada",
"pt:Milho-verde-em-conserva",
"pt:Molho-de-tomate",
"pt:Ovo-tipo-extra-branco",
"pt:Pao-integral-com-linhaca",
"pt:Pates-alimentaires",
"pt:Pates-au-pesto",
"pt:Po-para-manjar-de-coco",
"pt:Potages",
"pt:Queijo-cremoso",
"pt:Queijo-petit-suisse",
"pt:Ricota-fresca",
"pt:Salgadinho-de-batata",
"pt:Salgadinho-de-milho",
"pt:Sementes",
"pt:Sopa-de-carne",
"pt:Soupes",
"pt:Sucos",
"pt:Temperos",
"pt:Vegetais",
"pt:Vinho-tinto",
"pt:Vinho-verde",
"pt:Wafer",
"Pure-cod-liver-oil",
"vi:Gia-vi",
"vi:Thuc-pham-che-bien"];
