var labelsTags = [

"Organic",
"Vegetarian",
"EU Organic",
"Vegan",
"fr:AB Agriculture Biologique",
"Gluten-free",
"No preservatives",
"No colorings",
"fr:Ecocert",
"Fair trade",
"PDO",
"PGI",
"FR-BIO-01",
"FSC",
"fr:Labels de distributeurs",
"fr:Viande Française",
"Palm oil free",
"No GMOs",
"fr:AOC",
"Max Havelaar",
"No added sugar",
"Carbon footprint",
"No artificial flavors",
"ES-ECO-019-CT",
"fr:Viande Porcine Française",
"ES-ECO-016-CL",
"es:Producto-de-cooperativa",
"No artificial colors",
"Carbon compensated product",
"No lactose",
"Carrefour Quality",
"With sulfites",
"Fairtrade International",
"es:Etiquetas de calidad de España",
"Sustainable fishery",
"fr:Produit en braille",
"fr:Label Carrefour",
"No additives",
"Sustainable Seafood MSC",
"fr:Label Rouge",
"No flavour enhancer",
"es:Producto protegido de España",
"Pure cocoa butter",
"ES-ECO-020-CV",
"No flavors",
"fr:Saveurs de l'Année",
"ES-ECO-002-CM",
"fr:Testé par le panel test Carrefour",
"Rainforest Alliance",
"ES-ECO-024-MU",
"fr:Produit en Bretagne",
"fr:Sélection Intermarché",
"No added salt",
"fr:Viande Bovine Française",
"No sugar",
"es:Tierra de Sabor",
"fr:Garantie IPLC",
"ES-ECO-025-NA",
"es:FACE",
"fr:Halal",
"fr:Porc Français",
"Kosher",
"es:Calidad Certificada",
"fr:Bio-Solidaire",
"fr:Naturel",
"CH-BIO-006",
"fr:Qualité France",
"DE-ÖKO-013",
"ES-ECO-001-AN",
"IT-BIO-006",
"No milk",
"fr:Saveurs de l'Année 2013",
"Made in France",
"Natural flavors",
"fr:Aucun",
"ES-ECO-023-MA",
"Never frozen",
"fr:Fumé au bois de hêtre",
"fr:Saveurs de l'Année 2012",
"DE-ÖKO-001",
"Natural colorings",
"No aspartame",
"No Bisphenol-A",
"RSPO",
"fr:100% muscle",
"BE-BIO-01",
"DE-ÖKO-007",
"Demeter",
"No cholesterol",
"No eggs",
"fr:Bio-dynamie",
"DE-ÖKO-003",
"IT-BIO-007",
"fr:1-for-the-planet",
"fr:Certipaq",
"fr:Qualite-u",
"fr:Riche en Oméga-3",
"fr:Sans-conservateur-artificiel",
"fr:Sans-matiere-grasse-hydrogenee",
"ES-ECO-022-GA",
"EU Agriculture",
"Fed without GMOs",
"IT-BIO-009",
"No alcohol",
"USDA Organic",
"With Sunflower oil",
"fr:Agri-confiance",
"fr:Biogarantie",
"fr:Blé français",
"fr:Salé au sel sec",
"fr:Volaille française",
"25% less salt",
"No caffeine",
"No lecithine",
"Pure butter",
"Pure pork",
"fr:Bio-équitable",
"fr:Cacher-lepessah",
"fr:Engagement-qualite-labeyrie",
"fr:Maitre-artisan",
"fr:Sans arachide",
"fr:Sans-utilisation-d-ogm",
"fr:Saveurs de l'Année 2011",
"BE-BIO-02",
"NL-BIO-01",
"No MSG",
"Reinheitsgebot",
"Without",
"es:",
"es:DO",
"es:IGP Berenjena de Almagro",
"fr:Acier-recyclable",
"fr:Agriculture-familiale",
"fr:Ccpb",
"fr:Certifie-par-bureau-veritas",
"fr:Certisys-be-bio-01",
"fr:Cuit-au-feu-de-bois",
"fr:Fairetrade",
"fr:Nature-progres",
"fr:Safe",
"fr:Sans-lecithine-de-soja",
"ES-ECO-006-AR",
"ES-ECO-021-EX",
"IT-BIO-014",
"No soy",
"Vegan Society",
"es:DOCa",
"es:DOCa Rioja",
"fr:Aha",
"fr:Biologique-canada",
"fr:Bleu Blanc Coeur",
"fr:Cereales-d-origine-locale",
"fr:Controle-par-face",
"fr:Cuisson-vapeur",
"fr:Dop",
"fr:Ecocert-sas-f-32600",
"fr:Entreprise-du-patrimoine-vivant",
"fr:Fume-au-feu-de-bois",
"fr:Garantie-avec-du-ble-complet",
"fr:Inspire-teste-et-approuve-par-le-panel-test-carrefour",
"fr:Origine-certifiee-sud-ouest",
"fr:Origine-france",
"fr:Recette-traditionnelle",
"fr:Recommande-par-ufsbd",
"fr:Sans-huiles-hydrogenees",
"de:Okologische-produkt",
"1% for the planet",
"PT-BIO-04",
"Pure juice",
"en:Raw",
"Vegetarian Society",
"es:Alimentos de Extremadura",
"es:Reyno Gourmet",
"fr:A-l-eau-de-source",
"fr:Alimentation-100-vegetaux",
"fr:Au sel de Guérande",
"fr:Ble-de-france",
"fr:Ble-francais-selectionne",
"fr:Bureau-veritas",
"fr:Caae",
"fr:Certisys",
"fr:Collecte-de-proximite",
"fr:De-oko-006",
"fr:Eco",
"fr:Eco-emballages",
"fr:Ecolo-pass",
"fr:Eleve-en-plein-air",
"fr:European-fruit-juice-control-system",
"fr:Exploitations-familiales",
"fr:Filiere-alpina",
"fr:Garantie-qualite-or",
"fr:Lait-de-france",
"fr:Lait-non-homogeneise",
"fr:Medaille-d-or-paris-2011",
"fr:Non-fabrique-a-l-huile-d-arachide",
"fr:Oeufs-de-poules-elevees-en-plein-air",
"fr:Producteurs-paysans",
"fr:Produit-en-gourmandie",
"fr:Riche-en-fibres",
"fr:Sans-ajout-de-matiere-grasse",
"fr:Sans-cartillage",
"fr:Sans-emulsifiant",
"fr:Sans-epaississant",
"fr:Sans-gelatine",
"fr:Sans-huile",
"fr:Sans-matieres-grasses-hydrogenees",
"fr:Sans-polyphosphates",
"fr:Sans-poudre-de-lait",
"fr:Sans-proteines-de-lait",
"fr:Sans-viande",
"de:At-bio-301",
"de:Ohne-gentechnik",
"Authentic Trappist Product",
"Certified Belgian Abbey Beer",
"en:Dairy-free",
"ES-ECO-012-AS",
"ES-ECO-027-RI",
"IT-BIO-013",
"Not advised for pregnant women",
"Superior quality",
"es:DOP Pimentón de la Vera",
"es:IGP Lenteja de La Armuña",
"es:IGP Lenteja Pardina de Tierra de Campos",
"es:Sial-innovacion",
"fr:1-solidaire",
"fr:10-th-international-food-award-dusseldorf-1987",
"fr:100-filet",
"fr:100-origine-france",
"fr:100-pur-et-naturel",
"fr:100-pur-fruit-presse",
"fr:100-pur-jus-presse",
"fr:100-tournesol",
"fr:28-medailles-d-or",
"fr:Abcert-ag",
"fr:Agriculteurs-n-utilisant-aucun-produit-chimique-de-synthese-ni-pesticides-ni-ensilage",
"fr:Agriculture-francaise-durable",
"fr:Agriculture-france",
"fr:Alimentation-100-vegetaux-mineraux-et-vitamines",
"fr:Allege-en-sucre",
"fr:An",
"fr:Animavinum",
"fr:Appelation-d-origine-protegee",
"fr:Artisan",
"fr:Aucun-ensilage-d-herbe-ni-de-mais",
"fr:Avec-arome-naturel",
"fr:Bio-Cohérence",
"fr:Bio-pays-de-la-loire",
"fr:Canard-a-foie-gras-du-sud-ouest",
"fr:Certiconfiance",
"fr:Certifie-par-certipaq",
"fr:Certifie-par-qualisud",
"fr:Certifie-par-sgs-ics",
"fr:Certified-sustainable-palm-oil",
"fr:Choix-nutrition",
"fr:Classe-a",
"fr:Denominazione-di-origine-protetta",
"fr:Dolphin-safe",
"fr:Ecocert-f-32600",
"fr:Ecocert-fr-bio-01",
"fr:Emballage-sans-aluminium",
"fr:Engagement-qualite-carrefour",
"fr:Equitable-ecocert",
"fr:Fabrication-artisan-chocolatier-francais",
"fr:Fabrication-artisanale",
"fr:Fabrication-traditionnelle",
"fr:Facile-a-digerer",
"fr:Farine-100-francaise",
"fr:Filiere-soja-francais",
"fr:Fr-bio",
"fr:Fr-bio-10",
"fr:Fruits-selectionnes",
"fr:Iglo-forever-food",
"fr:Imprim-vert",
"fr:Indicacion-geografica-protegida",
"fr:Iso-9001",
"fr:Lait-100-origine-france",
"fr:Lait-biologique-francais",
"fr:Lait-origine-france",
"fr:Medaille-d-or",
"fr:Medaille-d-or-paris-2013",
"fr:Moins-de-3-de-matiere-grasse",
"fr:Norge",
"fr:Oeufs-origine-france",
"fr:Oeufs-pondus-en-france",
"fr:Oeufs-tries-a-la-main",
"fr:Origine-france-garantie",
"fr:Parmigiano-reggiano",
"fr:Pauvre-en-sodium",
"fr:Peche-a-la-ligne",
"fr:Pefc-30-31-113",
"fr:Porc-fermier-du-sud-ouest",
"fr:Premier-prix",
"fr:Preparees-a-la-main",
"fr:Producteurs-regionaux",
"fr:Produit-de-bretagne",
"fr:Produit-de-montagne",
"fr:Pur",
"fr:Pur-jus-de-fruits",
"fr:Qualite-controlee",
"fr:Qualite-or",
"fr:Recette-a-l-ancienne",
"fr:Riche-en-gout",
"fr:Sans-additif-artificiel",
"fr:Sans-adjonction-de-sel",
"fr:Sans-arete",
"fr:Sans-couenne",
"fr:Sans-edulcorants",
"fr:Sans-epaississants",
"fr:Sans-graisse-ajoutee",
"fr:Sans-lactoserum",
"fr:Sans-levure-ajoute",
"fr:Sans-levure-ajoutee",
"fr:Sans-matiere-grasse-ajoute",
"fr:Sans-polyphosphate",
"fr:Sans-saccharose",
"fr:Sans-utilisation-de-pecticide",
"fr:Sans-utilisation-de-pesticide",
"fr:Saveur-preservee",
"fr:Sin-gluten",
"fr:Skal",
"fr:Sol-association",
"fr:Source-de-vitamine-a",
"fr:Sucre-d-origine-naturelle",
"fr:Transforme-en-france",
"fr:Tres-faible-teneur-en-gluten",
"fr:Utz",
"it:Bio",
"ar:Ecocert",
"de:Ab",
"de:Ama-biozeichen",
"de:Ama-gutesiegel",
"de:Bio",
"de:Bio-europeen",
"de:Bio-nach-eg-okoverordnung",
"de:Eu-nicht-eu-landwirtschaft",
"de:Gentechnikfrei-erzeugt",
"de:Ohne-gentechnik-hergestellt",
"de:Osterreichische-landwirtschaft",
"en:0g-trans-fat",
"en:100-whole-grain",
"en:Ab",
"en:Agriculture-non-ue",
"en:American-heart-assn-certified",
"AT-BIO-402",
"en:Certified-by-oregon-tilth",
"CH-BIO-004",
"en:Cholesteral-free",
"en:Cold-processed",
"en:Ecocert",
"ES-ECO-002-AN",
"ES-ECO-003-AN",
"ES-ECO-017-CM",
"en:Ethical-award",
"en:Gelatin-free",
"en:Gluen-free",
"en:Great-gold-taste-2012",
"en:Halal",
"en:High-fibre",
"en:High-proteins",
"IT-BIO-003",
"IT-BIO-008",
"en:Laid-in-britain",
"Lowers cholesterol",
"en:Natural",
"en:Nut-free",
"en:Oko-garantie-bcs",
"PT-BIO-03",
"Pure beef",
"Rich in fiber",
"Rich in vitamin C",
"en:Salt-free",
"en:Sans-aspartame",
"en:Soil-association-organic",
"en:Suitable-for-diabetics",
"en:Sustainable-sea-food-msc",
"en:Trans-fat-free",
"TSG",
"en:Wheat-free",
"en:Wholegrains",
"es:0-azucares-anadidos",
"es:Alimentacion-consciente",
"es:Alimentos de Castilla-La Mancha",
"es:Bo-bio-126",
"es:Cz-bio-001",
"es:DO Manzanilla-Sanlúcar de Barrameda",
"es:DO Montilla-Moriles",
"es:DO Navarra",
"es:DO Toro",
"es:DOP Arroz de Valencia",
"es:DOP Azafrán de La Mancha",
"es:DOP Montes de Toledo",
"es:DOP Pasas de Málaga",
"es:DOP Pimentón de Murcia",
"es:DOP Sierra de Segura",
"es:DOP Vinagre de Jerez",
"es:Especie-protegida",
"es:Etiqueta de Calidad Doñana 21",
"es:Fuente-de-calcio-natural",
"es:Galicia Calidade",
"es:IGP Alubia de La Bañeza-León",
"es:IGP Garbanzo de Fuentesaúco",
"es:IGP Mazapán de Toledo",
"es:IGP Pemento do Couto",
"es:Producción Integrada",
"es:Sin-alcohol-0-0",
"es:VP",
"es:VP Campo de la Guardia",
"es:VT",
"es:VT Castilla",
"fr:0-calories",
"fr:0-matieres-grasses",
"fr:0-pesticide",
"fr:1-for-planet",
"fr:10-th-international-food-award-duseldorf-1887",
"fr:100-arabica",
"fr:100-d-origine-naturel",
"fr:100-francais",
"fr:100-france",
"fr:100-fruits",
"fr:100-natural-product",
"fr:100-plein-filet",
"fr:100-pommes-de-france",
"fr:100-pur-grain",
"fr:100-pur-jus-de-fruits",
"fr:100-recyclable",
"fr:100-semoule-de-ble-dur",
"fr:100-soja-francais",
"fr:100-teneur-en-fruits",
"fr:100-vegetable",
"fr:15-d-emballage",
"fr:2-3-m-g",
"fr:2008",
"fr:2009",
"fr:2011",
"fr:2012",
"fr:25-de-lait",
"fr:25-de-sel-en-moins",
"fr:30-de-sucre-en-moins-que-la-moyenne-des-colas-hors-light",
"fr:30-de-sucres",
"fr:30-moins-sucre",
"fr:40-sucres",
"fr:60-cereales",
"fr:60-de-m-g",
"fr:62-de-sucres-49-d-acide-gras-satures-36-de-sel-par-rapport-a-la-moyenne-des-principaux-biscuits-du-marche",
"fr:67-d-acides-gras-satures",
"fr:7-annees-d-age",
"fr:70-de-cacao",
"fr:75-de-cacao-minimum",
"fr:A-l-huile-d-olive-vierge-extra",
"fr:A-la-levure-boulangere",
"fr:A-la-moutarde-de-dijon",
"fr:A-la-perche",
"fr:A-teneur-reduit-en-sodium",
"fr:Abattu-en-france",
"fr:Aceitunas-de-espana",
"fr:Aceto-balsamico-di-modena-igp",
"fr:Adoucissant",
"fr:Afdiag",
"fr:Afdiag-epi-barre",
"fr:Afdiag-epi-de-ble-barre-dans-un-cercle",
"fr:Affinage-5-mois-minimum",
"fr:Affinage-de-tradition",
"fr:Agricultura-ecoloxica",
"fr:Agriculture-ecologique",
"fr:Agriculture-francaise-equitable",
"fr:Agriculture-u-e",
"fr:Aide-ue",
"fr:Alimentation-100-vegetaux-et-mineraux-et-vitamines",
"fr:Allege-en-matieres-grasses-par-rapport-a-la-moyenne-des-jambons",
"fr:Allegee-en-matieres-grasses",
"fr:Alliance-carton-nature",
"fr:Anima-vinum",
"fr:Animaux-nes-eleves-et-abattus-en-france",
"fr:Anti-stress",
"fr:Aoc-haut-medoc",
"fr:Apellation-d-origine-protegee",
"fr:Appelation-bourgone-passe-tout-grain-controlee",
"fr:Appellation-beaujolais-controlee",
"fr:Appellation-calvados-controlee",
"fr:Appellation-d-origine",
"fr:Appellation-d-origine-garantie-guerrouane",
"fr:Appellation-luberon-controlee",
"fr:Appellation-pommard-controlee",
"fr:Appertise",
"fr:Apport-en-matiere-grasse-maitrise",
"fr:Apport-en-sel-maitrise",
"fr:Aromes-et-colorants-naturels",
"fr:Artisan-chocolatier",
"fr:At-bio-301",
"fr:Au-feu-de-bois",
"fr:Au-lait-entier",
"fr:Au-sel-de-mer",
"fr:Aucune",
"fr:Aux-extraits-de-stevia",
"fr:Aux-oeufs-de-poules-elevees-en-plein-air",
"fr:Aux-oeufs-frais",
"fr:Avec-edulcorants",
"fr:Baratte-en-normandie",
"fr:Barquette-garantie-sans-bisphenol-a",
"fr:Beurre-a-teneur-reduite-en-mg",
"fr:Beverage-innovation-awards-2008",
"fr:Bien-se-nourrir-pour-mieux-vivre",
"fr:Bienfaisant",
"fr:Bio-allemand",
"fr:Bio-village",
"fr:Bio-vin-solidaire",
"fr:Bioagricert",
"fr:Ble-complet",
"fr:Ble-de-fabrication-francaise",
"fr:Ble-francais-issu-de-l-agriculture-responsable",
"fr:Ble-francais-sans-colorant",
"fr:Ble-sans-conservateur",
"fr:Boeuf-d-origine-controle",
"fr:Boeuf-francais-controle",
"fr:Boi-europeen",
"fr:Bouteille-100-recyclable",
"fr:Boyau-naturel",
"fr:Brasserie-artisanale",
"fr:Broye-a-la-meule-a-basse-temperature",
"fr:Bvcert",
"fr:Cabillaud-peche-en-atlantique-nord-ouest-et-atlantique-nord-est",
"fr:Cacao-30-minimum",
"fr:Cacao-30-minimum-dans-le-chocolat-au-lait",
"fr:Cacao-60-minimum",
"fr:Cacao-controle-par-ecocert-sa",
"fr:Caecv",
"fr:Canard-a-fois-gras-du-sud-ouest",
"fr:Canda-organic",
"fr:Caramel-au-sel-de-guerande",
"fr:Carton-recyclable",
"fr:Cereal-partners",
"fr:Certification-france",
"fr:Certification-par-it-bio-005",
"fr:Certificato-biologico-icea",
"fr:Certifie-ab-fr-bio-01-agriculture-france",
"fr:Certifie-bio-ocqv",
"fr:Certifie-certisys-be-bio-01",
"fr:Certifie-iso-9001",
"fr:Certifie-par-abcert-ag",
"fr:Certifie-par-blik-b-2600",
"fr:Certifie-par-blik-b2600-be-bio-02",
"fr:Certifie-par-certisys",
"fr:Certifie-par-ocacia",
"fr:Certifie-par-skal-nl-bio-01",
"fr:Certifie-sud-ouest",
"fr:Certified-cocoa",
"fr:Certifiee-par-be-bio-001",
"fr:Certifiees-par-sgs-ics",
"fr:Certifies-par-qualisud",
"fr:Ch-bio-06",
"fr:Charte-cosmebio",
"fr:Charte-qualite-environnement",
"fr:Chemouroth",
"fr:Chocolar-pur-beurre-de-cacao",
"fr:Chocolat-issus-du-commerce-equitable",
"fr:Choux-fleurs-de-bretagne",
"fr:Cnipt-n-228-414-8733",
"fr:Cnipt-n-88519048",
"fr:Collecte-en-france",
"fr:Colorants-d-origine-naturels",
"fr:Comite-agricultura-ecologica",
"fr:Comte",
"fr:Concours-general-agricole-medaille-d-argent-2013",
"fr:Concours-general-agricole-medaille-d-argent-paris-2010",
"fr:Conformement-au-reglement-bio",
"fr:Conservation-grade",
"fr:Conservation-naturelle",
"fr:Convient-a-l-alimentation-des-nourrissons",
"fr:Convient-aux-personnes-allergiques-au-gluten",
"fr:Creme-d-isigny",
"fr:Creme-origine-france",
"fr:Cristaux-d-huiles-essentielles-florisens",
"fr:Cru-bourgeois",
"fr:Cueillis-a-la-main",
"fr:Cuisine-de-pays",
"fr:Cuisine-en-france",
"fr:Cuisine-sans-huile-de-palme",
"fr:Cuisson-en-chaudron-de-cuivre-rouge",
"fr:Cuit-a-l-etouffee",
"fr:Cuit-sur-pierre",
"fr:Cuite-au-chaudron",
"fr:Cuite-sur-pierre",
"fr:Cultive-recolte-en-france",
"fr:Cuvee-prestige",
"fr:De-003-oko-kontrollstelle",
"fr:De-85-de-fruits",
"fr:De-la-nature-ardennaise",
"fr:De-oko-034",
"fr:Decongele-sur-place",
"fr:Decouenne",
"fr:Degraisse",
"fr:Denominacion-de-origen",
"fr:Developpe-les-energies-renouvelables",
"fr:Distillee-trois-fois",
"fr:Distribution-certifiee",
"fr:Distribution-certifiee-par-ecocert",
"fr:Distribution-certifiee-par-ecocert-sas",
"fr:Distribution-certifiee-qualite-france-sas-fr-bio-10",
"fr:Duree-de-vie-56-jours-minimum",
"fr:Eco-emballage",
"fr:Eco-label",
"fr:Ecocert-canada",
"fr:Ecocert-s-a-s-f-32600",
"fr:Ecoemballage",
"fr:Ecolopass",
"fr:Ecorecharge",
"fr:Elabore-au-pays-d-auge",
"fr:Elabore-avec-les-conseils-d-un-comite-de-pediatres",
"fr:Elabore-avec-les-conseils-d-un-pediatre",
"fr:Elabore-par-un-nutritionniste",
"fr:Eleve-en-france",
"fr:Eleve-en-futs-de-chene",
"fr:Eleve-sans-antibiotiques",
"fr:Eleveurs-laitiers-de-france",
"fr:Elu-produit-de-l-annee-2011",
"fr:Emballage-100-recyclable",
"fr:Emballage-reduit",
"fr:Engagement-qualite",
"fr:Entr-aide",
"fr:Entreprise-adaptee",
"fr:Eqc",
"fr:Eqcs-european-fruit-juice-control-system",
"fr:Es-eco-002",
"fr:Etiquette-en-braille",
"fr:F-32600-fr",
"fr:Fabrication-a-l-ancienne",
"fr:Fabrique",
"fr:Fabrique-dans-le-jura",
"fr:Fabrique-en-baratte",
"fr:Fabrique-en-corse",
"fr:Fabrique-en-isere",
"fr:Faible-teneur-en-matiere-grasse",
"fr:Faible-teneur-en-matieres-grasses",
"fr:Faible-teneur-en-sel",
"fr:Fairtrade-max-havelaar",
"fr:Fairtraide",
"fr:Feves-selectionnees",
"fr:Fibres",
"fr:Fieko-201",
"fr:Filiaire-nutrition",
"fr:Filiere-nutrition-omega-3-naturels",
"fr:Filiere-quinoa-bio-equitable",
"fr:Filiere-soja-francais-sans-ogm",
"fr:Filiere-soja-francais-sans-ogm-sojasun",
"fr:Flo-cert",
"fr:Fournisseur-officiel-de-la-cour-royale",
"fr:Fr-43-040-002-ce",
"fr:Fr-bio-09",
"fr:Fsc-c002324",
"fr:Fsc-c014047",
"fr:Fsc-mix",
"fr:Fumage-au-bois-de-hetre",
"fr:Fume-au-bois-d-arbres-fruitiers",
"fr:Fume-au-bois-de-sapin",
"fr:Fumes-delicatement-au-bois-de-hetre",
"fr:Garantie-boeuf-francais-controle",
"fr:Garantie-qualite",
"fr:Gb-org-05",
"fr:Gb-organic-certification-5",
"fr:Glucoregul",
"fr:Gold-medal-monde-selection-2010",
"fr:Good-food-foundation",
"fr:Gout-100-naturel",
"fr:Great-taste-gold-09",
"fr:Great-taste-gold-2007",
"fr:Guild-of-conservation-grade",
"fr:Gy-bio-602",
"fr:Haccp",
"fr:Huile-de-palme-durable",
"fr:Huile-de-palme-durable-certifiee-rspo",
"fr:Huile-de-palme-issue-de-forets-gerees-durablement",
"fr:Imo",
"fr:Impact-environnement-reduit",
"fr:Impact-environnemental-reduit",
"fr:Incice-carbone",
"fr:Indicazione-geografica-tipica",
"fr:Indice-carbone",
"fr:Indice-environnemental-3-6-pour-100g",
"fr:Inspire",
"fr:Iso-14001",
"fr:Issu-d-animaux-nourris-sans-ogm",
"fr:It-bio-006-agriculture-ue",
"fr:Jambon-de-porc-issu-d-animaux-nourris-sans-ogm-lt-0-9",
"fr:Jambon-qualite-superieure",
"fr:Ksa-kosher",
"fr:La-certification-qualite-iso-9001",
"fr:La-marque-n-1-de-vins-francais-dans-le-monde",
"fr:Label-quot-dolphin-safe-quot",
"fr:Lait-100-francais",
"fr:Lait-bio-francais",
"fr:Lait-bio-origine-france",
"fr:Lait-collecte-en-mayenne",
"fr:Lait-collectee-dans-les-fermes-selectionnees",
"fr:Lea-nature",
"fr:Lea-nature-group",
"fr:Leaf",
"fr:Legumes-frais-francais",
"fr:Les-memes-ingredients-qu-a-la-maison",
"fr:Liger-d-argent-2013-concours-vins-du-val-de-loire",
"fr:Lu-12-ce",
"fr:Lu-harmony",
"fr:Mais-doux-cultive-en-france",
"fr:Mais-sans-ogm",
"fr:Maitre-confiturier-de-france",
"fr:Marque-repere",
"fr:Master-blenders",
"fr:Medaille-argent-bruxelles-2012",
"fr:Medaille-argent-concours-mondial-bruxelles-2012",
"fr:Medaille-argent-vinalles-internationales-2013-paris",
"fr:Medaille-bronze-concours-2012-vignerons-independants",
"fr:Medaille-bronze-vignerons-independants-2012",
"fr:Medaille-d-argent-2013",
"fr:Medaille-d-argent-concours-des-burgondia-2010",
"fr:Medaille-d-argent-concours-general-agricole-paris-2013-medaille-de-l-agriculture-et-de-l-alimentation",
"fr:Medaille-d-argent-concours-mondial-bruxelles-2011",
"fr:Medaille-d-argent-paris",
"fr:Medaille-d-argent-paris-2012",
"fr:Medaille-d-argent-paris-2013-concours-general-agricole",
"fr:Medaille-d-argent-vinalies-internationales-2012-paris",
"fr:Medaille-d-or-2012",
"fr:Medaille-d-or-concours-de-bordeaux-2011",
"fr:Medaille-d-or-concours-general-agricole-paris",
"fr:Medaille-d-or-concours-general-agricole-paris-2011",
"fr:Medaille-d-or-macon-2003",
"fr:Medaille-d-or-paris-2012",
"fr:Medaille-d-or-paris-2013-concours-general-agricole",
"fr:Medaille-de-bronze-concours-des-grands-vins-de-france-macon-2010",
"fr:Medaille-de-bronze-du-concours-general-agricole",
"fr:Medaille-de-bronze-macon-2012",
"fr:Medaille-or-agriculture",
"fr:Medaille-or-concours-general-agricole-2012",
"fr:Medaille-or-du-guide-gilbert-gaillard",
"fr:Membres-fondateurs-de-l-issf-fondation-internationale-pour-la-durabilite-des-fonds-marins",
"fr:Mg",
"fr:Minimum-30-de-cacao",
"fr:Moins-de-1-de-sel",
"fr:Mon-choix",
"fr:Moule-a-la-louche",
"fr:Mozzarella-di-bufala",
"fr:Msc-sgs-nl-msc-c-0031",
"fr:N-de-tracabilite-07050-e-137",
"fr:N-de-tracabilite-26050-o-211-g-30",
"fr:Naturaplan",
"fr:Nature-et-progres",
"fr:Naturellement-bon",
"fr:Naturellement-sans-gluten",
"fr:Ne-en-france",
"fr:No-artificial-colourings",
"fr:Non-irradiees",
"fr:Non-ogm",
"fr:Nothing-artificial",
"fr:Nourri-sans-ogm-lt-0-9",
"fr:Oeuf-de-poule-alimentee-avec-65-de-cereales",
"fr:Oeuf-de-poule-fermiere-elevee-en-liberte",
"fr:Oeufs-francais",
"fr:Oloron-sainte-marie",
"fr:Omega-3",
"fr:Origine-bles-de-france",
"fr:Origine-italie",
"fr:Pain-sans-conservateur",
"fr:Panel-carrefour",
"fr:Participe-au-reboisement",
"fr:Parve",
"fr:Pas-de-sel-ajoute",
"fr:Pate-pur-beurre",
"fr:Pates-fraiches",
"fr:Pauvre-en-gluten",
"fr:Pauvre-en-sel",
"fr:Peche-francaise",
"fr:Peches-en-pleine-mer",
"fr:Pefc",
"fr:Petits-producteurs",
"fr:Picard",
"fr:Plant-bottle",
"fr:Plastique-pet-recyclable",
"fr:Point-vert",
"fr:Poissons-bleus-de-bretagne",
"fr:Pomme-origine-france",
"fr:Pommes-de-france",
"fr:Porc-charcutier-breton",
"fr:Porc-ne-et-eleve-au-pays-basque",
"fr:Poules-elevees-en-liberte",
"fr:Poules-nourries-sans-ogm",
"fr:Pour-vegetarien",
"fr:Premium",
"fr:Premium-beer",
"fr:Premium-geschmack-award",
"fr:Prepare-a-la-vapeur",
"fr:Presence-de-l-indice-environnemental",
"fr:Preservation-des-ressources-marines",
"fr:Preservation-du-patrimoine-forestier-mondial",
"fr:Prix-de-l-innovation-2010",
"fr:Prix-des-vinalies-2012",
"fr:Prodotto-in-italia",
"fr:Producteur-regionaux",
"fr:Production-certifiee-ccpb",
"fr:Produit-cerfifie-alimente-100-de-vegetaux",
"fr:Produit-dans-le-parc-naturel-perigord-limousin",
"fr:Produit-de-guyane",
"fr:Produit-elu-de-l-annee-2012-par-des-consommateurs-belges",
"fr:Produit-local",
"fr:Produit-normalise-i",
"fr:Produit-qualite",
"fr:Produit-trappiste-authentique",
"fr:Produits-de-bretagne",
"fr:Produto-organico-brasil",
"fr:Programme-d-agriculture-durable",
"fr:Programme-fracais-de-recuperation-et-de-retraitement-des-emballages",
"fr:Programme-francais-de-recuperation-et-de-retraitement-des-emballages",
"fr:Proprietaire-recoltant",
"fr:Proteines-100-vegetales",
"fr:Proteines-vegetales",
"fr:Pur-chevre",
"fr:Pur-fruit",
"fr:Pure-chocolat",
"fr:Qai-organic-certfied-usa",
"fr:Qualisud",
"fr:Qualita-macrobiotica",
"fr:Qualite-danoise",
"fr:Qualite-garantie",
"fr:Qualite-responsable",
"fr:Qualite-sans-arrete",
"fr:Qualite-supreme",
"fr:Race-charolaise",
"fr:Rafraichissant",
"fr:Recette-artisanale",
"fr:Recette-originale",
"fr:Recolte-manuellement",
"fr:Recoltes-testees-et-controlees-analyse-pesticides-et-metaux-lourds",
"fr:Recommande-par-usfbd",
"fr:Reconnu-saveur-de-l-annee-2012-goute-par-un-jury-de-consommateurs",
"fr:Regime-lacto-ovo-vegetarien",
"fr:Region-centre",
"fr:Respect-du-bien-etre-animal",
"fr:Riche-en-acide-gras-omega-3",
"fr:Riche-en-calcium",
"fr:Riche-en-cereales",
"fr:Riche-en-proteines",
"fr:Riche-en-vitamine-e",
"fr:Riche-n-omega-3-naturels",
"fr:Riz-de-camargue",
"fr:Roquefort",
"fr:Rspo-1106065",
"fr:Rspo-1106067",
"fr:Sale-au-sel-fin",
"fr:Sans-acides-gras-trans",
"fr:Sans-additif-bizarre",
"fr:Sans-addition-de-polyphosphate",
"fr:Sans-addition-de-polyphosphates",
"fr:Sans-agent-conservateur",
"fr:Sans-ajout-d-exhausteur-de-gout",
"fr:Sans-ajout-de-conserveur",
"fr:Sans-ajout-de-glutamate-monosodique",
"fr:Sans-aretes",
"fr:Sans-arome-vanille",
"fr:Sans-arretes",
"fr:Sans-ble",
"fr:Sans-cartilage",
"fr:Sans-colorant-articifiel",
"fr:Sans-colorant-ni-conservateur",
"fr:Sans-concervateur",
"fr:Sans-conservateur-conformement-a-la-reglement-en-vigeur",
"fr:Sans-conservateurs-artificiels",
"fr:Sans-conservatteur",
"fr:Sans-conversateur",
"fr:Sans-edulcorant",
"fr:Sans-edulcorant-artificiel",
"fr:Sans-electronarcose",
"fr:Sans-epaissisant",
"fr:Sans-epaissisant-ajoute",
"fr:Sans-epaississant-ajoute",
"fr:Sans-exhausteurs-de-gout-artificiels",
"fr:Sans-extrait",
"fr:Sans-fruit-a-coque",
"fr:Sans-fuile-de-palme",
"fr:Sans-glutamate-ajoute",
"fr:Sans-graisses-animales",
"fr:Sans-graisses-hydrogenees",
"fr:Sans-gras-trans",
"fr:Sans-ingredient-a-base-de-gluten",
"fr:Sans-matiere-grasse",
"fr:Sans-matiere-grasse-hydrogene",
"fr:Sans-matieres-grasses-hydrogenee",
"fr:Sans-matieres-grasses-hydrogenes",
"fr:Sans-mgs",
"fr:Sans-morceaux",
"fr:Sans-peau",
"fr:Sans-pepin",
"fr:Sans-phosphate",
"fr:Sans-piment",
"fr:Sans-produit-laitier",
"fr:Sans-proteine-de-lait",
"fr:Sans-sel",
"fr:Sans-sirop-de-mais",
"fr:Sans-sulfites",
"fr:Sans-utilisation-de-matieres-grasses-hydrogenees",
"fr:Sans-utilisation-de-pecticides",
"fr:Sans-vitamine-d3",
"fr:Sardines-selectionnees",
"fr:Saveur-2002",
"fr:Saveur-d-or-2011-concours-des-saveurs-regionales",
"fr:Saveur-en-or",
"fr:Saveurs-de-l-annee-2006",
"fr:Saveurs-en-or",
"fr:Saveurs-paris-ile-de-france",
"fr:Selectionne-par-nos-fromagers",
"fr:Ska",
"fr:Solo-pomodoro-italiano",
"fr:Source-de-calcium",
"fr:Source-de-vitamine-b9",
"fr:Source-de-vitamine-c",
"fr:Specialite-tradition-garentie",
"fr:Sucre-roux-non-raffine-pure-canne",
"fr:Sud-de-france",
"fr:Surgele",
"fr:Teneur-limite-en-sel",
"fr:Teneur-reduite-en-sel-1-27",
"fr:Teste-et-approuve-par-le-pannel-test-carrefour",
"fr:Tested-by-kids",
"fr:Tomates-de-plein-champ",
"fr:Toothfriendly",
"fr:Traditions-mediterraneennes",
"fr:Transport-optimise",
"fr:Trophee-de-l-innovation",
"fr:U-eco-raison",
"fr:Ufsbd",
"fr:Une-association-internationale-en-faveur-de-la-peche-durable",
"fr:Usda",
"fr:Utz-certified",
"fr:Utz-certified-cacao",
"fr:Utz-certified-cocoa",
"fr:Variete-native",
"fr:Vegan-friendly",
"fr:Veritablement-fume-en-tuye",
"fr:Veritas",
"fr:Viande-100-jambon",
"fr:Viande-100-muscle",
"fr:Viande-bovine-fracaise",
"fr:Viande-charolaise",
"fr:Viande-d-origine-controlee",
"fr:Viande-de-boeuf-origine-france",
"fr:Viande-de-porc-francais",
"fr:Viande-de-porc-origine-france",
"fr:Vignerons-independants",
"fr:Vinagre-de-jerez",
"fr:Vit",
"fr:Vive-le-gout",
"fr:Volaille-100-origine-francaise",
"fr:Volaille-origine-france",
"fr:Volailles-de-nos-regions",
"Gmp",
"it:Denominazione-d-origine-protetta",
"it:DOC",
"it:Docg",
"it:Indicazione-geografica-tipica",
"it:Origine-controllata",
"it:Qualita-controllata",
"it:Senza-glutine",
"it:Senza-lattosio",
"pt:Aop",
"pt:Certificacao-bdk",
"pt:Eau-soumise-a-une-technique-d-absorption-autorisee",
"pt:Nao-contem-gluten",
"pt:Sem-gluten",
"pt:Sem-gorduras-trans",
"pt:Sem-lactose",
"pt:Wine-spirits-2011-winery-of-the-year",
"pt:Zero-gordura-trans",
"vi:Giai-vang-chet-luong-ve-sinh-an-toan-thuc-pham",
"vi:Hang-viet-nam-chat-luong-cao"];
