var additivesTags = [

"E500ii - Sodium hydrogen carbonate",
"E341i - Monocalcium phosphate",
"E621 - Monosodium glutamate",
"E631 - Disodium inosinate",
"E170 - Calcium carbonate",
"E339i - Monosodium phosphate",
"E450iii - Tetrasodium diphosphate",
"E501i - Potassium carbonate",
"E508 - Potassium chloride",
"E202 - Potassium sorbate",
"E300 - Ascorbic acid",
"E330 - Citric acid",
"E341iii - Tricalcium phosphate",
"E476 - Polyglycerol polyricinoleate",
"E500i - Sodium carbonate",
"E509 - Calcium chloride",
"E627 - Disodium guanylate",
"E141i - Copper complexes of chlorophylls",
"E150d - Sulphite ammonia caramel",
"E171 - Titanium dioxide",
"E211 - Sodium benzoate",
"E325 - Sodium lactate",
"E339ii - Disodium phosphate",
"E407 - Carrageenan",
"E415 - Xanthan gum",
"E420i - Sorbitol",
"E460i - Microcrystalline cellulose",
"E535 - Sodium ferrocyanide",
"E551 - Silicon dioxide"];
