var additivesTags = [

"E500ii - Hidrogenocarbonato de sódio",
"E341i - Fosfato monocálcico",
"E621 - Glutamato monossódico",
"E631 - Inosinato dissódico",
"E170 - Carbonato de cálcio",
"E339i - Fosfato monossódico",
"E450iii - Difosfato tetrassódico",
"E501i - Carbonato de potássio",
"E508 - Cloreto de potássio",
"E202 - Sorbato de potássio",
"E300 - Ácido ascórbico",
"E330 - Ácido cítrico",
"E341iii - Fosfato tricálcico",
"E476 - Polirricinoleato de poliglicerol",
"E500i - Carbonato de sódio",
"E509 - Cloreto de cálcio",
"E627 - Guanilato dissódico",
"E141i - Complexos cúpricos de clorofilas",
"E150d - Caramelo sulfítico de amónia",
"E171 - Dióxido de titânio",
"E211 - Benzoato de sódio",
"E325 - Lactato de sódio",
"E339ii - Fosfato dissódico",
"E407 - Carragenina",
"E415 - Goma xantana",
"E420i - —sorbitol",
"E460i - Celulose microcristalina",
"E535 - Ferrocianeto de sódio",
"E551 - Dióxido de silício"];
