var categoriesTags = [

"pt:Sopa-instantanea",
"pt:Bebidas-nao-alcolicas",
"pt:Biscoito-salgado",
"pt:Refrigerantes",
"Beverages",
"Carbonated drinks",
"Sodas",
"fr:Tablette-chocolat-85",
"pt:Barra-de-cereal",
"pt:Bebida-nao-alcoolica",
"pt:Cereal-matinal-de-aveia",
"pt:Chocolate-aerado",
"pt:Extrato-de-malte-sabor-chocolate",
"pt:Guarana-em-po",
"pt:Massa-salgada",
"pt:Milho-verde-em-conserva",
"pt:Pao-de-forma",
"pt:Po-para-manjar-de-coco",
"pt:Salgadinho-de-milho",
"pt:Sucos",
"pt:Vegetais"];
