var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Maple syrups",
"Sodas",
"Dairies",
"Biscuits",
"Canned fishes",
"Canned foods",
"Fishes",
"Flours",
"Seafood",
"Tunas",
"fr:Thons pales",
"fr:Thons tropicaux",
"Candies",
"Creams",
"Dried fruits",
"Milks",
"Sugars",
"Waters",
"Wines",
"Yogurts",
"fr:Bonbons",
"fr:Bouillon",
"fr:Crèmes fraîches",
"fr:Eaux gazeuses",
"fr:Laits de soja",
"fr:Laits végétaux",
"fr:Mangues séchées",
"fr:Margarine-huile-olive",
"fr:Petits beurres",
"fr:Preparation-a-gateau",
"fr:Produits-d-erable-biologique",
"fr:Sauce-pour-cuisson",
"fr:Semoule",
"fr:Sirops",
"fr:Sodas au cola",
"fr:Thons albacore",
"fr:Thons listao",
"fr:Trempete-thai"];
