var categoriesTags = [

"Boissons",
"Boissons gazeuses",
"Sirops d'érable",
"Sodas",
"Produits laitiers",
"Biscuits",
"Poissons en conserve",
"Conserves",
"Poissons",
"Farines",
"Produits de la mer",
"Thons",
"Thons pales",
"Thons tropicaux",
"Confiseries",
"Crèmes",
"Fruits secs",
"Laits",
"Sucres",
"Eaux",
"Vins",
"Yaourts",
"Bonbons",
"Bouillon",
"Crèmes fraîches",
"Eaux gazeuses",
"Laits de soja",
"Laits végétaux",
"Mangues séchées",
"Margarine-huile-olive",
"Petits beurres",
"Preparation-a-gateau",
"Produits-d-erable-biologique",
"Sauce-pour-cuisson",
"Semoule",
"Sirops",
"Sodas au cola",
"Thons albacore",
"Thons listao",
"Trempete-thai"];
