var ingredientsTags = [

"",
"Ascorbic-acid",
"Berry-blend",
"Blueberry",
"Citric-acid",
"Live-cultures",
"Milk-solids",
"Peach",
"Peach-blend",
"Permitte-stabiliser",
"Permitted-flavouring",
"Permitted-stabilised",
"Potassium-sorbate",
"Raspberry-puree",
"Strawberry",
"Streptococcus-thermophilus-and-lactobacillus-bulgaricus",
"Sucrose",
"Tricalcium-phosphate"];
