var statusTags = [

"A-completer",
"A-verifier",
"Caracteristiques-completees",
"Characteristics completed",
"Complet",
"Complete",
"Date-limite-a-completer",
"Expiration date completed",
"Expiration date to be completed",
"Informations-nutritionnelles-completees",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients-completes",
"Nutrition facts completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos uploaded",
"Photos validated",
"Photos-validees",
"To be checked"];
