var statusTags = [

"Brands to be completed",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Complete",
"Expiration date completed",
"Expiration date to be completed",
"Ingredients completed",
"Ingredients to be completed",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos to be validated",
"Photos uploaded",
"Photos validated",
"Product name to be completed",
"Quantity to be completed",
"To be checked",
"To be completed"];
