##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration for DOCKER
#

# we must set the nginx container type before productopener-mappings.include
# abuse map gently because "set" is not allowed outside a server block
map "" $nginx_container {
	default "docker";
}

# some variables definitions to handle flavors and other topics
# but tweak it before hand to tell we are in docker
include snippets/productopener-mappings.include;

# variables useful to snippets/expiry-headers.include
# are loaded from /etc/nginx/conf.d/expires-no-json-xml.conf



server {
	listen 80;
	listen [::]:80;

	# Product Opener needs a root domain + a wildcard for all subdomains
	server_name ${PRODUCT_OPENER_DOMAIN} *.${PRODUCT_OPENER_DOMAIN};

	# this is the internal Docker DNS, cache only for 30s
	resolver 127.0.0.11 valid=30s;

	# some specific redirections
	include snippets/off.locations-redirects.include;

	# product opener common directives
	include snippets/productopener-server.include;

}

server {
	listen 80;
	listen [::]:80;

	server_name auth.${PRODUCT_OPENER_DOMAIN};

	# logs location
	access_log /var/log/nginx/auth-off-access.log;
	error_log /var/log/nginx/auth-off-error.log;

	gzip on;
	gzip_min_length 1000;

	# this is the internal Docker DNS, cache only for 30s
	resolver 127.0.0.11 valid=30s;
	location / {
		proxy_set_header Host $host;
		proxy_set_header Authorization $http_authorization;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		set $keycloak keycloak;
		proxy_pass http://$keycloak:8080;
	}
}

# this is to test folksonomy engine locally
# It might not respond if you didn't spin up the folksonomy project
# (https://github.com/openfoodfacts/folksonomy_api)
server {
	listen 80;
	listen [::]:80;

	server_name api.folksonomy.${PRODUCT_OPENER_DOMAIN};

	# logs location
	access_log /var/log/nginx/folksonomy-access.log;
	error_log /var/log/nginx/folksonomy-error.log;

	gzip on;
	gzip_min_length 1000;

	# this is the internal Docker DNS, cache only for 30s
	resolver 127.0.0.11 valid=30s;
	location / {
		proxy_set_header Host $host;
		proxy_set_header Authorization $http_authorization;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		set $folksonomy_api folksonomy_api;
		proxy_pass http://$folksonomy_api:8000;
	}
}
