name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: What steps can the team take to reproduce the issue?
      placeholder: |
        Steps to reproduce the behavior:

        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Type of device
      description: How were you accessing ProductOpener when you experienced the bug?
      multiple: false
      options:
        - Browser
        - Data dump (eg. MongoDB, CSV)
        - REST-API
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Browser version
      description: If you were using a browser, please specify the name (ie. Firefox or Safari) and version (eg. 91.0.2).
    validations:
      required: false
  - type: textarea
    attributes:
      label: Number of products impacted
      description: If relevant, number (or estimate) of products impacted by the feature at the time of creation of the issue
    validations:
      required: false
  - type: textarea
    attributes:
      label: Time per product
      description: Estimate of timeloss provoked or saved by the issue, per product
    validations:
      required: false
