name: Feature request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Problem description
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when […]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired solution
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives you have considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Number of products impacted
      placeholder: If relevant, number (or estimate) of products impacted by the feature at the time of creation of the issue
    validations:
      required: false
  - type: textarea
    attributes:
      label: Time per product
      placeholder: Estimate of timeloss provoked or saved by the issue, per product
    validations:
      required: false
