var categoriesTags = [

"Cakes",
"Dairies",
"Pastries",
"Choclate",
"Animal fats",
"Butters",
"Fats",
"Fresh",
"Milks",
"Vegetables and derived products",
"es:",
"es:Alubias-blancas-cocidas-en-conserva",
"es:Alubias-cocidas-en-conserva",
"es:Legumbres-y-derivados-en-conserva",
"es:Vegetales frescos",
"fr:Aluminium",
"fr:Aspirine",
"fr:Beurres demi-sel",
"fr:Gateaux-au-chocolat",
"fr:Gateaux-marbres",
"fr:Laits demi-écrémés",
"fr:Laits frais",
"fr:Laits-micro-filtres",
"fr:Madeleines",
"fr:Madeleines longues",
"fr:Muffins"];
