var categoriesTags = [

"Cakes",
"Dairies",
"Pastries",
"ar:Choclate",
"Grasas animales",
"Mantequillas",
"Aceites y grasas",
"Fresh",
"Leches",
"Vegetales y derivados",
"",
"Alubias-blancas-cocidas-en-conserva",
"Alubias-cocidas-en-conserva",
"Legumbres-y-derivados-en-conserva",
"Vegetales frescos",
"fr:Aluminium",
"fr:Aspirine",
"fr:Beurres demi-sel",
"fr:Gateaux-au-chocolat",
"fr:Gateaux-marbres",
"fr:Laits demi-écrémés",
"fr:Laits frais",
"fr:Laits-micro-filtres",
"fr:Madeleines",
"fr:Madeleines longues",
"fr:Muffins"];
