var statusTags = [

"A-completer",
"A-verifier",
"Brands-to-be-completed",
"Características completadas",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Completado",
"Complete",
"Date-limite-a-completer",
"Emballage-a-completer",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Fecha límite de consumo agregada",
"Imágenes agregadas",
"Imágenes validadas",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredientes completados",
"Ingredients-a-completer",
"Ingredients-completed",
"Ingredients-completes",
"Ingredients-to-be-completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Pendiente de comprobación",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos-validees",
"Product-name-to-be-completed",
"Quantite-a-completer",
"Quantity-to-be-completed",
"To-be-checked",
"To-be-completed",
"Valores nutricionales completados"];
