var categoriesTags = [

"Gâteaux",
"Produits laitiers",
"Pâtisseries",
"ar:Choclate",
"Matières grasses animales",
"Beurres",
"Matières grasses",
"Frais",
"Laits",
"Végétaux et dérivés",
"es:",
"es:Alubias-blancas-cocidas-en-conserva",
"es:Alubias-cocidas-en-conserva",
"es:Legumbres-y-derivados-en-conserva",
"es:Vegetales frescos",
"Aluminium",
"Aspirine",
"Beurres demi-sel",
"Gateaux-au-chocolat",
"Gateaux-marbres",
"Laits demi-écrémés",
"Laits frais",
"Laits-micro-filtres",
"Madeleines",
"Madeleines longues",
"Muffins"];
