var statusTags = [

"A-completar",
"A-completer",
"Brands to be completed",
"Cantidad-a-completar",
"Caracteristicas-a-completar",
"Caracteristicas-completadas",
"Caracteristiques-completees",
"Categorias-a-completar",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Date-limite-completee",
"Envase-a-completar",
"Expiration date completed",
"Expiration date to be completed",
"Fecha-limite-de-consumo-a-completar",
"Fecha-limite-de-consumo-agregada",
"Imagenes-a-agregar",
"Imagenes-a-validar",
"Imagenes-agregadas",
"Informations-nutritionnelles-completees",
"Ingredientes-a-completar",
"Ingredientes-completados",
"Ingredients completed",
"Ingredients-completes",
"Ingredients to be completed",
"Marcas-a-completar",
"Nombre-de-producto-a-completar",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"Product name to be completed",
"Quantity to be completed",
"To be completed",
"Valores-nutricionales-a-completar",
"Valores-nutricionales-completados"];
