var categoriesTags = [

"Aceites de oliva virgen extra",
"Aceites y grasas",
"Aceites de oliva",
"Grasas vegetales",
"Aceites vegetales",
"Vegetales y derivados",
"Untables vegetales",
"Vinagres",
"Mermeladas-y-confituras",
"Untables",
"Untables-dulces",
"Mermeladas-y-confituras-de-frutas",
"Endulzantes",
"Miel",
"",
"Condimentos",
"Groceries",
"Azafrán",
"Especias",
"Vegetales encurtidos",
"Encurtidos",
"Hortalizas",
"Aceitunas verdes",
"Aceitunas",
"Aceitunas verdes enteras",
"Aceitunas aliñadas",
"Mezcla de encurtidos",
"Aceitunas enteras",
"Mermeladas-y-confituras-de-citricos",
"Mermeladas-y-confituras-de-higos",
"Aceitunas verdes enteras aliñadas",
"Mermeladas-y-confituras-de-cebolla",
"Mermeladas-y-confituras-de-flores",
"Mermeladas-y-confituras-de-manzana",
"Mermeladas-y-confituras-de-naranja",
"Mermeladas-y-confituras-de-peras",
"Mermeladas-y-confituras-de-petalos-de-rosas",
"Mermeladas-y-confituras-de-verduras-y-hortalizas",
"Mermeladas-y-confituras-multifruta",
"Patés vegetales",
"Banderillas",
"Aceitunas verdes partidas aliñadas",
"Aceitunas partidas",
"Aceitunas verdes partidas",
"Aceitunas verdes deshuesadas",
"Aceitunas deshuesadas",
"Mermeladas-y-confituras-de-cereza",
"Mermeladas-y-confituras-de-limon",
"Mermeladas-y-confituras-de-melocoton"];
