var statusTags = [

"A completar",
"A-completer",
"Brands-to-be-completed",
"Cantidad a completar",
"Características a completar",
"Características completadas",
"Caracteristiques-completees",
"Categorías a completar",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Date-limite-completee",
"Envase a completar",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Fecha límite de consumo a completar",
"Fecha límite de consumo agregada",
"Imágenes a agregar",
"Imágenes a validar",
"Imágenes agregadas",
"Informations-nutritionnelles-completees",
"Ingredientes a completar",
"Ingredientes completados",
"Ingredients-completed",
"Ingredients-completes",
"Ingredients-to-be-completed",
"Marcas a completar",
"Nombre de producto a completar",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos-to-be-validated",
"Photos-uploaded",
"Product-name-to-be-completed",
"Quantity-to-be-completed",
"To-be-completed",
"Valores nutricionales a completar",
"Valores nutricionales completados"];
