log4perl.rootLogger=DEBUG, LOGFILE

# Avoid canonical for performance reasons. utf8 is disabled as otherwise it gets double-encoded by log4perl
log4perl.PatternLayout.cspec.S = sub { my $context = Log::Log4perl::MDC->get_context; use Cpanel::JSON::XS; return Cpanel::JSON::XS->new->allow_nonref->convert_blessed->allow_blessed->allow_unknown->utf8(0)->encode($context); }

log4perl.appender.LOGFILE=Log::Log4perl::Appender::File
log4perl.appender.LOGFILE.filename=/srv/obf/logs/minion_log4perl.log
log4perl.appender.LOGFILE.mode=append
log4perl.appender.LOGFILE.autoflush=1
log4perl.appender.LOGFILE.utf8=1
log4perl.appender.LOGFILE.layout=PatternLayout
log4perl.appender.LOGFILE.layout.ConversionPattern=[%r] %F %L %c %S %m{chomp}%n
