# This files enable live preview of your webcomponents
# (but you have to build it in your webcomonents project)

services:
  frontend:
    volumes:
      # this mounts the dist folder of the webcomponents project in the container
      # so that it can be used by the dynamicfront
      - ${WEBCOMPONENTS_DIR:-../openfoodfacts-webcomponents}/web-components:/opt/product-opener/node_modules/@openfoodfacts/openfoodfacts-webcomponents
  dynamicfront:
    volumes:
      # this mounts the dist folder of the webcomponents project in the container
      # so that it can be used by the dynamicfront
      - ${WEBCOMPONENTS_DIR:-../openfoodfacts-webcomponents}/web-components:/opt/product-opener/node_modules/@openfoodfacts/openfoodfacts-webcomponents
