var statusTags = [

"A completar",
"A-verifier",
"Brands-to-be-completed",
"Características completadas",
"Caracteristiques-completees",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Complete",
"Date-limite-a-completer",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Fecha límite de consumo agregada",
"Imágenes a validar",
"Imágenes agregadas",
"Informations-nutritionnelles-completees",
"Ingredientes completados",
"Ingredients-completed",
"Ingredients-completes",
"Ingredients-to-be-completed",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos-envoyees",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos-validees",
"Product-name-to-be-completed",
"Quantity-to-be-completed",
"To-be-checked",
"To-be-completed",
"Valores nutricionales completados"];
