var labelsTags = [

"Vegetarisch",
"es:Negra",
"Vegan",
"CO2-Emissionen",
"Ökologische Produkt",
"fr:Utz-certified",
"CH-BIO-006",
"EU Organic",
"es:Vegetalien",
"es:Vegetarien",
"Sustainable fishery",
"Sustainable Seafood MSC",
"fr:Oic",
"Fair trade",
"fr:M-bio",
"fr:Aha",
"Max Havelaar",
"fr:De-la-region",
"Biodynamic agriculture",
"Demeter",
"Fairtrade International",
"Grüne Punkt",
"PGI",
"fr:AB Agriculture Biologique",
"fr:Eco-emballages",
"fr:Ip-suisse",
"fr:Leger",
"Bio",
"Bio-dynamie",
"Bio-suisse",
"Naturafarm",
"FSC",
"Gluten-free",
"No caffeine",
"No colorings",
"Ohne Gentechnik",
"es:Negras",
"fr:AOC",
"fr:Bio7-initiative",
"fr:Biosuisse",
"fr:Ch-igp-038",
"fr:Fromages-a-pate-molle-a-croute-naturelle",
"fr:Fromages-au-lait-thermise",
"fr:Fromages-de-suisse",
"fr:Fromages-de-vache",
"fr:Fsc-emballage",
"fr:Ketchup",
"fr:Labels de distributeurs",
"fr:Naturaplan",
"fr:Pro-montagna",
"fr:Produits-laitiers",
"fr:Sans-ajout-d-exhausteur-de-gout",
"fr:Sans-conservateur-artificiel",
"fr:Testé par le panel test Carrefour",
"fr:Tomate",
"fr:Weightwatchers"];
