var categoriesTags = [

"Dairies",
"Fats",
"Vegetable fats",
"Vegetable oils",
"Olive oils",
"Yogurts",
"Beverages",
"Extra-virgin olive oils",
"Groceries",
"Candies",
"Vegetables",
"Vegetables and derived products",
"Chocolates",
"es:Untables vegetales",
"es:Mermeladas-y-confituras",
"es:Untables",
"es:Untables-dulces",
"Vinegars",
"Condiments",
"Biscuits",
"Meals",
"Meats",
"Spreads",
"Breakfasts",
"Canned foods",
"Cheeses",
"es:Mermeladas-y-confituras-de-frutas",
"Carbonated drinks",
"Frozen foods",
"Pastas",
"es:Endulzantes",
"es:Miel",
"fr:Produit-de-boulangerie",
"Fruit yogurts",
"Sauces",
"es:",
"fr:Chocolats Suisse",
"Canned Vegetables",
"Prepared meats",
"es:Azafrán",
"es:Especias",
"Pickled vegetables",
"Pickles",
"Sweet spreads",
"fr:Biscuiterie",
"Cereals",
"Creams",
"Fishes",
"Milks",
"Seafood",
"Sodas",
"fr:Chocolats noirs",
"Flavoured yogurts",
"Waters",
"fr:Apéritif",
"fr:Chocolats au lait",
"Animal fats",
"Butters",
"Cow Cheeses",
"Olives",
"Rices",
"fr:Pâtes à tartiner",
"fr:Pâtes sèches",
"fr:Preparation-a-base-de-viande",
"fr:Sodas au cola",
"fr:Viandes de porc",
"Chips and fries",
"Green olives",
"Salted spreads",
"fr:Barres",
"fr:Fromages à pâte fraîche",
"fr:Fromages à tartiner",
"fr:Lasagnes préparées",
"fr:Plats cuisinés surgelés",
"fr:Saucissons",
"fr:Thés glacés",
"Dried fruits",
"Fresh",
"Fruit juices",
"Fruit juices and nectars",
"Sausages",
"fr:Beurres pasteurisés",
"fr:Chips",
"fr:Eaux gazeuses",
"fr:Fromages à pâte fondue",
"fr:Pâtes à tartiner aux noisettes",
"fr:Pâtes fraîches",
"fr:Plats préparés en conserve",
"French cheeses",
"Green whole olives",
"Hot drinks",
"Industrial cheese",
"Jams",
"Marinated olives",
"Meals with meat",
"Mixed pickles",
"Sheep's milk yogurts",
"Spices",
"Whole olives",
"es:Mermeladas-y-confituras-de-citricos",
"es:Mermeladas-y-confituras-de-flores",
"es:Mermeladas-y-confituras-de-higos",
"es:Mermeladas-y-confituras-de-petalos-de-rosas",
"fr:Assaisonnements",
"fr:Barres chocolatées",
"fr:Barres de céréales",
"fr:Biscuits au chocolat",
"fr:Biscuits diététiques",
"fr:Chocolats avec amandes",
"fr:Laits demi-écrémés",
"fr:Laits végétaux",
"fr:Pates",
"fr:Petits beurres",
"fr:Plats préparés à réchauffer au micro-ondes",
"fr:Ravioli",
"fr:Sauces salades",
"fr:The-froid",
"fr:Viande-porc-salee",
"de:Kartoffelchips",
"Breaded products",
"Diet drinks",
"Diet sodas",
"Food additives",
"Fresh vegetables",
"Orange juices",
"Pastries",
"Salmons",
"Salts",
"Whole marinated green olives",
"es:Mermeladas-y-confituras-de-cebolla",
"es:Mermeladas-y-confituras-de-manzana",
"es:Mermeladas-y-confituras-de-naranja",
"es:Mermeladas-y-confituras-de-peras",
"es:Mermeladas-y-confituras-de-verduras-y-hortalizas",
"es:Mermeladas-y-confituras-multifruta",
"es:Patés vegetales",
"fr:Biscuit-aux-cereales",
"fr:Bonbons",
"fr:Bouillon-en-cube",
"fr:Cabillauds",
"fr:Cafe-solube",
"fr:Cafés",
"fr:Cafés en poudre",
"fr:Chocolats en poudre",
"fr:Chocolats noirs extra fin",
"fr:Choucroute-cuite",
"fr:Colins",
"fr:Crèmes entières",
"fr:Eaux minérales",
"fr:Fromages pasteurisés",
"fr:Laits entiers",
"fr:Légumes secs",
"fr:Mayonnaises",
"fr:Mozzarella",
"fr:Raviolis en conserve",
"fr:Riz pour risotto",
"fr:Salamis",
"fr:Sauces tomate",
"fr:Saucisse-a-rotir",
"fr:Saucisson-de-porc-fumee-a-cuire",
"fr:Serac",
"fr:Sodas au cola light",
"de:Salat",
"de:Schweinefleisch",
"Apricot jams",
"Banderillas",
"Cakes",
"Canned fishes",
"Cottage-cheese",
"Cracked marinated green olives",
"Cracked olives",
"Flavors",
"Fruits",
"Green cracked olives",
"Green pitted olives",
"Hams",
"Ice creams",
"Ice creams and sorbets",
"Low-fat yogurts",
"Margarines",
"Pies",
"Pineapple juices",
"Pitted olives",
"Potatoes",
"Rapeseed oils",
"Smoked fishes",
"Soy milks",
"Squeezed juices",
"Tunas",
"Vanilla yogurts",
"es:Mermeladas-y-confituras-de-cereza",
"es:Mermeladas-y-confituras-de-limon",
"es:Mermeladas-y-confituras-de-melocoton",
"fr:Beurres allégés",
"fr:Biscuits-au-beurre",
"fr:Biscuits feuilletés",
"fr:Biscuits-sale",
"fr:Boisson-au-soja",
"fr:Boisson-au-the",
"fr:Boisson-de-table-gazeifiee",
"fr:Boisson-lactee",
"fr:Boissons-au-the",
"fr:Boissons-aux-fruits",
"fr:Boissons chaudes instantanées",
"fr:Boissons énergétiques",
"fr:Boissons-instantanees",
"fr:Cenovis",
"fr:Chewing-gum",
"fr:Chocolats blancs",
"fr:Chorizos",
"fr:Condiments à tartiner",
"fr:Crackers",
"fr:Crèmes fraîches",
"fr:Eaux minérales naturelles",
"fr:Entrées et snacks surgelés",
"fr:Escargots",
"fr:Frites",
"fr:Frites surgelées",
"fr:Fromages au lait thermisé",
"fr:Fromages de Suisse",
"fr:Fromages-double-creme",
"fr:Fromages italiens",
"fr:Fruits en conserve",
"fr:Fruits-frais",
"fr:Galette-vegetale",
"fr:Galettes de céréales",
"fr:Galettes de riz",
"fr:Galettes de riz complet",
"fr:Gélifiants",
"fr:Huiles-de-soja",
"fr:Jambons blancs",
"fr:Joghurt",
"fr:Laits d'amande",
"fr:Laits de riz",
"fr:Laits frais",
"fr:Laits-micro-filtres",
"fr:Légumes bio",
"fr:Légumes surgelés",
"fr:Mayonnaise-en-bouteille",
"fr:Mayonnaise-en-tube",
"fr:Meringues",
"fr:Micro-ondes",
"fr:Mortadelle-suisse",
"fr:Moutardes",
"fr:Pate-a-gateau",
"fr:Pâtes à tartiner au chocolat",
"fr:Pates-penne",
"fr:Pates-penne-becs-de-plumes",
"fr:Petits-dejeuners-instantanes",
"fr:Poisons",
"fr:Poissons panés",
"fr:Pommes de terre Charlotte",
"fr:Pop-corn",
"fr:Preparation-a-base-de-legumes",
"fr:Preparation-de-fruits",
"fr:Raclettes",
"fr:Raisins secs",
"fr:Riz Basmati",
"fr:Riz cargo",
"fr:Riz long grain",
"fr:Sauces-aux-herbes",
"fr:Saucisse-de-porc",
"fr:Saumon-seche",
"fr:Saumons fumés",
"fr:Sel-aux-herbes",
"fr:Semoule-de-ble-dur",
"fr:Semoule-de-mais",
"fr:Semoule-lactee-pour-enfants",
"fr:Sirops",
"fr:Sodas au cola sans caféine",
"fr:Spaghetti",
"fr:Spatzli",
"fr:Stracciatella",
"fr:Tablettes de chocolat",
"fr:Tartes salées",
"fr:Tofu",
"fr:Viandes de boeuf",
"fr:Yaourt-a-la-mangue",
"fr:Yaourt-mocca"];
