var categoriesTags = [

"Produits laitiers",
"Matières grasses",
"Matières grasses végétales",
"Huiles",
"Huiles d'olive",
"Yaourts",
"Boissons",
"Huiles d'olive vierges extra",
"Epicerie",
"Confiseries",
"Légumes",
"Végétaux et dérivés",
"Chocolats",
"es:Untables vegetales",
"es:Mermeladas-y-confituras",
"es:Untables",
"es:Untables-dulces",
"Vinaigres",
"Condiments",
"Biscuits",
"Plats préparés",
"Viandes",
"Produits à tartiner",
"Petit-déjeuners",
"Conserves",
"Fromages",
"es:Mermeladas-y-confituras-de-frutas",
"Boissons gazeuses",
"Surgelés",
"Pâtes alimentaires",
"es:Endulzantes",
"es:Miel",
"Produit-de-boulangerie",
"Yaourts aux fruits",
"Sauces",
"es:",
"Chocolats Suisse",
"Légumes en conserve",
"Charcuteries",
"es:Azafrán",
"es:Especias",
"Pickles de légumes",
"Pickles",
"Produits à tartiner sucrés",
"Biscuiterie",
"Céréales",
"Crèmes",
"Poissons",
"Laits",
"Produits de la mer",
"Sodas",
"Chocolats noirs",
"Yaourts aromatisés",
"Eaux",
"Apéritif",
"Chocolats au lait",
"Matières grasses animales",
"Beurres",
"Fromages de vache",
"Olives",
"Riz",
"Pâtes à tartiner",
"Pâtes sèches",
"Preparation-a-base-de-viande",
"Sodas au cola",
"Viandes de porc",
"Chips et frites",
"Olives vertes",
"Produits à tartiner salés",
"Barres",
"Fromages à pâte fraîche",
"Fromages à tartiner",
"Lasagnes préparées",
"Plats cuisinés surgelés",
"Saucissons",
"Thés glacés",
"Fruits secs",
"Frais",
"Jus de fruits",
"Jus et nectars de fruits",
"Saucisses",
"Beurres pasteurisés",
"Chips",
"Eaux gazeuses",
"Fromages à pâte fondue",
"Pâtes à tartiner aux noisettes",
"Pâtes fraîches",
"Plats préparés en conserve",
"Fromages de France",
"Green whole olives",
"Boissons chaudes",
"Fromages industriels",
"Confitures",
"Olives marinées",
"Plats à base de viande",
"Mixed pickles",
"Yaourts au lait de brebis",
"Epices",
"Whole olives",
"es:Mermeladas-y-confituras-de-citricos",
"es:Mermeladas-y-confituras-de-flores",
"es:Mermeladas-y-confituras-de-higos",
"es:Mermeladas-y-confituras-de-petalos-de-rosas",
"Assaisonnements",
"Barres chocolatées",
"Barres de céréales",
"Biscuits au chocolat",
"Biscuits diététiques",
"Chocolats avec amandes",
"Laits demi-écrémés",
"Laits végétaux",
"Pates",
"Petits beurres",
"Plats préparés à réchauffer au micro-ondes",
"Ravioli",
"Sauces salades",
"The-froid",
"Viande-porc-salee",
"de:Kartoffelchips",
"Produits panés",
"Boissons light",
"Sodas light",
"Additifs alimentaires",
"Légumes frais",
"Jus d'orange",
"Pâtisseries",
"Saumons",
"Sels",
"Whole marinated green olives",
"es:Mermeladas-y-confituras-de-cebolla",
"es:Mermeladas-y-confituras-de-manzana",
"es:Mermeladas-y-confituras-de-naranja",
"es:Mermeladas-y-confituras-de-peras",
"es:Mermeladas-y-confituras-de-verduras-y-hortalizas",
"es:Mermeladas-y-confituras-multifruta",
"es:Patés vegetales",
"Biscuit-aux-cereales",
"Bonbons",
"Bouillon-en-cube",
"Cabillauds",
"Cafe-solube",
"Cafés",
"Cafés en poudre",
"Chocolats en poudre",
"Chocolats noirs extra fin",
"Choucroute-cuite",
"Colins",
"Crèmes entières",
"Eaux minérales",
"Fromages pasteurisés",
"Laits entiers",
"Légumes secs",
"Mayonnaises",
"Mozzarella",
"Raviolis en conserve",
"Riz pour risotto",
"Salamis",
"Sauces tomate",
"Saucisse-a-rotir",
"Saucisson-de-porc-fumee-a-cuire",
"Serac",
"Sodas au cola light",
"de:Salat",
"de:Schweinefleisch",
"Confitures d'abricot",
"Banderillas",
"Gâteaux",
"Poissons en conserve",
"en:Cottage-cheese",
"Cracked marinated green olives",
"Cracked olives",
"Arômes",
"Fruits",
"Green cracked olives",
"Olives vertes dénoyautées",
"Jambons",
"Glaces",
"Glaces et sorbets",
"Yaourts allégés en matière grasse",
"Margarines",
"Tartes",
"Jus d'ananas",
"Olives dénoyautées",
"Pommes de terre",
"Huiles de colza",
"Poissons fumés",
"Laits de soja",
"Jus de fruits 100% pur jus",
"Thons",
"Yaourts vanille",
"es:Mermeladas-y-confituras-de-cereza",
"es:Mermeladas-y-confituras-de-limon",
"es:Mermeladas-y-confituras-de-melocoton",
"Beurres allégés",
"Biscuits-au-beurre",
"Biscuits feuilletés",
"Biscuits-sale",
"Boisson-au-soja",
"Boisson-au-the",
"Boisson-de-table-gazeifiee",
"Boisson-lactee",
"Boissons-au-the",
"Boissons-aux-fruits",
"Boissons chaudes instantanées",
"Boissons énergétiques",
"Boissons-instantanees",
"Cenovis",
"Chewing-gum",
"Chocolats blancs",
"Chorizos",
"Condiments à tartiner",
"Crackers",
"Crèmes fraîches",
"Eaux minérales naturelles",
"Entrées et snacks surgelés",
"Escargots",
"Frites",
"Frites surgelées",
"Fromages au lait thermisé",
"Fromages de Suisse",
"Fromages-double-creme",
"Fromages italiens",
"Fruits en conserve",
"Fruits-frais",
"Galette-vegetale",
"Galettes de céréales",
"Galettes de riz",
"Galettes de riz complet",
"Gélifiants",
"Huiles-de-soja",
"Jambons blancs",
"Joghurt",
"Laits d'amande",
"Laits de riz",
"Laits frais",
"Laits-micro-filtres",
"Légumes bio",
"Légumes surgelés",
"Mayonnaise-en-bouteille",
"Mayonnaise-en-tube",
"Meringues",
"Micro-ondes",
"Mortadelle-suisse",
"Moutardes",
"Pate-a-gateau",
"Pâtes à tartiner au chocolat",
"Pates-penne",
"Pates-penne-becs-de-plumes",
"Petits-dejeuners-instantanes",
"Poisons",
"Poissons panés",
"Pommes de terre Charlotte",
"Pop-corn",
"Preparation-a-base-de-legumes",
"Preparation-de-fruits",
"Raclettes",
"Raisins secs",
"Riz Basmati",
"Riz cargo",
"Riz long grain",
"Sauces-aux-herbes",
"Saucisse-de-porc",
"Saumon-seche",
"Saumons fumés",
"Sel-aux-herbes",
"Semoule-de-ble-dur",
"Semoule-de-mais",
"Semoule-lactee-pour-enfants",
"Sirops",
"Sodas au cola sans caféine",
"Spaghetti",
"Spatzli",
"Stracciatella",
"Tablettes de chocolat",
"Tartes salées",
"Tofu",
"Viandes de boeuf",
"Yaourt-a-la-mangue",
"Yaourt-mocca"];
