var labelsTags = [

"Végétarien",
"es:Negra",
"Végétalien",
"Empreinte carbone",
"Bio",
"Utz-certified",
"CH-BIO-006",
"Bio européen",
"es:Vegetalien",
"es:Vegetarien",
"Pêche durable",
"Pêche durable MSC",
"Oic",
"Commerce équitable",
"M-bio",
"Aha",
"Max Havelaar",
"De-la-region",
"Bio-dynamie",
"Demeter",
"Fairtrade International",
"Point Vert",
"IGP",
"AB Agriculture Biologique",
"Eco-emballages",
"Ip-suisse",
"Leger",
"de:Bio",
"de:Bio-dynamie",
"de:Bio-suisse",
"de:Naturafarm",
"FSC",
"Sans gluten",
"Sans caféine",
"Sans colorants",
"Sans OGM",
"es:Negras",
"AOC",
"Bio7-initiative",
"Biosuisse",
"Ch-igp-038",
"Fromages-a-pate-molle-a-croute-naturelle",
"Fromages-au-lait-thermise",
"Fromages-de-suisse",
"Fromages-de-vache",
"Fsc-emballage",
"Ketchup",
"Labels de distributeurs",
"Naturaplan",
"Pro-montagna",
"Produits-laitiers",
"Sans-ajout-d-exhausteur-de-gout",
"Sans-conservateur-artificiel",
"Testé par le panel test Carrefour",
"Tomate",
"Weightwatchers"];
