var storesTags = [

"Auchan",
"Bio-kalt",
"Boutique-cailler",
"Carrefour",
"Coop",
"Denner",
"Distributeur-automatique",
"Epicerie-de-le-vaud",
"Ikea",
"Intermarche",
"Le-marche-des-corbeaux",
"Leclerc",
"M-p-restaurants-at-cicg",
"Magasin-de-la-chocolaterie-villars-route-de-la-fonderie-2-1701-fribourg-suisse",
"Mcdonald-s",
"Migros",
"Migros-nyon",
"Milenium",
"Musee-du-blonay-chamby",
"Nyon",
"Okcon-2013",
"Pharmacie",
"Reformhaus-muller",
"Suisse",
"Tesco",
"Www-virgenextra-com"];
