var statusTags = [

"A-completar",
"A compléter",
"A vérifier",
"Brands-to-be-completed",
"Caracteristicas-a-completar",
"Caracteristicas-completadas",
"Caractéristiques à compléter",
"Caractéristiques complétées",
"Catégories à compléter",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Complete",
"Date limite à compléter",
"Date limite complétée",
"Emballage à compléter",
"Envase-a-completar",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Fecha-limite-de-consumo-a-completar",
"Fecha-limite-de-consumo-agregada",
"Imagenes-a-agregar",
"Imagenes-a-validar",
"Imagenes-agregadas",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingredientes-a-completar",
"Ingredientes-completados",
"Ingrédients à compléter",
"Ingredients-completed",
"Ingrédients complétés",
"Ingredients-to-be-completed",
"Marques à compléter",
"Nom du produit à compléter",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos à envoyer",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos validées",
"Product-name-to-be-completed",
"Quantité à compléter",
"Quantity-to-be-completed",
"To-be-checked",
"To-be-completed",
"Valores-nutricionales-a-completar",
"Valores-nutricionales-completados"];
