var categoriesTags = [

"Dairies",
"Groceries",
"Yogurts",
"fr:Sauces",
"Biscuits",
"Spreads",
"Breakfasts",
"Milks",
"Beverages",
"Candies",
"Chocolates",
"Condiments",
"Frozen foods",
"Meals",
"Sweet spreads",
"fr:Apéritif",
"fr:Barres",
"fr:Barres de céréales",
"fr:Laits végétaux",
"fr:Mayonnaises",
"fr:Pâtes à tartiner",
"de:Kartoffelchips",
"Animal fats",
"Butters",
"Carbonated drinks",
"Cereals",
"Cheeses",
"Chips and fries",
"Creams",
"Fats",
"Fishes",
"Flavors",
"Food additives",
"Fruit yogurts",
"Margarines",
"Meats",
"Olives",
"Pastas",
"Pickled vegetables",
"Pickles",
"Prepared meats",
"Rices",
"Salted spreads",
"Seafood",
"Sodas",
"Vanilla yogurts",
"Vegetable fats",
"Vegetables",
"Waters",
"fr:Biscuit-aux-cereales",
"fr:Biscuits-au-beurre",
"fr:Biscuits au chocolat",
"fr:Biscuits-sale",
"fr:Boissons-aux-fruits",
"fr:Bouillon-de-poule",
"fr:Cenovis",
"fr:Chips",
"fr:Chocolats en poudre",
"fr:Chorizos",
"fr:Colins",
"fr:Condiments à tartiner",
"fr:Crackers",
"fr:Crèmes entières",
"fr:Demi-margarine",
"fr:Fromages à pâte fraîche",
"fr:Fromages à tartiner",
"fr:Galette-vegetale",
"fr:Joghurt",
"fr:Laits d'amande",
"fr:Laits de riz",
"fr:Laits demi-écrémés",
"fr:Lasagnes préparées",
"fr:Microonde",
"fr:Moutardes",
"fr:Pates",
"fr:Pâtes à tartiner aux noisettes",
"fr:Plats cuisinés surgelés",
"fr:Pop-corn",
"fr:Riz long grain",
"fr:Sauces salades",
"fr:Sauces tomate",
"fr:Saucissons",
"fr:Spatzli",
"fr:Stracciatella",
"fr:Thes-glaces-au-citron",
"fr:Tofu",
"fr:Yaourt-a-la-mangue",
"fr:Yaourt-mocca"];
