var categoriesTags = [

"Dairies",
"Groceries",
"Sauces",
"Beverages",
"Yogurts",
"Vegetables",
"Christmas-pudding",
"Candies",
"Cheeses",
"Chocolates",
"Fruits",
"Canned foods",
"Fats",
"Wines",
"Fresh vegetables",
"Animal fats",
"Chicken",
"Breads",
"Butters",
"Meats",
"Alcoholic drinks",
"Seafood",
"Cereals",
"Ready-meals",
"Red wines",
"Fishes",
"Beef",
"Dark-chocolate",
"Pork",
"Beers",
"Eggs",
"Fresh-fruits",
"Milks",
"Prepared meats",
"Rices",
"Tomatoes",
"Dressing",
"Fruit juices",
"Fruit juices and nectars",
"Mushrooms",
"Spreads",
"Vegetables and derived products",
"White wines",
"Fresh-mushrooms",
"Pastas",
"Salad",
"Berries",
"Carbonated drinks",
"Hams",
"Pork-meat",
"Pork-pies",
"Sodas",
"Sugars",
"Ketchup",
"Beef-meat",
"Biscuits",
"Breakfasts",
"Herbs",
"Lamb",
"Salted-butter",
"Spices",
"Sweet spreads",
"Sweets",
"Cola",
"Condiments",
"Creams",
"Crisps",
"Jams",
"Unsalted-butter",
"Vegetable fats",
"White-bread",
"Blueberries",
"Canned fishes",
"Coconut-milk",
"Coffee",
"Creme-fraiche",
"Flours",
"Food-colouring",
"Fresh-herbs",
"Grapes",
"Lamb-meat",
"Meals",
"Milk-chocolates",
"Pies",
"Pork-pie",
"Salmons",
"Semi-skimmed-milk",
"Sliced-white-bread",
"Tunas",
"Vegetable oils",
"Whole-milk",
"Broccoli",
"Cabbage",
"Canned tunas",
"Chicken-meat",
"Citrus",
"Cow Cheeses",
"Curry-paste",
"Dried fruits",
"French-red-wine",
"Frozen foods",
"Goat-s-cheese",
"Hard liquors",
"Herbal teas",
"Hot drinks",
"Icing-sugar",
"Meat-pie",
"Mustard",
"Nuts",
"Parmesan-cheese",
"Pate",
"Pizza",
"Poultry",
"Raw",
"Salads",
"Sandwich",
"Sausages",
"Smoked-salmon",
"Soluble-coffee",
"Teas",
"Tropical fruits",
"fr:Chocolats au lait",
"fr:Chocolats noirs",
"Apples",
"Asparagus",
"Australian-red-wine",
"Bacon",
"Canned-meat",
"Cauliflower",
"Chicken-breast",
"Chilean-white-wine",
"Chips and fries",
"Cured-meat",
"Dark-chocolates",
"Desserts",
"French cheeses",
"Fresh",
"Fresh-salads",
"Fromage-frais",
"Frozen-vegetables",
"Gammon",
"Ice creams",
"Ice creams and sorbets",
"Industrial cheese",
"Insects",
"Lemons",
"Mint-sauce",
"Muesli",
"Orange juices",
"Pastry-dough",
"Pesto",
"Pitenza-tomatoes",
"Pizzas",
"Plums",
"Pork-chops",
"Sandwich-spread",
"Sauvignon-blanc",
"Seasoning",
"Self-raising-flour",
"Skimmed-milk",
"Soups",
"Spaghetti",
"Stilton",
"Sugarfree-gum",
"Thai-rice",
"Turkey",
"Vanilla",
"Vanilla-extract",
"Vegetable rods",
"Vinegars",
"Wheat flours",
"Almonds",
"fr:Apéritif",
"Camemberts",
"fr:Camemberts pasteurisés",
"fr:Fromages à pâte molle à croûte fleurie",
"fr:Fromages pasteurisés",
"fr:Pates",
"fr:Pâtes sèches",
"fr:Spaghetti",
"",
"Anchovy",
"Anchovy-paste",
"Ants",
"Aperitifs",
"Apple-and-pear-juices",
"Apple-juice-from-concentrate",
"Apple juices",
"Apple-pie",
"Apricots",
"Australian-white-wine",
"Avocados",
"Baby-sanmarzano-tomatoes",
"Back-bacon",
"Baked-beans",
"Baking-powder",
"Balsamic vinegars",
"Bananas",
"Basmati-rice",
"Beans",
"Beef-dripping",
"Beef-mince",
"Blackberries",
"Blue-veined cheeses",
"Blueberry-jam",
"Broccoli-cauliflower",
"Cabbages",
"Cacao",
"Cake-icing",
"Cakes",
"Californian-red-wines",
"Camenbert-cheese",
"Canned-clams",
"Canned-fruits",
"Canned Vegetables",
"Capers",
"Caramel-dessert",
"Carbonated-sodas",
"Caster-sugar",
"Cauliflowers",
"Chardonnay",
"Cheddar",
"Cherry-tomatoes",
"Chewing-gum",
"Chicken-breasts",
"Chicken-eggs",
"Chicken-tikka-masala",
"Chicken-tikka-masala-with-spiced-basmati-rice",
"Chickpeas",
"Chilli",
"Chilli-sauce",
"Chocolate-biscuits",
"Clams",
"Cocoa-powder",
"Cod",
"Cod-fillets",
"Cola-sodas",
"Confectionery",
"Coriander-seeds",
"Cornichons",
"Cotes-du-rhone",
"Courgettes",
"Crackers",
"Cream-cheese",
"Crickets",
"Croissants",
"Crustaceans",
"Cucumbers",
"Cumberland-sausages",
"Cured-fish",
"Cured-pork",
"Cured-pork-loin",
"Custard",
"Custard-apples",
"Dairy-cream",
"Dairy-drinks",
"Dates",
"Dehydrated-soup",
"Dijon-mustard",
"Double-concentrate-tomato-puree",
"Dressings",
"Ducks",
"Easy-to-cook-chicken-breasts",
"Egg-white-powder",
"Emmental-cheese",
"Emmentaler",
"En-gb-cornflour",
"En-us-corn-starch",
"Energy-drinks",
"Enoki-mushrooms",
"Fine-beans",
"Fish fillets",
"Flaked-almonds",
"Food-coulouring",
"French-white-wine",
"French-white-wines",
"Fresh-chicken",
"Fresh-meat",
"Fresh-tomatoes",
"Fruit yogurts",
"Fruited-yogurts",
"Gelatine",
"Genio-tomatoes",
"Gherkins",
"Ginger",
"Ginger-beer",
"Goats-butter",
"Granulated-sugar",
"Green-beans",
"Green-curry-paste",
"Green olives",
"Green pitted olives",
"Ground-almonds",
"Gruyere-cheese",
"Gum",
"Haggis",
"Hot-dog",
"Jelly",
"Juice",
"Juice-drink",
"Juice-drinks",
"Juices",
"Lard",
"Leeks",
"Lemongrass-paste",
"Limes",
"Loire-valley-white-wine",
"Low-fat yogurts",
"Mackerel",
"Mackerel-fillets-in-sunflower-oil",
"Mackerels",
"Merlot",
"Mild-cheddar",
"Milk-chocolate",
"Mince-pies",
"Mints",
"Mussels",
"Nans",
"Oil",
"Oils",
"Olives",
"Onions",
"Orange-and-pineapple-juices",
"Orange-blossom-water",
"Orange-juice-from-concentrate",
"Oyster-mushrooms",
"Oyster-sauce",
"Pak-choi",
"Parsnips",
"Pastries",
"Peach-apricot",
"Peanut-butter",
"Piccolo-tomatoes",
"Pickled vegetables",
"Pickles",
"Pineapple",
"Pinot-grigio",
"Pitted olives",
"Pizza-bases",
"Pork-bacon",
"Pork-loin",
"Pork-mince",
"Pork-sausages",
"Potato-chips",
"Poultries",
"Prawns",
"Prepared-chicken",
"Processed-cheese",
"Products sold before year 2000",
"Products-sold-in-the-years-1990",
"Prune-juice",
"Puff-pastry-dough",
"Quiche",
"Radish",
"Rasberries",
"Raspberry",
"Ratatouille",
"Ready-meal",
"Red-curry-paste",
"Red-grapes",
"Rhubarb",
"Roast-ham",
"Salt-and-malt-vinegar-crisps",
"Salt-and-vinegar-crisps",
"Salts",
"Sancerre",
"Sandiwch",
"Sandwiches",
"Sardines",
"Sardines-in-brine",
"Shiraz-wine",
"Shortccrust-pastry-dough",
"Shortcrust-pastry",
"Snacks",
"Snails",
"Soft-cheese",
"Soy-sauce",
"Soya-drink",
"Spearmint-sugarfree-gum",
"Spring-onions",
"Steak-and-ale-pies",
"Steak-pie",
"Strawberries",
"Strawberry",
"Strawberry-jam",
"Strawberry yogurts",
"Superfood",
"Swede",
"Sweetelle-tomatoes",
"Tartare-sauce",
"Teriyaki-sauce",
"Tomato-puree",
"Unslated-butter",
"Unsmoked-back-bacon",
"Vegetable-fat-spread",
"Vodka",
"Watermelons",
"White-chocolates",
"Wholegrain-mustard",
"Wholegrains",
"Worcestershire-sauces",
"Yeast",
"Yeast-extract-spreads",
"Yogurt-drink",
"es:Alimentos estimulantes",
"es:Cacaos y chocolates",
"fr:Bières blondes",
"fr:Biscuits secs",
"fr:Boisson-rafraichissante",
"fr:Bonbons-a-la-menthe",
"fr:Chicken",
"fr:Chips",
"fr:Chocolats blancs",
"fr:Chocolats noirs extra fin",
"fr:Coconut-cream",
"fr:Coconut-milk",
"fr:Coqs",
"fr:Crackers",
"fr:Eaux-de-vie",
"fr:Farines de maïs",
"fr:Financiers",
"fr:Flocons-d-avoine",
"fr:Frites",
"fr:Frites surgelées",
"fr:Fromages à pâte pressée cuite",
"fr:Haricots",
"fr:Jus-de-citron",
"fr:Jus-de-pomme-et-de-mangue",
"fr:Jus-de-pomme-et-de-poire",
"fr:Mollusques",
"fr:Pain-a-l-ail",
"fr:Pains croustillants",
"fr:Pâtes à tartiner",
"fr:Pates-fusilli",
"fr:Penne",
"fr:Plats préparés en conserve",
"fr:Poulet-korma",
"fr:Ready-meals",
"Rums",
"fr:Sauces au soja",
"fr:Sauces Pesto Rosso",
"fr:Sauces pour pâtes",
"fr:Sodas au cola",
"fr:Tablettes de chocolat",
"it:Snacks"];
