var citiesTags = [

"Ancenis (Loire-Atlantique, France)",
"Andrézieux-Bouthéon (Loire, France)",
"Biars-sur-Cère (Lot, France)",
"Carhaix-Plouguer (Finistère, France)",
"Castanet-Tolosan (Haute-Garonne, France)",
"Changé (Mayenne, France)",
"Clamart (Hauts-de-Seine, France)",
"Corcieux (Vosges, France)",
"Cuincy (Nord, France)",
"Dole (Jura, France)",
"Domfront (Orne, France)",
"Douarnenez (Finistère, France)",
"Dunkerque (Nord, France)",
"Ferrières-en-Bray (Seine-Maritime, France)",
"Grigny (Essonne, France)",
"Hesdin-l'Abbé (Pas-de-Calais, France)",
"Isigny-sur-Mer (Calvados, France)",
"Lisieux (Calvados, France)",
"Oloron-Sainte-Marie (Pyrénées-Atlantiques, France)",
"Pacé (Orne, France)",
"Pennes-Mirabeau (Bouches-du-Rhône, France)",
"Ploudalmézeau (Finistère, France)",
"Retiers (Ille-et-Vilaine, France)",
"Rians (Cher, France)",
"Strasbourg (Bas-Rhin, France)",
"Val-de-Meuse (Haute-Marne, France)"];
