var labelsTags = [

"Assured Food Standards",
"Vegetarian",
"Organic",
"Soil Association Organic",
"EU Organic",
"Gluten-free",
"Gb-org-05",
"Fair trade",
"Fairtrade International",
"",
"Vegan",
"Pl-eko-07",
"Wheat-free",
"No milk",
"Tesco Nurture",
"British Lion Quality",
"Halal",
"Organic-soil-association",
"Proterra-certified",
"Rainforest Alliance",
"Raw",
"The-prince-s-countryside-fund",
"British-dental-health-foundation-approved",
"Carbon footprint",
"Free-from-gluten",
"Freedom Food",
"FSC",
"Gb-org-02",
"Green Dot",
"Irish-dental-association-approved",
"No alcohol",
"Omsco",
"Pefc",
"PGI",
"Sustainable fishery",
"Sustainable Seafood MSC",
"Vegetarian Society",
"fr:Eco-emballages",
"100% natural",
"Aoc",
"Appelation-d-origine-protegee",
"Assure-food-standards",
"Carbon-trust-reducing-co2-label",
"Cholesterol-lowering",
"Class-a-eggs",
"Cold-processed",
"DE-ÖKO-007",
"Denominación de Origen",
"Denominacion-de-origen-califada",
"Eco-emballages",
"Es-12-00215-bi-ce",
"Free-from-dairy",
"Free-from-egg",
"Free-from-milk",
"Free-from-wheat",
"Free-range",
"Fsc-mix-paper-made-from-responsible-sources-fsc-c008015",
"Great-gold-taste-2012",
"High fibres",
"High proteins",
"Ie-org-02",
"Laid-in-britain",
"Mafra-korea-non-pesticide",
"Max Havelaar",
"Medaille-d-argent-vins-de-bordeaux-2013",
"NL-BIO-01",
"No-added-msg",
"No-artificial-colours",
"No-artificial-flavourings-colours-or-preservative",
"No-artificial-preservatives",
"No-carbs-per-serving",
"No eggs",
"No lactose",
"No sugar",
"Non-gmo-soya",
"Nut-free",
"Nuts-free",
"Point-vert",
"Recipe-by-michel-roux",
"Restricted-designation-of-origin",
"Rspca-monitored",
"Salt-free",
"Suitable for diabetics",
"Suitable-for-freezing",
"Sustainable-non-ogm-soya",
"Taste-tested-by-customers",
"Utz-certified",
"Wholegrains",
"fr:Lait-collecte-dans-nos-fermes-selectionnees"];
