var categoriesTags = [

"Dairies",
"Beverages",
"Almond-milk",
"Cereals",
"Dried fruits",
"Milks",
"Nuts",
"Almonds",
"Biscuits",
"Candies",
"Cookies",
"Fruit yogurts",
"Herbal teas",
"Hot drinks",
"Teas",
"Waters",
"Yogurts",
"Breads",
"Carbonated drinks",
"Cheeses",
"Chocolates",
"Groceries",
"Low-fat yogurts",
"Peanut-butter",
"Sandwiches",
"Sauces",
"Wafers",
"Yaourts",
"Apple juices",
"Baked-beans",
"Bananas",
"Breakfasts",
"Brownie",
"Cakes",
"Canned-meat",
"Carbonated-sodas",
"Chocolate-chip-cookie",
"Concentrated apple juices",
"Concentrated fruit juices",
"Cottage-cheese",
"Diet-coke-lime",
"Eggs",
"Energy-drinks",
"Fruit juices",
"Fruit juices and nectars",
"Fruits",
"Ginseng",
"Green teas",
"Lollipops",
"Muesli",
"Oatmeal",
"Organic-eggs",
"Precision-instruments",
"Pretzels",
"Processed-cheese-product-in-a-can",
"Protein-bar",
"Sodas",
"Sweet-potatoes",
"Tortilla-chips",
"Tropical fruits",
"Turkey-breast",
"Vegetables",
"Vegetables and derived products",
"Vegetarian-mock-meat",
"Wholegrains",
"fr:Ailes-de-poulet-epicees",
"fr:Bonbons",
"fr:Carottes",
"fr:Cheeseburger",
"fr:Chips-au-mais",
"fr:Eaux gazeuses",
"fr:Eaux minérales",
"fr:Eaux minérales gazeuses",
"fr:Hamburgers",
"fr:Nuggets-de-poulet"];
