var labelsTags = [

"Organic",
"Carbon footprint",
"Gluten-free",
"USDA Organic",
"Vegan",
"Vegetarian",
"0g-trans-fat",
"1% for the planet",
"100-pure-ginseng-no-sugar-added-guarantee",
"100-whole-grain",
"American-heart-assn-certified",
"American-human",
"Certified-by-oregon-tilth",
"Cholesteral-free",
"Class-a-eggs",
"Gelatin-free",
"Gluen-free",
"High fibres",
"High proteins",
"Humane-farming",
"No lactose",
"No milk",
"No preservatives",
"No-rbst",
"No sugar",
"Nut-free",
"Rainforest Alliance",
"Salt-free",
"Wheat-free",
"Wholegrains",
"fr:Ksa-kosher",
"fr:Qai-organic-certfied-usa"];
