var storesTags = [

"Alara-health-store",
"Asda",
"Food-wine",
"Fred-meyer",
"Freres-tang",
"Fuddruckers",
"Heb-grocery",
"Mcdonald-s",
"Monoprix",
"Ninety-nine-restaurant",
"Prospectors",
"Safeway",
"Score",
"Star-market",
"Stop-and-shop",
"Von-s",
"Walmart",
"Www-harney-com",
"Wyndham-boston-andover-hotel"];
