var categoriesTags = [

"Dairies",
"Milks",
"Beverages",
"Herbal teas",
"Hot drinks",
"en:Peanut-butter",
"Teas",
"en:Baked-beans",
"en:Banana",
"Biscuits",
"Breads",
"en:Brownie",
"Candies",
"Carbonated drinks",
"Cheeses",
"en:Chocolate-chip-cookie",
"Cookies",
"Green teas",
"en:Oatmeal",
"en:Organic-eggs",
"en:Precision-instruments",
"en:Pretzels",
"en:Sweet-potatoes",
"en:Tortilla-chips",
"en:Turkey-breast",
"Waters",
"fr:Bonbons",
"fr:Eaux gazeuses",
"fr:Eaux minérales",
"fr:Eaux minérales gazeuses"];
