var ingredientsTags = [

"Almondmilk",
"Almonds",
"Alpha-tocopherol",
"Calcium-carbonate",
"Carrageenan",
"Cocoa",
"Dutch-process",
"Evaporated-cane-juice",
"Filtered-water",
"India-and-ceylon",
"Natural-flavor",
"Natural-flavors",
"Natural-vitamin-e",
"Organic-citrus-flavor",
"Organic-ginko",
"Organic-green-tea",
"Organic-lemon-grass",
"Organic-whole-grain-steel-cut-oats",
"Potassium-citrate",
"Sea-salt",
"Sunflower-lecithin",
"Superior-teas-from-darjeeling",
"Vitamin-a-palmitate",
"Vitamin-d2-and"];
