var categoriesTags = [

"Fats",
"Extra-virgin olive oils",
"Olive oils",
"Vegetable fats",
"Vegetable oils",
"Vegetables and derived products",
"es:Untables vegetales",
"Vinegars",
"es:Mermeladas-y-confituras",
"es:Untables",
"es:Untables-dulces",
"Pralinen",
"es:Mermeladas-y-confituras-de-frutas",
"es:Endulzantes",
"es:Miel",
"Condiments",
"Groceries",
"es:",
"es:Azafrán",
"es:Especias",
"Pickled vegetables",
"Pickles",
"Vegetables",
"Beverages",
"Dairies",
"Alcoholic drinks",
"Beers",
"Green olives",
"Olives",
"Frozen-desserts",
"Speiseeis-und-sorbets",
"Desserts",
"Frozen foods",
"Sorbets",
"Gefrorene-fruchte",
"Cheeses",
"Cow Cheeses",
"Green whole olives",
"Marinated olives",
"Mixed pickles",
"Whole olives",
"es:Mermeladas-y-confituras-de-citricos",
"es:Mermeladas-y-confituras-de-higos",
"fr:Camemberts",
"fr:Fromages à pâte molle à croûte fleurie",
"Peanut-butter",
"Soja-und-derivate",
"Meats",
"Prepared meats",
"Whole marinated green olives",
"Joghurte",
"es:Mermeladas-y-confituras-de-cebolla",
"es:Mermeladas-y-confituras-de-flores",
"es:Mermeladas-y-confituras-de-manzana",
"es:Mermeladas-y-confituras-de-naranja",
"es:Mermeladas-y-confituras-de-peras",
"es:Mermeladas-y-confituras-de-petalos-de-rosas",
"es:Mermeladas-y-confituras-de-verduras-y-hortalizas",
"es:Mermeladas-y-confituras-multifruta",
"es:Patés vegetales",
"fr:Fromages pasteurisés",
"",
"Alcopop",
"Cocktail-sauce",
"Cola",
"Fruchtetees",
"Garnelen",
"Gefrorene-beeren",
"Gefrorene-erdbeeren",
"Gefrorene-himbeeren",
"Gemuse-getranke",
"Himbeer-sorbets",
"Honig",
"Joghurt",
"Limonade",
"Mango-sorbets",
"Mate",
"Miel",
"Mischung-fur-falafel",
"Passionsfrucht-sorbets",
"Pasta-saucen",
"Pasteten-vegetarier",
"Pilsner",
"Risotto",
"Saucen",
"Senf",
"Snacks",
"Vodka",
"Zaziki",
"Zitronen-sorbets",
"Zuckerfreier-kaugummi",
"Animal fats",
"Banderillas",
"Breads",
"Butters",
"Canned foods",
"Carbonated drinks",
"Cracked marinated green olives",
"Cracked olives",
"Fishes",
"Green cracked olives",
"Green pitted olives",
"Hams",
"Meals",
"Meals with meat",
"Pastas",
"Pitted olives",
"Seafood",
"Sodas",
"en:Zucker",
"es:Mermeladas-y-confituras-de-cereza",
"es:Mermeladas-y-confituras-de-limon",
"es:Mermeladas-y-confituras-de-melocoton",
"fr:Bacon",
"fr:Beurres demi-sel",
"fr:Bières blondes",
"fr:Pates",
"fr:Pates-farcies",
"fr:Plats à base de viande bovine",
"fr:Plats préparés en conserve",
"fr:Purées d'amande",
"fr:Purées d'oléagineux",
"fr:Ravioli",
"fr:Raviolis au boeuf",
"fr:Raviolis en conserve",
"fr:Rehausseur-de-gout",
"fr:Viandes de porc",
"it:Crema-di-yogurt"];
