var labelsTags = [

"Vegetarisch",
"Vegan",
"es:Negra",
"es:Vegetalien",
"es:Vegetarien",
"CO2-Emissionen",
"Ökologische Produkt",
"EU Organic",
"Utz-certified",
"DE-ÖKO-001",
"Ohne Gentechnik",
"Ab",
"Bio",
"Bio-europeen",
"Glutenfrei",
"Msc-org",
"en:Bio7initiative",
"DE-ÖKO-003",
"DE-ÖKO-013",
"Fair trade",
"Fairtrade International",
"FSC",
"Grüne Punkt",
"No colorings",
"No preservatives",
"Rainforest Alliance",
"Vegan Society",
"es:Negras",
"fr:Cuisine-sans-huile-de-palme",
"fr:Eco-emballages",
"fr:Moins-de-1-de-sel",
"fr:Premium-beer",
"fr:Saveurs de l'Année",
"fr:Saveurs de l'Année 2011",
"fr:Saveurs de l'Année 2013",
"fr:Viande Bovine Française",
"fr:Viande Française"];
