var labelsTags = [

"Vegetarian",
"Vegan",
"es:Negra",
"es:Vegetalien",
"es:Vegetarien",
"Carbon footprint",
"Organic",
"EU Organic",
"de:Utz-certified",
"DE-ÖKO-001",
"No GMOs",
"de:Ab",
"de:Bio",
"de:Bio-europeen",
"de:Glutenfrei",
"de:Msc-org",
"Bio7initiative",
"DE-ÖKO-003",
"DE-ÖKO-013",
"Fair trade",
"Fairtrade International",
"FSC",
"Green Dot",
"No colorings",
"No preservatives",
"Rainforest Alliance",
"Vegan Society",
"es:Negras",
"fr:Cuisine-sans-huile-de-palme",
"fr:Eco-emballages",
"fr:Moins-de-1-de-sel",
"fr:Premium-beer",
"fr:Saveurs de l'Année",
"fr:Saveurs de l'Année 2011",
"fr:Saveurs de l'Année 2013",
"fr:Viande Bovine Française",
"fr:Viande Française"];
