var ingredientsTags = [

"Acidity-regulator",
"Dextrose",
"E262",
"E627",
"E631",
"Flavour-and-taste-substances",
"Flavouring-substances",
"Gum-arabic-gum-acacia",
"Maltodextrin",
"Monosodium-glutamate",
"Onion",
"Paprika",
"Paprika-concetration",
"Parsley",
"Potatoes",
"Salt",
"Sonflower-oil",
"Spices",
"Stabilizer",
"Sugar-powder",
"Sugars",
"Vegetable-oil",
"Yeast-concentration"];
