var statusTags = [

"A-completar",
"A-completer",
"A-verifier",
"Caracteristicas-a-completar",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Characteristics completed",
"Characteristics to be completed",
"Complet",
"Complete",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Expiration date completed",
"Expiration date to be completed",
"Fecha-limite-de-consumo-a-completar",
"Imagenes-a-validar",
"Imagenes-agregadas",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredientes-a-completar",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients-completes",
"Ingredients to be completed",
"Marcas-a-completar",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"Photos validated",
"Photos-validees",
"Quantite-a-completer",
"To be checked",
"To be completed",
"Valores-nutricionales-a-completar"];
