var categoriesTags = [

"Biscuits",
"Candies",
"Chocolates",
"Dairies",
"Beverages",
"Waffles",
"Yogurts",
"fr:Gaufrettes",
"Cheeses",
"Milks",
"Waters",
"Fats",
"Hot drinks",
"fr:Chocolats noirs",
"fr:Chocolats noirs extra fin",
"fr:Eaux minérales",
"fr:Eaux minérales naturelles",
"fr:Fromages fondus",
"fr:Laits demi-écrémés",
"fr:Laits UHT",
"ar:Choclate",
"Animal fats",
"Breads",
"Breakfasts",
"Butters",
"Cakes",
"Carbonated drinks",
"Chips",
"Chips and fries",
"Chocolate desserts",
"Cookies",
"Creams",
"Desserts",
"Eau-minerale",
"Fishes",
"Green teas",
"Herbal teas",
"Margarines",
"Meta-category",
"Seafood",
"Sodas",
"Stirred yogurts",
"Teas",
"Tunas",
"Vegetable fats",
"fr:Apéritif",
"fr:Biscottes",
"fr:Bonbons",
"fr:Cacao",
"fr:Cafés",
"fr:Chips",
"fr:Chocolats en poudre",
"fr:Crèmes dessert",
"fr:Crèmes dessert chocolat",
"fr:Crèmes fraîches",
"fr:Crèmes fraîches épaisses",
"fr:Crêpes",
"fr:Crêpes et galettes",
"fr:Fauffrette",
"fr:Gaufres fourrées",
"fr:Gaufrettes fourrées",
"fr:Genoise",
"fr:Laits concentrés",
"fr:Laits concentrés sucrés",
"fr:Médicaments",
"fr:Non alimentaire",
"fr:Vermicelle"];
