var additivesTags = [

"E1420 - Amidon acétylé",
"E14xx - Amidons modifiés",
"E150a - Caramels",
"E170 - Carbonate de calcium",
"E202 - Sorbate de potassium",
"E300 - Acide ascorbique",
"E322 - Lécithines",
"E330 - Acide citrique",
"E331 - Citrates de sodium",
"E336 - Tartrates de potassium",
"E339 - Orthophosphates de sodium",
"E410 - Farine de graines de caroube",
"E420 - Sorbitol",
"E422 - Glycérol",
"E450 - Sels métalliques de diphosphates",
"E450 - Sels métalliques de diphosphates",
"E452 - Polyphosphates",
"E471 - Mono- et diglycérides d'acides gras alimentaires",
"E472e - Ester Monoacéthyltartrique de mono- et diglycérides d'acides gras",
"E475 - Esters polyglycériques d'acides gras",
"E476 - Esters polyglycériques d'acides gras d'huile de ricin",
"E500 - Carbonates de sodium",
"E503 - Carbonates d'ammonium",
"E504 - Carbonates de magnésium",
"E950 - Acésulfame K",
"E951 - Aspartame"];
