var categoriesTags = [

"Dairies",
"Cheeses",
"Desserts",
"Animal fats",
"Biscuits",
"Breakfasts",
"Butters",
"Candies",
"Chips and fries",
"Chocolate desserts",
"Dried fruits",
"Fats",
"Fresh",
"Groceries",
"Jams",
"Meats",
"Prepared meats",
"Sauces",
"Spreads",
"Sweet spreads",
"fr:Apéritif",
"fr:Chips",
"fr:Crèmes dessert",
"fr:Crèmes dessert chocolat",
"fr:Desserts-lactes",
"fr:Desserts-lactes-au-chocolat",
"fr:Fruits au sirop",
"fr:Raclettes",
"fr:Salamis",
"fr:Saucissons"];
