var statusTags = [

"A-completar",
"A-completer",
"A-verifier",
"Brands to be completed",
"Caracteristicas-completadas",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Complet",
"Data-de-validade-a-completar",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Expiration date completed",
"Expiration date to be completed",
"Imagens-a-validar",
"Imagens-enviadas",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredientes-completados",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients-completes",
"Ingredients to be completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"Photos-validees",
"Product name to be completed",
"Quantite-a-completer",
"Quantity to be completed",
"To be completed",
"Valores-nutricionais-completados"];
