var categoriesTags = [

"Produits laitiers",
"Fromages",
"Desserts",
"Matières grasses animales",
"Biscuits",
"Petit-déjeuners",
"Beurres",
"Confiseries",
"Chips et frites",
"Desserts au chocolat",
"Fruits secs",
"Matières grasses",
"Frais",
"Epicerie",
"Confitures",
"Viandes",
"Charcuteries",
"Sauces",
"Produits à tartiner",
"Produits à tartiner sucrés",
"Apéritif",
"Chips",
"Crèmes dessert",
"Crèmes dessert chocolat",
"Desserts-lactes",
"Desserts-lactes-au-chocolat",
"Fruits au sirop",
"Raclettes",
"Salamis",
"Saucissons"];
