var statusTags = [

"A-completar",
"A compléter",
"A vérifier",
"Brands-to-be-completed",
"Caracteristicas-completadas",
"Caractéristiques à compléter",
"Caractéristiques complétées",
"Catégories à compléter",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Data-de-validade-a-completar",
"Date limite à compléter",
"Date limite complétée",
"Emballage à compléter",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Imagens-a-validar",
"Imagens-enviadas",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingredientes-completados",
"Ingrédients à compléter",
"Ingredients-completed",
"Ingrédients complétés",
"Ingredients-to-be-completed",
"Marques à compléter",
"Nom du produit à compléter",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos à envoyer",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos validées",
"Product-name-to-be-completed",
"Quantité à compléter",
"Quantity-to-be-completed",
"To-be-completed",
"Valores-nutricionais-completados"];
