var ingredientsTags = [

"Acid",
"Beeswax",
"Beetroot-red",
"Beta-carotene",
"Carnauba-wax",
"Colours",
"Critric-acid",
"E414",
"E418",
"Emulsifiar",
"Fruit-juices-from-concentrate",
"Gelling-agents",
"Glazing-agents",
"Glucose-syrup",
"Hydrogenated-vegetable-oil",
"Lemon",
"Natural-flavourings",
"Orange",
"Starch",
"Strawberry",
"Sucrose-esters-of-fatty-acids",
"Sugar"];
