var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Condiments",
"Fats",
"Groceries",
"Herbal teas",
"Hot drinks",
"Palm oils",
"Salts",
"Spices",
"Vegetable fats",
"Vegetable oils",
"Waters",
"Yaourts",
"Yaourts-nature",
"fr:Eaux gazeuses",
"fr:Infusions minceur",
"fr:Sels de table"];
