var categoriesTags = [

"Boissons",
"Boissons gazeuses",
"Condiments",
"Matières grasses",
"Epicerie",
"Infusions",
"Boissons chaudes",
"Huiles de palme",
"Sels",
"Epices",
"Matières grasses végétales",
"Huiles",
"Eaux",
"en:Yaourts",
"en:Yaourts-nature",
"Eaux gazeuses",
"Infusions minceur",
"Sels de table"];
