var statusTags = [

"A-completer",
"Caracteristiques-a-completer",
"Categories-a-completer",
"Categories-to-be-completed",
"Characteristics-to-be-completed",
"Date-limite-a-completer",
"Emballage-a-completer",
"Expiration-date-to-be-completed",
"Informations-nutritionnelles-completees",
"Ingredients-a-completer",
"Ingredients-to-be-completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos-envoyees",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validees",
"Quantite-a-completer",
"To-be-completed"];
