var categoriesTags = [

"Beverages",
"Candies",
"Fruit juices and nectars",
"Vegetables and derived products",
"Dairies",
"Fruit juices",
"Breakfasts",
"Cakes",
"Canned foods",
"Jams",
"Spreads",
"Sweet spreads",
"fr:Boisson-sucree-non-alcoolisee",
"Canned Vegetables",
"Cheeses",
"Concentrated fruit juices",
"Vegetables",
"fr:Bonbons",
"Biscuits",
"Carbonated drinks",
"Meals",
"Meats",
"Sodas",
"fr:Fromages blancs",
"Alcoholic drinks",
"Beers",
"Canned beans",
"Chocolates",
"Fresh",
"Fruit nectars",
"Groceries",
"Pineapple juices",
"Prepared meats",
"Squeezed juices",
"Squeezed pineapple juices",
"Yogurts",
"fr:Apéritif",
"fr:Legumes-secs-en-conserve",
"Chips and fries",
"Chocolate desserts",
"Concentrated orange juices",
"Cow Cheeses",
"Desserts",
"Drinkable yogurts",
"Fishes",
"French cheeses",
"Fruit sodas",
"Fruit yogurts",
"Herbal teas",
"Hot drinks",
"Mango nectars",
"Meta-category",
"Milks",
"Orange juices",
"Poultries",
"Sauces",
"Seafood",
"Spices",
"Sugars",
"Teas",
"Waters",
"fr:Achards",
"fr:Bières blondes",
"fr:Biscuits-meringues",
"fr:Boucherie",
"Camemberts",
"fr:Camemberts pasteurisés",
"fr:Chewing-gum",
"fr:Chips",
"fr:Chocolat-fourre-au-fruit",
"fr:Chocolats au lait",
"fr:Chocolats blancs",
"fr:Conserve-de-legumes-cuisines",
"fr:Dessert-lacte",
"fr:Eaux de sources",
"fr:Eaux minérales",
"fr:Echine-de-porc-assaisonnee",
"fr:Friandise",
"fr:Fromages à pâte molle à croûte fleurie",
"Canned cheeses",
"fr:Fromages pasteurisés",
"fr:Laits aromatisés",
"fr:Legumes-sec-en-conserve",
"fr:Limonades",
"fr:Melange-d-epices",
"fr:Mousses au chocolat",
"fr:Nectar-de-letchis",
"fr:Nectars-de-litchis",
"fr:Plats préparés surgelés",
"fr:Produit-au-citron",
"fr:Produit-au-sucre-de-canne",
"fr:Produits introuvables en Métropole",
"fr:Saucissons",
"fr:Saucissons à l'ail",
"fr:Sodas aux fruits exotiques",
"fr:Sucres blancs",
"fr:Sucres de canne",
"fr:Tablettes de chocolat",
"fr:Thés noirs",
"fr:Viandes de porc"];
