var categoriesTags = [

"Boissons",
"Confiseries",
"Jus et nectars de fruits",
"Végétaux et dérivés",
"Produits laitiers",
"Jus de fruits",
"Petit-déjeuners",
"Gâteaux",
"Conserves",
"Confitures",
"Produits à tartiner",
"Produits à tartiner sucrés",
"Boisson-sucree-non-alcoolisee",
"Légumes en conserve",
"Fromages",
"Jus de fruits à base de concentré",
"Légumes",
"Bonbons",
"Biscuits",
"Boissons gazeuses",
"Plats préparés",
"Viandes",
"Sodas",
"Fromages blancs",
"Boissons alcoolisées",
"Bières",
"Haricots en conserve",
"Chocolats",
"Frais",
"Nectars de fruits",
"Epicerie",
"Jus d'ananas",
"Charcuteries",
"Jus de fruits 100% pur jus",
"Jus d'ananas pur jus",
"Yaourts",
"Apéritif",
"Legumes-secs-en-conserve",
"Chips et frites",
"Desserts au chocolat",
"Jus d'orange à base de concentré",
"Fromages de vache",
"Desserts",
"Yaourts à boire",
"Poissons",
"Fromages de France",
"Sodas aux fruits",
"Yaourts aux fruits",
"Infusions",
"Boissons chaudes",
"Nectars de mangue",
"Méta-catégorie",
"Laits",
"Jus d'orange",
"Volailles",
"Sauces",
"Produits de la mer",
"Epices",
"Sucres",
"Thés",
"Eaux",
"Achards",
"Bières blondes",
"Biscuits-meringues",
"Boucherie",
"Camemberts",
"Camemberts pasteurisés",
"Chewing-gum",
"Chips",
"Chocolat-fourre-au-fruit",
"Chocolats au lait",
"Chocolats blancs",
"Conserve-de-legumes-cuisines",
"Dessert-lacte",
"Eaux de sources",
"Eaux minérales",
"Echine-de-porc-assaisonnee",
"Friandise",
"Fromages à pâte molle à croûte fleurie",
"Fromages en conserve",
"Fromages pasteurisés",
"Laits aromatisés",
"Legumes-sec-en-conserve",
"Limonades",
"Melange-d-epices",
"Mousses au chocolat",
"Nectar-de-letchis",
"Nectars-de-litchis",
"Plats préparés surgelés",
"Produit-au-citron",
"Produit-au-sucre-de-canne",
"Produits introuvables en Métropole",
"Saucissons",
"Saucissons à l'ail",
"Sodas aux fruits exotiques",
"Sucres blancs",
"Sucres de canne",
"Tablettes de chocolat",
"Thés noirs",
"Viandes de porc"];
