var categoriesTags = [

"Beverages",
"Fruit juices and nectars",
"Canned foods",
"Fruit juices",
"Vegetables",
"fr:Légumes en conserve",
"Candies",
"Dairies",
"Meals",
"Meats",
"Biscuits",
"Breakfasts",
"Carbonated drinks",
"Chocolates",
"Concentrated fruit juices",
"Fruit nectars",
"Groceries",
"Jams",
"Pineapple juices",
"Prepared meats",
"Sodas",
"Spreads",
"Squeezed juices",
"Squeezed pineapple juices",
"Sweet spreads",
"fr:Apéritif",
"fr:Haricots en conserve",
"fr:Legumes-secs-en-conserve",
"Alcoholic drinks",
"Beers",
"Cheeses",
"Chips and fries",
"Chocolate desserts",
"Concentrated orange juices",
"Cow Cheeses",
"Desserts",
"Fishes",
"Fruit sodas",
"Fruit yogurts",
"Herbal teas",
"Hot drinks",
"Mango nectars",
"Meta-category",
"Milks",
"Orange juices",
"Poultries",
"Seafood",
"Spices",
"Sugars",
"Teas",
"Waters",
"Yogurts",
"fr:Achards",
"fr:Biscuits-meringues",
"fr:Boucherie",
"fr:Camemberts",
"fr:Chewing-gum",
"fr:Chips",
"fr:Chocolat-fourre-au-fruit",
"fr:Chocolats au lait",
"fr:Chocolats blancs",
"fr:Conserve-de-legumes-cuisines",
"fr:Dessert-lacte",
"fr:Eaux de sources",
"fr:Eaux minérales",
"fr:Echine-de-porc-assaisonnee",
"fr:Friandise",
"fr:Fromages à pâte molle à croûte fleurie",
"fr:Fromages en conserve",
"fr:Fromages pasteurisés",
"fr:Laits aromatisés",
"fr:Legumes-sec-en-conserve",
"fr:Limonades",
"fr:Melange-d-epices",
"fr:Mousses au chocolat",
"fr:Nectar-de-letchis",
"fr:Nectars-de-litchis",
"fr:Plats préparés surgelés",
"fr:Produit-au-citron",
"fr:Produit-au-sucre-de-canne",
"fr:Produits introuvables en Métropole",
"fr:Sauces",
"fr:Saucissons",
"fr:Saucissons à l’ail",
"fr:Sodas aux fruits exotiques",
"fr:Sucres blancs",
"fr:Sucres de canne",
"fr:Tablettes de chocolat",
"fr:Thés noirs",
"fr:Viandes de porc"];
