var originsTags = [

"Afrique-du-sud",
"Bourmont",
"Bras-panon",
"Cadbury-france",
"Chine",
"Distributeur-dilletto-saint-gilles-ile-de-la-reunion",
"France",
"Ile-de-la-reunion",
"Ile-maurice",
"Importe-par-rennie-et-thony",
"Le-port",
"Leognan",
"Mafate",
"Saint-andre",
"Saint-denis",
"Saint-pierre",
"Sainte-anne",
"Sainte-marie",
"Sainte-suzanne",
"Suisse"];
