var categoriesTags = [

"Beverages",
"en:Raw",
"Wines",
"Breads",
"Cereals",
"en:Muesli",
"Red wines",
"Alcoholic drinks",
"Bee products",
"en:Cacao",
"Candies",
"en:Chicken-eggs",
"Chocolates",
"Desserts",
"Dried fruits",
"en:Eggs",
"Farming products",
"en:Herbs",
"Honeys",
"en:Jelly",
"en:Mussels",
"Nuts",
"en:Orange-juice-from-concentrate",
"en:Prepared-chicken",
"en:Superfood",
"White wines",
"en:Wholegrains",
"fr:Boisson-rafraichissante"];
