var statusTags = [

"A-completer",
"Brands to be completed",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Complete",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Empty",
"Expiration date completed",
"Expiration date to be completed",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients-completes",
"Ingredients to be completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be uploaded",
"Photos to be validated",
"Photos uploaded",
"Photos validated",
"Product name to be completed",
"Quantite-a-completer",
"Quantity to be completed",
"To be checked",
"To be completed",
"Vide"];
