var statusTags = [

"A-completer",
"Brands to be completed",
"Caracteristiques-a-completer",
"Categories-a-completer",
"Categories to be completed",
"Characteristics to be completed",
"Date-limite-a-completer",
"Emballage-a-completer",
"Empty",
"Expiration date to be completed",
"Informations-nutritionnelles-a-completer",
"Ingredients-a-completer",
"Ingredients to be completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-envoyer",
"Photos to be uploaded",
"Product name to be completed",
"Quantite-a-completer",
"Quantity to be completed",
"To be completed",
"Vide"];
