var categoriesTags = [

"Dairies",
"Yogurts",
"Beverages",
"Carbonated drinks",
"Sodas",
"Biscuits",
"Canned fishes",
"Canned foods",
"Fats",
"Fishes",
"Groceries",
"Milks",
"Seafood",
"Tunas",
"Vegetable fats",
"fr:Bouillon",
"fr:Thons pales",
"fr:Thons tropicaux",
"Breakfasts",
"Cereals",
"Condiments",
"Creams",
"Desserts",
"Dried fruits",
"Flours",
"Fresh",
"Maple syrups",
"Margarines",
"Mustard",
"Olive oils",
"Processed-cheese-product-in-a-can",
"Rices",
"Sauces",
"Soy milks",
"Spreads",
"Sweet spreads",
"Topping",
"Vanilla yogurts",
"Vegetable oils",
"Virgin olive oils",
"Waters",
"Wines",
"fr:Barres",
"fr:Barres de céréales",
"fr:Beurres-d-erable",
"fr:Boissons énergisantes",
"fr:Cererales-pour-petit-dejeuner",
"fr:Crèmes fraîches",
"fr:Eaux gazeuses",
"Ketchup",
"fr:Laits demi-écrémés",
"fr:Laits frais",
"fr:Laits-micro-filtres",
"fr:Laits végétaux",
"fr:Pâtes à tartiner",
"fr:Preparation-pour-desserts",
"fr:Produits-d-erable-biologique",
"fr:Raisins secs",
"fr:Raisins secs Sultanines",
"fr:Semoule",
"fr:Sodas au cola",
"fr:Thons albacore",
"fr:Thons listao",
"fr:Yaourts-0"];
