var categoriesTags = [

"Produits laitiers",
"Yaourts",
"Boissons",
"Boissons gazeuses",
"Sodas",
"Biscuits",
"Poissons en conserve",
"Conserves",
"Matières grasses",
"Poissons",
"Epicerie",
"Laits",
"Produits de la mer",
"Thons",
"Matières grasses végétales",
"Bouillon",
"Thons pales",
"Thons tropicaux",
"Petit-déjeuners",
"Céréales",
"Condiments",
"Crèmes",
"Desserts",
"Fruits secs",
"Farines",
"Frais",
"Sirops d'érable",
"Margarines",
"en:Mustard",
"Huiles d'olive",
"en:Processed-cheese-product-in-a-can",
"Riz",
"Sauces",
"Laits de soja",
"Produits à tartiner",
"Produits à tartiner sucrés",
"en:Topping",
"Yaourts vanille",
"Huiles",
"Huiles d'olive vierges",
"Eaux",
"Vins",
"Barres",
"Barres de céréales",
"Beurres-d-erable",
"Boissons énergisantes",
"Cererales-pour-petit-dejeuner",
"Crèmes fraîches",
"Eaux gazeuses",
"Ketchup",
"Laits demi-écrémés",
"Laits frais",
"Laits-micro-filtres",
"Laits végétaux",
"Pâtes à tartiner",
"Preparation-pour-desserts",
"Produits-d-erable-biologique",
"Raisins secs",
"Raisins secs Sultanines",
"Semoule",
"Sodas au cola",
"Thons albacore",
"Thons listao",
"Yaourts-0"];
