var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Canned fishes",
"Canned foods",
"Dairies",
"Fishes",
"Seafood",
"Sodas",
"Tunas",
"fr:Thons pales",
"fr:Thons tropicaux",
"Biscuits",
"Condiments",
"Creams",
"Dried fruits",
"Groceries",
"Maple syrups",
"Milks",
"en:Mustard",
"Waters",
"Wines",
"fr:Bouillon",
"fr:Crèmes fraîches",
"fr:Eaux gazeuses",
"fr:Laits de soja",
"fr:Laits végétaux",
"fr:Produits-d-erable-biologique",
"fr:Raisins secs",
"fr:Raisins secs Sultanines",
"fr:Semoule",
"fr:Sodas au cola",
"fr:Thons albacore",
"fr:Thons listao"];
