var statusTags = [

"A-completar",
"Cantidad-a-completar",
"Caracteristicas-a-completar",
"Caracteristicas-completadas",
"Categorias-a-completar",
"Categories to be completed",
"Characteristics to be completed",
"Envase-a-completar",
"Expiration date to be completed",
"Fecha-limite-de-consumo-a-completar",
"Fecha-limite-de-consumo-agregada",
"Imagenes-a-agregar",
"Imagenes-a-validar",
"Imagenes-agregadas",
"Ingredientes-a-completar",
"Ingredientes-completados",
"Ingredients to be completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos to be uploaded",
"Photos to be validated",
"Photos uploaded",
"To be completed",
"Valores-nutricionales-a-completar",
"Valores-nutricionales-completados"];
