var statusTags = [

"A completar",
"Cantidad a completar",
"Características a completar",
"Características completadas",
"Categorías a completar",
"Categories-to-be-completed",
"Characteristics-to-be-completed",
"Envase a completar",
"Expiration-date-to-be-completed",
"Fecha límite de consumo a completar",
"Fecha límite de consumo agregada",
"Imágenes a agregar",
"Imágenes a validar",
"Imágenes agregadas",
"Ingredientes a completar",
"Ingredientes completados",
"Ingredients-to-be-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"To-be-completed",
"Valores nutricionales a completar",
"Valores nutricionales completados"];
