var statusTags = [

"A-completar",
"A-completer",
"Caracteristicas-a-completar",
"Caracteristicas-completadas",
"Caracteristiques-completees",
"Characteristics completed",
"Date-limite-completee",
"Envase-a-completar",
"Expiration date completed",
"Fecha-limite-de-consumo-a-completar",
"Fecha-limite-de-consumo-agregada",
"Imagenes-a-agregar",
"Imagenes-a-validar",
"Imagenes-agregadas",
"Informations-nutritionnelles-completees",
"Ingredientes-a-completar",
"Ingredientes-completados",
"Ingredients completed",
"Ingredients-completes",
"Nutrition facts to be completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"To be completed",
"Valores-nutricionales-a-completar",
"Valores-nutricionales-completados"];
