var categoriesTags = [

"Vegetales y derivados",
"",
"Congelados",
"Vegetales congelados o ultracongelados",
"Bebidas",
"Pan-y-reposteria",
"Groceries",
"Hortalizas",
"Vegetales frescos",
"Vegetales encurtidos",
"Encurtidos",
"Alimentos estimulantes",
"Untables vegetales",
"Cacaos y chocolates",
"Alimentos-frescos",
"Hortalizas frescas",
"Verduras-y-hortalizas-y-sus-productos",
"Hortalizas congeladas",
"Cereales-y-derivados",
"Salsas",
"Aperitivos",
"Bebidas vegetales",
"Hierbas-aromaticas-y-especias",
"Comidas preparadas",
"Vegetales",
"Aceitunas",
"Fritos",
"Fritos-de-origen-vegetal",
"Verduras-y-hortalizas-fritas",
"Patatas-fritas",
"Untables",
"Desserts",
"Chips-de-verduras-y-hortalizas-fritas",
"Chips-fritos",
"Mermeladas-y-confituras",
"Untables-dulces",
"Vegetales en conserva",
"Aceites y grasas",
"Grasas vegetales",
"Frutas",
"Aceites vegetales",
"Chips-de-patatas-fritas",
"Frutos-secos",
"Aceites de oliva",
"Mezclas-de-vegetales-congelados",
"Aceites de oliva virgen extra",
"Vegetales deshidratados",
"Postres vegetales",
"Dulces-tipicos-de-navidad",
"Soy desserts",
"Platos-preparados-vegetales",
"Comidas-preparadas-congeladas",
"Mermeladas-y-confituras-de-frutas",
"Cereales",
"Condimentos",
"Chips-de-patatas-fritas-clasicas",
"Salsas de tomate",
"Patés vegetales",
"Aceitunas verdes",
"Bebidas-de-soja",
"Chips-de-patatas-fritas-lisas",
"Legumbres congeladas",
"Platos-preparados",
"Tortitas de cereales",
"Dairies",
"Yogures",
"Tofus",
"Yogures vegetales",
"Soy milk yogurts",
"Hamburguesas-vegetales",
"Postres",
"Postres-helados",
"Caldos-consomes-sopas-y-cremas",
"Legumbres-y-derivados",
"Chips-de-patatas-fritas-en-aceite-de-girasol",
"Legumbres-y-derivados-en-conserva",
"Bebidas alcohólicas",
"Zumos y néctares de frutas",
"Zumos de frutas",
"Endulzantes",
"Bebidas-de-soja-natural-endulzadas",
"Infusiones",
"Platos-preparados-en-conserva",
"Platos-preparados-vegetales-en-conserva",
"Preparados-vegetales",
"Semillas",
"Aceitunas aliñadas",
"Vinagres",
"Aceitunas enteras",
"Frutas tropicales",
"Judías verdes congeladas",
"Judías verdes congeladas troceadas",
"Salsas de tomate frito",
"Turrones",
"de:Pralinen",
"Aceitunas negras",
"Aceitunas deshuesadas",
"Bebidas-de-zumo-de-frutas-y-soja",
"Bebidas refrescantes",
"Chips-de-patatas-fritas-en-aceite-de-oliva",
"Especias",
"Aceitunas verdes partidas aliñadas",
"Aceitunas partidas",
"Aceitunas verdes partidas",
"Mezcla de encurtidos",
"Chips-de-patatas-fritas-onduladas",
"Zumos exprimidos refrigerados",
"Menestras-congeladas",
"Salteados-de-vegetales-congelados",
"Tortitas-de-maiz",
"Cítricos",
"Caldos",
"Gazpachos",
"Granizados",
"Miel",
"Sopas",
"Tomates",
"Pastas alimenticias",
"Ajos",
"Cebollas",
"Helados-y-sorbetes",
"Leches-de-cereales",
"Aceitunas verdes deshuesadas",
"Zumos de naranja",
"Bebidas-de-soja-con-chocolate",
"Brotes",
"Caldos-de-verduras",
"Frutas-congeladas",
"Mermeladas-y-confituras-de-frutas-del-bosque",
"Aceitunas negras enteras",
"Aceitunas verdes enteras",
"Berenjenas encurtidas",
"Algas",
"Azafrán",
"Brotes-de-judia-mungo",
"Brotes de judía mungo en conserva",
"Brotes en conserva",
"Chips-de-patatas-fritas-con-sabores",
"Judias-verdes-redondas-congeladas",
"Judias-verdes-redondas-troceadas-congeladas",
"Mazapanes",
"Pan-de-molde",
"Salsas de mostaza",
"Tortitas de arroz",
"Zanahorias",
"Alcaparras encurtidas",
"Zumos exprimidos no refrigerados",
"Aguas envasadas y hielo",
"Aguas minerales naturales",
"Alcachofas congeladas",
"Brócolis",
"Guisantes congelados",
"Habas congeladas",
"Leches-de-chufa",
"Mantecados-y-polvorones",
"Mantecados-y-polvorones-con-grasa-vegetal",
"Mezclas-de-verduras-y-hortalizas-congeladas",
"Postres-de-soja-con-chocolate",
"Tortitas-de-arroz-con-chocolate-negro",
"Plátanos",
"Cervezas",
"Candies",
"Chocolates",
"Aceitunas verdes rellenas",
"Aceitunas rellenas",
"Brócolis congelados",
"Cereales-congelados",
"Cremas-de-verduras",
"Garbanzos-con-verduras-en-conserva",
"Helados-con-leche-vegetal",
"Helados-de-hielo",
"Horchatas-de-chufa",
"Judias-verdes-planas-congeladas",
"Judias-verdes-planas-troceadas-congeladas",
"Mermeladas-y-confituras-de-melocoton",
"Yogures-de-soja-naturales",
"fr:Chocolats noirs",
"Chili peppers",
"Melones",
"Pepinillos encurtidos",
"Spices",
"Ajos-tiernos",
"Alubias-con-verduras-en-conserva",
"Apios",
"Caramelos-y-golosinas",
"Frutas-del-bosque-congeladas",
"Helados-de-palo-con-leche-vegetal",
"Leches-de-arroz",
"Mermeladas-y-confituras-de-ciruela",
"Mermeladas-y-confituras-de-citricos",
"Puerros",
"Salsas-napolitanas",
"Semillas-de-girasol-con-cascara-tostadas-con-sal",
"Semillas-de-lino",
"Semillas-de-sesamo",
"Tabletas-de-chocolate-negro-con-edulcorantes",
"Yogures-de-soja-con-frutas-del-bosque",
"fr:Poivrons",
"fr:Poivrons farcis",
"Frutas del bosque",
"Aceitunas negras deshuesadas",
"Aceitunas verdes partidas aliñadas a la gazpacha",
"Aceitunas verdes rellenas de pimiento",
"Remolacha encurtida",
"Cebollas encurtidas",
"Zumos de naranja exprimidos refrigerados",
"Alcachofas-troceadas-congeladas",
"Aperitivos-de-patatas",
"Aros-de-maiz",
"Bebidas vegetales congeladas",
"Caldos-de-verduras-en-brik",
"Currys",
"Espinacas congeladas",
"Figuritas-de-mazapan",
"Frutas en conserva",
"Granizados-de-horchata-de-chufa",
"Horchatas de chufa congeladas",
"Kétchups",
"Leches-de-arroz-naturales",
"Leches-de-frutos-de-cascara",
"Lentejas-con-verduras-en-conserva",
"Mantecados-y-polvorones-de-aceite-de-oliva",
"Mermeladas-y-confituras-de-fresa",
"Mermeladas-y-confituras-de-verduras-y-hortalizas",
"Mezclas-de-frutas-congeladas",
"Pimentón",
"Pimientos",
"Semillas-de-girasol-con-cascara-tostadas-aguasal",
"Semillas-de-lino-dorado",
"Setas congeladas",
"Banderillas",
"Zumos de naranja exprimidos no refrigerados",
"Cafés",
"Cebollas congeladas troceadas",
"Coles de Bruselas congeladas",
"Curcuma-molida",
"Dulces-de-membrillo",
"Galletas",
"Jengibre-molido",
"Leches-de-almendras",
"Limonadas",
"Maíz congelado",
"Mermeladas-y-confituras-de-higos",
"Mermeladas-y-confituras-de-naranja",
"Mezclas-de-frutas-del-bosque-congeladas",
"Pimientos-deshidratados",
"Salsas-de-chiles",
"Semillas-de-sesamo-crudas",
"Surtido de setas congeladas",
"Tabletas-de-chocolate-negro-para-cobertura",
"Zanahorias congeladas",
"de:Frozen-desserts",
"de:Speiseeis-und-sorbets",
"Zumos de manzana",
"Zumos procedentes de concentrado",
"Frozen foods",
"Limones",
"Zumos multifruta",
"Zanahorias encurtidas",
"Piñas",
"Aceitunas verdes deshuesadas aliñadas",
"Sorbets",
"Zumos de mandarina",
"Acelgas congeladas",
"Alubias-blancas-cocidas-en-conserva",
"Alubias-cocidas-en-conserva",
"Arroces-con-vegetales-congelados",
"Bebidas-de-soja-natural-sin-azucar",
"Bebidas-de-zumo-de-melocoton-y-soja",
"Bebidas-de-zumo-de-pina-y-soja",
"Bebidas-de-zumo-multifruta-y-soja",
"Bebidas-refrescantes-a-base-de-limon",
"Calabazas",
"Caldos-de-verduras-en-cubitos",
"Chocolate",
"Ensaladillas-congeladas",
"Esparragos-congelados",
"Espárragos verdes congelados",
"Espinacas congeladas en hojas",
"Galletas-tipo-maria-sin-gluten",
"Garbanzos",
"Guacamoles",
"Lacteos",
"Legumbres secas",
"Lentejas-cocidas-en-conserva",
"Maiz-en-grano-congelado",
"Mayonesas",
"Mazapanes-de-soto",
"Mermeladas-y-confituras-multifruta",
"Pimenton-ahumado",
"Pimenton-dulce",
"Postres-de-soja-con-vainilla",
"Pures-de-frutas",
"Rabanitos",
"Rabanos",
"Sorbetes",
"Tomate-natural-rallado",
"Tomates-deshidratados",
"Yogures-de-soja-con-frutas-tropicales",
"Yogures-de-soja-con-melocoton",
"fr:Bio",
"de:Gefrorene-fruchte",
"Manzanas",
"Clementinas",
"Mandarinas",
"Naranjas",
"Pimientos encurtidos",
"Zumos de mandarina exprimidos refrigerados",
"Seafood",
"Aceitunas verdes enteras aliñadas",
"Acelgas congeladas en hojas",
"Ajos congelados troceados",
"Arroz congelado",
"Bebidas-de-zumo-de-naranja-y-soja",
"Cardos congelados",
"Cebollas-tiernas",
"Cremas-de-verduras-frescas",
"Endulzantes de origen vegetal",
"Esparragos-verdes-enteros-congelados",
"Frutas-de-aragon",
"Frutas deshidratadas",
"Frutas-tropicales-congeladas",
"Granizados-de-limon",
"Harinas-vegetales",
"Helados-de-palo-de-horchata-de-chufa",
"Mayonesas-sin-huevo",
"Mazorquitas-de-maiz-encurtidas",
"Menestras-de-verduras-en-conserva",
"Mermeladas-y-confituras-de-cebolla",
"Mermeladas-y-confituras-de-cereza",
"Mermeladas-y-confituras-de-flores",
"Mermeladas-y-confituras-de-petalos-de-rosas",
"Mojos",
"Pasteles-de-gloria",
"Patatas congeladas",
"Patatas-fritas-en-bastones",
"Pimientos-verdes",
"Polos-de-leche-de-soja-recubiertos-con-chocolate",
"Salchichas-vegetales",
"Salsas-agridulces",
"Salteados-de-vegetales-asados-congelados",
"Seitanes",
"Siropes",
"Sofritos",
"Sorbetes-de-limon",
"Tomate-natural-triturado",
"Tortitas-de-maiz-con-chocolate-negro",
"Tortitas de varios cereales",
"Turrones-blandos",
"Turrones-de-chocolate-negro",
"Turrones-de-coco",
"Vegetales-liofilizados",
"Vino-tinto",
"Zanahorias-baby-congeladas",
"fr:Gouter",
"de:Soja-und-derivate",
"Aguacates",
"Canned foods",
"Aceitunas troceadas",
"Zumos multifruta procedente de concentrado",
"Fresones",
"Uvas",
"Aceitunas verdes rellenas de limón",
"Melocotones",
"Ajos encurtidos",
"Jengibre encurtido",
"Guindillas encurtidas",
"Zumos de piña",
"Frambuesas",
"Zumos multifruta exprimido refrigerados",
"Zumos de piña exprimidos refrigerados",
"Zumos de manzana exprimidos no refrigerados",
"Fresas",
"Vinoses",
"Ajos tiernos congelados",
"Alcachofas-baby-congeladas",
"Almendras-rellenas",
"Arándanos deshidratados",
"Barritas-de-frutos-secos",
"Bebidas-de-soja-con-cafe",
"Bebidas de soja con vainilla",
"Bebidas líquidas de soja",
"Bebidas vegetales líquidas",
"Bombones",
"Calabacines",
"Cardo-en-conserva",
"Charcuteria",
"Chips-de-patatas-fritas-sin-sal-anadida",
"Chocolate en polvo",
"Coliflores congeladas",
"Conservas-de-pescado",
"Copos de cereales",
"Edulcorantes",
"Edulcorantes-a-base-de-estevia",
"Ensaladas-chinas",
"Espinacas-con-pasas-y-pinones-congeladas",
"Espinacas congeladas troceadas",
"Garbanzos congelados",
"Granizados-de-cafe",
"Guindillas-deshidratadas-picantes",
"Judías verdes",
"Leches-de-avena",
"Leches-de-trigo",
"Legumbres frescas",
"Mantecados-y-polvorones-con-margarina-vegetal",
"Mermeladas-y-confituras-de-arandanos",
"Mermeladas-y-confituras-de-frambuesas",
"Mermeladas-y-confituras-de-frutas-tropicales",
"Mermeladas-y-confituras-de-limon",
"Mermeladas-y-confituras-de-manzana",
"Mermeladas-y-confituras-de-peras",
"Mermeladas-y-confituras-de-tomate",
"Mezclas-de-chips-de-verduras-y-hortalizas-fritas",
"Mezclas-de-leches-vegetales",
"Panes-de-molde-sin-gluten",
"Panes-de-tipo-baguette-sin-gluten",
"Pasta-de-almendras",
"Pastas-de-wasabi",
"Pepinos",
"Pimenton-picante",
"Pimientos-rojos",
"Quesos",
"Salsas bravas",
"Salsas de soja",
"Semillas-de-sesamo-tostadas",
"Tabletas-de-chocolate-negro",
"Tempuras-de-verduras-congeladas",
"Tomates-deshidratados-en-aceite",
"Tumacas",
"Turrones-de-chocolate-negro-con-almendras",
"Turrones-de-chocolate-rellenos",
"Turrones-duros",
"Uvas-sin-semillas",
"Vegetales-para-paella-congelados",
"Vino-blanco",
"Yogures-de-soja-con-arandanos",
"Yogures-de-soja-con-fresa",
"Yogures-de-soja-con-limon",
"Zanahorias-en-rodajas-congeladas",
"fr:Mollusques",
"fr:Moules",
"fr:Tablettes de chocolat",
"de:",
"de:Fruchtetees",
"de:Gefrorene-beeren",
"de:Gefrorene-erdbeeren",
"de:Gefrorene-himbeeren",
"de:Gemuse-getranke",
"de:Himbeer-sorbets",
"de:Mango-sorbets",
"de:Mischung-fur-falafel",
"de:Passionsfrucht-sorbets",
"de:Pasta-saucen",
"de:Pasteten-vegetarier",
"de:Risotto",
"de:Rot-wein-alcohol",
"de:Rotwein",
"de:Saucen",
"de:Snacks",
"de:Zitronen-sorbets",
"Hierbas aromáticas",
"Aromatic plants",
"Biscuits",
"Aceitunas negras troceadas",
"Moras",
"Arándanos",
"Canned fishes",
"Canned sardines",
"Carbonated drinks",
"Cheeses",
"Cerezas",
"Chirimoyas",
"Cocos",
"Zumos de manzana procedentes de concentrado",
"Zumos de pomelo procedente de concentrado",
"Zumos de tomate procedente de concentrado",
"Cookies",
"Culinary plants",
"Fishes",
"Néctares de frutas",
"Zumos de pomelo",
"Pomelos",
"Aceitunas verdes troceadas",
"Néctares de guayaba",
"Limas",
"Mangos",
"Margarinas",
"Nísperos",
"Leches",
"en:Pan-y-reposteria",
"Papayas",
"Aceites de cacahuete",
"Peras",
"Ciruelas",
"Granadas",
"Pomelos chinos",
"Red wines",
"Zumos de manzana exprimidos refrigerados",
"Vinagres de arroz",
"Sardines",
"Aceitunas de color cambiante",
"Aceitunas de color cambiante enteras",
"Aceites de sésamo",
"Sodas",
"Zumos de mandarina exprimidos no refrigerados",
"Zumos de tomate",
"Aceites de oliva virgen",
"White wines",
"Wines from Spain",
"en:Yeast-extract-spreads",
"Acelgas congeladas troceadas",
"Aditivos-alimentarios",
"Agua",
"Agua-con-gas",
"Aguacates-congelados",
"Aguas",
"Alimentos especiales",
"Alimentos-funcionales",
"Alimentos infantiles",
"Alioli",
"Altramuces-encurtidos",
"Aparitivos",
"Apio-encurtido",
"Aros-de-cebolla-empanados",
"Atjar-tjampoer",
"Atun-claro",
"Atun-claro-en-aceite-de-oliva",
"Bandeja-de-plastico",
"Barritas-de-anacardos",
"Bases-de-pizza",
"Bebidas-de-zumo-de-manzana-y-soja",
"Berenjenas",
"Bolitas-de-coco-recubiertas-de-chocolate",
"Bolsa-de-plastico",
"Bonito-del-norte",
"Bonito-del-norte-ecologico",
"Bonito-del-norte-en-aceite-de-oliva",
"Brotes-de-cebolla",
"Brotes de cebolla frescos",
"Brotes frescos",
"Calabacines-congelados",
"Calabacines-en-dados-congelados",
"Calabazas-congeladas",
"Calabazas-en-dados-congeladas",
"Caldos-de-verduras-en-cacitos",
"Castanas-congeladas",
"Cebolleta-liofilizada",
"Champiñones",
"Champiñones laminados",
"Chile-liofilizado",
"Chips-de-patatas-fritas-con-corte-grueso",
"Col-lombarda-encurtida",
"Col-verde-en-conserva",
"Coles de Bruselas",
"Complementos Alimenticios",
"Conservas-ecologicas",
"Conservas-vegetales",
"Corazones-de-alcachofas-congelados",
"Cremas de cacahuete",
"Cremas-de-cacao-y-avellanas",
"Cremas de frutos secos",
"Creme-dessert",
"Cuscuses-con-vegetales-congelados",
"Digestivo",
"Dulces-de-almendras",
"Dulces-de-confiteria",
"Espárragos",
"Esparragos-verdes",
"Esparragos-verdes-troceados-congelados",
"Flan",
"Fresas-congeladas",
"Frutas-frescas",
"Frutos-de-cascara-congelados",
"Galletas-tipo-maria-con-chocolate-sin-gluten",
"Garbanzos-cocidos-en-conserva",
"Garbanzos-con-espinacas",
"Garrofones-congelados",
"Granadas-congeladas",
"Granizados-de-mojito",
"Granizados-de-turron",
"Guindas-al-marrasquino",
"Helados-de-palo-de-leche-de-soja-con-chocolate",
"Hierbas aromáticas frescas",
"Higos",
"Jalapenos-en-rodajas-encurtidos",
"Jalapenos-encurtidos",
"Jengibre-deshidratado",
"Jengibre-liofilizado",
"Judias-verdes-con-patatas-congeladas",
"Kiwis",
"Leche-entera",
"Leches-de-avellanas",
"Leches-de-espelta",
"Leches-de-kamut",
"Leches-de-quinoa",
"Legumbres",
"Limonadas-exprimidas-ambiente",
"Limonadas-exprimidas-refrigeradas",
"Lombardas-congeladas",
"Maiz-en-mazorca-congelado",
"Mantecados-y-polvorones-con-chocolate",
"Mermelada",
"Mermeladas-y-confituras-de-calabaza",
"Mermeladas-y-confituras-de-mango",
"Mermeladas-y-confituras-de-melon",
"Mezcla-para-sofrito-congelada",
"Mezclas-de-frutas-tropicales-congeladas",
"Mezclas-de-pimientos-multicolores",
"Mezclas-de-pimientos-multicolores-congelados",
"Mezclas-de-vegetales-para-pure",
"Mezclas-de-verduras-y-hortalizas",
"Moras-congeladas",
"Mostazas-a-la-antigua",
"Mueslis",
"Nabos",
"Noodles",
"Noras-deshidratadas",
"Pan-de-higo",
"Pan-de-mlde",
"Pan-tostado",
"Papadams",
"Parrillada-de-verduras-congelada",
"Patata-para-tortilla",
"Patatas",
"Patatas-panadera-congeladas",
"Pepitas-de-chocolate-negro",
"Perejil-congelado",
"Pimienta-negra-en-grano-molinillo",
"Pimientas-verdes-encurtidas",
"Pimientos-choriceros-deshidratados",
"Pimientos-congelados",
"Pinas-congeladas",
"Pistos-congelados",
"Platerinas",
"Platos-precocinados",
"Plum-cakes-sin-gluten",
"Pochas-con-verduras-congeladas",
"Preparados-para-bebidas",
"Pure-de-patatas",
"Rebozados",
"Reposteria",
"Romanesco-congelado",
"Salsas-para-pizzas",
"Salsas-sicilianas",
"Salsas-verdes",
"Semillas-de-girasol-sin-cascara",
"Semillas-de-lino-marron",
"Setas-boletus-edulis-congeladas",
"Setas frescas",
"Sirope de agave",
"Siropes-de-chocolate",
"Snacks",
"Soja-frita",
"Sorbetes-de-frutas-del-bosque",
"Surtidos-de-mermeladas",
"Sushi",
"Sushi-vegetal",
"Tabletas-de-chocolate-negro-con-almendras-con-edulcorantes",
"Tabletas-de-chocolate-negro-con-naranja",
"Tamaris",
"Tarrinas-y-bloques-de-helado-con-leche-vegetal",
"Tarrinas-y-bloques-de-helado-de-leche-de-arroz-y-vainilla",
"Tomate-seco-en-aceite",
"Tonicas",
"Tortitas-de-arroz-con-algarroba",
"Turrones-de-cacahuete",
"Turrones-de-mazapan-de-cabello-de-angel",
"Turrones-de-yema-tostada",
"Uvas-blancas",
"Uvas-blancas-sin-semillas",
"Uvas-negras",
"Uvas-negras-sin-semillas",
"Vinagres de manzana",
"Vinagres de vino",
"Vinagretas",
"Virutas-de-chocolate-negro",
"Yogures-de-soja-con-albaricoque",
"Yogures-de-soja-con-cerezas",
"Yogures-de-soja-con-frambuesa",
"Yogures-de-soja-con-frutas-variadas",
"Yogures-de-soja-con-mango",
"Yogures-de-soja-con-platano",
"Zumo",
"fr:Apéritif",
"fr:Boisson-a-l-avoine",
"fr:Boisson-a-l-avoine-bio",
"fr:Boisson-au-riz",
"fr:Boisson-au-riz-bio",
"fr:Boisson-au-riz-thai-et-quinoa-bio",
"fr:Cafe-lyophilise",
"fr:Chocolat-noir-a-la-menthe",
"fr:Chocolat-noir-aux-ecorces-d-orange-confites",
"fr:Chocolat-noir-fleur-de-sel",
"fr:Chocolats de dégustation",
"Sidras",
"fr:Dessert-en-poudre",
"fr:Haricots",
"fr:Laits entiers",
"fr:Manzana",
"fr:Plats préparés en conserve",
"fr:Poivron-farci-a-la-morue",
"fr:Sardines à l'huile",
"fr:Sardines à l'huile d'olive",
"fr:Sodas au cola",
"it:Bevande-vegetali",
"it:Cioccolatini",
"it:Organic",
"it:Pasta-di-semola-di-grano-duro",
"it:Pesto",
"it:Pesto-rosso",
"pt:Ervas-aromaticas",
"pt:Ervas-aromaticas-e-especiarias",
"pt:Hortela-verde",
"pt:Plantas-de-hortela-verde"];
