var labelsTags = [

"Vegetariano",
"Vegano",
"Ecológico",
"Ecológico UE",
"Sin gluten",
"Sin OMG",
"ES-ECO-019-CT",
"Con sulfitos",
"Producto-de-cooperativa",
"ES-ECO-016-CL",
"Sin lactosa",
"Etiquetas de calidad de España",
"Negra",
"Producto protegido de España",
"ES-ECO-002-CM",
"ES-ECO-020-CV",
"",
"ES-ECO-025-NA",
"FACE",
"ES-ECO-024-MU",
"FSC",
"Tierra de Sabor",
"IGP",
"ES-ECO-023-MA",
"FR-BIO-01",
"Calidad Certificada",
"DE-ÖKO-001",
"ES-ECO-001-AN",
"Comercio justo",
"DOP",
"DE-ÖKO-013",
"En braille",
"Sin huevo",
"DE-ÖKO-007",
"Vegetarien",
"Vegan Society",
"Vegetalien",
"Huella de carbono",
"DE-ÖKO-003",
"IT-BIO-006",
"IGP Berenjena de Almagro",
"ES-ECO-013-IB",
"ES-ECO-022-GA",
"IT-BIO-007",
"IT-BIO-014",
"Alimentos de Extremadura",
"ES-ECO-006-AR",
"Fairtrade International",
"Kosher",
"Ley de pureza de 1516",
"Reyno Gourmet",
"Utz-certified",
"fr:AB Agriculture Biologique",
"fr:Cuit-au-feu-de-bois",
"de:Utz-certified",
"BE-BIO-01",
"Agricultura biodinámica",
"DO",
"DOCa",
"DOCa Rioja",
"ES-ECO-021-EX",
"NL-BIO-01",
"DOP Pimentón de la Vera",
"Halal",
"CH-BIO-006",
"Demeter",
"IT-BIO-009",
"IGP Alubia de La Bañeza-León",
"IGP Lenteja Pardina de Tierra de Campos",
"PT-BIO-04",
"AT-BIO-402",
"Authentic Trappist Product",
"BO-BIO-126",
"Certified Belgian Abbey Beer",
"ES-ECO-012-AS",
"ES-ECO-026-VAS",
"ES-ECO-027-RI",
"IT-BIO-013",
"Sin colesterol",
"Sin colorantes",
"Sin leche",
"Sin conservantes",
"IGP Lenteja de La Armuña",
"PT-BIO-03",
"Sial-innovacion",
"fr:Equitable-ecocert",
"Etiquetas de distribuidores",
"it:Vegano",
"it:Vegetariano",
"de:Glutenfrei",
"Alimentos de Castilla-La Mancha",
"BE-BIO-02",
"Carrefour Quality",
"CH-BIO-004",
"CZ-BIO-001",
"DO Manzanilla-Sanlúcar de Barrameda",
"DO Montilla-Moriles",
"DO Toro",
"en:Eco-emballages",
"ES-ECO-002-AN",
"ES-ECO-003-AN",
"ES-ECO-017-CM",
"Etiqueta de Calidad Doñana 21",
"Galicia Calidade",
"Producción Integrada",
"IT-BIO-003",
"IT-BIO-008",
"Reduce el colesterol",
"Sin azúcares añadidos",
"Sin alcohol",
"DOP Arroz de Calasparra",
"DOP Arroz de Valencia",
"DOP Azafrán de La Mancha",
"DOP Chufa de Valencia",
"DOP Estepa",
"DOP Montes de Toledo",
"DOP Pasas de Málaga",
"DOP Pimentón de Murcia",
"DOP Sierra de Segura",
"DOP Vinagre de Jerez",
"IGP Garbanzo de Fuentesaúco",
"IGP Mazapán de Toledo",
"IGP Pemento do Couto",
"IGP Plátano de Canarias",
"en:Point-vert",
"Rainforest Alliance",
"Rico en fibra",
"Rico en vitamina C",
"Vegetarian Society",
"VP",
"VP Campo de la Guardia",
"Ab-agriculture-biologique",
"Alimentos-artesanos-de-navarra",
"Bio-europeen",
"Certificado-msc-de-pesca-sostenible",
"Con-edulcorantes",
"Fuente-de-calcio-natural",
"Fuente-de-fibra",
"Igp-turron-de-alicante",
"Igp-turron-de-jijona",
"Negras",
"No-recomendado-consumo-a-menores-de-3-anos",
"Platos-preparados",
"Producto-de-coopeerativa",
"Producto-de-espana",
"Sin-alcohol-0-0",
"Sin-colorantes-ni-conservantes",
"Sin-grasas-hidrogenadas",
"fr:Sin-colorantes",
"fr:Sin-conservantes",
"fr:Sin-gluten",
"Panel Test Carrefour",
"fr:Vegetariano",
"it:Gb-org-05",
"it:Senza-latte",
"pt:Ecologico",
"pt:Ecologico-ue",
"pt:Vegano",
"pt:Vegetariano"];
