var statusTags = [

"A completar",
"A-completer",
"A-verifier",
"Brands-to-be-completed",
"Cantidad a completar",
"Características a completar",
"Características completadas",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categorías a completar",
"Categories-a-completer",
"Categories-to-be-completed",
"Characteristics-completed",
"Characteristics-to-be-completed",
"Complet",
"Completado",
"Complete",
"Completo",
"Data-de-validade-a-completar",
"Data-de-validade-completada",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Envase a completar",
"Expiration-date-completed",
"Expiration-date-to-be-completed",
"Fecha límite de consumo a completar",
"Fecha límite de consumo agregada",
"Imágenes a agregar",
"Imágenes a validar",
"Imágenes agregadas",
"Imágenes validadas",
"Imagens-enviadas",
"Imagens-validadas",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredientes a completar",
"Ingredientes completados",
"Ingredients-a-completer",
"Ingredients-completed",
"Ingredients-completes",
"Ingredients-to-be-completed",
"Marcas a completar",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nombre de producto a completar",
"Nutrition-facts-completed",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Pendente-de-verificacao",
"Pendiente de comprobación",
"Photos-a-valider",
"Photos-envoyees",
"Photos-to-be-uploaded",
"Photos-to-be-validated",
"Photos-uploaded",
"Photos-validated",
"Photos-validees",
"Product-name-to-be-completed",
"Quantite-a-completer",
"Quantity-to-be-completed",
"To-be-checked",
"To-be-completed",
"Valores-nutricionais-completados",
"Valores nutricionales a completar",
"Valores nutricionales completados"];
