var labelsTags = [

"de:Vegetarisch",
"de:Vegan",
"Organic",
"EU Organic",
"Gluten-free",
"No GMOs",
"ES-ECO-019-CT",
"With sulfites",
"es:Producto-de-cooperativa",
"ES-ECO-016-CL",
"No lactose",
"Spanish quality label",
"es:Negra",
"Spanish protected product",
"ES-ECO-002-CM",
"ES-ECO-020-CV",
"es:",
"ES-ECO-025-NA",
"FACE",
"ES-ECO-024-MU",
"FSC",
"Tierra de Sabor",
"PGI",
"ES-ECO-023-MA",
"FR-BIO-01",
"Calidad Certificada",
"DE-ÖKO-001",
"ES-ECO-001-AN",
"Fair trade",
"PDO",
"DE-ÖKO-013",
"In braille",
"No eggs",
"DE-ÖKO-007",
"es:Vegetarien",
"Vegan Society",
"es:Vegetalien",
"Carbon footprint",
"DE-ÖKO-003",
"IT-BIO-006",
"PGI Berenjena de Almagro",
"ES-ECO-013-IB",
"ES-ECO-022-GA",
"IT-BIO-007",
"IT-BIO-014",
"Alimentos de Extremadura",
"ES-ECO-006-AR",
"Fairtrade International",
"Kosher",
"Reinheitsgebot",
"Reyno Gourmet",
"es:Utz-certified",
"fr:AB Agriculture Biologique",
"fr:Cuit-au-feu-de-bois",
"de:Utz-certified",
"BE-BIO-01",
"Biodynamic agriculture",
"Denominación de Origen",
"Denominación de Origen Calificada",
"DOCa Rioja",
"ES-ECO-021-EX",
"NL-BIO-01",
"PDO Pimentón de la Vera",
"fr:Halal",
"CH-BIO-006",
"Demeter",
"IT-BIO-009",
"PGI Alubia de La Bañeza-León",
"PGI Lenteja Pardina de Tierra de Campos",
"PT-BIO-04",
"AT-BIO-402",
"Authentic Trappist Product",
"BO-BIO-126",
"Certified Belgian Abbey Beer",
"ES-ECO-012-AS",
"ES-ECO-026-VAS",
"ES-ECO-027-RI",
"IT-BIO-013",
"No cholesterol",
"No colorings",
"No milk",
"No preservatives",
"PGI Lenteja de La Armuña",
"PT-BIO-03",
"es:Sial-innovacion",
"fr:Equitable-ecocert",
"fr:Labels de distributeurs",
"it:Vegano",
"it:Vegetariano",
"de:Glutenfrei",
"Alimentos de Castilla-La Mancha",
"BE-BIO-02",
"Carrefour Quality",
"CH-BIO-004",
"CZ-BIO-001",
"DO Manzanilla-Sanlúcar de Barrameda",
"DO Montilla-Moriles",
"DO Toro",
"en:Eco-emballages",
"ES-ECO-002-AN",
"ES-ECO-003-AN",
"ES-ECO-017-CM",
"Etiqueta de Calidad Doñana 21",
"Galicia Calidade",
"Integrated production",
"IT-BIO-003",
"IT-BIO-008",
"Lowers cholesterol",
"No added sugar",
"No alcohol",
"PDO Arroz de Calasparra",
"PDO Arroz de Valencia",
"PDO Azafrán de La Mancha",
"PDO Chufa de Valencia",
"PDO Estepa",
"PDO Montes de Toledo",
"PDO Pasas de Málaga",
"PDO Pimentón de Murcia",
"PDO Sierra de Segura",
"PDO Vinagre de Jerez",
"PGI Garbanzo de Fuentesaúco",
"PGI Mazapán de Toledo",
"PGI Pemento do Couto",
"PGI Plátano de Canarias",
"en:Point-vert",
"Rainforest Alliance",
"Rich in fiber",
"Rich in vitamin C",
"Vegetarian Society",
"Vino de Pago",
"VP Campo de la Guardia",
"es:Ab-agriculture-biologique",
"es:Alimentos-artesanos-de-navarra",
"es:Bio-europeen",
"es:Certificado-msc-de-pesca-sostenible",
"es:Con-edulcorantes",
"es:Fuente-de-calcio-natural",
"es:Fuente-de-fibra",
"es:Igp-turron-de-alicante",
"es:Igp-turron-de-jijona",
"es:Negras",
"es:No-recomendado-consumo-a-menores-de-3-anos",
"es:Platos-preparados",
"es:Producto-de-coopeerativa",
"es:Producto-de-espana",
"es:Sin-alcohol-0-0",
"es:Sin-colorantes-ni-conservantes",
"es:Sin-grasas-hidrogenadas",
"fr:Sin-colorantes",
"fr:Sin-conservantes",
"fr:Sin-gluten",
"fr:Testé par le panel test Carrefour",
"fr:Vegetariano",
"it:Gb-org-05",
"it:Senza-latte",
"pt:Ecologico",
"pt:Ecologico-ue",
"pt:Vegano",
"pt:Vegetariano"];
