var purchase_placesTags = [

"Altea-espagne",
"Andorra",
"Barcelona",
"Barcelone",
"Carrefour",
"Conil-de-la-frontera-espagne",
"Cordoba",
"Delicatessen-lukas",
"El-corte-ingles",
"Espagne",
"Espana",
"Gerone",
"Hipercor",
"Horno-artesano",
"La-granja",
"Madrid",
"Madrid-comunidad-autonoma",
"Malaga",
"Pampelune",
"Panymas-las-arenas",
"Portbou",
"Sitio-web",
"Spagna",
"Spanien",
"Toledo",
"Www-flamencochueca-com"];
