var categoriesTags = [

"es:Vegetales y derivados",
"es:Vegetales frescos",
"es:Vegetales-congelados",
"es:Pan-y-reposteria",
"Beverages",
"es:Alimentos estimulantes",
"es:Cacaos y chocolates",
"Vegetables",
"Pickled vegetables",
"Pickles",
"Groceries",
"es:Aperitivos",
"es:Cereales-y-derivados",
"es:Bebidas vegetales",
"es:Platos-preparados-vegetales",
"fr:Sauces",
"es:Vegetales",
"es:Vegetales en conserva",
"es:Hierbas-aromaticas-y-especias",
"es:Frutos-secos",
"Olives",
"es:Frutas frescas",
"es:Untables vegetales",
"es:Dulces-tipicos-de-navidad",
"es:Patés vegetales",
"es:Vegetales deshidratados",
"es:Postres-vegetales",
"es:Mermeladas-y-confituras",
"Green olives",
"Alcoholic drinks",
"es:Preparados-vegetales",
"es:Tofus",
"es:Caldos-consomes-sopas-y-cremas",
"es:Hamburguesas-vegetales",
"Fruit juices and nectars",
"Fruit juices",
"es:Legumbres-y-derivados",
"Marinated olives",
"Fats",
"Olive oils",
"Vegetable fats",
"Vegetable oils",
"es:Infusiones",
"Extra-virgin olive oils",
"es:Semillas",
"Cracked marinated green olives",
"Cracked olives",
"Green cracked olives",
"Whole olives",
"es:Platos-preparados",
"Pastas",
"es:Bebidas-de-zumo-y-soja",
"es:Endulzantes",
"Black olives",
"es:Algas",
"es:Aguas envasadas y hielo",
"es:Aguas minerales naturales",
"Mixed pickles",
"Orange juices",
"Pitted olives",
"Black whole olives",
"Chili peppers",
"Pickled eggplants",
"Spices",
"es:Brotes",
"fr:Poivrons",
"fr:Poivrons farcis",
"Gazpacha marinated green olives",
"Green pitted olives",
"Refrigerated squeezed juices",
"Squeezed juices",
"es:Bebidas refrescantes",
"es:Frutas en conserva",
"Candies",
"Condiments",
"Green stuffed olives",
"Green whole olives",
"Pickled capers",
"Squeezed orange juices",
"Stuffed olives",
"es:Caramelos-y-golosinas",
"fr:Confiseries de France",
"fr:Nougats",
"Banderillas",
"Green olives stuffed of pepper",
"Pickled beets",
"Pickled carrots",
"Pickled cucumbers",
"Pickled onions",
"es:",
"es:Cafés",
"es:Legumbres-y-derivados-en-conserva",
"es:Pures-de-frutas",
"de:Gefrorene-fruchte",
"Apple juices",
"Pitted marinated green olives",
"Refrigerated squeezed orange juices",
"Seafood",
"es:Frutas-congeladas",
"es:Lacteos",
"es:Vino-tinto",
"de:Soja-und-derivate",
"Black pitted olives",
"Dairies",
"Pickled garlic",
"Pineapple juices",
"Refrigerated squeezed pineapple juices",
"Vinegars",
"es:Bombones",
"es:Chocolate en polvo",
"es:Harinas-vegetales",
"es:Helados-de-hielo",
"es:Mazorquitas-de-maiz-encurtidas",
"es:Quesos",
"es:Vino-blanco",
"fr:Apéritif",
"fr:Mollusques",
"fr:Moules",
"de:Gemuse-getranke",
"de:Pasteten-vegetarier",
"de:Pralinen",
"de:Rot-wein-alcohol",
"de:Rotwein",
"de:Snacks",
"Beers",
"Biscuits",
"Black chopped olives",
"Canned fishes",
"Canned foods",
"Canned sardines",
"Cereals",
"Chopped olives",
"Concentrated apple juices",
"Concentrated fruit juices",
"Cookies",
"Desserts",
"Fishes",
"Fruit nectars",
"Green olives stuffed of lemon",
"Guava nectars",
"Meals",
"Milks",
"Pickled ginger",
"Pickled guindilla peppers",
"Pickled peppers",
"Red wines",
"Refrigerated squeezed apple juices",
"Sardines",
"Semi-ripe olives",
"Semi-ripe whole olives",
"Squeezed apple juices",
"Virgin olive oils",
"Whole marinated green olives",
"Wines",
"Wines from Spain",
"Yogurts",
"es:Aditivos-alimentarios",
"es:Agua",
"es:Alimentos especiales",
"es:Alimentos-funcionales",
"es:Alimentos infantiles",
"es:Aparitivos",
"es:Apio-encurtido",
"es:Charcuteria",
"es:Complementos Alimenticios",
"es:Copos de cereales",
"es:Creme-dessert",
"es:Dulces-de-confiteria",
"es:Mermelada",
"es:Mueslis",
"es:Preparados-para-bebidas",
"es:Pure-de-patatas",
"es:Sorbetes",
"es:Untables",
"es:Zumos-de-mandarina-exprimida-refrigerados",
"fr:Cafe-lyophilise",
"fr:Dessert-en-poudre",
"fr:Laits entiers",
"fr:Poivron-farci-a-la-morue",
"fr:Sardines à l'huile",
"fr:Sardines à l'huile d'olive",
"it:Bevande-vegetali"];
