var labelsTags = [

"Vegetarian",
"Vegan",
"Organic",
"EU Organic",
"Gluten-free",
"ES-ECO-019-CT",
"ES-ECO-016-CL",
"es:Producto-de-cooperativa",
"No GMOs",
"With sulfites",
"es:Etiquetas de calidad de España",
"es:Producto protegido de España",
"ES-ECO-020-CV",
"No lactose",
"ES-ECO-002-CM",
"ES-ECO-024-MU",
"es:Tierra de Sabor",
"ES-ECO-025-NA",
"es:FACE",
"es:Calidad Certificada",
"FR-BIO-01",
"ES-ECO-001-AN",
"PGI",
"DE-ÖKO-013",
"ES-ECO-023-MA",
"DE-ÖKO-001",
"DE-ÖKO-007",
"Fair trade",
"PDO",
"FSC",
"DE-ÖKO-003",
"ES-ECO-022-GA",
"IT-BIO-006",
"IT-BIO-007",
"Kosher",
"No eggs",
"Reinheitsgebot",
"es:",
"es:IGP Berenjena de Almagro",
"fr:Cuit-au-feu-de-bois",
"ES-ECO-006-AR",
"ES-ECO-021-EX",
"IT-BIO-014",
"Vegan Society",
"es:DO",
"es:DOCa",
"es:DOCa Rioja",
"de:Okologische-produkt",
"BE-BIO-01",
"CH-BIO-006",
"Demeter",
"IT-BIO-009",
"PT-BIO-04",
"es:Alimentos de Extremadura",
"es:Reyno Gourmet",
"fr:Bio-dynamie",
"de:Ohne-gentechnik",
"Authentic Trappist Product",
"Certified Belgian Abbey Beer",
"ES-ECO-012-AS",
"ES-ECO-027-RI",
"Fairtrade International",
"IT-BIO-013",
"NL-BIO-01",
"No colorings",
"No preservatives",
"es:DOP Pimentón de la Vera",
"es:IGP Lenteja de La Armuña",
"es:IGP Lenteja Pardina de Tierra de Campos",
"fr:Indicacion-geografica-protegida",
"fr:Sin-gluten",
"AT-BIO-402",
"BE-BIO-02",
"CH-BIO-004",
"ES-ECO-002-AN",
"ES-ECO-003-AN",
"ES-ECO-017-CM",
"IT-BIO-003",
"IT-BIO-008",
"Lowers cholesterol",
"No alcohol",
"PT-BIO-03",
"Rich in fiber",
"Rich in vitamin C",
"es:0-azucares-anadidos",
"es:Alimentos de Castilla-La Mancha",
"es:Bo-bio-126",
"es:Cz-bio-001",
"es:DO Manzanilla-Sanlúcar de Barrameda",
"es:DO Montilla-Moriles",
"es:DO Toro",
"es:DOP Arroz de Valencia",
"es:DOP Azafrán de La Mancha",
"es:DOP Montes de Toledo",
"es:DOP Pasas de Málaga",
"es:DOP Pimentón de Murcia",
"es:DOP Sierra de Segura",
"es:DOP Vinagre de Jerez",
"es:Etiqueta de Calidad Doñana 21",
"es:Fuente-de-calcio-natural",
"es:Galicia Calidade",
"es:IGP Alubia de La Bañeza-León",
"es:IGP Garbanzo de Fuentesaúco",
"es:IGP Mazapán de Toledo",
"es:IGP Pemento do Couto",
"es:Producción Integrada",
"es:Sin-alcohol-0-0",
"es:VP",
"es:VP Campo de la Guardia",
"fr:Aceitunas-de-espana",
"fr:Halal",
"fr:Produit en braille",
"it:Bio",
"it:Senza-glutine",
"it:Senza-lattosio"];
