var categoriesTags = [

"Breakfasts",
"Dairies",
"Baby foods",
"Spreads",
"Sweet spreads",
"fr:Pâtes à tartiner",
"Milks",
"Beverages",
"Fats",
"Margarines",
"Vegetable fats",
"fr:Apéritif",
"fr:Céréales pour bébé",
"fr:Céréales pour petit-déjeuner",
"fr:Laits entiers",
"fr:Laits UHT",
"Breads",
"Candies",
"Canned foods",
"Cereals",
"Cheeses",
"Chips and fries",
"Chocolates",
"Concentrated fruit juices",
"Concentrated orange juices",
"Flours",
"Fruit juices",
"Fruit juices and nectars",
"Hot drinks",
"Meals",
"Meta-category",
"Orange juices",
"Pastas",
"Soups",
"Vegetables and derived products",
"Wheat flours",
"fr:Biscottes",
"fr:Biscottes au froment",
"fr:Biscuits-aperitifs",
"fr:Biscuits-sales",
"fr:Cafés",
"fr:Chips",
"fr:Chocolats en poudre",
"fr:Corn-flakes",
"fr:Dès 06 mois",
"fr:Édulcorants",
"fr:Farines de blé tendre",
"fr:Farines de blé type T45",
"fr:Laits concentrés",
"fr:Laits concentrés non sucrés",
"fr:Laits en poudre",
"fr:Pâtes à tartiner au chocolat",
"fr:Produits sous license",
"fr:Puree-de-legumes-pour-bebe",
"fr:Veloutés"];
