var categoriesTags = [

"Petit-déjeuners",
"Produits laitiers",
"Aliments pour bébé",
"Produits à tartiner",
"Produits à tartiner sucrés",
"Pâtes à tartiner",
"Laits",
"Boissons",
"Matières grasses",
"Margarines",
"Matières grasses végétales",
"Apéritif",
"Céréales pour bébé",
"Céréales pour petit-déjeuner",
"Laits entiers",
"Laits UHT",
"Pains",
"Confiseries",
"Conserves",
"Céréales",
"Fromages",
"Chips et frites",
"Chocolats",
"Jus de fruits à base de concentré",
"Jus d'orange à base de concentré",
"Farines",
"Jus de fruits",
"Jus et nectars de fruits",
"Boissons chaudes",
"Plats préparés",
"Méta-catégorie",
"Jus d'orange",
"Pâtes alimentaires",
"Soupes",
"Végétaux et dérivés",
"Farines de blé",
"Biscottes",
"Biscottes au froment",
"Biscuits-aperitifs",
"Biscuits-sales",
"Cafés",
"Chips",
"Chocolats en poudre",
"Corn-flakes",
"Dès 06 mois",
"Édulcorants",
"Farines de blé tendre",
"Farines de blé type T45",
"Laits concentrés",
"Laits concentrés non sucrés",
"Laits en poudre",
"Pâtes à tartiner au chocolat",
"Produits sous license",
"Puree-de-legumes-pour-bebe",
"Veloutés"];
