var statusTags = [

"A-completer",
"Caracteristiques-a-completer",
"Categories-a-completer",
"Categories to be completed",
"Characteristics completed",
"Characteristics to be completed",
"Complete",
"Date-limite-a-completer",
"Emballage-a-completer",
"Expiration date completed",
"Expiration date to be completed",
"Informations-nutritionnelles-a-completer",
"Ingredients-a-completer",
"Ingredients completed",
"Ingredients to be completed",
"Nutrition facts completed",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"Photos validated",
"To be checked",
"To be completed"];
