var categoriesTags = [

"Beverages",
"Dairies",
"Yogurts",
"Alcoholic drinks",
"Pastas",
"it:Biscotti",
"it:Latticini",
"Hot drinks",
"Wines",
"fr:Cafés",
"it:Formaggio",
"it:Organic",
"Biscotti",
"Candies",
"Cheeses",
"Chocolates",
"Groceries",
"it:Caffe",
"it:Cracker",
"it:Formaggi",
"Aceto-balsamico",
"Cakes",
"Chopeed-tomatoes",
"Fromage-a-tartiner",
"Liqueur",
"Nocino",
"Peeled-tomatoes",
"Red wines",
"Sauces",
"Spices",
"Sugars",
"Waffles",
"fr:Amaretto",
"fr:Aperifitf",
"fr:Apéritif",
"fr:Biscotto",
"fr:Biscuits-aperitifs",
"fr:Biscuits-sales",
"fr:Chocolats de Pâques",
"fr:Formaggi",
"fr:Fromages à pâte filée",
"fr:Fromages au lait de bufflonne",
"fr:Fromages pasteurisés",
"fr:Gaufrettes",
"fr:Gewurztraminer",
"fr:Liqueurs",
"fr:Mozzarella",
"fr:Oeufs en chocolat",
"fr:Pates",
"fr:Pates-fusilli",
"fr:Pâtes sèches",
"fr:Pizzoccheri",
"fr:Viandes-bovines",
"it:Bevande-vegetali",
"it:Biscotti-frollini",
"it:Cioccolatini",
"it:Cipolla-a-cubetti",
"it:Confetti-di-chewing-gum-ripieni",
"it:Crackers",
"it:Crema-di-yogurt",
"it:Creme-caramel",
"it:Ctg-a",
"it:Formaggio-a-pasta-filata",
"it:Formaggio-fuso",
"it:Latte",
"it:Latte-parzialmente-scremato",
"it:Lunga-conservazione",
"it:Miele",
"it:Mozzarella-di-bufala-campana",
"it:Organico",
"it:Pasta-all-uovo",
"it:Pasta-di-semola-di-grano-duro",
"it:Pepe",
"it:Pesto",
"it:Pesto-rosso",
"it:Pomodoro",
"it:Succo-e-polpa",
"it:Uova-medie",
"it:Wafer-con-crema-al-cioccolato",
"it:Yogurt-con-pezzi-di-frutta"];
