var labelsTags = [

"Organic",
"Carbon footprint",
"Gluten-free",
"EU Organic",
"Uni-en-iso",
"PDO",
"it:Vegano",
"it:Vegetariano",
"Vegan",
"Vegetarian",
"FSC",
"IT-BIO-006",
"IT-BIO-014",
"Kosher",
"No lactose",
"No sugar",
"Parents",
"PGI",
"fr:AOC",
"fr:Dop",
"it:100-formaggio-italiano",
"it:Bio",
"it:Biologico",
"it:Con-cioccolato-solo-puro-cacao",
"it:Gb-org-05",
"it:Gorgonzola",
"it:Igp",
"it:Intero",
"it:Iso-9001",
"it:It-01-124-ce",
"it:L",
"it:Lievitata-naturalmente",
"it:Non-contiene-coloranti",
"it:Non-contiene-conservanti",
"it:Senza-additivi-conservanti-e-coloranti-grassi-idrogenati-e-ingredienti-ogm",
"it:Senza-grassi-idrogenati",
"it:Senza-latte",
"it:Sistema-di-qualita-certificato-iso-9001",
"it:Tradizione-e-sapori-di-modena"];
