var manufacturing_placesTags = [

"Angri-sa",
"Badia-polesine",
"C-l-a-s-s-p-a-compagnia-delle-specialita-alimentari-liguri-sanremo-s-p-a",
"Castiglion-delle-stiviere-mn",
"Chiusanico",
"Colussi-group",
"Colussi-s-p-a",
"Distributore",
"Fabbricante",
"Imperia",
"Inghilterra",
"Italia",
"Italia-parma",
"Italie",
"Jesi-an",
"Liguria",
"Lombardia",
"Matelica-mc",
"Milano",
"Milano-provincia",
"Orsago-tv",
"Regno-unito",
"Rovigo-provincia",
"Stabilimento-balvano-pz",
"Stabilimento-castiglione-delle-stiviere-mn",
"Veneto"];
