var tracesTags = [

"Altra-frutta-a-guscio",
"Arachide",
"Cacahuete",
"Feninalanina",
"Fruit-sec-a-coque",
"Fruits-a-coque",
"Frutta-a-guscio",
"Glutine",
"Latte",
"Latte-e-derivati-del-latte",
"Made-in-factory",
"Made-in-factory-with-only-natural-tomatoes",
"Mais",
"Nocciole",
"Oeufs",
"Puo-contenere-tracce-di-frutta-a-guscio-e-soia",
"Soia",
"Soja",
"Solfiti",
"Sulfites",
"Uova",
"Uovo"];
