var categoriesTags = [

"Beverages",
"Dairies",
"Yogurt",
"Alcoholic drinks",
"Pastas",
"Biscotti",
"Latticini",
"Hot drinks",
"Wines",
"fr:Cafés",
"Formaggio",
"Organic",
"en:Biscotti",
"Candies",
"Cheeses",
"Chocolates",
"Groceries",
"Caffe",
"Cracker",
"Formaggi",
"en:Aceto-balsamico",
"Cakes",
"en:Chopeed-tomatoes",
"en:Fromage-a-tartiner",
"en:Liqueur",
"en:Nocino",
"en:Peeled-tomatoes",
"Red wines",
"Sauces",
"Spices",
"Sugars",
"Waffles",
"fr:Amaretto",
"fr:Aperifitf",
"fr:Apéritif",
"fr:Biscotto",
"fr:Biscuits-aperitifs",
"fr:Biscuits-sales",
"fr:Chocolats de Pâques",
"fr:Formaggi",
"fr:Fromages à pâte filée",
"fr:Fromages au lait de bufflonne",
"fr:Fromages pasteurisés",
"fr:Gaufrettes",
"fr:Gewurztraminer",
"fr:Liqueurs",
"fr:Mozzarella",
"fr:Oeufs en chocolat",
"fr:Pates",
"fr:Pates-fusilli",
"fr:Pâtes sèches",
"fr:Pizzoccheri",
"fr:Viandes-bovines",
"Bevande-vegetali",
"Biscotti-frollini",
"Cioccolatini",
"Cipolla-a-cubetti",
"Confetti-di-chewing-gum-ripieni",
"Crackers",
"Crema-di-yogurt",
"Creme-caramel",
"Ctg-a",
"Formaggio-a-pasta-filata",
"Formaggio-fuso",
"Latte",
"Latte-parzialmente-scremato",
"Lunga-conservazione",
"Miele",
"Mozzarella-di-bufala-campana",
"Organico",
"Pasta-all-uovo",
"Pasta-di-semola-di-grano-duro",
"Pepe",
"Pesto",
"Pesto-rosso",
"Pomodoro",
"Succo-e-polpa",
"Uova-medie",
"Wafer-con-crema-al-cioccolato",
"Yogurt-con-pezzi-di-frutta"];
