var labelsTags = [

"Organic",
"Emissioni di CO2",
"Senza glutine",
"EU Organic",
"en:Uni-en-iso",
"DOP",
"Vegano",
"Vegetariano",
"de:Vegan",
"de:Vegetarisch",
"FSC",
"IT-BIO-006",
"IT-BIO-014",
"Kosher",
"Senza lattosio",
"No sugar",
"en:Parents",
"PGI",
"fr:AOC",
"fr:Dop",
"100-formaggio-italiano",
"Bio",
"Biologico",
"Con-cioccolato-solo-puro-cacao",
"Gb-org-05",
"Gorgonzola",
"Igp",
"Intero",
"Iso-9001",
"It-01-124-ce",
"L",
"Lievitata-naturalmente",
"Non-contiene-coloranti",
"Non-contiene-conservanti",
"Senza-additivi-conservanti-e-coloranti-grassi-idrogenati-e-ingredienti-ogm",
"Senza-grassi-idrogenati",
"Senza-latte",
"Sistema-di-qualita-certificato-iso-9001",
"Tradizione-e-sapori-di-modena"];
