var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Sodas",
"Dairies",
"Frozen foods",
"Vegetables",
"Cereals",
"Fishes",
"Seafood",
"Canned foods",
"Cheeses",
"Meals",
"Salmons",
"Waters",
"Yogurts",
"fr:Eaux minérales",
"fr:Légumes secs",
"Biscuits",
"Breakfasts",
"Canned fishes",
"Ice creams and sorbets",
"Smoked fishes",
"fr:Eaux de sources",
"fr:Galettes de céréales",
"fr:Saumons fumés",
"fr:Saumons fumés d'élevage",
"Aromatic herbs",
"Aromatic plants",
"Cakes",
"Canned sardines",
"Canned Vegetables",
"Condiments",
"Culinary plants",
"Fresh vegetables",
"Groceries",
"Ice creams",
"Meats",
"Milks",
"Plain yogurts",
"Prepared meats",
"Rices",
"Sardines",
"fr:Céréales pour petit-déjeuner",
"fr:Crèmes glacées",
"fr:Fromages pasteurisés",
"fr:Limonades",
"fr:Plats cuisinés surgelés",
"fr:Plats préparés en conserve",
"fr:Sardines à l'huile",
"fr:Saucissons",
"fr:Terrines",
"Alcoholic drinks",
"Baby foods",
"Beers",
"Blue-veined cheeses",
"Breads",
"Candies",
"Chocolates",
"Cookies",
"Cow Cheeses",
"Drinkable yogurts",
"Fats",
"Fruit juices",
"Fruit juices and nectars",
"Jams",
"Olive oils",
"Pastas",
"Pies",
"Potatoes",
"Spreads",
"Sweet spreads",
"Tunas",
"Vanilla yogurts",
"Vegetable fats",
"Vegetable oils",
"Vegetable rods",
"Vegetables and derived products",
"Virgin olive oils",
"White wines",
"Wines",
"Wines from Spain",
"fr:Barres",
"fr:Barres de céréales",
"fr:Blé",
"fr:Ble-precuit",
"fr:Blés durs",
"fr:Boissons énergétiques",
"fr:Boulgour",
"fr:Carottes",
"fr:Chocolats dessert",
"fr:Chocolats noirs",
"fr:Coeurs de palmier",
"fr:Coeurs de palmier en conserve",
"fr:Crêpes et galettes",
"fr:Fromages à pâte fraîche",
"fr:Fromages à pâte persillée français",
"fr:Fromages au lait cru",
"fr:Fromages blancs",
"fr:Fromages de brebis",
"fr:Fromages de chèvre",
"fr:Galettes",
"fr:Glaces au chocolat",
"fr:Glaces rhum-raisin",
"fr:Houmous",
"fr:Jus-de-goyave",
"fr:Laits 1er âge",
"fr:Laits de coco",
"fr:Laits demi-écrémés",
"fr:Laits demi-écrémés biologiques",
"fr:Laits pour bébé",
"fr:Laits UHT",
"fr:Laits végétaux",
"fr:Légumes surgelés",
"fr:Lentilles sèches",
"fr:Madeleines",
"fr:Pate",
"fr:Pates",
"fr:Pois-chiches",
"fr:Pois chiches en conserve",
"fr:Pommes de terre Agata",
"fr:Puree-de-pois",
"fr:Quenelles",
"fr:Quenelles de volaille",
"fr:Ravioli",
"fr:Raviolis à la bolognaise",
"fr:Raviolis au boeuf",
"fr:Raviolis en conserve",
"fr:Riz cargo",
"fr:Riz long grain",
"fr:Riz parfumés",
"fr:Roqueforts",
"fr:Sardines à l'huile d'olive",
"fr:Sardines à la tomate",
"fr:Sirops",
"fr:Sodas au cola",
"fr:Sorbets",
"fr:Sorbets au citron",
"fr:Tartes au saumon",
"fr:Tartes salées",
"fr:Thons albacore",
"fr:Thons tropicaux",
"fr:Yaourts-a-boire-a-la-vanille",
"fr:Yaourts-natures-bio"];
