var labelsTags = [

"Organic",
"fr:AB Agriculture Biologique",
"EU Organic",
"FR-BIO-01",
"No alcohol",
"No colorings",
"No preservatives",
"fr:Porc Français",
"fr:Salé au sel sec",
"fr:Viande Française",
"100% natural",
"Carbon footprint",
"Never frozen",
"PDO",
"fr:15-d-emballage",
"fr:A-la-perche",
"fr:AOC",
"fr:Collecte-en-france",
"fr:Fume-au-bois-d-arbres-fruitiers",
"fr:Fumé au bois de hêtre",
"fr:Gy-bio-602",
"fr:Produit-de-guyane",
"fr:Region-centre"];
