var additivesTags = [

"E330 - Acide citrique",
"E322 - Lécithines",
"E412 - Gomme de guar",
"E150c - Caramel ammoniacal",
"E202 - Sorbate de potassium",
"E415 - Gomme xanthane",
"E101 - Riboflavine",
"E211 - Benzoate de sodium",
"E300 - Acide ascorbique",
"E414 - Gomme d'acacia",
"E471 - Mono- et diglycérides d'acides gras alimentaires",
"E331 - Citrates de sodium",
"E407 - Carraghénanes",
"E440a - CAS 9000-69-5",
"E102 - Tartrazine",
"E122 - Azorubine carmoisine",
"E14XX - Amidons modifiés",
"E250 - Nitrite de sodium",
"E290 - Dioxyde de carbone",
"E306 - Extrait riche en tocophérols",
"E410 - Farine de graines de caroube",
"E420 - Sorbitol",
"E422 - Glycérol",
"E445 - Esters glycériques de résine de bois",
"E500 - Carbonates de sodium",
"E1001 - Sels et esters de choline",
"E110 - Jaune orangé S",
"E1100 - Amylases",
"E120 - Acide carminique",
"E133 - Bleu brillant FCF",
"E1442 - Phosphate de diamidon hydroxypropyle",
"E150d - Caramel au sulfite d'ammonium",
"E160 - Caroténoïdes",
"E160a - Bêta-carotène",
"E160c - Extrait de paprika",
"E220 - Anhydride sulfureux",
"E223 - Disulfite de sodium",
"E252 - Nitrate de potassium",
"E260 - Acide acétique",
"E270 - Acide lactique",
"E282 - Propionate de calcium",
"E296 - Acide malique",
"E321 - Buthylhydroxytoluène",
"E332 - Citrates de potassium",
"E333 - Citrates de calcium",
"E338 - Acide orthophosphorique",
"E339 - Orthophosphates de sodium",
"E341 - Phosphate de calcium d'hydrogène",
"E375 - Acide nicotinique",
"E385 - Éthylène diamine tétra-acétate de calcium disodium",
"E428 - Gélatine",
"E441 - Gélatine animale",
"E444 - Acétate isobutyrate de saccharose",
"E450 - Sels métalliques de diphosphates",
"E466 - Carboxyméthylcellulose",
"E472b - Ester diacétyl-lactique de mono- et diglycérides d'acides gras",
"E475 - Esters polyglycériques d'acides gras",
"E476 - Esters polyglycériques d'acides gras d'huile de ricin",
"E511 - Chlorure de magnésium",
"E519 - Sulfate de cuivre",
"E621 - Glutamate monosodique",
"E627 - Guanylate disodique",
"E631 - Inosinate disodique",
"E640 - Glycines"];
