var categoriesTags = [

"Boissons",
"Boissons gazeuses",
"Sodas",
"Produits laitiers",
"Surgelés",
"Légumes",
"Céréales",
"Poissons",
"Produits de la mer",
"Conserves",
"Fromages",
"Plats préparés",
"Saumons",
"Eaux",
"Yaourts",
"Eaux minérales",
"Légumes secs",
"Biscuits",
"Petit-déjeuners",
"Poissons en conserve",
"Glaces et sorbets",
"Poissons fumés",
"Eaux de sources",
"Galettes de céréales",
"Saumons fumés",
"Saumons fumés d'élevage",
"Herbes aromatiques",
"Plantes aromatiques",
"Gâteaux",
"Sardines en conserve",
"Légumes en conserve",
"Condiments",
"Plantes condimentaires",
"Légumes frais",
"Epicerie",
"Glaces",
"Viandes",
"Laits",
"Yaourts natures",
"Charcuteries",
"Riz",
"Sardines",
"Céréales pour petit-déjeuner",
"Crèmes glacées",
"Fromages pasteurisés",
"Limonades",
"Plats cuisinés surgelés",
"Plats préparés en conserve",
"Sardines à l'huile",
"Saucissons",
"Terrines",
"Boissons alcoolisées",
"Aliments pour bébé",
"Bières",
"Fromages à pâte persillée",
"Pains",
"Confiseries",
"Chocolats",
"Cookies",
"Fromages de vache",
"Yaourts à boire",
"Matières grasses",
"Jus de fruits",
"Jus et nectars de fruits",
"Confitures",
"Huiles d'olive",
"Pâtes alimentaires",
"Tartes",
"Pommes de terre",
"Produits à tartiner",
"Produits à tartiner sucrés",
"Thons",
"Yaourts vanille",
"Matières grasses végétales",
"Huiles",
"Légumes tiges",
"Végétaux et dérivés",
"Huiles d'olive vierges",
"Vins blancs",
"Vins",
"Vins espagnols",
"Barres",
"Barres de céréales",
"Blé",
"Ble-precuit",
"Blés durs",
"Boissons énergétiques",
"Boulgour",
"Carottes",
"Chocolats dessert",
"Chocolats noirs",
"Coeurs de palmier",
"Coeurs de palmier en conserve",
"Crêpes et galettes",
"Fromages à pâte fraîche",
"Fromages à pâte persillée français",
"Fromages au lait cru",
"Fromages blancs",
"Fromages de brebis",
"Fromages de chèvre",
"Galettes",
"Glaces au chocolat",
"Glaces rhum-raisin",
"Houmous",
"Jus-de-goyave",
"Laits 1er âge",
"Laits de coco",
"Laits demi-écrémés",
"Laits demi-écrémés biologiques",
"Laits pour bébé",
"Laits UHT",
"Laits végétaux",
"Légumes surgelés",
"Lentilles sèches",
"Madeleines",
"Pate",
"Pates",
"Pois-chiches",
"Pois chiches en conserve",
"Pommes de terre Agata",
"Puree-de-pois",
"Quenelles",
"Quenelles de volaille",
"Ravioli",
"Raviolis à la bolognaise",
"Raviolis au boeuf",
"Raviolis en conserve",
"Riz cargo",
"Riz long grain",
"Riz parfumés",
"Roqueforts",
"Sardines à l'huile d'olive",
"Sardines à la tomate",
"Sirops",
"Sodas au cola",
"Sorbets",
"Sorbets au citron",
"Tartes au saumon",
"Tartes salées",
"Thons albacore",
"Thons tropicaux",
"Yaourts-a-boire-a-la-vanille",
"Yaourts-natures-bio"];
