var labelsTags = [

"Bio",
"AB Agriculture Biologique",
"Bio européen",
"FR-BIO-01",
"Sans alcool",
"Sans colorants",
"Sans conservateurs",
"Porc Français",
"Salé au sel sec",
"Viande Française",
"100% naturel",
"Empreinte carbone",
"Jamais congelé",
"AOP",
"15-d-emballage",
"A-la-perche",
"AOC",
"Collecte-en-france",
"Fume-au-bois-d-arbres-fruitiers",
"Fumé au bois de hêtre",
"Gy-bio-602",
"Produit-de-guyane",
"Region-centre"];
