var categoriesTags = [

"Beverages",
"Carbonated drinks",
"Sodas",
"Frozen foods",
"Vegetables",
"Cereals",
"Canned foods",
"Dairies",
"Fishes",
"Seafood",
"Cheeses",
"Meals",
"fr:Légumes secs",
"Canned fishes",
"Ice creams and sorbets",
"Waters",
"fr:Eaux minérales",
"fr:Galettes de céréales",
"Aromatic herbs",
"Aromatic plants",
"Breakfasts",
"Canned sardines",
"Condiments",
"Culinary plants",
"Fresh vegetables",
"Groceries",
"Ice creams",
"Meats",
"Milks",
"Prepared meats",
"Rices",
"Salmons",
"Sardines",
"fr:Céréales pour petit-déjeuner",
"fr:Crèmes glacées",
"fr:Eaux de sources",
"fr:Fromages pasteurisés",
"fr:Légumes en conserve",
"fr:Limonades",
"fr:Plats cuisinés surgelés",
"fr:Plats préparés en conserve",
"fr:Sardines à l'huile",
"fr:Saucissons",
"fr:Terrines",
"Alcoholic drinks",
"Baby foods",
"Beers",
"Biscuits",
"Blue-veined cheeses",
"Breads",
"Cakes",
"Candies",
"Chocolates",
"Cookies",
"Cow Cheeses",
"Fats",
"Fruit juices",
"Fruit juices and nectars",
"Olive oils",
"Pastas",
"Pies",
"Potatoes",
"Smoked fishes",
"Tunas",
"Vegetable fats",
"Vegetable oils",
"Vegetable rods",
"Virgin olive oils",
"White wines",
"Wines",
"Wines from Spain",
"fr:Barres",
"fr:Barres de céréales",
"fr:Blé",
"fr:Ble-precuit",
"fr:Blés durs",
"fr:Boissons énergétiques",
"fr:Boulgour",
"fr:Chocolats dessert",
"fr:Chocolats noirs",
"fr:Coeurs de palmier",
"fr:Coeurs de palmier en conserve",
"fr:Crêpes et galettes",
"fr:Fromages à pâte fraîche",
"fr:Fromages à pâte persillée français",
"fr:Fromages au lait cru",
"fr:Fromages blancs",
"fr:Fromages de brebis",
"fr:Fromages de chèvre",
"fr:Galettes",
"fr:Glaces au chocolat",
"fr:Glaces rhum-raisin",
"fr:Houmous",
"fr:Jus-de-goyave",
"fr:Laits 1er âge",
"fr:Laits de coco",
"fr:Laits demi-écrémés",
"fr:Laits demi-écrémés biologiques",
"fr:Laits pour bébé",
"fr:Laits UHT",
"fr:Laits végétaux",
"fr:Légumes surgelés",
"fr:Lentilles sèches",
"fr:Pate",
"fr:Pates",
"fr:Pois-chiches",
"fr:Pois chiches en conserve",
"fr:Pommes de terre Agata",
"fr:Puree-de-pois",
"fr:Quenelles",
"fr:Quenelles de volaille",
"fr:Ravioli",
"fr:Raviolis à la bolognaise",
"fr:Raviolis au boeuf",
"fr:Raviolis en conserve",
"fr:Riz cargo",
"fr:Riz long grain",
"fr:Riz parfumés",
"fr:Roqueforts",
"fr:Sardines à l'huile d'olive",
"fr:Sardines à la tomate",
"fr:Saumons fumés",
"fr:Saumons fumés d'élevage",
"fr:Sirops",
"fr:Sodas au cola",
"fr:Sorbets",
"fr:Sorbets au citron",
"fr:Tartes au saumon",
"fr:Tartes salées",
"fr:Thons albacore",
"fr:Thons tropicaux"];
