var citiesTags = [

"Brunoy (Essonne, France)",
"Camaret-sur-Aigues (Vaucluse, France)",
"Capelle-Balaguier (Aveyron, France)",
"Carcassonne (Aude, France)",
"Cayenne (Guyane, France)",
"Chécy (Loiret, France)",
"Faverolles (Somme, France)",
"Ferrière-Bochard (Orne, France)",
"Loudéac (Côtes-d'Armor, France)",
"Montayral (Lot-et-Garonne, France)",
"Onet-le-Château (Aveyron, France)",
"Plougasnou (Finistère, France)",
"Port-Louis (Guadeloupe, France)",
"Roiffieux (Ardèche, France)",
"Roquefort-sur-Soulzon (Aveyron, France)",
"Saint-Denis-de-l'Hôtel (Loiret, France)",
"Saint-Étienne (Loire, France)",
"Theix (Morbihan, France)",
"Troarn (Calvados, France)",
"Varennes-sur-Fouzon (Indre, France)",
"Wisches (Bas-Rhin, France)"];
