name: Link rot
on:
  - push

jobs:
  check:
    name: Link rot check
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get files that need to be checked
        id: get_files
        run: |
          html_files=$(find html/donate -type f -name '*.html' -print)
          html_files=$(echo "$html_files" | xargs | sed -e 's/ /,/g')
          file_list="CONTRIBUTING.md,README.md,$html_files"
          echo "all_files=$file_list" >> "$GITHUB_OUTPUT"
          echo $file_list

      - name: Check URLs
        uses: paramt/url-checker@7925d0eb953d828a840eeefab0a64cc70d9bdaac # v0.3.1
        id: url-checker
        with:
          files: "${{ steps.get_files.outputs.all_files }}"

      - uses: LouisBrunner/checks-action@937cbbcde3259005b50746dc91cde29098aac2ff # v3.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check
          status: completed
          conclusion: ${{ steps.check.outputs.conclusion }}
          output: ${{ steps.check.outputs.output }}
