name: Generate OpenAPI JSON

on:
  push:
    paths:
      - 'docs/api/ref/api.yaml'
      - '.github/workflows/generate-openapi-json.yml'

jobs:
  generate-openapi-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install openapi-generator-cli
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Generate openapi.json from YAML
        run: |
          openapi-generator-cli generate -i docs/api/ref/api.yaml -g openapi -o html/resources/files

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-generate openapi.json from YAML'
          file_pattern: html/resources/files/api.json
