name: Ventilate issues to the right GitHub projects

on:
  issues:
    types:
      - labeled

jobs:
  add-to-projects:
    name: Ventilate issues to the right GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/43 # Add issue to the openfoodfacts-design project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: mockups available, needs mockup
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/36 # Add issue to the open pet food facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: open pet food facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/11 # Add issue to the open products facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: open products facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/37 # Add issue to the open beauty facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: open beauty facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/4 # Add issue to the packaging project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: packaging
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/25 # Add issue to the documentation project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: documentation
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/5 # Add issue to the folksonomy project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: folksonomy project
          label-operator: OR         
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/44 # Add issue to the data quality project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: data quality
          label-operator: OR    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/82 # Add issue to the search project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: search
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/41 # Add issue to the producer platform project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: producers platform
          label-operator: OR    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/19 # Add issue to the infrastructure project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: infrastructure
          label-operator: OR   
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/92 # Add issue to the Nutri-Score project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: nutriscore
          label-operator: OR   
