name: '💥 Auto-Label Merge Conflicts on PRs'
on:
  push:
  pull_request_target:
    types: [synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0  # v3.0.3 (2025-01-06)
        with:
          dirtyLabel: "💥 Merge Conflicts"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          retryMax: 5
          retryAfter: 5000
