var categoriesTags = [

"Extra-virgin olive oils",
"Fats",
"Olive oils",
"Vegetable fats",
"Vegetable oils",
"Vegetables and derived products",
"es:Untables vegetales",
"es:Mermeladas-y-confituras",
"es:Untables",
"es:Untables-dulces",
"Vinegars",
"es:Mermeladas-y-confituras-de-frutas",
"es:Endulzantes",
"es:Miel",
"es:",
"Condiments",
"Groceries",
"es:Azafrán",
"es:Especias",
"Pickled vegetables",
"Pickles",
"Vegetables",
"Green olives",
"Olives",
"Green whole olives",
"Marinated olives",
"Mixed pickles",
"Whole olives",
"es:Mermeladas-y-confituras-de-citricos",
"es:Mermeladas-y-confituras-de-flores",
"es:Mermeladas-y-confituras-de-higos",
"es:Mermeladas-y-confituras-de-petalos-de-rosas",
"Whole marinated green olives",
"es:Mermeladas-y-confituras-de-cebolla",
"es:Mermeladas-y-confituras-de-manzana",
"es:Mermeladas-y-confituras-de-naranja",
"es:Mermeladas-y-confituras-de-peras",
"es:Mermeladas-y-confituras-de-verduras-y-hortalizas",
"es:Mermeladas-y-confituras-multifruta",
"es:Patés vegetales",
"",
"Banderillas",
"Beverages",
"Carbonated drinks",
"Cracked marinated green olives",
"Cracked olives",
"Green cracked olives",
"Green pitted olives",
"Pitted olives",
"es:Mermeladas-y-confituras-de-cereza",
"es:Mermeladas-y-confituras-de-limon",
"es:Mermeladas-y-confituras-de-melocoton"];
