var statusTags = [

"A compléter",
"Caractéristiques à compléter",
"Caractéristiques complétées",
"Catégories à compléter",
"Categories-to-be-completed",
"Characteristics-to-be-completed",
"Date limite à compléter",
"Date limite complétée",
"Emballage à compléter",
"Expiration-date-to-be-completed",
"Informations nutritionnelles à compléter",
"Informations nutritionnelles complétées",
"Ingrédients à compléter",
"Ingrédients complétés",
"Ingredients-to-be-completed",
"Marques à compléter",
"Nom du produit à compléter",
"Nutrition-facts-to-be-completed",
"Packaging-to-be-completed",
"Photos à envoyer",
"Photos à valider",
"Photos envoyées",
"Photos-to-be-validated",
"Photos-uploaded",
"Quantité à compléter",
"To-be-completed"];
