var statusTags = [

"A-completer",
"Caracteristiques-a-completer",
"Caracteristiques-completees",
"Categories-a-completer",
"Categories to be completed",
"Characteristics to be completed",
"Date-limite-a-completer",
"Date-limite-completee",
"Emballage-a-completer",
"Expiration date to be completed",
"Informations-nutritionnelles-a-completer",
"Informations-nutritionnelles-completees",
"Ingredients-a-completer",
"Ingredients-completes",
"Ingredients to be completed",
"Marques-a-completer",
"Nom-du-produit-a-completer",
"Nutrition facts to be completed",
"Packaging to be completed",
"Photos-a-envoyer",
"Photos-a-valider",
"Photos-envoyees",
"Photos to be validated",
"Photos uploaded",
"Quantite-a-completer",
"To be completed"];
